Week2 [STEP 2] yeeton
yagom-academy/swift-starter-week2 pull request #105
Opened 2022-02-18 14:46 UTC by yeeton37

@YebinKim 
안녕하세요 비비!!

이번 step2에서는 로또 번호를 랜덤으로 6개 생성 후  그 로또번호를 제가 찍은 로또 번호와 맞춰보는 함수를 구현했습니다~

generateRandomNumber() 는 랜덤 번호를 생성하는 함수로,
makingNumbers(Set)에 랜덤으로 뽑은 Int 값을 6개 넣고 그 개수가 6개가 되면 출력하도록 해주었습니다.

그 다음으로, checkLottoNumber() 함수를 구현했습니다. 이는 로또번호를 확인하는 함수입니다.
교집합 메서드를 사용하였고, 이를 변수 chosenNumber 에 저장해주었습니다.

제가 가장 고민했던 부분은

겹치는 번호를 출력해주는 부분에서 [1, 4, 19] 이런 식의 출력이  아니라
1, 4, 19 이런 식으로 출력되도록 해야 하는 부분이었습니다.

구글링을 한 결과  joined를 사용하는 방법을 알게 되었습니다.
joined  메소드는 배열의 문자열들을 하나로 연결한 문자열을 반환합니다. 
또 원소 사이에 분리 기호를 삽입할 수도 있습니다. 그래서 저는 문자열을 분리하기 위해 ", " 를 추가해주었습니다.

감사합니다!

2022-02-19 07:14 UTC, yeeton37 reviewed
비비! 제가 PR 보내고 다시 확인하다가, 
로또 당첨 번호를 저장하는 변수를 전역 변수로 설정했더니, 추후에 랜덤 추출 함수를 실행했을 때 계속 똑같은 번호가 반복해서 나오더라구요. 이유를 알아보니 전역변수로 설정해서 그런 것이더라구요. 

그래서 함수 안에 변수를 넣어서 지역변수로 선언하는 것으로 코드를 변경해주었습니다!

(하지만 아직  정확히 전역 변수로 선언해주면 왜 안되고, 지역변수로 선언해주면 왜 되는 지 정확하게는 모르겠습니다.. 감만 있을 뿐 ㅠㅠ.)

2022-02-20 14:21 UTC, YebinKim requested changes
예톤님 안녕하세요~
Step2 진행하느라 고생 많으셨어요! ☺️👏

이번 스텝에서의 출력 요구사항을 위해 고민을 많이 하셨군요!
[joined(separator:)](https://developer.apple.com/documentation/swift/array/1690077-joined) 를 활용한 요소의 분리+결합 방법은 문제를 해결하기에 적절했던 것으로 보여요 😄
해당 함수의 문서도 한 번 읽고 넘어가자는 뜻에서 링크를 남겨둡니다.

> 로또 당첨 번호를 저장하는 변수를 전역 변수로 설정했더니, 추후에 랜덤 추출 함수를 실행했을 때 계속 똑같은 번호가 반복해서 나오더라구요. 이유를 알아보니 전역변수로 설정해서 그런 것이더라구요.

이에 관련해서는 아마 전역변수 그 자체가 문제이기 보다는 **전역변수의 초기화 과정이 없기 때문에 발생한 문제**로 보여요.
지역변수와 전역변수의 차이점이 무엇인지를 한 번 생각해보면 이번 스텝에서는 어떤 영역에서의 선언(어떤 스코프에서의 선언)이 더 적절했을지에 대한 이유를 찾아볼 수 있을 거 같은데요! 😆
**지역변수와 전역변수는 어느 시점에 초기화 되는지**, **함수를 여러번 호출했을 때 항상 일정한 값을 유지하는지**를 중심으로 한 번 생각해보실 수 있을까요?
감이 잘 안 잡힌다면 이 부분은 회의실에서 좀 더 얘기 나눠보아요! 🙌👂

그리고 이번 스텝에서도 파일 참조의 누락이 보이는데요 👀

<img width="253" alt="file missing" src="https://user-images.githubusercontent.com/38066039/154846917-1731649d-9227-4a4e-9470-873f692745b5.png">

이 부분 확인 한 번 부탁드려요~


---

현재 구현한 함수는 순서도의 흐름을 잘 따라가고 있고 또 출력 요구사항 또한 잘 준수하고 있는 것으로 보이는데요!
프로젝트 파일 참조의 누락이 있어서 이 부분 한 번 확인이 필요해 보여서 Request Changes 로 요청 드렸어요~

혹시 그 외에도 확인이 필요한 부분이나 고민했던 내용이 있다면 같이 좀 더 얘기해보아요! 🙆‍♀️😊

2022-02-21 07:33 UTC, yeeton37 commented on CodeStarterCamp_Week2/main.swift
> + func checkLottoNumber() {
헙 또 실수를... 고치겠습니다!!

2022-02-21 07:34 UTC, yeeton37 commented on CodeStarterCamp_Week2/main.swift
> +     let chosenNumber : Set<Int> = Set(generateLottoNumber()).intersection(Set(myLottoNumbers))
구글링을 하다가 저 형태를 보고 똑같이 써줬네요 ㅠ 이미 타입이 정해져있으면 안써줘도 되는군요! 참고하겠습니다 ㅎㅎ

2022-02-21 07:44 UTC, yeeton37 commented on CodeStarterCamp_Week2/main.swift
> +generateLottoNumber()
저는 generateLottoNumber() 이라는 함수를 먼저 호출하고, 그 다음에 checkLottoNumber() 를 실행해줘야 되는 줄 알았어요..!
다시 코드를 보니 checkLottoNumber() 함수 선언할 때 이미  generateLottoNumber() 를 실행해서 교집합을 구한 것이라
제가 이중으로 호출한 거네요 ㅎㅎ 참고해서 다시 작성하겠습니다!

2022-02-21 07:54 UTC, yeeton37 reviewed
안녕하세요 비비! 이번 수정은 
1. 불필요하게 generateLottoNumber()를 한번 더 호출해준 부분 삭제하고,
 2. let chosenNumber : Set<Int> = Set(generateLottoNumber()).intersection(Set(myLottoNumbers))
에서 타입을 또 명시해준 것 삭제했습니다.
3. control+ i로 코드를 깔끔하게 줄 맞추기를 해주었습니다
4. 전에 올린 commit 에서 잘못 올라간 step3 파일은 삭제한 후 다시 commit 헤주었습니다!
5. 
좋은 피드백 항상 감사해요 ㅎㅎ

2022-02-21 08:37 UTC, YebinKim approved these changes
예톤님 안녕하세요~
리뷰 반영 고맙습니다! 😄

이번 스텝을 위한 필수 구현 사항이 모두 적용된 모습 확인했어요~
DM으로 머지 의사 확인해주셔서 바로 머지 진행할게요! 🙌
다음 스텝 진행도 화이팅입니다 😆🔥

+) 수정사항 중 3번(코드 정렬)과 관련해서는 반영이 덜 된 부분이 보여서 추가 코멘트 남겨두었습니다 👀 확인 한 번 부탁드려요!

2022-02-21 08:37 UTC, YebinKim commented on CodeStarterCamp_Week2/main.swift
> + }
여전히 정렬이 맞지 않는 코드가 보이네요 😵
코드의 띄어쓰기 및 탭 정렬은 실행 로직과 직접적으로 연관되는 부분은 아니지만,
협업 시 발생할 수 있는 충돌을 줄이고 가독성을 높일 수 있기에 잘 챙겨갈 수 있으면 좋겠습니다 ☺️

2022-02-21 08:39 UTC, merged