Week2 [STEP 3] yeeton
yagom-academy/swift-starter-week2 pull request #112
Opened 2022-02-21 09:14 UTC by yeeton37

@YebinKim 
안녕하세요 비비 ㅎㅎ
Week2-Step 3 과제 제출합니다.
main.swift에서는 step2의 코드를 주석처리하고 step3의 함수만 실행해주었습니다!

첫 번째로 회차와 로또 번호들을  lottoHistory 라는 이름의 Dictionary 타입의 변수에 저장되도록 했습니다.
두 번째로 generateRandomNumber() 함수를 통해 6개의 랜덤한 숫자를 set타입의 변수 makingNumbers에 저장되도록 했습니다.
세 번째로 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장하도록 하는 함수 saveLottoNumber를 선언해주었습니다.
네 번째로 함수 호출부에서 적어준 endRound 만큼 saveLottoNumber를 실행하여 딕셔너리에 저장되도록 해주었습니다.
마지막으로는 함수 searchLottoNumber()를 선언해서 원하는 회차를 입력하면 
"\(round)회차의 로또 당첨 번호는 \(joinedStr) 입니다." 를 출력하도록 하는 함수를 구현해주었습니다.

제가 저번 step2 에서 전역변수와 지역변수의 차이점에 대해 여쭤봤었는데, 비비가 지역변수와 전역변수는 어느 시점에 초기화 되는지, 함수를 여러번 호출했을 때 항상 일정한 값을 유지하는 지를 고민해보라고 하셨는데요!

```
var makingNumbers = Set<Int>()
func generateRandomNumber() -> Set<Int> {
    
    while makingNumbers.count < 6 {
        makingNumbers.insert(Int.random(in: 1...45))
    }
    return makingNumbers
}
```
이렇게 전역변수로 makingNumbers()를 선언했을 경우, 함수 generateRandomNumber()를 호출해도 변수의 초기화 과정이 일어나지 않아서 항상 일정한 값이 나온 것 같습니다.

그래서 
```
func generateRandomNumber() -> Set<Int> {
    var makingNumbers = Set<Int>()
    
    while makingNumbers.count < 6 {
        makingNumbers.insert(Int.random(in: 1...45))
    }
    return makingNumbers
}
```
이렇게 함수 안에서 지역변수로 설정해주었더니, 함수generateRandomNumber()를 호출할 때마다 변수 makingNumbers()이 초기화되는 것으로 생각해보았습니다!
제 생각이 맞을까요??ㅎㅎ

비비님의 코멘트 기다리겠습니다 항상 감사해요~

2022-02-21 11:19 UTC, YebinKim requested changes
안녕하세요 예톤님! ☺️
Step3 진행까지 고생 많으셨습니다 😄👏

어떤 순서로 고민하셨는지를 상세히 적어주셔서 코드를 이해하기 수월했어요!
그리고 동사구를 활용한 함수의 네이밍을 통해 그 기능을 유추할 수 있어서 각 함수의 동작을 쉽게 이해할 수 있었어요 👍

지난번 스텝에서 질문드렸던 지역변수와 전역변수의 차이도 고민해보셨군요!
어느 한 쪽이 정답은 아니지만, 초기화 시점과 값 유지에 대해 고민할 수 있으면 이후 각 필요에 따라 잘 사용할 수 있을 거 같습니다 ☺️


---

이번 스텝과 관련해서는 라인별 코멘트를 통해 의견을 남겨두었으니 확인 부탁드려요.
**딕셔너리의 키값 타입**과 관련해 예톤님의 의견을 들어보고 싶어서 Request Changes 로 요청 드릴게요 🙇

혹시 그 외에도 고민했던 부분이나 코멘트에 관련한 질문이 있다면 코멘트 답글 또는 DM 부탁드려요! 🙌

2022-02-21 12:39 UTC, yeeton37 commented on CodeStarterCamp_Week2/step3.swift
> +var lottoHistory = [String?: Set<Int>]()
딕셔너리의 키값에 값이 들어가지 않을 수도 있다는 생각에 옵셔널로 해주었습니다!
(예를 들어 1~5까지 round를 돌렸는데, 사용자가 round에 6를 입력할 경우를 생각해주었습니다.)
옵셔널을 쓰는 게 맞았을까요?

2022-02-21 12:40 UTC, yeeton37 commented on CodeStarterCamp_Week2/step3.swift
> +func generateRandomNumber() -> Set<Int> {
앗 그러네요! lotto가 포함되는게 더 나은 이름이라고 생각돼서 바꾸었는데, 새로 선언하는 것 보다 재사용하면 훨씬 알기 쉽겠네요! 앞으로 그렇게 하겠습니다 ㅎㅎ

2022-02-21 12:40 UTC, yeeton37 commented on CodeStarterCamp_Week2/step3.swift
> +
넵! 파일명만 보고도 알 수 있게 고쳐보겠습니다

2022-02-21 13:03 UTC, YebinKim commented on CodeStarterCamp_Week2/step3.swift
> +var lottoHistory = [String?: Set<Int>]()
옵셔널 타입을 사용하는 게 불가능한 것은 아닙니다! 다만, 키가 없는 값은 딕셔너리로서 어떤 의미를 가지는지 궁금하네요 🤔

사용자가 round에 6을 입력했다는 것은 존재하지 않는 키 값을 입력했을 때를 가정하시는 걸까요?
존재하지 않는 키 값으로 딕셔너리 값을 찾고자 했을 때는 어떤 값을 만나게 될까요?

2022-02-21 14:09 UTC, yeeton37 commented on CodeStarterCamp_Week2/step3.swift
> +var lottoHistory = [String?: Set<Int>]()
헉.. 키가 없는 값은 딕셔너리로서 의미가 없을 것 같아요. 키가 있어야 value가 함께 저장되는 것이니까요!!
그러면 이럴 경우에 옵셔널 선언을 굳이 해주지 않아도 된다고 생각해도 될까요? 🧐

존재하지 않는 키 값으로 딕셔너리 값을 찾고자 했을 때는 아무런 값도 출력되지 않을 것 같아요!

2022-02-21 15:16 UTC, yeeton37 reviewed
안녕하세요 비비!
비비의 코멘트와 캠퍼의 도움을 받아 키값 타입을 변경해주었습니다. ㅎㅎ

1. 저는 딕셔너리의 특성을 깊게 생각하지 못했던 것 같아요! 딕셔너리에서 키값이 없으면 아무런 의미가 없다는 것을 알고.. 딕셔너리의 키값 선언부분에서 String? -> String 로 수정해주었습니다.

하지만 사용자가 키값을 입력할 때 범위에 어긋나는 숫자를 입력할 경우 (예시. round가 1~5까지만 돌도록 설정 해놓았는데, 사용자가 6을 입력할 경우) 에는 else문을 추가해서 해당 회차는 아직 실행되지 않았습니다.라고 출력해주도록 변경해보았습니다. 

2. step2에서 사용했던 함수명인 generateLottoNumber()로 이름을 바꿔주었습니다. 함수의 재사용을 위해서요!

3. 파일명을 step3-> step3 로또번호 저장 으로 바꾸어주어 파일명을 보고도 알아챌 수 있도록 했습니다.

읽어주셔서 감사해요 비비><

2022-02-21 16:27 UTC, YebinKim commented on CodeStarterCamp_Week2/step3.swift
> +var lottoHistory = [String?: Set<Int>]()
1. 네네 저도 키가 없는 값은 딕셔너리로서 의미를 가지지 않는다고 생각했어요! 그래서 이런 의도를 표현하자면 옵셔널 선언이 필요하지 않다고 생각합니다 😊
2. **아무런 값**도 출력되지 않을까요? 이 부분은 직접 확인해보시면 좋을 거 같아요 😄🙌

2022-02-22 10:52 UTC, YebinKim approved these changes
예톤님 안녕하세요~
드린 질문들에 대해 고민 후 공유해주셔서 감사합니다 😄

그런데 현재 Step3 와 관련된 코드가 포함된 파일의 이름이 `step3 로또번호저장.swift` 인 것으로 보여요!
한글로 된 이름은 읽기 쉽지만 터미널 및 웹에서 문자코드가 깨질 위험이 있지 않을까요? 🤔
이 부분 한 번 더 생각해볼 수 있으면 좋을 거 같아요.

---

이번 스텝에서 수행하고자 했던 내용은 모두 진행되었다고 생각해 Approve 로 리뷰 의견 드립니다!
머지 의사 한 번 확인해주시면 이대로 머지 진행하거나 수정을 한 번 더 진행해볼 수 있도록 할게요 😊

추가 코멘트가 하나 있으니 이 부분 확인 후 설명이 필요한 부분이 있다면 언제든 DM 주세요 👂🙌

2022-02-22 10:52 UTC, YebinKim commented on CodeStarterCamp_Week2/step3 로또번호저장.swift
> +        let joinedStr = lottoLog.map { String($0) }.joined(separator: ", ")
고차함수 [map(_:)](https://developer.apple.com/documentation/swift/array/3017522-map) 을 사용하셨군요! 👀
이 코드는 어떤 방식으로 동작하고 있을까요?

2022-02-22 13:27 UTC, yeeton37 commented on CodeStarterCamp_Week2/step3 로또번호저장.swift
> +        let joinedStr = lottoLog.map { String($0) }.joined(separator: ", ")
넵 저도 이부분이 엄청 어려웠는데요..
map은 콜렉션 내부의 데이터를 변형해서 새로운 콜렉션을 만들어주는 것이고, 
그래서 lottoLog라는 dictionary 컬렉션 내부에 저장된 데이터를 String 타입으로  변경해준 것이라고 생각합니다  
{ String($0) } 은 클로저를 축약한 표현으로, 인자값을 축약해서 $0으로 표현해준 것입니다.
사실 이 부분은 클로저에 대해 더 공부가 필요해보입니다 ..ㅠㅠ 
여기서 머지 희망합니다!!>_< 감사해요

2022-02-22 13:38 UTC, merged