Week2 [STEP 2] Makseong2
yagom-academy/swift-starter-week2 pull request #114
Opened 2022-02-21 13:55 UTC by Makseong2

@Journey36 

안녕하세요 글렌님~
요즘 갑자기 추워져서 그런지 감기에 크게 시달리고 있습니다 ㅎ..
감기 항상 조심하세요!

피드백 항상 감사드립니다~😃

2022-02-22 05:17 UTC, Journey36 requested changes
@Makseong2
안녕하세요, 막성님! 몸은 괜찮으신가요? 빠른 쾌유를 빕니다.
작성해주신 코드 확인 후 코멘트 남겼으니 확인 부탁드립니다.

2022-02-22 05:17 UTC, Journey36 commented on CodeStarterCamp_Week2/step2.swift
> +        lotteryNumbers.update(with: pickedNumber)
`Set`에는 `insert`와 `update`가 있죠. 둘의 차이는 무엇이고, `update`를 사용한 이유가 있을까요?

2022-02-22 05:17 UTC, Journey36 commented on CodeStarterCamp_Week2/step2.swift
> +    if Set(myLotteryNumbers) == lotteryNumbers {
로직에 치명적인 문제가 있는 것 같습니다!

2022-02-22 05:17 UTC, Journey36 commented on CodeStarterCamp_Week2/step2.swift
> +        let winningMessage = "축하합니다! 겹치는 번호는 \(myLotteryNumbers[0]),\(myLotteryNumbers[1]),\(myLotteryNumbers[2]),\(myLotteryNumbers[3]),\(myLotteryNumbers[4]),\(myLotteryNumbers[5]) 입니다!"
겹치는 번호가 하나면 어떻게 되나요?

2022-02-22 05:17 UTC, Journey36 commented on CodeStarterCamp_Week2/main.swift
> +compare(lotteryNumbers : lotteryNumbers, myLotteryNumbers: myLotteryNumbers)
`lotteryNumberGenerator()`가 실행되지 않네요?

2022-02-23 11:11 UTC, Makseong2 commented
@Journey36 

안녕하세요 글렌님! 

걱정해 주셔서 감사 드립니다. 
아직 미열이 있지만 저번보다는 훨씬 괜찮아 졌습니다!

제가 이번 step2 해석을 완전히 잘못 해석 하고 있었더라구요?
그래서 로직이 맞지 않았던것 같습니다..

문제 다시 해결하여 푸쉬 하였습니다~!

감사합니다!

2022-02-24 02:14 UTC, Journey36 reviewed
@Makseong2 
안녕하세요, 막성님. 몸이 그래도 조금씩 나아지고 계셔서 다행입니다!  무리하지 마시고, 빠른 쾌유 바랍니다.
그리고 작성해주신 코드를 봤는데, 코드가 깔끔하고 가독성도 좋은 것 같습니다.
코멘트 남겼으니 답변주시면 확인하고 머지 진행하도록 하겠습니다! 고생하셨습니다.

2022-02-24 02:14 UTC, Journey36 commented on CodeStarterCamp_Week2/step2.swift
> +        let lotteryNumber = compareLotteryNumbers.map{String($0)}.joined(separator: ", ")
map을 사용해보셨네요!  👍

2022-02-24 03:51 UTC, Makseong2 commented
@Journey36 

안녕하세요 글렌님!
위에 update 와 insert 차이 를 썼엇는데 , 코멘트가 안달렸을까요? pending 이라 나오는 것도 그렇고, 코멘트가 달수 없게 되있네요?
이부분은 한번 확인 해 보겠습니다 ~다시 여기다 코멘트 달겠습니다~~ 감사합니다. 
### insert
값을 추가하고, 추가된 결과를 튜플로 리턴합니다 (중복이면 false, 추가된값)
쉽게 말하면, 추가할 값이 이미 set 에 있으면 추가가 안되고(false), 추가할 값이 set 에 없으면 성공적으로 추가가 됩니다(true) .

### update
```swift
@inlinable public mutating func update(with newMember: Element) -> Element?
```
반환타입이 Optional 입니다. 그러니까 반환하는 값이 내가 추가한 요소 일수도 있고, nil 수도 있습니다.
확인해본결과, 
기존 set 에 내가 추가할 값이 "있으면"~ Optional(추가할값)이 되구요~
기존 set 에 내가 추가할 값이 "없으면"~ nil 을 리턴 하게 됩니다.

### update 사용하게된 이유

사실 이것저것 알아보다가 별생각 없이 썻습니다..
값을 추가한다는 것은 동일하지만, 리턴을 해주는 방식이 다르다는걸 알았네요!

2022-02-24 06:03 UTC, Journey36 commented
@Makseong2 
그렇군요! ㅎㅎㅎ `insert`와 `update`의 차이는 **값을 처리하는 방식**에서 차이가 조금 있습니다.
`insert`의 경우는 말씀해주셨듯이, 이미 존재하는 값은 추가되지 않습니다.
`update`의 경우는 문서를 잘 읽어보시면, **무조건적으로** 값을 삽입한다고 되어있습니다. 즉, 기존에 존재하는 값도 `insert`와 다르게 대체된 값으로 삽입이 된다는 겁니다. ㅎㅎㅎ 정말 필요한가 싶은 정도의 차이이지만, 알아두면 좋을 것 같아요! 🙂

아무튼 스텝 진행하시느라 고생 많으셨습니다. 여기서 머지하도록 하겠습니다. 👍👍👍

2022-02-24 06:03 UTC, merged