Week2 [STEP 3] lia388
yagom-academy/swift-starter-week2 pull request #117
Opened 2022-02-21 15:31 UTC by lia388

@TTOzzi 

안녕하세요 또치님😊 step3 pr 드립니다!

### 고민의 고민
실은 계속 고민하다 하나 안 풀리는 게 있었는데 일단 pr을 합니다,,
다름이 아니라 Dictionary에 넣어서 print 했을 때 지금 코드에서 `"1회차 : "[...]"` 이렇게 됩니다!
현재는 value를 
- String으로 받아서 `"[...]"` 이렇게 나오고
- Set<Int>로 받으면 `set([...])` 이렇게
- Int로는 어떻게 받을 수 있는건지 모르겠습니다😭 조언 부탁드릴게요,,!

### 양쪽 대괄호 제거
마지막 func에서 대괄호 제거하는데 `trimmingCharacters` 을 사용해 보았습니다!
Stirng에서만 사용 가능하다보니 기존 코드를 어떻게 변경해야 하는지 고민했는데 `String()`로 바꾸는 게 아니라 `"\()"`로 바꾸면 되더라구요,,
이번 step도 고민이 많았습니다ㅎㅎ,, 리뷰 잘 부탁드립니다!!😌

2022-02-21 17:26 UTC, TTOzzi requested changes
안녕하세요 리아님! 학습 속도가 굉장히 빠르시군요! :thumbsup:
커밋을 작업 단위로 잘 나눠주시고, 메세지도 명확하게 적어주셔서 어떤 흐름으로 작업하셨는지 파악이 쉽네요! 좋습니다 😊

### 고민의 고민

> 실은 계속 고민하다 하나 안 풀리는 게 있었는데 일단 pr을 합니다,,
> 다름이 아니라 Dictionary에 넣어서 print 했을 때 지금 코드에서 `"1회차 : "[...]"` 이렇게 됩니다!
> 현재는 value를
>
> - String으로 받아서 `"[...]"` 이렇게 나오고
> - Set로 받으면 `set([...])` 이렇게
> - Int로는 어떻게 받을 수 있는건지 모르겠습니다😭 조언 부탁드릴게요,,!

아하하 제가 질문을 잘 이해를 못했어요 :sweat: 
리아님께서 생각하신 Int로 받았을 때의 기댓값은 어떤 형태인가요?!

----

디테일한 피드백은 코멘트로 남겨두었습니다!
이해 안 되는 부분이나 궁금한 점 있으시면 코멘트 남겨주세요 :bow:

2022-02-21 17:26 UTC, TTOzzi commented on CodeStarterCamp_Week2/main.swift
> +        lottoNumberDict["\(count)회차"] = "\(lottoNumbers)"
로또 숫자 정보를 String 타입으로 가공해서 Dictionary에 넣어주신 이유가 궁금해요 👀 
지금 스텝의 요구사항만을 처리하는 데엔 문제가 없지만, 만약 스텝 2에서 했던 것처럼 n회차의 로또 번호와 나의 로또 번호를 비교하고 싶은 상황이 생긴다면 구현이 더 어려워질 것 같아요.
확장성을 고려해 데이터의 저장은 있는 그대로를 저장하고, 가공은 출력하는 시점에 해주는 건 어떨까요? 리아님의 생각이 궁금합니다!

2022-02-21 17:26 UTC, TTOzzi commented on CodeStarterCamp_Week2/main.swift
> +        let finalLottoNumber = "\(winnigLottoNumber)".trimmingCharacters(in: ["[","]"])
```suggestion
        let finalLottoNumber = winnigLottoNumber.trimmingCharacters(in: ["[","]"])
```
[String: String] 타입의 Dictionary 인 `lottoNumberDict` 에서 가져온 값 `winnigLottoNumber`는 이미 String 타입이라 따로 문자열 보간법을 사용해 String 변환을 해주지 않아도 될 것 같아요!

2022-02-22 02:24 UTC, lia388 commented on CodeStarterCamp_Week2/main.swift
> +func findSecondLottoNumber(week: String, lottoNumberDict: Dictionary<String, String>) {
앗! 넵넵! 수정해보았습니다!
`func findWeekLottoNumber(in week: String, from lottoNumberDict: [String: Set<Int>]) {`

2022-02-22 02:31 UTC, lia388 commented on CodeStarterCamp_Week2/main.swift
> +    if let winnigLottoNumber = lottoNumberDict["\(week)"] {
`guard let`의 경우, `if let`보다 훨씬 가독성 있게 표현 가능하며 예외상황만 표현할 경우 훨씬 간편하게 사용 가능합니다. 하지만, 더 까다롭습니다! 먼저, `return, break, continue, throw` 등의 제어문 전환 명령어를 쓸 수 없는 상황이라면 사용이 불가능합니다. 그리고 함수나 메서드, 반복문 등 특정 블록 내부에 위치하지 않는다면 사용이 제한됩니다.

(`winningLottoNumber`로 수정했습니다 *_*)

2022-02-22 02:35 UTC, lia388 commented on CodeStarterCamp_Week2/main.swift
> +        lottoNumberDict["\(count)회차"] = "\(lottoNumbers)"
이게 Pr할때 여쭤봤던 질문인데요ㅠㅠ step3 course에서 예시로 `"1회차" : [1, 2, 3, 4, 5]` 이렇게 딕셔너리에 들어가야 한다고 했는데, [String: Set<Int>]로 하는 경우 `"1회차" : set([1, 2, 3, 4, 5])`로 결과값이 뜨더라구요ㅠ 그래서 `set()`를 없애고자 String으로 바꿨는데 여전히 양쪽 따옴표가 있는 `"[1, 2, 3, 4, 5]"`로 뜨길래 일단 Pr한 거였습니다ㅠ
말씀해주신대로 가공만 출력시점에 해줄 수 있으면 좋을 거 같은데, 혹시 `Set<Int>` 상황에서도 출력하는 시점에 가공이 가능할까요?

2022-02-22 02:46 UTC, lia388 commented on CodeStarterCamp_Week2/main.swift
> +}
악!! 제가 마지막에 출력값 바꾸려고 노력하다가 원래 22번째 줄에 `lottoNumberDict["\(count)회차"] = generateLottoNumbers()`였는데, 함수가 아닌 상수`let lottoNumbers = generateLottoPack()`로 변환해서 String을 적용하려다가 변경이 있었던 것 같습니다!!

일단 딕셔너리에 [String: String]으로 할 지 [String: Set<Int>]로 할지 못 정한 상태이기 때문에 우선은 코멘트에 수정한 코드 남겨두겠습니다!
(혹시 이런 중간 과정도 커밋을 하는 게 낫다면 말씀해주세요!)

```swift
func generateLottoPack() -> [String: Set<Int>] {
    var lottoNumberDict: [String: Set<Int>] = [String: Set<Int>]()
    for count in 1...5 {
        lottoNumberDict["\(count)회차"] = generateLottoNumbers()
    }
    return lottoNumberDict
}
```

2022-02-22 13:31 UTC, TTOzzi commented on CodeStarterCamp_Week2/main.swift
> +}
아하 넵! 코멘트 남겨주신대로 수정하면 해결되겠네요!
(코드 수정은 커밋으로 남겨주시는 게 더 좋긴 해요!)

2022-02-22 13:38 UTC, TTOzzi commented on CodeStarterCamp_Week2/main.swift
> +        lottoNumberDict["\(count)회차"] = "\(lottoNumbers)"
출력하는 시점에 Set을 꺼내서 `"1, 2, 3, 4, 5"` 형태의 문자열로 변경할 순 없을까요?!
배열로 변환한다던지.. 하는 방식으로요!

2022-02-22 16:11 UTC, lia388 commented on CodeStarterCamp_Week2/main.swift
> +        let finalLottoNumber = "\(winnigLottoNumber)".trimmingCharacters(in: ["[","]"])
코드를 `Dictionary<String, String>`에서 `[String: Set<Int>]`로 변경하여 
`let finalLottoNumber = "\(winnigLottoNumber)".trimmingCharacters(in: ["[","]"])`
이건 유지하겠습니다!

2022-02-22 16:26 UTC, lia388 commented
@TTOzzi 

또치님! 코드 수정 후 다시 커밋 드립니다!
그 중간에 `"1회차" : set([1, 2, 3, 4, 5])` 변경 관련해서 여쭤봤던 부분은 다른 스터디원 분이랑 얘기해보니 과제 자체를 제가 잘못 이해한 것 같더라구요,,! 미션 설명에서 `"1회차" : [1, 2, 3, 4, 5]`에 value값이 `Set<Int>`인걸 유추하라는 식의 얘기였던 것 같은데, 저는 step3의 과제가 Dictionary 추출 & 2주차 로또 번호 추출로 이해했습니다🥲 그래서 괄호 제거 방법은 `trimmingCharacters`로 알았으니 수정한 코드 봐주시고 괜찮으시면 머지 해주시면 감사하겠습니다ㅎㅎ

2022-02-23 11:48 UTC, TTOzzi commented on CodeStarterCamp_Week2/main.swift
> +func generateLottoPack() {
`lottoNumberDict`를 함수 내에서 만들어 반환하는 방식에서, `lottoNumberDict`를 밖으로 옮기신 이유가 궁금해요 👀 
`lottoNumberDict`를 전역으로 선언하면 어디서든 접근할 수 있다는 장점이 있지만, 함수 내의 로직이 함수 밖의 다른 값에 영향을 주게 되어 로직이 복잡해지면 이 함수의 로직이 다른 곳에 어떤 영향을 줄지 예상하기 어렵다는 단점도 있습니다.
음.. 풀어서 설명하려니 뭔가 구구절절해진 느낌인데 `side effect`,  `pure function` 키워드에 대해 공부해보시면 좋을 것 같습니다 🙂

2022-02-23 11:49 UTC, TTOzzi commented
고생하셨습니다~! 🙇🙇

2022-02-23 11:50 UTC, merged