Week2 [Step3] JeeeeSang
yagom-academy/swift-starter-week2 pull request #123
Opened 2022-02-22 07:11 UTC by JeeeeSangRyul

전역변수를 사용하지 않는 방식에 대해 고민해 보았습니다.
@Monsteel

2022-02-22 11:47 UTC, Monsteel requested changes
안녕하세요 상률님 ☀️ 주말은 잘 보내셨나요?! 😁
Step3진행하시느라 수고 많으셨습니다~!

몇가지 간단한 리뷰를 달아보았어요! 확인 부탁드립니다 🙏

그리고, `makeLottoNumbers`와 `makeTotalWeek` 그리고, `makeLottoDictionary`로
하는 역할에 따라 각 함수들을 나누어 주셔서 명확하게 어떤 프로그램인지 보다 파악하기 쉬웠습니다 🙌

하지만 우려되는 부분이 있는데요, `makeTotalWeek` 과`makeLottoDictionary`는 매번 같은 횟수의 반복문을 두번씩 돌게 됩니다. 예를들어 10회차의 로또 당첨 번호를 생성하는 경우, for문 반복문은 20번 돌게 됩니다. 지금 당장에는 문제가 없겠지만 숫자가 커지면, 1,000회차의 로또 당첨 번호를 생성하는 경우, 2,000번 돌게 되는 셈인데요, 이 부분을 개선할 수 있는 방법은 없을까요? 🤔

이 부분에 대해서도 고민해 주시면 감사하겠습니다! 🙏

2022-02-22 11:47 UTC, Monsteel commented on CodeStarterCamp_Week2/Step3.swift
> +        emptyArray.append("\(week)회차")
"회차"라는 단위를 Dictionary의 key값에 포함시킨 이유가 있으신가요?! 🙋🏻‍♂️
"단위"를 제외하고 출력시에 단위를 붙여주는 방법은 어떨까요?! 🤔

2022-02-22 11:47 UTC, Monsteel commented on CodeStarterCamp_Week2/Step3.swift
> +        return
사용자에게 왜 출력이 되지 않았는지 알려주면 어떨까요?! 🤔
만약 출력이 되지 않고 바로 끊기면 어떤 이유인지 사용자가 파악하기 어려울것 같아요 😵‍💫

2022-02-22 11:47 UTC, Monsteel commented on CodeStarterCamp_Week2/Step3.swift
> +func makeTotalWeek(totalWeek : Int)-> [String]{
`week`이라는 키워드가 가르키고 있는 `회차`라는 개념은 조금 다른것 같아요.
단위를 `주차`로 통일하거나, `회차`로 통일하여 가져가는 등, 한가지 개념으로 일원화를 하는건 어떨까요?! 🤔

아마.. 매주 추첨되는 로또의 특성을 코드에 담아내신 것 같아요😓

2022-02-22 13:58 UTC, JeeeeSangRyul commented
같은 횟수로 두번 도는 함수를 개선하기 위해서 기존에 회차를 저장해두는 함수를 지워줬습니다. 불필요하다고 생각했습니다. 
그리고 빈 dictionary에 기능을 추가하여 1000회 로또를 진행하면 1000번만 진행되게 해봤습니다. 
회차의 경우 주차와 헷갈려서 week->draw로 바꾸었습니다.
그리고 guard let을 통해서 사용했던 기존코드를 if let으로 바꾸어 사용자로 하여금 잘못된 값이 들어오면 "해당 회차는 존재하지 않습니다"라는 문구를 출력하게 해두었습니다.

감사합니다 ~

2022-02-23 17:26 UTC, Monsteel approved these changes
안녕하세요 상률님!
리뷰가 늦어져 죄송합니다 🙏

남긴 리뷰를 통하여 고민해주시고 적용해주신 덕분에 코드가 훨씬 깔끔해진것 같아요 👍

수고많으셨습니다~! 🎉

2022-02-23 17:26 UTC, merged