Week2 [Step2] SEO-YJ
yagom-academy/swift-starter-week2 pull request #126
Opened 2022-02-22 13:52 UTC by SEO-YJ

@hrjy6278 
안녕하세요 지스님!
Week2-step2 과제를 구현하였습니다.

Step1 순서도와의 다른점
1. Array 대신 Set을 이용하여 구현하였습니다.
2. 6번 반복하는 대신, 무한루프를 이용하였습니다.

질문
Q1. Set을 print함수에서 출력하려 할 때, "[1, 2, 3, 4, 5"]" 와 같이 대괄호가 같이 포함되는 문제가 발생하였습니다.
이를 없애줄 메소드를 찾았으나, 결국 찾지 못하여
printSet이라는 함수를 정의하여 Set을 출력하는 함수를 구현하였습니다.
혹시, 대괄호를 없앨 수 있는 메소드가 있는지 궁금합니다!

2022-02-23 02:13 UTC, hrjy6278 requested changes
안녕하세요 유준님! 지스입니다.
빠르게 스텝2를 해주셨네요 고생하셨어요👍

전반적으로 코드 네이밍도 괜찮았고 파라미터 명도 괜찮네요. 책읽듯이 코드를 읽을 수 있었습니다.
Set을 활용한점도 아주 좋았던 것 같아요!
빠르게 PR해주신만큼 리뷰도 빠르게 해드리겠습니다 ㅎㅎ

---

### 질문 주신내용
질문

> 1. Set을 print함수에서 출력하려 할 때, "[1, 2, 3, 4, 5"]" 와 같이 대괄호가 같이 포함되는 문제가 발생하였습니다.
> 이를 없애줄 메소드를 찾았으나, 결국 찾지 못하여
> printSet이라는 함수를 정의하여 Set을 출력하는 함수를 구현하였습니다.
> 혹시, 대괄호를 없앨 수 있는 메소드가 있는지 궁금합니다!

이 부분은 코멘트를 한번 확인해주세요!

마지막으로  현재 Git Commit된게 한개네요. 이정도 볼륨이면 적어도 함수가 3개니 커밋이 3개정도는 나와야 된다고 생각됩니다. 다음부터는 함수 한개 == 커밋한개 를 해보는게 어떨까요?

일단은 유준님의 생각이 더 듣고싶어 머지 처리는 진행하지 않고, RequestChange를 요청드릴게요!
고생하셨습니다!

궁금한게 있으시면 DM으로 대화 나누시죠!

2022-02-23 02:13 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    }
반복문의 무한루프를 이용해주셨네요! 👏🏻

저희가 아는 For 반복문 말고도 While이라는 조건반복문이 있습니다.
이 반복문을 for문 안에 있는 조건문도 없어질 것 같고 코드가 좀더 간결해 질 것 같은데 한번 공부해볼까요?

2022-02-23 02:13 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    var lottoNumbers = Set<Int>()
`Set`타입을 활용하신점 대단합니다!

조금 더 공부하고싶으시면 Set에 꺽쇠 <> 는 무엇일까요? 이 부분은 시간나실때 공부하시길 바라면서 ㅎㅎ

2022-02-23 02:13 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    }
이 부분이 질문 주신 내용이 맞을까요?
그렇다면 음.. `Set<Int>` 타입이 아닌 `Set<String>` 타입에 `joined` 메서드가 있으니 한번 참고를...ㅎㅎ

`Set<String>` 타입을 이용하면 loopCount도 없어질 것 같고 여러모로 좋을 것 같네요!

2022-02-23 02:13 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    let intersectionNumber: Set<Int> = chooseNumber.intersection(winningNumber)
`intersection`이라는 메서드는 저도 처음봤네요 ㅋㅋㅋㅋ 이렇게 쉽게 비교가 가능하다니...ㅋㅋㅋ 대단하십니다👍
다만 타입명시는 생략해도 될 것 같아요!

2022-02-23 02:13 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    }
음 이 부분이 조금 애매한데요. 함수명은 `checkNumber` 인데 비교한 번호가 비어있는지 아닌지 확인하고, `print` 를 사용하고 있습니다. 
이렇게 되면 함수가 `print를 해주는 역활과` `비교하는 역활` 두 가지 하고 있다고 생각해요. 

이 부분을 함수를 나눠서 사용할 순 없을까요?

2022-02-23 02:37 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    }
While이라는 조건문은 condition이 false를 반환하기 전 까지 계속 반복되는 것을 확인하였습니다!
이를 통해, for 문 내부에 있는 조건문을 생략하여 코드를 간결하게 작성하였습니다!

2022-02-23 10:14 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    }
Set<Int>를 Set<String>으로 수정하여, joined 메서드를 추가하고, 위 printSet 함수를 제거하여 구현하였습니다!

2022-02-23 10:14 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    let intersectionNumber: Set<Int> = chooseNumber.intersection(winningNumber)
넵! 저번에 컴파일러 딴에서 타입을 구분할 수 있으면 생략하는 것이 좋다고 말씀해주셨는데, 이 부분을 놓친 것 같습니다 ㅠㅠ

2022-02-23 10:15 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    }
print를 해주는 함수 printIntersectionNumber 함수와
비교하는 역할 함수 checkNumber 함수를 
구분하여 
"함수가 한 가지의 기능"만을 하도록 수정하였습니다!

2022-02-23 10:16 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    var lottoNumbers = Set<Int>()
혹시, 이 <>가  "제네릭"이라는 것인가요....?
찾아 봤는데, 아직 잘 이해가 되지 않네요,,

2022-02-23 10:18 UTC, SEO-YJ commented
@hrjy6278 
지스님!
피드백 해주신 사항 대로 코드를 다시 수정하여 PR요청드렸습니다!
감사합니다!

2022-02-23 11:29 UTC, hrjy6278 requested changes
유준님 수정하신건 잘 봤습니다.

제가 몇가지 코멘트를 드렸으니 확인 부탁드려요!

2022-02-23 11:29 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
>      }
해당 부분의 `checkNumber` 함수는  함수명만 봤을때 단순히 어떠한 숫자를 체크하는 로직만 타야된다고 생각됩니다.

지금은 `checkNumber` 함수가 로또번호 맞추기의 모든 시작점이 된 느낌이에요.
유준님이 코드를 작성하셨으니 해당 함수가 어떤 역활을 할 지 잘 파악이 되겠지만 저같이 처음보는 사람(동료)은 해당 함수명을 보고는 어떠한걸 체크한다는지 전혀 파악이 되질 않는 것 같아요.

가령 `startLottoGame` 같은 함수를 만든 뒤 해당 함수에 로직을 타게하는 방법도 좋을 것 같습니다.
그렇지 않다면 저 checkNumber 함수명을 바꿔야 되지않을까요? 유준님의 생각은 어떤가요?

해결하기 힘드시면 같이 DM 나눠보아요!

2022-02-23 11:29 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
>  func drawLotto() -> Set<Int> {
함수명이 조금 어색한 것 같아요. draw보다는 makeLottoNumbers 같은 더 정확한 명칭이 필요할 것 같아요! 유준님은 어떻게 생각하시나요? 이 코멘트를 따라서 굳이 바꾸실 필요는 없습니다. :)

2022-02-23 11:29 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +func printIntersectionNumber(intersectionNumber: Set<String>) {
이미 함수명에서 IntersectionNumber를 한다고 명시했는데 파라미터명으로 또 intersectionNumber는 중복되는 감이 있습니다.
와일드카드 패턴을 한번 써볼까요?
그리고 이걸 처음 보는 사람의 입장에서 해당 앱이 로또번호 맞추기 게임이라고 해서 코드를 봤는데 `IntersecionNumber`는 조금 어색한 감이 있는것 같아요.

조금 더 다른사람이 봤을때 편히 읽을수 있는 단어는 없을까요? 이 부분은 필수로 안고치셔도 됩니다. 저만 어려울수도 있으니깐요 ㅎ

2022-02-23 12:01 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
>      }
맞습니다! 함수는 함수명을 봤을 때, '이 함수는 어떠한 로직을 탈 것이다.'
라는 것을 명백히 알 수 있도록 함수명을 작성하여야 합니다.
말씀해주신 것 처럼 checkNumber는 '숫자를 체크한다' 이런 의미로 동료에게 읽혀질 것 같습니다.
그러면, 이 함수는 '숫자를 체크하는 로직' 한 가지 기능만을 구현해야 합니다.

그래서, 코드를 
1. 함수가 어떠한 로직일 지 유추가능하도록 함수명을 작성
2. 함수가 '한 가지의 기능' 만을 하도록 더 세분화
하여 다시 수정해보겠습니다!

Week1에서 함수를 지스님이 말한 방식대로 작성한 것을 배웠었는데,
이를 조금 간과하고 작성한 것 같습니다 ㅠㅠ

2022-02-23 12:03 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
>  func drawLotto() -> Set<Int> {
draw라는 단어가 "뽑는다" 라는 의미로 번역기에서 확인하여 작성하였는데,
사실 저도 draw가 이런 의미가 있는지 처음 알았고,
동료들이 명확히 알 수 있는 단어로 수정하는 것이 맞다고 생각합니다. 감사합니다!

2022-02-23 12:05 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +func changeLiteral(integerNumber: Set<Int>) -> Set<String> {
'함수를 호출할 때 함수 사용자의 입장에서 매개변수의 역할을 좀 더 명확하게 표현'할 수 있는
전달인자 레이블을 사용하여
함수와 매개변수가 어떠한 관계인지 유추할 수 있도록 수정해보겠습니다!

2022-02-23 12:06 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
>      }
아,,, 꼼꼼하지 못했던 것 같습니다 ㅠㅠㅠ

2022-02-23 15:20 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
>  func drawLotto() -> Set<Int> {
아 draw란 뜻이 뽑는다라는 의미도 있죠.. ㅋㅋㅋ 유준님의 작성하신 함수명이 더 적절한 것 같네요. 영어가 부족하다 보니 이런일이 발생하네요 😢😢😢

2022-02-25 03:49 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +func printIntersectionNumber(intersectionNumber: Set<String>) {
intersection이라는 단어보다,
compare(비교하다.)라는 뜻이 더 익숙한 단어라고 생각되어 이것으로 고쳐보겠습니다!

2022-02-25 03:52 UTC, SEO-YJ commented
@hrjy6278 
코드가 동료들이 편하게 읽을 수 있도록 개선하는 것의 중요성을 느꼈습니다!
함수의 이름, 전달인자 레이블, 매개변수 등을 통해
이 함수가 어떤 기능을 하는지, 어떤 로직인지 유추할 수 있도록 수정해보았습니다!

makeLottoNumbers 함수
: makeLottoNumbers(로또 숫자들을 만들다.)

compareNumbers 함수
: chooseNumbers(고른 숫자들)과 winningNumbers(당첨 숫자들)을 비교한다.
sameNumbers(같은 숫자들)을 반환한다.

changeLiteral 함수
:  integerNumbers(정수 숫자들)을 Literal(문자열)로 바꾼다.
literalNumbers(문자열 숫자들)을 반환한다.

printSameNumbers 함수
: 같은 숫자들(sameNumers)를 출력한다.

printLottoResult 함수
: 로또 결과를 출력한다.

부족한 부분, 보완할 부분 등을 언제든지 얘기해주시면 감사하겠습니다!!

2022-02-25 04:02 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
>  func drawLotto() -> Set<Int> {
이 함수의 로직이 "랜덤한 로또 숫자를 만드는 것."이 핵심인 것 같아,
makeLottoNumbers로 명명하였습니다!

2022-02-25 07:47 UTC, hrjy6278 approved these changes
유준님 안녕하세요! 수정해주신 코드 잘봤습니다.

고민을 많이 해주신 코드였던것 같네요. 전반적으로 이제 함수를 읽을때 술슬 읽히고 어떤 로직을 실행할지 이름만 보고도 유추할 수 있는것 같습니다.

이번 스텝에서 경험은 다 해보셨다고 생각하여 머지 처리하겠습니다 
제가 몇가지 코멘트는 남겨 드렸으니 한번 보시고 참고정도만 부탁드려요!
스텝3로 넘어가시죠!

고생하셨습니다!

2022-02-25 07:47 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    return sameNumbers
굳이 상수 선언을 하지 않고 리턴을 바로 할 수 있을 것 같네요 :)

2022-02-25 07:47 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +var winnigLottoNumbers = makeLottoNumbers()
이 부분은 변수로 선언해주셨네요. 이유가 궁금합니다!

2022-02-25 07:47 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    print("축하합니다! 겹치는 번호는 " + sameNumbers.sorted().joined(separator: ", ") + " 입니다!")
이런 계산하는 로직이 담겨있을 땐 바로 print 처리를 하지 않고 개인적으로 상수로 빼는 편입니다.

```
let resultLottoNumbers = sameNumbers.sorted().joined(separator: ", ")

print("축하합니다! 겹치는 번호는 " + resultLottoNumbers + " 입니다!")

```

이 부분은 개인차이가 있는것 같습니다ㅎㅎ

2022-02-25 07:47 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
checkNumber의 함수명이 바뀌었네요! 이제 좀 더 잘 읽히는 것 같네요 :)

2022-02-25 07:47 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +func changeLiteral(of integerNumbers: Set<Int>) -> Set<String> {
함수명도 배열을 리턴하니 복수형이 되야 할까요?!

2022-02-25 07:47 UTC, merged

2022-02-25 11:23 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    return sameNumbers
return chooseNumbers.intersection(winningNumbers)
바로 리턴할 수 있는 것은 위 코드처럼 하도록 하겠습니다!

2022-02-25 11:25 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +var winnigLottoNumbers = makeLottoNumbers()
음,,, winningLottoNumbers에 다른 값이 들어가지 않으므로 상수로 선언하는 것이 더 괜찮아 보입니다,,

2022-02-25 11:26 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +    print("축하합니다! 겹치는 번호는 " + sameNumbers.sorted().joined(separator: ", ") + " 입니다!")
상수를 하나 선언하여 처리하니, print문이 보기에 더 간결한 것 같습니다!
문자열을 연산하는 부분에서는 상수로 따로 빼서 처리해보도록 하겠습니다.

2022-02-25 11:42 UTC, SEO-YJ commented on CodeStarterCamp_Week2/main.swift
> +func changeLiteral(of integerNumbers: Set<Int>) -> Set<String> {
@hrjy6278 
literal이라는 단어의 뜻이 '문자열'이라고 생각하여, '문자들의 나열'로 생각해 단어 자체가 복수형인 것 같아 위와 같이 이름을 작성하였었습니다!

정확히 literal의 단어 뜻을 찾아보니 
'컴퓨터 분야에서 리터럴(literal)은 데이터 그 자체를 뜻 한다. 
변수에 넣는 변하지 않는 데이터이다.'
라고 나오는 군요,,,

'문자열'을 검색하니, character, string 등이 뜻으로 나오는데
둘 다 '자료형'이여서 함수명으로 넣는 것이 좋지 않아보여, 이름을 어떻게 짓는게 좋을까 고민이됩니다,,

2022-02-26 15:04 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +func changeLiteral(of integerNumbers: Set<Int>) -> Set<String> {
넵 이런부분은 아직 네이밍짓기가 애매한 것 같네요. 추후에 `extension` 을 배우면 좀 더 네이밍이 쉽지 않을까 생각됩니다 ㅎ