Week2 [Step3]
yagom-academy/swift-starter-week2 pull request #129
Opened 2022-02-22 16:16 UTC by sozohoy

@Journey36 
안녕하세요 글렌님! step 3 입니다 !
- 저번에 말씀해주신 joined(separator: )를 이용해서 코드를 작성해 보았습니다.
- 컬렉션 타입 선언을 일관성 있게 진행했습니다.
- 옵셔널 값은 nil-coalescing을 사용해서 간편하며 안전하게 추출해보았습니다!
항상 감사합니다 ! 좋은 하루 되세요 !

2022-02-22 21:19 UTC, Journey36 requested changes
@sozohoy 
안녕하세요, 지석님! 스텝 진행하시느라 고생 많으셨습니다.
작성하신 코드를 봤는데, 피드백을 최대한 신경써서 반영하려는 듯한 모습이 보였습니다. 👍
코드를 확인하다가 궁금한 부분을 코멘트로 남겼으니 확인 부탁드립니다.

2022-02-22 21:19 UTC, Journey36 commented on step3/main.swift
> +        roundNumbers.append(randomIndex)
`randomNumbers.sorted()`가 어떤 타입을 반환하는지 자세하게 살펴보면, 더 쉽게 작성할 수 있는 방법이 존재할겁니다!

그리고, 정렬이 지금 정상적으로 이루어지나요??

2022-02-23 14:04 UTC, sozohoy commented on step3/main.swift
> +var lottoNumbers = [String: Array<String>]()
- 앗! 이 방법은 생각하지 못했습니다. 감사합니다!!

2022-02-23 14:05 UTC, sozohoy commented on step3/main.swift
> +        roundNumbers.append(randomIndex)
- 정렬이 지금 정상적으로 되지 않네요! 수정하겠습니다 !

2022-02-24 05:41 UTC, Journey36 reviewed
@sozohoy 
안녕하세요, 지석님! 스텝 진행하느라 고생 많으셨습니다! 코멘트 달아놨습니다만, 확인하시고 다음번에 참고하시면 좋을 것 같습니다. 이번 스텝은 여기서 머지하겠습니다. 고생하셨어요!

2022-02-24 05:41 UTC, Journey36 commented on step3/main.swift
> +    changeIntToString = roundNumbers.map(String.init)
`map`을 잘 활용해주셨네요 👍
지석님처럼 함수 자체를 넣어주는 것도 가능하고 trailing-closure의 축약문법으로 아래와 같이 사용도 가능합니다:
```swift
changeIntToString = roundNumbers.map { String($0) }
```

2022-02-24 05:41 UTC, Journey36 commented on step3/main.swift
>          roundNumbers.append(randomIndex)
이 부분은 아직 캐치를 못하신 것 같아서 알려드리자면, `sorted()`의 반환타입은 `[Int]`입니다. 그래서 딱히 반복문을 돌면서 원소를 배열에다가 집어넣어줄 필요가 없어요. ㅎㅎㅎ

2022-02-24 05:41 UTC, merged

2022-02-24 10:08 UTC, sozohoy commented on step3/main.swift
> +    changeIntToString = roundNumbers.map(String.init)
- 좋은 정보 감사합니다!!😃

2022-02-24 10:08 UTC, sozohoy commented on step3/main.swift
>          roundNumbers.append(randomIndex)
- 아..!!!! 그렇군요.... 감사합니다!! 전혀 캐치 못하고 있었네요!