Week2 [STEP 1] themoon
yagom-academy/swift-starter-week2 pull request #130
Opened 2022-02-22 20:01 UTC by themoon

@YebinKim 
- week2 step1 내용입니다.
- 코드를 생성하지 않으면서 순서도만 봐도 코드를 짤 수 있도록 신경써보았습니다.
- Set Collection의 Element name을 remove하는 방식과 dict element key로 삭제하는 두 가지 방법 중 dict로 한 번 해보고 싶어서 만들어보았습니다. 

- Array로 로또 번호가 담겨있는 Collection을 만들게되면 삭제하게 되면서 index가 밀리는 문제가 있어 Set, Dictionary를 사용하는 방법으로 만들게 되었습니다.

2022-02-23 13:18 UTC, YebinKim requested changes
더문님 안녕하세요!
Week2 프로젝트에 진입하신 것을 환영해요 🥳🎉

함수가 수행해야 할 내용을 상세하게 순서도로 적어주셨는데요.
Dictionary 타입의 key를 삭제하며 랜덤한 수를 뽑는 과정이 흥미로웠습니다 😆
게다가 error 출력까지 고려하셨군요 👍

순서도를 보며 궁금한 점이 몇 가지 보여서 하나씩 질문드려볼게요!

### < 궁금한 점 >
1. PR 코멘트로는 `Set`과 `Dictionary`를 사용했다고 하셨는데 순서도에는 `Set` 타입이 보이지 않네요! 어떤 단계에서 사용하고자 하셨을까요?
2. `numbers = 1` 단계에서 numbers 는 어떤 변수 또는 상수일까요? 변수/상수를 어떤 목적으로 선언했을지 설명이 필요할 거 같아요 👀
3. `비어있는 dict의 key/value를 numbers/numbers 형태로 저장` 단계에서 numbers 형태로 저장한다는 것은 어떤 의미셨을까요?
4. `lottoNumber의 값이 nil인가?` 단계에서 lottoNumber 는 어떤 변수 또는 상수일까요?
5. `랜덤 번호가 들어있는 Element가 key/value의 형태로 들어있는 dict에서 랜덤으로 Element 하나를 뽑아서 상수에 저장` 에서 Element는 _랜덤 번호가 들어있는 Element_ 와 _dict에서 랜덤으로 Element 하나를 뽑아서_ 중 어떤 Element로 쓰고자 하신 걸까요? 
6. `6개의 랜덤한 숫자를 저장할 빈 배열인 Array에 랜덤으로 뽑은 상수 Element의 key를 추가` 단계에서 상수 Element의 key는 무엇을 말씀하시는 걸까요?


---

현재 순서도의 흐름 중 이해가 어려운 부분이 있어 Request Changes 로 요청드렸습니다! 🤔

그리고 가능하면 순서도의 내용은 **코드 없이 문장으로만 작성**해보시면 어떨까요?
문법의 영향 없이 함수의 논리적 흐름을 생각할 수 있고 이후 코드의 변경이 있을 때도 순서도와 싱크를 맞추기 더 수월할 거 같아요~

2022-02-23 15:22 UTC, themoon commented
1. PR 코멘트로는 Set과 Dictionary를 사용했다고 하셨는데 순서도에는 Set 타입이 보이지 않네요! 어떤 단계에서 사용하고자 하셨을까요?
- Set또한 Element name으로 삭제할 수 있어서 Dict의 key로 삭제하는 방식과 동일하여 따로 순서도로 표현하지 않았습니다!
설명한다면 순서도 내 값이 nil일때 no라는 상황에서 Element의 key가 아닌 set일떄에는 name으로 변한다는 차이점이 있습니다.

2. numbers = 1 단계에서 numbers 는 어떤 변수 또는 상수일까요? 변수/상수를 어떤 목적으로 선언했을지 설명이 필요할 거 같아요 👀
- numbers는 반복문 내 사용하는 임시변수입니다. 해당 내용은 순서도 수정하여 반영하도록 하겠습니다. 
좀더 구체적으로 작성하는 버릇이 필요할 것 같다는 생각이 듭니다.. ㅠㅠ

3. 비어있는 dict의 key/value를 numbers/numbers 형태로 저장 단계에서 numbers 형태로 저장한다는 것은 어떤 의미셨을까요?
- 반복문을 돌았을떄 numbers는 반복문내에서의 임시변수 입니다. 1부터 45까지의 숫자가 임시변수에 저장되며,
이떄 저는 1...45의 형태가 만들어진다고 생각했고 임시변수를 dict에 대입하면 dict key(1...45)/numbers(1...45)의 형태로 저장됩니다.
코드로 썼을떄는 dict[numbers] = numbers가 됩니다.

4. lottoNumber의 값이 nil인가? 단계에서 lottoNumber 는 어떤 변수 또는 상수일까요?
- lottoNumber는 상수입니다. 순서도 작성이 틀린 것 같습니다. 랜덤으로 뽑힌 상수의 값이 nil인가?로 변경하겠습니다. 

5. 랜덤 번호가 들어있는 Element가 key/value의 형태로 들어있는 dict에서 랜덤으로 Element 하나를 뽑아서 상수에 저장 에서 
Element는 랜덤 번호가 들어있는 Element 와 dict에서 랜덤으로 Element 하나를 뽑아서 중 어떤 Element로 쓰고자 하신 걸까요?
- 말이 좀 어렵게 적어놔서 이해하는데 조금 어려웠던 것 같습니다. dict에서 랜덤으로 Element 하나를 뽑아서 상수에 저장하는 방식입니다.
순서도 수정하였습니다!

6. 6개의 랜덤한 숫자를 저장할 빈 배열인 Array에 랜덤으로 뽑은 상수 Element의 key를 추가 단계에서 상수 Element의 key는 무엇을 말씀하시는 걸까요?
- 상수 Element의 key는 말그대로 상수(dict Element).key입니다. 랜덤으로 뽑은 상수(Element)가 [12 : 23] 일떄 12(Key)만 가져온다는 뜻 입니다. 랜덤으로 뽑은 상수 key를 추가한다라고 쓰고 싶었는데 애매한 표현인 것 같아서 Element를 덧붙여 적었습니다.

순서도 새롭게 작성하여 올리겠습니다!

2022-02-24 22:36 UTC, YebinKim requested changes
더문님 안녕하세요~
리뷰 반영 고맙습니다! ☺️
구체적으로 작성되어 순서도의 각 내용이 오류없이 이해되고 있는 것으로 보입니다 👀

작은 디테일이지만 순서도의 퀄리티를 높이기 위해 아래 코멘트를 확인 부탁드립니다!

1. Set의 활용 방법이 Dictionary와 같아 순서도에 표기해주지 않으신 것으로 이해했는데요. 이때 두 콜렉션 타입을 같은 용도로 쓰고 있음에도 서로 다른 타입으로 선언하고자 한 이유가 무엇일까요?

2. 타입을 한글과 영문 및 축약어을 섞어 표시하고 있는 것으로 보여요(인트형, int형 / dictionary, dict 등) 타입을 표시할 때는 Swift API Design Guidelines 의 `[General Conventions](https://www.swift.org/documentation/api-design-guidelines/#general-conventions)` 을 준수해 대문자 카멜케이스로 작성해보면 어떨까요?
    > Follow case conventions. Names of types and protocols are UpperCamelCase. Everything else is lowerCamelCase.

3. `반복문 내 사용할 int형 임시변수로 1을 선언` 은 변수의 선언과 값 대입이 모호한 문장으로 보여요. 선언과 값 대입을 분리한 문장으로 작성하면 어떨까요?

4. `비어있는 dict의 key/value를 임시변수/임시변수로 저장` 도 2번과 같이 타입의 선언과 대입할 값이 모호한 문장으로 보여요. 둘을 분리해서 표현하는 문장으로 작성해보면 어떨까요?

---

이번 스텝의 주요 목표인 **콜렉션 타입의 활용**과 관련해 궁금한 점이 있어 한 번 더 Request Changes로 요청드렸습니다 😊

혹시 코멘트 중 설명이 필요하거나 추가로 질문이 필요할 때는 언제든 DM 주세요 👀🙌

2022-02-27 13:22 UTC, YebinKim approved these changes
더문님 안녕하세요!
리뷰 코멘트 확인 및 답글 작성 감사합니다.

3번 코멘트와 관련해서 제 의도를 좀 더 설명드리자면 변수와 선언과 값 할당(대입)은 명확히 구분되는 개념이고, 순서도를 작성하는 이유는 **프로그램/함수의 논리적인 흐름**과 **타입의 선언 및 활용에 관한 흐름**을 이해하기 위함이기 때문에 정확하게 작성하는 게 필요하다고 생각했어요.
또한, 말씀하신 것 처럼 문맥상 충분히 이해 가능한 문장일 수 있지만 언어를 배우는 초기 단계에서 변수와 선언과 값 할당이 구분되는 개념임을 명확히 짚고 넘어가고자 코멘트 드렸습니다 😄


---

여러 번의 Step1 수정 진행 정말 고생 많으셨습니다 😊👏
이번 스텝의 목표였던 `순서도를 그대로 코드로 옮겼을 때, 원하는 동작이 이루어 질 수 있을 정도로 상세한 순서도 작성`은 충분히 수행한 거 같아 Approve 로 리뷰 의견 드렸어요~

머지 의사 한 번 확인해주시면 현재 상태에서 바로 머지 진행할 수 있도록 할게요.

코멘트에 대한 궁금증이나 스텝 진행 중 의견이 필요한 부분이 있다면 DM 또는 이번과 같이 코멘트로 질문 해주세요! `질문 환영 ᕕ( ᐛ )ᕗ` 입니다 😆

2022-02-27 13:32 UTC, themoon commented
어떤 말씀인지 충분히 이해된 것 같습니다 ㅜㅜ 
좀 더 확실히 적어보니 저에게 도움 되는 것 같아요. 
머지 부탁드립니다!

2022-02-27 14:12 UTC, YebinKim commented
머지 의사 확인 고맙습니다! (굉장히 빠르네요 👀🚀)
다음 스텝 진행도 화이팅이에요~!

2022-02-27 14:13 UTC, merged