Week2 [STEP 2] yyjjgg
yagom-academy/swift-starter-week2 pull request #139
Opened 2022-02-24 13:45 UTC by yyjjgg

@hrjy6278 

# Week2 [STEP 2]

- STEP 1 에서 순서도를 먼저 작성해서 그런지 코드로 옮겨 작성할 때 막힘없이 쉽게 작성되어 놀라웠습니다.

- 겹치는 번호를 확인하기 위해 checkLottoNumber 함수를 생성 하고
lottoNumber와 myLottoNumber 교집합을 찾기 위한 intersection을 사용하였습니다.
또한 겹치는 번호가 있을 경우를 알기 위해 if 구문을 사용하고 intersection.count 가 0 보다 클 경우
겹치는 번호를 출력하고, 그렇지 않을 경우 겹치지 않는다는 멘트를 출력하도록 하였습니다.

- 한번의 명령만 입력하면 실행 될 수 있도록 playLotto 함수를 생성하였습니다.

- playLotto 함수에서 saveLottoNumber() 에 "Result of call to 'saveLottoNumber()' is unused"
라는 경고문구가 떠서 구글링을 해본 후 경고문구를 없애기 위한 @discardableResult 를 사용하였습니다.

- 궁금한 점 : 위 경우처럼 return을 하고 그 반환 값을 사용하지 않는다면 코드가 잘못 된 것인가요?

2022-02-24 14:49 UTC, hrjy6278 requested changes
안녕하세요 준근님! 코드 잘 보았습니다.
전체적으로 함수명도 읽기 쉽고 코드 컨벤션도 아주 잘해주셨습니다. 👍👍  많이 성장하셨네요..후후..
또한 순서도에 맞게 로직을 짜주셔서 대단하다고 느끼고 있습니다 👏🏻👏🏻

준근님이 조금 더 성장할 수 있도록 제가 몇가지 코멘트를 드렸으니 한번 확인 부탁드립니다.

준근님의 생각을 듣고 싶은 몇가지가 있고, 수정을 바라는곳도 몇군데 있어서 PR은 Reqeust Changes로 마치겠습니다. 혹시 궁금하거나 이해가 안되시는 부분있으면 DM으로 얘기 나눠요! 수고하셨습니다. 💯

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +var lottoNumber: Set<Int> = Set<Int>()
전역적으로 사용되는 변수를 선언해주셨네요. 
`함수 안에서 쓰는 변수나 상수`와, `전역적인 변수`의 차이는 무엇이 있을까요? 한번 공부해보시는게 좋을 것 같습니다.

그리고 한가지더! 
`var lottoNumber: Set<Int> = Set<Int>()` 를 
`var lottoNumber = Set<Int>()` 이렇게 바꾸면 에러가 날까요? 안날까요? 

안나면 왜 안날까요? 안나는 이유를 공부하시고 댓글로 한번 써주시면 좋을 것 같습니다. :)

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
순서도와 일치하는 로직이네요! 아주 좋습니다. 함수명도 아주 좋네요 :) 👍 

다만 만약 해당 함수는 11번 줄에 있는 `lottoNumber` 변수가 사라질시에 해당 기능을 할 수 있는 함수가 될까요?
이를 해결하려면 어떻게 해야될까요?

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
이부분이 질문주신 내용이군요!
`@discardableResult` 을 저도 가아끔 쓰긴하는데 보통은 잘 안씁니다...

이 부분은 코딩을 좀 더 해보셔야 언제 써야할지 말아야 할지 판단이 스실것 같습니다.

현재는 lottoNumber 전역변수가 있어서 리턴타입이 쓸모가 없어지네욤. 한번 리턴타입을 활용해보시는 걸 추천드려봅니다.

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    let intersection: Set<Int> = lottoNumber.intersection(myLottoNumber)
값을 여러개 담고 있는 경우 변수나 상수명에 복수형으로 써주셔야 됩니다!

`let intersections`!!

intersection는 교집합이라는 뜻을 가지고 있었군요.. 이 부분의 상수명을 조금 더 쉽게 작성해 주셨으면 좋겠습니다.

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
해당 함수명을 읽어봤을때는 로또번호를 체크하는 로직을 담고 있는 것 같습니다.
함수의 정의부분을 살펴보아도 29번 라인이 체크를 해주는 것 같습니다.

다만 해당 함수에서 체크뿐만 아니라 출력결과를 `print` 해주고 있네요!
이 경우 함수 하나에 두가지의 로직을 담고 있다고 생각을 하게됩니다.

준근님의 생각은 어떤가요? 

그리고 로직중 count > 0 이라는 로직이 있습니다. 이것도 좋지만 `isEmpty` 메서드를 한번 찾아보시는 것도 추천드려봅니다.

2022-02-24 14:49 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
한번 더 함수를 감싸주신점이 아주 대단하십니다 👍

2022-02-25 14:52 UTC, yyjjgg commented on CodeStarterCamp_Week2/main.swift
> +var lottoNumber: Set<Int> = Set<Int>()
- 두 변수의 차이에 대해서 알아보니 함수 안에서 쓰는 변수나 상수는 해당 함수 내부에서 특정동작을 하고난 후,
그 값을 다른곳으로 전달해주거나 그냥 없어질 경우에만 사용하고, 전역적인 변수는 코드 전체에서 사용할 수 있습니다.

-  저는 이번 코드에서 lottoNumber를 세 함수에서 사용하기 때문에 전역적인 변수로 선언하였는데,
위 처럼 두 변수의 차이를 공부해보니 함수 안에서 쓰는 변수(지역변수)로 선언한 후 리턴하여
리턴 값을 활용하는 방법이 있겠다는 생각이 들었습니다. 그래서 STEP 1에서 로또번호생성 후 그 값을
리턴하라고 한 이유도 있던게 아닐까 하는 또 다른 생각이 이어지고 또 @discardableResult를
사용하지 않아도 되겠구나 라는 생각까지 들었습니다.

- var lottoNumber: Set<Int> = Set<Int>() 를 var lottoNumber = Set<Int>()로 바꿔보았는데
에러는 발생하지 않고 정상적으로 실행되었습니다.
Set는 축약문법이 없기때문에 에러가 발생해야 한다고 생각했는데 왜 에러가 발생하지 않았는지 모르겠어서
구글링을 엄청나게 해보았는데 아무리 찾아도 왜 축약문법이 없는지, 왜 에러가 발생하지 않는지에 대해서
찾아내지 못했습니다...

2022-02-25 15:16 UTC, yyjjgg commented on CodeStarterCamp_Week2/main.swift
> +}
- 변수 lottoNumber 를 전역변수가 아닌 함수 makeLottoNumber 내부에 지역변수로 선언하면 해결할 수 있습니다.

- 저는 전역변수로 한번에 선언하고 사용하는게 편리하니까 더 좋다고 생각하였는데
첫번째 코멘트와 두번째 코멘트가 전역변수라는 비슷한 맥락에서 질문을 주신것 같아서
왜 이런 질문을 주셨을지 다시 한번 생각해보려고 더 알아보았는데 비록 정확한 이유는 찾지 못했지만
어떤 한 블로그에서 "전역변수는 이제는 왠만해선 자제해야 될 코딩 스타일이다"라는 내용을 보고
전역변수는 사용을 자제해야한다는 사실을 알게되었습니다.
왜 사용을 자제해야하는지 이유를 알고싶다면 무엇을 포인트로 찾아봐야 하는지 알고싶습니다

2022-02-25 15:49 UTC, yyjjgg commented on CodeStarterCamp_Week2/main.swift
> +    let intersection: Set<Int> = lottoNumber.intersection(myLottoNumber)
- 상수, 변수, 함수 명을 복수형으로 변경하였습니다.

- 상수 Intersection 을 winningLottoNumbers(당첨번호) 로 변경하였습니다.

2022-02-25 16:24 UTC, yyjjgg commented on CodeStarterCamp_Week2/main.swift
> +}
- 지스님의 의견을 듣고 다시 살펴보니 두 로직을 나누는게 좋을것 같아서 함수를 새로 생성하여 기능을 나누었습니다.
함수 checkLottoNumbers 의 당첨결과를 print 하는 내용을 없애고 printLottoResult 라는 함수를 생성하여
당첨결과를 print 하도록 함수 하나에 있던 두가지 로직을 두개의 함수로 나누었습니다!

- isEmpty 메서드를 찾아보니 count > 0 을 사용하는것 보다 isEmpty가 지금의 로직에서
더 확실하게 '일치하는 것이 있는가, 없는가'로 나눌 수 있다고 생각되어 변경하였습니다.

2022-02-25 16:24 UTC, yyjjgg commented on CodeStarterCamp_Week2/main.swift
> +}
감사합니다!!@

2022-02-26 14:56 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
이 부분은 아직 답을 못찾으셔도 됩니다. 다만 나중에 더 깊게 알고 싶으시면 메모리 구조에 대해 더 공부해보시면 될 것 같습니다.

2022-02-26 14:57 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +}
변경하신 부분이 github에 올라와있지 않은 것 같아요. 혹시 Push를 해주셨을까요?

2022-02-26 14:59 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    let intersection: Set<Int> = lottoNumber.intersection(myLottoNumber)
이 부분도 변경사항이 보이지 않습니다. 수정 후에 push를 해주셨을까요??!

2022-03-02 01:43 UTC, hrjy6278 approved these changes
준근님 안녕하세요! 코드 잘 읽었습니다.

print해주는 함수도 새로 생기고 check를 해주는 로직이 담긴 함수도 생기고 분리를 해주셨네요 좋습니다.

함수의 파라미터로 기본값을 생성하는 구문을 써주셨네요 공부를 많이 하신것 같습니다 :)

이번 스텝에서 경험하실 부분은 다 경험했다고 판단하여 여기서 마무리하겠습니다.
스텝3로 넘어가시죠! 고생하셨습니다!

2022-03-02 01:43 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +    let winningLottoNumbers: Set<Int> = lottoNumbers.intersection(myLottoNumbers)
타입명시는 생략해도 될 것 같네요!

2022-03-02 01:43 UTC, hrjy6278 commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(winningLottoNumbers) 입니다!")
이렇게 그냥 출력하게 되면 [1,2,3] 이렇게 출력될 것 같습니다. 이를 해결 할 순 없을까요? 스텝3에서 한번 해볼까요?

2022-03-02 01:43 UTC, merged