Week2 [STEP 2] Dino
yagom-academy/swift-starter-week2 pull request #147
Opened 2022-02-27 06:27 UTC by Jun-12

@1Consumption 

순서도를 보면서 코드를 작성하는 과정에서 가장 먼저 막혔던 부분이 있었습니다. 바로 1 ~45 사이의 랜덤한 숫자를 생성하는 방법이었는데, 이것은 구글링을 통해 알아냈고 생각보다 간단하였습니다.
```Swift
var randomNumbers: Int = Int.random(in: 1...45)
```
이 방법을 통해 번호를 생성할 때 순서도에 맞게 while 을 사용하여 반복문을 만들어 주었습니다.
위 방법과 마찬가지로 **당첨 번호**도 랜덤으로 생성해주었습니다.
그 후, 겹치는 번호를 출력할 때 사용할 수 있도록 ‘**겹치는 로또번호**’에 해당하는 변수를 만들어 당첨 번호와 내 로또 번호를 비교해 겹치는 숫자를 담아주었습니다. 그리고 switch 구문을 사용해서 겹치는 숫자가 없을 경우와 있을 경우 각각의 문자열을 출력하도록 작성했습니다.

이렇게 코드를 작성하고 생각했던 점은, 
```Swift
print("축하합니다! 겹치는 번호는 \(correctNumbers) 입니다!")
```
이렇게 출력을 하게 되면 숫자가 대괄호에 감싸져서 나오게 됩니다. 하지만 보기에는 대괄호에 감싸져 있지 않았습니다. 
이 부분은 어떻게 보완할 수 있을지 고민해보려고 합니다!

2022-02-28 12:55 UTC, 1Consumption requested changes
안녕하세요 디노님~ 고생하셨습니다!

로또 넘버끼리 비교하고 결과를 잘 도출하네요!👍 
그런데 커밋이 조금 아쉽네요. 조금 더 단위를 작게 쪼갤 수 있지 않았을까요?
다음부터는 커밋을 보다 상세하게 나눠보도록 해요.

------------------------------

아래는 고민하신 점에 대한 제 코멘트입니다.
>  `print("축하합니다! 겹치는 번호는 \(correctNumbers) 입니다!")`
이렇게 출력을 하게 되면 숫자가 대괄호에 감싸져서 나오게 됩니다. 하지만 보기에는 대괄호에 감싸져 있지 않았습니다.
이 부분은 어떻게 보완할 수 있을지 고민해보려고 합니다!


`correctNumbers`는 배열이네요! 배열 자체를 출력하면 `[`, `]`에 감싸져서 나오죠! 이를 반복문을 통해 배열 내의 요소를 순회하면 어떨까요?


나머지 피드백은 코멘트를 통해 남겼습니다!

2022-02-28 12:55 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +    }
이부분은 중복되는 코드 같아요. 메소드로 중복되는 코드를 줄여볼까요?

2022-02-28 12:55 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +    }
이부분도 다른 콜렉션 타입의 메소드를 쓰면 코드가 더 간결해질거 같아요.

2022-03-03 01:41 UTC, Jun-12 commented
피드백 해주신 점을 생각하면서 코드를 작성해봤습니다.

1. `chooseNumbers` 메소드의 중복코드를 합쳐주었습니다. 메소드 내에서 `randomSixNumbers` 리스트를 생성해 Set 값들을 반환하도록 만들어주었습니다.

2. `randomNumber` 변수를 상수로 변경하였습니다.

3. 중복코드가 합쳐진 `chooseNumbers` 메소드를 `myLottoNumbers`와` lottoNumbers`에 부여하는 역할을 하는 `chooseAllNumbers` 메소드를 만들어주었습니다.

4. `compareNumbers` 내의 for 반복문을 Set 타입의 교집합으로 바꿔주고 값들을 반환할 수 있도록 수정하였습니다. 값을 반환하기에 `correctNumbers`는 불필요하다 생각되어 삭제하였습니다. 그리고 메소드 이름을 `compare`로 변경해준 뒤, 매개변수 `mine`과 `thisWeek`을 생성해주었습니다. 메소드를 하나하나 실행하기보다는 비교할 리스트를 지정하면 자동으로 교집합도 같이 구해주도록 해주고 싶었고, 매개변수를 사용하면 재사용성도 더 좋겠다고 생각했습니다.

5. switch 조건문을 `confirmTheWin` 메소드 내에서 수행하도록 변경하였습니다. 그리고 `compare.count` 조건보다 `compare.isEmpty`이 가독성이 더 좋다고 생각되어 변경하였습니다.

6. 겹치는 숫자를 대괄호 없이 출력하기 위해 숫자를 하나하나 출력해주는 `separateNumbers` 메소드를 만들고 `confirmTheWin` 내에  불러왔습니다. `separateNumbers` 에서 이미 숫자를 출력했기 때문에 하나의 문자열을 여러개로 나누어주었습니다.

7. 마지막으로 커밋에 대해 궁금한 점이 있었습니다. 커밋을 할 때에는 작동 가능한 하나의 완성된? 단위가 되어야 한다고 들은 적이 있습니다. 하지만 말씀하신 것처럼 기능적인 부분으로 나누어서 커밋을 할 때에는 기능 여러개가 연관되어 있어서 한 기능을 수정하면 다른 기능이 컴파일 에허가 나타날 때도 있었습니다. 이럴 때에는 코드를 작성하는 순서를 바꿔가면서 두개의 조건(작동 가능한 코드, 한 커밋당 하나의 기능)을 모두 만족시키며 커밋을 해야하나요? 아니면 연관되는 기능들조차 모두 한 기능으로 치고 작성을 해야 할까요?

2022-03-04 13:08 UTC, 1Consumption approved these changes
> 마지막으로 커밋에 대해 궁금한 점이 있었습니다. 커밋을 할 때에는 작동 가능한 하나의 완성된? 단위가 되어야 한다고 들은 적이 있습니다. 하지만 말씀하신 것처럼 기능적인 부분으로 나누어서 커밋을 할 때에는 기능 여러개가 연관되어 있어서 한 기능을 수정하면 다른 기능이 컴파일 에허가 나타날 때도 있었습니다. 이럴 때에는 코드를 작성하는 순서를 바꿔가면서 두개의 조건(작동 가능한 코드, 한 커밋당 하나의 기능)을 모두 만족시키며 커밋을 해야하나요? 아니면 연관되는 기능들조차 모두 한 기능으로 치고 작성을 해야 할까요?

이미 답을 알고 계신듯 합니다. 코드에는 순서가 있고, 그 순서대로 커밋을 하는게 좋아보입니다.

2022-03-04 13:08 UTC, merged

2022-03-04 15:03 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +}
피드백 감사드립니다! 네이밍은 말씀해주신대로 수정해보겠습니다. 그리고 커밋은 좀 더 많이 해보고 어느 지점에서 커밋을 해야할지를 생각해보면서 해야겠네요..!