Week2 [STEP 2] themoon
yagom-academy/swift-starter-week2 pull request #152
Opened 2022-03-01 04:57 UTC by themoon

@YebinKim 

week2 step2 내용입니다.

과제 출력을 위해 순서도에 없는 array를 추가사용하여 출력하도록 해보았습니다. 

저번 회의에서 알려주신 띄어쓰기나 네이밍 관련해서 좀더 신경 써 작성해보았습니다!

2022-03-01 22:33 UTC, YebinKim requested changes
더문님 안녕하세요~
Step2 진행까지 고생 많으셨습니다 😆👏

대괄호 없이 출력해야 한다는 요구사항을 맞추기 위해 Array 타입을 사용하셨군요!
`joined(separator:)` 메서드와 함께 적절히 활용하셨다고 생각합니다 😄

코드를 읽었을 때, 코멘트에 언급해주신 것 처럼 네이밍과 띄어쓰기에 신경쓰셨음이 느껴졌어요 😊
띄어쓰기에 관련해서는 추가 코멘트를 남겨두었으니 확인 한 번 부탁드려요!

그리고 현재 커밋을 스텝 구현 사항으로 묶어서 한 번에 올리신 것으로 보이는데,
다음에는 구현 흐름과 기능에 따라 나눠서 커밋을 올려보면 어떨까요?
커밋을 잘 나눠서 관리할수록 코드의 히스토리를 파악하거나 다른 사람과 함께 협업하기 수월해질 수 있다고 생각해요.


---

**이번 스텝의 요구사항** 및 **프로그램의 기능 단위로 함수를 작성하는 것**과 관련해 확인이 필요한 부분이 있어 Request Changes 로 요청드렸어요~
코멘트 내용 또는 학습 내용과 관련해 질문이 있다면 언제든 DM 주세요 ᕕ( ᐛ )ᕗ

2022-03-01 22:33 UTC, YebinKim commented on CodeStarterCamp_Week2/main.swift
> +var resultLottoNumbers: [String] = []
콜렉션 타입임을 나타내기 위해 복수형의 이름을 사용하고 있네요 👍

2022-03-01 22:33 UTC, YebinKim commented on CodeStarterCamp_Week2/main.swift
> +func lottoPrinter() -> Array<Int> {
`lottoPrinter()` 는 로또 번호를 출력하는 이름으로 보이네요! 👀
현재 함수의 기능과 같이 `생성한 로또번호를 반환받는다`는 의미가 드러나도록 이름을 수정해보면 어떨까요?

2022-03-01 22:33 UTC, YebinKim commented on CodeStarterCamp_Week2/main.swift
> +    var randomNumbers: [Int : Int] = [:]
딕셔너리를 표현할 때는 Swift API Design Guidelines 의 [Collection Types](https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html) 과 같이 Key에는 콜론을 붙이고, Value에는 한 칸 띄어쓰기를 작성하는 방식을 활용해보면 어떨까요?

2022-03-01 22:33 UTC, YebinKim commented on CodeStarterCamp_Week2/main.swift
> +    for numbers in 1...45{
중괄호의 앞뒤로 공백을 추가하는 스타일이 통일되지 않은 것으로 보이네요 👀
(16번 라인, 25번 라인, 43번 라인에서는 띄어쓰기가 없지만 그 외는 모두 공백이 있어요)
코드의 가독성을 위해 일괄 추가해보면 어떨까요?

2022-03-04 04:07 UTC, themoon commented on CodeStarterCamp_Week2/main.swift
> +    for numbers in 1...45{
반영 하였습니다!

2022-03-04 04:07 UTC, themoon commented on CodeStarterCamp_Week2/main.swift
> +    var randomNumbers: [Int : Int] = [:]
딕셔너리를 표현하는 방법을 이제야 알았네요 ㅠㅠ 적용하겠습니다!

2022-03-04 04:07 UTC, themoon commented on CodeStarterCamp_Week2/main.swift
> +func lottoPrinter() -> Array<Int> {
수정하였습니다!

2022-03-04 04:18 UTC, themoon commented on CodeStarterCamp_Week2/main.swift
> +}
나누어서 한번 작성해보았습니다!

2022-03-04 04:21 UTC, themoon commented
Request Changes 요청 드렸습니다. 다음부터는 작업 단위 별 쪼개서 commit 작성하도록 하겠습니다!

2022-03-06 14:20 UTC, YebinKim approved these changes
더문님 안녕하세요 😄
리뷰 코멘트 반영 고맙습니다!

이번 스텝에서의 주요 목표였던 **step1 순서도의 구현**과 **`찍은 번호`와 `로또 당첨 번호`의 겹치는 숫자를 확인하는 함수**를 생성하고 호출하는 것은 수행되었다고 생각해서 리뷰 의견 Approve 로 드렸어요~
머지 의사 알려주시면 바로 머지 진행하도록 하겠습니다!

그리고 다음 스텝에서는 **함수의 선언과 호출 및 전역 변수/상수 선언 외에는 함수 밖에서 코드가 작성되지 않도록** 작성해볼 수 있었으면 좋겠습니다!
컴퓨터 프로그램은 복잡한 요구사항을 수행하기 위해 큰 기능을 작은 기능 단위로 분할하고, 작은 기능은 함수 등의 코드 블럭으로 묶어서 사용하는 것이 기본 흐름이며,
기능을 작게 나누고 코드를 블럭으로 작성하는 이유는 코드 블럭들이 어떻게 조합하냐에 따라 서로 다른 기능을 수행할 수 있기 때문이라고 생각하기 때문이에요 (코드의 범용성) 😊

혹시 이와 관련해서 궁금한 점이 있다면 제 의도를 더 설명드려볼 수 있도록 할게요 👀
언제든 DM 주세요~ 😆🙌

2022-03-07 14:49 UTC, themoon commented
감사합니다! 다음 코드 작성에는 조금 더 분리하여 진행 해보도록 하겠습니다. 머지 부탁드립니다!

2022-03-07 15:17 UTC, merged