Week2 [Step2] 자유인
yagom-academy/swift-starter-week2 pull request #154
Opened 2022-03-03 11:07 UTC by freemandevloper

@1Consumption  내 번호와 맞추어보기 코드 업로드 했습니다.

고민 했었던 점

1. 로또 당첨 번호 생성 함수 makeLotterySet와 겹치는 숫자를 확인하는 함수 veryifyLottoResult의 매개변수를 굳이 써줄 필요 없다고 판단하여 각각 func makeLotterySet(), func verifyLottoResult()라 썼는데 더 가독성을 좋게 해줄 방법이 있을지 궁금합니다.

2. Set이랑 array가 교집합이 가능했던것이 신기했습니다. 인간의 직관으로는 당연하게 되는거인데 Swift에서 서로 다른 컬렉션간의 계산을 허락해준게 신기하네요.

3. 함수에서 매개변수 기본 값을 미리 지정할수 있는것처럼 내가 찍은 번호 배열을 myLottoNumbers 변수에 할당할때 6개의 번호만 할당할 수 있는 간결한 코드가 없을지 궁금하네요. 

신경 썼었던 점

지난 Week1 Step2, 3 내용 피드백을 참고하여 제가 까먹은 피드백이 없도록 확인하였으며, 특히 제가 처음에 코드들을 한번에 업로드한걸 알고구글링으로 git add 취소하기를 검색하여 git add Xcode파일명 을 활용하여 git add를 취소하고 코드 단위별로 다시 업로드 했습니다.

최대한 간결하게 직관적으로 코드를 작성할수 있도록 했습니다.

2022-03-03 16:02 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +    }        else {
else가 너무 　　멀　　리　　　있　　　네　　　요...

2022-03-03 16:05 UTC, 1Consumption requested changes
어프루브를 잘못 눌렀네요.

2022-03-03 16:27 UTC, freemandevloper commented on CodeStarterCamp_Week2/main.swift
> -
넵 수정해서 다시 추가했습니다.

2022-03-03 16:27 UTC, freemandevloper commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [3, 5, 11, 14, 20, 26]
넵 랜덤하게 만들었습니다.

2022-03-03 16:28 UTC, freemandevloper commented on CodeStarterCamp_Week2/main.swift
> +    }
아 네 영어랑 비슷하네요 되도록이면 이중 부정문을 쓰지 않고 되도록 긍정문을 쓰게 하게끔 하는게

2022-03-03 16:29 UTC, freemandevloper commented on CodeStarterCamp_Week2/main.swift
> +    }        else {
허허.. 요건 리인덴트가 못잡았네요... 혹시 이 부분은 왜 못잡는지 아시려나요...??

2022-03-03 16:30 UTC, freemandevloper commented
> 안녕하세요 자유인님~
> 
> 코드가 점점 읽기 좋아지네요! 👍 고민하신 부분에 대한 제 생각을 남겨봤어요!
> 
> > 1. 로또 당첨 번호 생성 함수 makeLotterySet와 겹치는 숫자를 확인하는 함수 veryifyLottoResult의 매개변수를 굳이 써줄 필요 없다고 판단하여 각각 func makeLotterySet(), func verifyLottoResult()라 썼는데 더 가독성을 좋게 해줄 방법이 있을지 궁금합니다.
> 
> 왜 매개변수로 받지 않아도 되었을까요? 왜 접근이 되는걸까요? 전역변수를 사용했기 때문 아닐까요? 전역변수를 사용하지 않는다면 어떻게 될까요?
> 
> > 2. Set이랑 array가 교집합이 가능했던것이 신기했습니다. 인간의 직관으로는 당연하게 되는거인데 Swift에서 서로 다른 컬렉션간의 계산을 허락해준게 신기하네요.
> 
> `Set`의 `intersection` 메소드의 매개변수에는 `Sequence` 프로토콜을 채택한 애가 오면 되기 때문인데요, 아래 링크를 참고해주세요. https://academy.realm.io/kr/posts/try-swift-soroush-khanlou-sequence-collection/
> 
> > 3. 함수에서 매개변수 기본 값을 미리 지정할수 있는것처럼 내가 찍은 번호 배열을 myLottoNumbers 변수에 할당할때 6개의 번호만 할당할 수 있는 간결한 코드가 없을지 궁금하네요.
> 
> 음... 이건 어떤걸 의도하신건지 잘 모르겠어요 나중에 디코에서 얘기를 나눠보도록 해요.
> 
> 나머지는 코멘트로 남겼습니다!

2022-03-04 12:16 UTC, 1Consumption requested changes
코멘트 확인 부탁드리겠습니다.

2022-03-04 12:16 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +makeMyAutoLottoNumbers()
코드를 복붙하라는 말이 아니었습니다.
`매소드를 재사용 할 수 있는가?` 라는 관점에서 다시 생각해주세요.
메소드를 재사용 하려면 지금 형태로는 불가능 할겁니다. 특정 변수에 직접 접근하고 있으니까요.
그렇다면 이 메소드를 어떻게 바꿔야할까요?
랜덤 넘버를 생성만 하고 반환해주는 역할을 하면 어떨까요?

2022-03-11 11:08 UTC, closed without merging