3 dino12
yagom-academy/swift-starter-week2 pull request #158
Opened 2022-03-07 13:28 UTC by Jun-12

@1Consumption 

1. 먼저 로또의 회차를 저장하는 round 변수를 만들어 주었습니다. 로또 당첨을 확인할 때마다 회차가 올라가도록 `generateLottoNumbers` 메소드를 만들어 한 번 당첨을 확인할때 `round = round + 1` 이 되도록 했습니다.

2. 그 후에 로또 회차와 번호를 저장하는 `lottoIndicator` 딕셔너리를 만들고` generateLottoNumbers`를 5번 반복하고 각 회차와 로또 번호를 `lottoIndicator`에 저장하도록 하였습니다. 

3. `lottoIndicator` 중 2회차의 로또 당첨번호를 찾도록 `showSecondRound` 메소드에서 옵셔널 값을 안전한 `if-let`을 통해 추출하였습니다. 

4. 또 2회차 로또 번호도 마찬가지로 대괄호 없이 출력해야 하므로, `removeBrackets`를 `compare`에 국한되지 않게 하기위해 매개변수를 만들어 `lottoNumbers`도 호출될 수 있게 해주었습니다.

2022-03-08 14:32 UTC, 1Consumption requested changes
늦어서 죄송합니다ㅠㅠ

코멘트 확인 부탁드리겠습니다!

2022-03-08 14:32 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +    myLottoNumbers = makeRandomSixNumbers()
이번 미션은 로또 회차를 저장하는거 아닌가요?

2022-03-08 14:32 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +        lottoIndicator[round] = lottoNumbers
메소드에서 반환을 받아 딕셔너리에 저장하면 어떨까요? 지금은 전역 변수의 값을 바꾸고 전역변수에 접근하고있네요.

2022-03-09 07:14 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +}
헉 오타라니.. 그것도 두번이나 나서 에러가 안떴었군요.. 바로 수정하겠습니다😂

2022-03-09 07:14 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +    round = round + 1
저렇게 사용하는게 코드 길이가 더 짧아지니 좋겠네요!

2022-03-09 07:20 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +        print(someSet, terminator: " ")
네이밍을 잘못했군요.. 수정해보겠습니다!

2022-03-09 07:30 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +    myLottoNumbers = makeRandomSixNumbers()
그 말씀은 기존에 작성한 코드를 왜 수정했냐는 뜻이신가요..? 아니면 먼저 수정하지 않고 이번 미션에서 수정한 이유를 물어보시는건가요?

2022-03-09 07:30 UTC, Jun-12 commented on CodeStarterCamp_Week2/main.swift
> +        lottoIndicator[round] = lottoNumbers
말씀하신대로 수정해보겠습니다!

2022-03-09 10:04 UTC, Jun-12 commented
우선 피드백 감사드립니다!!😄

몇가지 여쭤보고 싶은 것들이 있는데, 

첫 번째는 "이번 미션은 로또 회차를 저장하는거 아닌가요?"라고 말씀하셨는데, 이 질문의 의미를 잘 모르겠습니다! 기존에 작성한 코드를 왜 수정했냐는 뜻이신지 아니면 전 단계에서 수정하지 않고 이번 미션에서 수정한 이유를 물어보시는 것인지 말씀해주시면 감사하겠습니다..

두 번쨰는 수정하는 과정에서 궁금했던점이 있습니다. 마지막에 피드백 주신 것처럼 메소드 내에서 전역변수에 접근하지 않고 반환받은 값을 lottoIndicator 딕셔너리에 할당하도록 하였습니다. 그런데 할당을 하는 것만으로도 confirmTheWin이 작동하는 부분이 잘 이해가 가질 않았습니다. generateLottoNumbersFiveTimes 메소드에 confirmTheWin 메소드가 포함되지만, 할당하는 것 만으로도 출력이 가능한가요? 결론적으로는 generateLottoNumbersFiveTimes 메소드를 실행하는 부분을 삭제하고 할당만 해주었습니다.

세 번쨰는 이번 미션과는 좀 동떨어진 내용이기는 하지만, compare 메소드에 관련된 질문입니다.
```Swift
func compare(mine: Set<Int>, thisWeek: Set<Int>) -> Set<Int> {
    let intersection: Set<Int> = myLottoNumbers.intersection(lottoNumbers)
    return intersection
}
```
이 메소드의 경우 사실 
```Swift
let intersection: Set<Int> = myLottoNumbers.intersection(lottoNumbers)
```
이 부분이
```Swift
let intersection: Set<Int> = mine.intersection(thisWeek)
```
이런식으로 매개변수들의 교집합을 할당하는 방식으로 작성하려고 했습니다만, 이렇게 할 경우 매개변수에 계속 다른 값을 할당함에도 불구하고 교집합이 매번 같은 값들이 나온다고 생각했는데 제가 놓치고 있는 부분이 어떤 부분인지 피드백 해주시면 감사하겠습니다..!!

2022-03-10 11:48 UTC, 1Consumption commented
> 첫 번째는 "이번 미션은 로또 회차를 저장하는거 아닌가요?"라고 말씀하셨는데, 이 질문의 의미를 잘 모르겠습니다! 기존에 작성한 코드를 왜 수정했냐는 뜻이신지 아니면 전 단계에서 수정하지 않고 이번 미션에서 수정한 이유를 물어보시는 것인지 말씀해주시면 감사하겠습니다..

아 별 뜻은 없었어요. 단지 매번 본인의 로또번호를 갱신하고 있는거 같아서 여쭤봤어요. 불필요한 동작을 여러번 하는 느낌이 들었거든요.

> 두 번쨰는 수정하는 과정에서 궁금했던점이 있습니다. 마지막에 피드백 주신 것처럼 메소드 내에서 전역변수에 접근하지 않고 반환받은 값을 lottoIndicator 딕셔너리에 할당하도록 하였습니다. 그런데 할당을 하는 것만으로도 confirmTheWin이 작동하는 부분이 잘 이해가 가질 않았습니다. generateLottoNumbersFiveTimes 메소드에 confirmTheWin 메소드가 포함되지만, 할당하는 것 만으로도 출력이 가능한가요? 결론적으로는 generateLottoNumbersFiveTimes 메소드를 실행하는 부분을 삭제하고 할당만 해주었습니다.

``` swift
func generateLottoNumbersFiveTimes(mine: Set<Int>, thisWeek: Set<Int>) -> [Int: Set<Int>] {
    var indicator: [Int: Set<Int>] = [:]
    for _ in 1...5 {
        generateLottoNumbers(mine: mine, thisWeek: thisWeek)
        indicator[round] = lottoNumbers
    }
    return indicator
}

func generateLottoNumbers(mine: Set<Int>, thisWeek: Set<Int>) {
    chooseAllNumbers()
    confirmTheWin(mine: mine, thisWeek: thisWeek)
    round += 1
}
```

위 코드가 작성해주신 코드인데요, generate 메소드 내부에서 confirmTheWin 메소드를 호출하고 있네요. 

세번째 질문은 잘 이해를 하지 못하겠네요. 이부분은 디스코드에서 얘기를 나눠봐도 될까요?

2022-03-11 09:18 UTC, Jun-12 commented
@1Consumption 

디스코드로 여쭤보려고 했는데 오프라인이셔서 여기에 여쭤볼께요!! 오늘이 피드백 받을 수 있는 마지막날이라고 하셔서..ㅠㅠ

우선 generate 메소드 내부에서 confirmTheWin 메소드를 호출하고 있지만 저는 generate 메소드를 실행시키지 않았고
```Swift
lottoIndicator = generateLottoNumbersFiveTimes(mine: myLottoNumbers, thisWeek: lottoNumbers)
showSecondRound()
```
위처럼 마지막 두 줄의 코드에서 첫 번째는 lottoIndicator에 값을 할당하는 부분이고, 두 번째는 옵셔널 값을 추출하는 부분인데 이렇게만 작성해도 confirmTheWin 메소드가 작동되는 이유가 궁금합니다. 

그리고 세 번쨰 질문의 경우
```Swift
func compare(mine: Set<Int>, thisWeek: Set<Int>) -> Set<Int> {
    let intersection: Set<Int> = myLottoNumbers.intersection(lottoNumbers)
    return intersection
}
```
지금은 위처럼 compare 메소드가 작성되어 있습니다. 하지만 이렇게 작성하기 전에 제가 작성했던 compare 메소드는
```Swift
func compare(mine: Set<Int>, thisWeek: Set<Int>) -> Set<Int> {
    let intersection: Set<Int> = mine.intersection(thisWeek)
    return intersection
}
```
이렇게 였습니다. myLottoNumbers 대신 매개변수 mine을, lottoNumbers 대신 매개변수 thisWeek을 넣어둔 상태였죠. 하지만 이렇게 작성을 하고 실행을 시키니까 compare 메소드가 교집합을 구하지 못하더군요.. 이것을 5번 반복하는 generateLottoNumbersFiveTimes를 거치면 "아쉽지만 겹치는 번호가 없습니다." 를 5번 출력했습니다. 꼭 메소드 내에 직접 myLottoNumbers와 lottoNumbers를 넣어주어야 제대로 된 교집합을 구하던데 그 이유가 궁금하다는 얘기였습니다. 혹시 좀 더 설명이 필요한 부분이 있으신가요?

2022-03-11 11:08 UTC, closed without merging