[Week2] Step2 둘리
yagom-academy/swift-starter-week2 pull request #170
Opened 2022-04-19 06:42 UTC by yuvinrho

@leeari95 
# Step2 

## 로또번호 생성 함수 생성
func lottoNumberGenerator() -> [Int]

1. 생성된 로또 번호를 담을 Int 배열타입 변수를 선언합니다.
2. while 문을 이용하여 로또번호 배열 카운트가 6개보다 작으면  random 함수를 사용해 1~45사이 로또 번호를 생성하여 로또번호 배열에 추가합니다. 만약 중복된 번호면 로또번호 배열에 추가하지 않고 다시 로또 번호를 생성합니다.
3. 6개에 중복되지 않은 로또번호가 완성되면 리턴합니다.

## 로또번호 체크 함수 생성
func lottoNumberChecker(compare lottoNumber: [Int], with myLottoNumber: [Int])

로또번호 생성 함수에 의해 생성된 로또번호와 내 로또번호를 비교하여 맞은 번호를 출력해주는 함수를 만들었습니다.
로또 번호를 비교하여 맞은 번호를 체크한다는 의미로 함수 이름과 네이밍을 지었는데 의미가 잘 전달 될까요?ㅠ 영어가 짧아서 이름짓기 어렵습니다.ㅠㅠ

1. 함수 매개변수로 로또번호 배열과 내 로또번호 배열이 들어갑니다.
2. hitNumbers 라는 String 배열타입 변수를 만들어서 맞은 번호들을 저장했습니다. 원래는 Int 배열타입 변수로 만들었습니다. 그런데 맞은 번호를 출력하니 '축하합니다! 겹치는 번호는 [2 ,3 ,5] 입니다!' 이런형태로 번호가 대괄호 안에 출력되었습니다. 과제에서는 대괄호 없이 출력되야하기 떄문에 이 대괄호를 없애기 위해 고민을 많이했고 시간도 엄청 걸렸습니다.ㅠㅠㅠㅠ 고민한 결과 String 배열을 만들어서 맞은 숫자들은 String타입으로 변환하여 저장하였습니다. 그리고 이 String 배열타입을 joined 함수를 사용하여 String으로 변환하였고, 각 숫자 사이에는 구분자는 seperator:" ," 로 설정하여 step2 요구사항과 같게 출력하였습니다. 혹시 더 쉬운 방법이 있을까요? 간단한 방법이 있는데 제가 너무 어렵게 생각한것인지 궁금합니다~~

2022-04-19 07:43 UTC, leeari95 requested changes
둘리 안녕하세요~ 😆
벌써 스텝2 까지 구현하시다니.. 대단하세요! 정말 고생 많으셨어요~ 👏🏻

아래 의견들과 코멘트들은 어디까지나 정답은 아니니까 꼭 참고만 해주셨으면 좋겠어요.

## 칭찬 드리고 싶은 부분

* 요구사항에 맞게 출력하시려고 고민하신 흔적이 보여요. 👍🏻
* argument label을 적극 활용해보셨네요 👍🏻
* 순서도의 흐름과 같은 흐름이여서 코드 읽기가 수월했어요 👍🏻

## 저의 의견

* 네이밍 의미 자체는 좋은 것 같아요. 다만 swift api design guidelines에 따르면 변수는 명사, 함수는 동사로 짓는 것이 규칙이에요. 문서를 다시 한번 읽어보면 좋을 것 같습니다 😊 ([참고링크](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage))
* `joined()` 메소드로 문제를 심플하게 잘 해결해보신 것 같은데요?  또다른 방법이 있긴 합니다! [reduce](https://developer.apple.com/documentation/swift/array/2298686-reduce)를 활용하면 [Int] > [String]으로 변환, 쉼표와 함께 String으로 변환까지 한꺼번에 해결해볼 수도 있습니다!
	* 앗 그리고 separator가 `" ,"`가 아니라 `", "`여야 되지 않을까요?

이 외 자세한 피드백은 코멘트로 남겨드렸으니 확인해주시면 될 것 같습니당! 🙏🏻
혹시 코멘트에 대한 의문점이나 질문사항이 있다면 바로바로 DM 부탁드리겠습니다!
(코멘트보다 빠른 답변을 받으실 수 있어요!)

고생 많으셨습니다!

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    }
만약 정말 운이 안좋아서 random한 숫자가 10번이상 중복된다면 이 로직은 과연 효율적인 걸까요?
이런 불필요한 반복을 줄이기 위해서는 어떤 방법이 좋을까요?
힌트를 드리자면... 
[Swift - shuffled()](https://developer.apple.com/documentation/swift/array/2994757-shuffled)
이 함수를 활용해보세요!!!!
화이팅!

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    var numbers: [Int] = []
numbers는 어떤 숫자들인지 유추가 어렵습니다. 더 좋은 이름은 없을까요?

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +func lottoNumberGenerator() -> [Int] {
명사형입니다. 이 함수에는 명사이름이 어울리지 않는듯합니다. 😊

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +func lottoNumberChecker(compare lottoNumber: [Int], with myLottoNumber: [Int]) {
argument label을 잘 활용해보셨네요. 멋집니다!!! 😁👏🏻
그런데 이 함수이름도 명사형이네요. 다시한번 고민해볼까요? 🥺

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    }
함수가 로또번호 체크도 하고... 결과값도 출력하고 있네요.
제가 보기엔 함수가 두가지의 기능을 하고 있는 것 같은데, 기능별로 분리해보면 좋을 것 같네요! 🤔

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +
불필요한 공백은 지워주시는게 좋습니다. 😉

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    else {
else를 중괄호 바로 옆에 적지않고 줄바꿔 적은 이유가 궁금합니다! 🤔

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    //print(numbers)
테스트 코드는 꼭꼭 PR보내기 전에 점검해서 지워보도록 합시당! 😁

2022-04-19 07:43 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +
이 공백도 필요할까요???
공백에도 이유가 있어야해요. 중요합니다! 
이유없는 코드를 적지 않도록 습관을 들여봅시다! 💪🏻

2022-04-20 01:41 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +    }
힌트 감사합니다!! shuffled() 함수를 사용하여 1~45 숫자를 섞은 후 숫자 6개만 가져오도록 함수를 수정하여 숫자가 중복되었는지 따로 확인할 필요가 없어져서 코드가 깔끔하게 되었습니다~

2022-04-20 01:43 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +    var numbers: [Int] = []
lottoNumber 변수하나만으로 1~45숫자 셔플하여 6개 가져온 값을 저장하도록 수정하였습니다~

2022-04-20 01:46 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +func lottoNumberGenerator() -> [Int] {
아이고ㅠㅠ 자꾸 잊어버리고 제마음대로 이름을 짓게 됩니다. 항상 이름짓는 방법을 생각하면서 짓겠습니다~

2022-04-20 01:47 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +func lottoNumberChecker(compare lottoNumber: [Int], with myLottoNumber: [Int]) {
checkLottoNumber 로 이름을 동사형으로 수정하였습니다~

2022-04-20 01:50 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +
네 불필요한 부분은 삭제하였습니다~

2022-04-20 01:51 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +    else {
앗.. 이유는 없습니다ㅎㅎ 이제부터 중괄호 옆에 바로 적도록 하겠습니다~

2022-04-20 01:51 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +    //print(numbers)
네~~ 감사합니다

2022-04-20 01:53 UTC, yuvinrho commented on CodeStarterCamp_Week2/main.swift
> +
공백에도 이유가 있는지 몰랐습니다ㅎㅎ 불필요한 부분은 지우고 항상 이유를 생각하여 적도록 하겠습니다!

2022-04-20 06:54 UTC, leeari95 approved these changes
수정사항 잘 확인했습니다.
제 의견을 적극 반영해주셔서 정말 감사드려요. 🙏🏻
둘리가 너무 잘해주셔서 저도 너무 기쁘네요!
더이상 문제없어서 머지해드릴게요. 🤗 다음 스텝도 화팅이에요!! 💪🏻

2022-04-20 06:54 UTC, merged