Mission2: Step2: 내 번호와 맞추어보기!
yagom-academy/swift-starter-week2 pull request #172
Opened 2022-04-19 13:56 UTC by wolframhwang

@llghdud921 
안녕하세요 제리!

자꾸 야밤에 PR 드리는 것 같아서 좀 죄송해지네요;;

이번엔 Step2 숙제를 해결한 패치를 Pull Request합니다.

1. 네이밍에 신경을 쓰려고했습니다.
    - 함수는 최대한 동사로 사용하려고 했습니다.
    - 변수, 상수들은 최대한 명사, 그리고 직관적으로 알아보기 쉽게 하려고 했습니다.
2. 함수를 많이 나눴습니다.
   - 랜덤넘버 생성기, 로또 생성기, 당첨 번호 생성기 마지막으로 내 로또 결과를 알아볼수 있는 함수로 까지 나눴습니다.
   - map이 있어서 map을 사용했습니다.

> 아쉬운점: 랜덤 넘버 생성 시, 아무래도 미스매칭되면 시간복잡도가 많이 늘어나는 거같은데 안좋은 프로그램을 만든 것 같다는 생각

2022-04-20 17:44 UTC, llghdud921 requested changes
안녕하세요! 제리입니당
늦게 리뷰드려 너무 죄송합니다,, 이해해주셔서 감사드려요! ☺️

### Good
- 네이밍 완벽합니다... 💯
- 말씀해주신 대로 함수를 잘 분리해주셨어요! 요구사항에 나와있는 것 이상으로 더 노력하신 것 같아서 너무 좋았습니당 👍 

### 조언 드릴 부분
> 아쉬운점: 랜덤 넘버 생성 시, 아무래도 미스매칭되면 시간복잡도가 많이 늘어나는 거같은데 안좋은 프로그램을 만든 것 같다는 생각

이 부분이 저도 아쉽다고 생각했어요! 
현재 `isUseNumber`를 이용하여 45개의 Bool값을 가진 배열에 계속해서 접근하는 방식인데요
이 부분은 시간복잡도 측면에서 효율적이지 못할 것 같다는 생각이 들어요
음... 다른 방법을 생각해보자면 Set이라는 중복값이 허용되지 않는 Collection type을 이용해 발생한 넘버가 배열에 존재하는지? 계속 체크해보는 방법이 있지 않을까 합니다 
개선이 되면 전역변수도 없어지고 코드도 간결해지고 이래저래 좋아지지 않을까욥...
꼭 정답은 아니에요! 지금도 잘~ 돌아갑니당ㅎㅎ

그리고 앞 스텝에서 따로 말씀을 안드렸는데 로또만드는 구현부 파일을 main.swift가 아닌 lotto.swift 파일로 분리하고 main.swift 코드 실행부만 넣으면 코드 관리가 쉽지 않을까 합니당!! :)

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func generateRandomNumber() -> Int{
```suggestion
func generateRandomNumber() -> Int {
```
아래 함수들은 잘 작성해주셨는데 두개의 함수가 컨벤션에 맞지 않네용 개선해보아요!!

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func generateLotto() -> [Int]{
[Int] 배열을 반환하고 있으므로 generateLottoNumbers라는 네이밍이 더 명확할 것 같습니다~
이번 스텝에서는 반환값을 가지는 함수를 작성해보았는데요! 반환값을 고려하여 네이밍해보는 습관을 들이시면 좋을 것 같네요 :)

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    var lotto: [Int] = [Int](repeating: 0, count: lottoCountLimit)
전 이러한 형식을 처음보는데 쌉고수시군요...? 🤭
저는 Array(repeating: 0, count: lottoCountLimit) 형식만 사용해보았었는데요... 정말 궁금해서 여쭤보는데 이거 어떻게 알게되셨나요...? (자동완성도 안되던데...)
자료형도 명확하고 너무 좋아보이네요!!

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    var winningNumbers: [Int] = []
네이밍 굿 💯

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func getMyLottoResult() -> String {
get보다는 함수내부에서 String을 print하여 `printMyLottoResult` 요렇게 하는 것이 조금 더 명확할 것 같습니다!

2022-04-20 17:44 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +                .joined(separator: ", ")
map과 joined를 사용하시다니.... 👍 
심지어 축약형을 사용하지 않아 더 코드가 읽기 쉬워요!!

2022-04-20 22:33 UTC, wolframhwang commented
@llghdud921 
안녕하세요 제리!

> get보다는 함수내부에서 String을 print하여 printMyLottoResult 요렇게 하는 것이 조금 더 명확할 것 같습니다!

이부분에 대한 네이밍 리팩토링을 진행했습니다.

> 저는 Array(repeating: 0, count: lottoCountLimit) 형식만 사용해보았었는데요... 정말 궁금해서 여쭤보는데 이거 어떻게 알게되셨나요...? (자동완성도 안되던데...)

이 부분은 오히려 제가 C/C++만 했어서, Array 써서 할당하는게 불편하더라고요..?
그래서 찾다보니 이러한 방식도 있다더라~ 라는 글을 스치듯 본것같아요
자세히는 저도 잘모르겠습니다 ㅎㅎ;

> 아래 함수들은 잘 작성해주셨는데 두개의 함수가 컨벤션에 맞지 않네용 개선해보아요!!

랜덤함수 만드는 부분을 아예 바꿔버려서, 함수를 지우기로 했습니다 ㅎㅎ 


항상 리뷰 감사드립니다.
그리고, 이틀동안 고생하셨습니다!

2022-04-21 05:05 UTC, llghdud921 requested changes
빠르게 리팩토링 해주셨네요!!
간단한 코멘트 남겨두었으니 확인 부탁드립니다 :)

2022-04-21 05:05 UTC, llghdud921 commented on CodeStarterCamp_Week2/MyLottoNumber.swift
> +let lottoNumberSet = [Int](1...45)
```suggestion
let lottoCountLimit = 6
let lottoNumberLimit = 45
let lottoNumberRange = 1...lottoNumberLimit
let lottoNumberSet = [Int](lottoNumberRange)
```
사용하지 않는 변수가 있네요! 위에처럼 쓰려고 했던 것일까요..?

2022-04-21 05:05 UTC, llghdud921 commented on CodeStarterCamp_Week2/MyLottoNumber.swift
> +let lottoNumberSet = [Int](1...45)
위 네가지 변수는 `generateLotto`내에 있어도 괜찮을 것 같습니다!
해당 변수들은 전역변수인데 프로그래밍할때 지양하는데요 그 이유는 코드 어디서나 접근할 수 있어 변수가 섞일 수도 있고 저장되어있는 값을 파악하기 어렵습니다. 
전역변수가 아닌 지역변수로 개선해보는 것이 좋을 것 같아요 :)

2022-04-21 05:56 UTC, wolframhwang commented
@llghdud921 
안녕하세요 제리

언급주신 부분이 두개 정도로 생각이되는데요,
1. 상수, 함수에 컨텍스트 맞추기
2. Bound변수에 사용하지 않는 상수로 범위잡기

이 두 부분 수정사항이 반영된 패치를 pr합니다~

2022-04-21 10:15 UTC, llghdud921 commented
리팩토링하신거 잘 보았습니다~ 역시👍
다음 스텝으로 가시죠~~~ 🥳

2022-04-21 10:16 UTC, merged