Week2 [Step2] Lily
yagom-academy/swift-starter-week2 pull request #183
Opened 2022-04-21 04:07 UTC by hililyy

안녕하세요!! Step2 PR 드립니다!!😆

2022-04-21 04:47 UTC, leeari95 requested changes
릴리님 안녕하세요! 👋🏻
스텝2을 빠르게 구현해주셨네요! 😄
이번엔 몇가지 피드백 드릴게 있어서 코멘트를 많이 남겨드렸는데, 
혹시 궁금한 사항이나 어려운점이 있다면 DM 부탁드릴게요!
고생많으셨습니다!

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +        let winNumber = Int(arc4random_uniform(45) + 1)
Swift 4.2 이후에는 랜덤한 난수를 뽑으려먼 어떤 함수를 사용해야할까요?

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +        if !winLottoNumbers.contains(winNumber) {
만약 운이 정말 나빠서 같은 숫자가 중복으로 뽑히게 된다면...
의도된 횟수만큼 반복할까요?
불필요한 반복을 줄이기 위해서는 어떤 방법이 있을까요?

> 힌트: [Swift - shuffled()](https://developer.apple.com/documentation/swift/array/2994757-shuffled)

해결이 어렵다면 다음에 고민해봐도 괜찮아요. 😊

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +        for _count in 0...5 {
Swift API Design Guidelines에서는 네이밍을 [어떤 case](https://www.swift.org/documentation/api-design-guidelines/#general-conventions)로 지으라고 되어있던 것 같은데..
그리고 이름이 언더바 하나로 구분지을 수 있을까요?
저는 무슨 뜻인지 전혀 모르겠어요! 🤔

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    }
이 함수는 로또번호를 검사도하고... 결과도 출력하는 것 같네요?
함수가 두가지의 기능을 하는 것 같아요.
기능별로 쪼개볼 수 있을까요?

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +var myWinLottoNumbers: [Int] = []
전역에서 변수를 이렇게 관리하는 것 보다
함수의 파라미터와 반환값을 이용해보는 것은 어떻게 생각하세요?

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +            }
음.. index 때문에 for문을 이중으로 사용하신 걸로 보여지네요.
이중 반복문은 코드의 해석을 난해하게 하는 주범이 되기도해서 보통은 지양하는 편이에요.
이것보다 더 좋은 방법이 있을 것 같은데요!!! 😁
위에서 사용했던 contains 함수를 써보는 건 어떨까요?
아니면 [enumerated](https://developer.apple.com/documentation/swift/array/1687832-enumerated)라는 함수도 활용해볼 수 있을 것 같네요~

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +        for count in 0...myWinLottoNumbers.count-1 {
```suggestion
        for count in 0..<myWinLottoNumbers.count {
```

이렇게도 가능할 거 같은데요?

2022-04-21 04:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +            count < myWinLottoNumbers.count-1 ? print("\(myWinLottoNumbers[count])", terminator: ", ") : print("\(myWinLottoNumbers[count])", terminator: " ")
로또번호를 이미 위에서 검사를 하지 않았나요?
그런데... 여기서도 반복문을 돌면서 count가 myWinLottoNumbers보다 작은지 확인하면서 출력하는 것 같네요?

바로 myWinLottoNumbers 배열을 String 타입으로 변환해서 출력해줄 수는 없을까요?

2022-04-21 05:12 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +        let winNumber = Int(arc4random_uniform(45) + 1)
Int.random(in: 1...45)라고 적어야 하네요!! 수정하겠습니다!!

2022-04-21 05:20 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +        if !winLottoNumbers.contains(winNumber) {
고민해보겠습니다..!! 🥺

2022-04-21 05:49 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +        for _count in 0...5 {
네 수정하겠습니다!!!

2022-04-21 05:49 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +    }
쪼개서 다시 해 볼게요!!!

2022-04-21 05:50 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +var myWinLottoNumbers: [Int] = []
뭔가 안좋은 습관이 들어 있는 것 같네요 ㅠㅠ.. 수정하겠습니다!!

2022-04-21 05:50 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +        for count in 0...myWinLottoNumbers.count-1 {
감사합니다🥺🥺🥺

2022-04-21 05:51 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +            }
아.. 이중 반복문을 자주 사용해서 몰랐네요 ㅠㅠ.. 다시 수정해보겠습니다!!!

2022-04-21 05:52 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +            count < myWinLottoNumbers.count-1 ? print("\(myWinLottoNumbers[count])", terminator: ", ") : print("\(myWinLottoNumbers[count])", terminator: " ")
이 부분은 번호를 출력할 때 마지막 번호만 ','가 없어서 이렇게 해보았어요..!! 다른 방법으로 수정해보겠습니다!!!!  감사합니다!😆😆

2022-04-25 14:47 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    var resultString: String = ""
타입 추론을 사용하시지 않고, 명시를 해주신 점이 너무 좋네요! 최고에요!! 👍🏻

2022-04-25 14:48 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +            if myWinLottoNumbers.first == result {
이 부분은 전역변수를 바로 참조하는 것 보다,
전달받은 파라미터를 참조해도 될 것 같은데요?
```suggestion
    if winNumber.isEmpty {
        print("아쉽지만 겹치는 번호가 없습니다.")
    } else {
        for result in winNumber {
            if winNumber.first == result {
```

2022-04-25 14:52 UTC, merged

2022-04-25 15:01 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +var myWinLottoNumbers: [Int] = checkLottoNumbers(winLottoNumbers: winLottoNumbers, myLottoNumbers: myLottoNumbers)
var와 let을 구별해서 사용해야 되는데 적용을 잘 못하네요 ㅠ.ㅠ  다음에는 유의해서 작성하겠습니다!

2022-04-25 15:02 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +        if !winNumbers.contains(winNumber) {
짧게 쓰는게 더 좋은 코드라는 생각을 무의식적으로 하고 있던것 같아요! 읽는 사람의 입장에서도 많이 고민해봐야겠네요🤔 알려주셔서 감사합니다😆

2022-04-25 15:05 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(winLottoNumbers: [Int], myLottoNumbers: [Int]) -> [Int] {
네이밍이 정말 어려운것 같아요... 가독성 좋은 네이밍도 많은 고민을 해보겠습니다! 감사합니다!!!

2022-04-25 15:10 UTC, hililyy commented on CodeStarterCamp_Week2/main.swift
> +            if myWinLottoNumbers.first == result {
헙 그렇네요... 전역변수로 선언했으니까 굳이 파라미터로 전달해줄 필요도 없었던것같기도 하네용.. 
알려주셔서 감사합니다!!!🤣