Week2 [STEP 3] inho
yagom-academy/swift-starter-week2 pull request #184
Opened 2022-04-21 04:37 UTC by inho-98

@ye-ha 
## Step 3 과제 PR입니다!
### 과제 리뷰 (Step2에서 바뀐점)
- 11번 코드에 회차를 담기 위한 변수를 선언했습니다.
- 12번 코드에 회차와 로또 당첨번호를 담을 빈 Dictionary 를 선언했습니다.
- `createLottoNumbers` 함수를 실행할때마다 이전 회차에 +1 을 하고, 새로 만든 `storeLottoNumberList` 함수를 호출합니다.
#### `storeLottoNumberList` 함수 구현
- 로또를 생성할 때 회차가 증가하는걸 감안해서 Dictionary에 키값을 추가할 때 문자열 보간법을 이용했습니다.
- 오름차순으로 정렬된 결과를 출력하기 위해 미리 `lottoNumbers.sorted()` 해주었습니다.
#### `findLottoNumberList` 함수 구현
- 회차를 정수타입 매개변수로 받아서 원하는 회차의 로또번호를 출력하도록 구현했습니다.
- Dictionary에서 값을 안전하게 가져오기 위해 `if let` 옵셔널 바인딩을 이용했습니다.
- print의 결과롤 배열을 출력할 때 대괄호 없이 원소만 출력하기 위해 우선 map을 이용해서 정수 타입 배열을 문자열 배열로 바꾸고,
그 문자열 배열에 joined 메서드를 적용했습니다.
- 회차 범위 밖의 숫자를 입력했을 때 출력될 메세지를 추가했습니다.
#### `repeatCreatingLotto` 함수 구현
- 로또 번호를 여러번 생성할 때 함수를 이용하면 편리할것 같아서 반복할 횟수를 매개변수로 받는 함수를 만들었습니다.
- 반복문 내부에서는 로또 번호를 생성하고, 내 번호와 비교하고, 결과를 보여주는 함수들을 호출합니다.
---
### 고민했던 점
- 모든 함수에서 함수의 역할을 알 수 있도록 네이밍과 argument label을 정했습니다.
- 이전 PR에서 `checkWinning` 네이밍에 명사가 붙는 아이디어를 주셔서 생각해봤는데, lotto나 number이 적합한것 같으면서도
뒤에 매개변수 이름으로 중복되어서 일단은 그대로 두었습니다..!
- 과제 설명에는 `2회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다.`식으로만 나오면 된다고 했는데, 생성한 로또 번호들을 보여주고 싶어서`repeatCreatingLotto`의 실행결과로 보이도록 했습니다. (61, 62번 코드를 주석처리하면 보이지 않게 가능합니다!)
---
### 해결되지 않은 점
- 51번 코드에서 map 메서드와 그 뒤에 클로저 부분을 문서들을 참고해서 만들었는데
```
let stringWinningNumbers = winningNumbers.map { number: Int -> String in
            String(number)
        }
``` 
이 코드의 클로저 부분을 `{ String($) }` 으로 축약하긴 했지만 원래 코드에서 어떤 부분이 어떤 기능을 하는지 완전히 이해하진 못했습니다..!

---
### 조언을 얻고싶은 부분
- 네이밍에 신경을 많이 쓰긴 했는데, 몇몇 이름이 좀 겹치는게 어쩔수 없는지, 그리고 적절하게 이름이 지어진건지 궁금합니다! (너무 길지도 않고 정보가 부족하지도 않은지..?)
- 60번 61번 코드를 주석처리하고 `createLottoNumbers`함수만 반복해서 로또 번호를 생성하고 결과는  `2회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다.` 이런 식으로만 보여주고싶을때 59번 코드에서 `createdLottoNumbers` 값을 사용하지 않는다고 노란색 경고가 뜨는데, 그게 함수들이 매개변수를 주고받는 상황이라 어쩔 수 없는지, 더 나은 방법을 찾을만 한지 궁금합니다!

2022-04-22 09:31 UTC, ye-ha requested changes
인호님, 이번 스텝도 고생 많으셨습니다! 
스텝마다 발전하는 모습이 멋집니다. 👍

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
선언하는 스타일을 통일하는건 어떨까요?

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또가 아직 진행되지 않았습니다.")
51번 코드에서 stringWinningNumbers라는 상수를 새로 만드신 이유가 있나요? 
더불어 53번 코드에서는 상수를 만들지 않고 보간법을 사용하신 이유가 있나요?

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +    lottoWinningNumberList["\(round)회차"] = lottoNumbers.sorted()
`winningNumber`가 이기는 숫자로 해석이 되는데, 약간 어색하게 느껴져요.

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +var lottoWinningNumberList = [String: [Int]]()
딕셔너리를 사용하셨군요. 👏👏👏👏

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +func repeatCreatingLotto(for times: Int) {
어떤 의미로 함수 네이밍을 하신지 이해했지만.. repeat가 함수 이름이 들어가니 어색하게 느껴져요! 반복한다는 의미를 빼보는건 어떨까요? 🤔

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        showResult(use: sameNumbers)
1. 질문 주신, 61-62번 코드를 삭제했을 때 60번 코드에서 노란 에러가 뜨는 부분은 인호님이 해결하실 수 있답니다. 힌트: 60번에서 `createLottoNumbers`함수의 반환값을 할당해주고 있습니다. 
2. 과정을 출력하는 함수를 만드신 것, 멋집니다! 👍 다만, 요구하는 기능보다 더 많은 기능을 만들었을 때 오버 엔지니어링이 될 수 있답니다.

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +findLottoNumberList(of: 2)
`findLottoNumberList(of: 2)` 저는 이 부분이 두 라운드를 진행한다는 의미보다는 다른 의미로 읽히는데, 어떻게 생각하시나요?

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +repeatCreatingLotto(for: 5)
`repeatCreatingLotto(for: 5)` 이 부분을 읽었을 때 어떤 의미인지 확 와닿지 않습니다. 🤔

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +    if let winningNumbers = lottoWinningNumberList["\(round)회차"] {
`if let`을 사용하셔서 안전하게 옵셔널을 처리한 부분, 아주 좋습니다! 👍👍👍👍

2022-04-22 09:31 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        let stringWinningNumbers = winningNumbers.map { String($0) }
저는 이해하고 사용하는 것이 좋다고 생각해요. 현재 사용한 코드를 왜 이렇게 작성했는지 이해할 수 있도록 조금씩 공부해보시는 것을 추천드립니다!

2022-04-23 05:39 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또가 아직 진행되지 않았습니다.")
지난 스텝에서 joined 쓴 이유랑 같은데, 제가 선택한 방법은 [Int]을 [String]으로 바꾸고 joined 메서드를 사용하는 것이었습니다!
그걸 보여주기 위해 `stringWinningNumbers` 변수를 선언해서 담았습니다.
그래서 51번, 52번 코드를 
```
var stringWinningNumbers = [String]()

for winningNumber in winningNumbers {
    stringWinningNumbers.append(String(winningNumber))
}

print("\(round)회차의 로또 당첨 번호는 \(stringWinningNumbers.joined(separator: ", ")) 입니다.")
```
이런 식으로도 똑같이 출력이 가능한데, 같은 코드가 map으로도 가능해서 적용했습니다.
그런데..!! 생각해보니까 굳이 변수 선언하고 따로  하지 않고,  map과 joined 메서드를 한번에 쓸수 있을 거라는 생각이 스쳐서 적용해보니까 잘 작동해서 아래처럼 코드 수정했습니다..! 😆
`print("\(round)회차의 로또 당첨 번호는 \(winningNumbers.map({ String($0) }).joined(separator: ", ")) 입니다.")`

2022-04-23 05:40 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +    lottoWinningNumberList["\(round)회차"] = lottoNumbers.sorted()
음.. winning number 이라는 말이 당첨 번호 의미로도 쓰여서 사용했는데 혹시 수정하는게 나을까요..!

2022-04-23 05:49 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +repeatCreatingLotto(for: 5)
과제 설명대로 로또 생성을 5번 실행한다는 의미로 사용했는데, 의미 전달이 모호한것 같아서
`runLottoCreation(for: 5)` 로 수정했습니다! 의견한번더 부탁드립니다 😀

2022-04-23 05:50 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +        let stringWinningNumbers = winningNumbers.map { String($0) }
map을 사용하지 않고 의도대로 코드를 작성할 수는 있어서 클로저를 사용해봤고, 표현식과 경량화문법 공부하고 익히는 중입니다! 🙂

2022-04-23 05:58 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +findLottoNumberList(of: 2)
함수에 대한 부연설명을 조금 하자면(이해하셨을 수도 있지만..!) 
<img width="632" alt="스크린샷 2022-04-23 오후 2 54 48" src="https://user-images.githubusercontent.com/71054048/164881060-6195897b-720d-4d62-9755-0d828468d1a6.png">
사진에서 요구사항을 정해진 숫자대로만 하지 않고, 예를들어 로또번호 10회 생성과 그중 8회차 로또 출력 과 같이 기능을 더 구현하기 위함이었습니다! 그래서
`repeatCreatingLotto(for: 5)` 함수는 로또 번호생성을 5번 진행한다는 뜻이고,
`findLottoNumberList(of: 2)` 함수는 로또 5번 진행으로 생성된 당첨번호 리스트 중 두번째 요소를 찾는 함수의 의미로 사용했습니다.
제가 따로 설명을 해야하는게 좋지 않은 네이밍인것 같아서 일단 argument label 을 of 에서 at으로 수정했는데 함수 이름도 의미가 아직 모호할까요..?!

2022-04-23 06:00 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +func repeatCreatingLotto(for times: Int) {
반복한다는 의미 대신 실행한다는 의미로 `runLottoCreation(for times: Int)` 로 수정했습니다! 이 네이밍은 어떤가요..? 🤔

2022-04-23 06:42 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +        showResult(use: sameNumbers)
61번 62번 코드를 사용한 이유로, 지난 스텝의 결과도 이어서 사용하고, 또 만들어 놓은 함수를 쓰지 않는게 아쉬워서 넣었는데, 다시 생각해보니까 함수가 어떤 기능을 하는 코드를 묶어두고 원할때 함수 이름만 호출해서 사용하는 강한 장점이 있으니까 구현해 놓은 함수를 꼭 사용할 필요가 없다는 생각도 들었습니다! 그래서 함수 호출은 주석처리하고,  `let createdLottoNumbers = createLottoNumbers()` 부분은
 `let _ = createLottoNumbers()` 대체했습니다! (`createLottoNumbers` 의 결과가 쓰이지 않아서)
출력 결과는 `2회차의 로또 당첨 번호는 3, 22, 31, 34, 37, 44 입니다.` 와 같이 남습니다 🙂
오버 엔지니어링 얘기도 해주셔서 내용을 한번 찾아봤습니다. 👍

2022-04-25 00:31 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
고민해 봤는데, 질문의 의미를 잘 모르겠습니다..! 🥲

2022-04-25 08:07 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
13번 상수만 타입이 명시되어 있습니다!

2022-04-25 08:12 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또가 아직 진행되지 않았습니다.")
좋습니다! 
그렇다면 질문드려 볼게요. 
다른 사람이 인호님의 코드를 보았을 때, 
1. 기존의 51번 코드처럼 할당받는 값의 의미를 담은 이름의 상수,
2. 인호님이 수정해주신 `print("\(round)회차의 로또 당첨 번호는 \(winningNumbers.map({ String($0) }).joined(separator: ", ")) 입니다.")`
어떤 코드가 더 읽기 쉬울 것이라고 예상하시나요?

2022-04-25 08:15 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +    lottoWinningNumberList["\(round)회차"] = lottoNumbers.sorted()
아, 파파고를 돌려 보니 winning number라고 나오는군요. 저는 [winning의 사전적 정의](https://en.dict.naver.com/#/entry/enko/35f3ecace03443898b34744ef1028db6) 때문에 형용사로 읽혀서 어색하다고 생각했어요. 🤔

2022-04-25 08:17 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +func repeatCreatingLotto(for times: Int) {
전보다 좋습니다. 😄 
다만.. 반복과 마찬가지로 실행한다는 의미의 run도 잘쓰지 않는 것 같아요 🤔 
추가로 무엇을 생성하는지 더 자세하게 써주면 좋습니다. 네이밍이 구체적인게 좋아요!

2022-04-25 08:18 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        showResult(use: sameNumbers)
좋습니다. 😄 
특정 함수의 리턴값이 쓰이지 않는다면 꼭 리턴을 해야 할까요?

2022-04-25 08:26 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +findLottoNumberList(of: 2)
글처럼 읽힐 수 있도록 아규먼트 레이블을 사용하는 것이기 때문에 호출 부분만 생각해서 보자면.. 
기존에는 find lotto number list of 2, 
변경해주신 at을 적용했을 때는 find lotto number list at 2 입니다.
흠.. 영어가 모국어가 아니기도 하고, 어순이 바뀐 이런 상황에서는 네이밍이 좀 힘들더라고요  🤔 
뒤에 나오는 2가 어떤 것에서 비롯된 2인지 명확하게 알리기 위해서 아규먼트 레이블을 제거하는 것도 방법일 수 있을 것 같아요.

2022-04-25 08:27 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +repeatCreatingLotto(for: 5)
우선, 전보다 좋습니다! 👍 윗 코멘트에 의견 남겼으니 참고해주세요 ㅎㅎ

2022-04-25 08:44 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
말씀해 주시니까 이제야 보이네요..!ㅎㅎ 통일하겠습니다!

2022-04-25 08:44 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또가 아직 진행되지 않았습니다.")
다른 사람이 보기엔 지금 코드가 가독성도 떨어지고 이해하기 어려울것 같습니다!
그래서 아래처럼 상수에 값을 할당한 다음 문자열 보간법으로 상수를 대입하는게 좋을것 같습니다.
```
let stringWinningNumbers = winningNumbers.map{ String($0) }.joined(separator: ", ")
print("\(round)회차의 로또 당첨 번호는 \(stringWinningNumbers) 입니다.")
```

2022-04-25 08:46 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +        showResult(use: sameNumbers)
리턴을 남겨뒀던 이유가 Step1 에서 작성한 순서도에 '값을 반환한다' 라는 부분이 있었어서 통일성을 유지하고 싶었는데, 
코드만 보자면 없애는것도 좋고, 순서도도 고려하면 남겨도 될것같고,, 이유 없이 남겨둔건 아니어서 괜찮을것 같은데 어떻게 생각하시나요? 🤔

2022-04-25 08:48 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +findLottoNumberList(of: 2)
가독성이 목표라고 생각하면 아규먼트 레이블을 지우는 것도 좋은것 같습니다!
그렇게 되면 find lotto number list round 2 정도가 되는데, 이것도 조금 아쉽긴 하지만 at 이나 of 만 쓰인것보단 전달력이 더 나은것 같아요!

2022-04-25 08:54 UTC, inho-98 commented on CodeStarterCamp_Week2/main.swift
> +func repeatCreatingLotto(for times: Int) {
`playLotto(for times: Int)` 라는 네이밍이 의도를 잘 나타낸다고 생각되는데 어떤가요..? 이름은 짧아도 의미가 더 잘 와닿는것 같아서요..!

2022-04-25 10:34 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또가 아직 진행되지 않았습니다.")
좋습니다! 하나 더 말씀드리면, string이라고 써주신 부분은 저는 주로 `converted` 같은 변환되었다는 의미를 담는 편입니다! 😄

2022-04-25 10:34 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +func repeatCreatingLotto(for times: Int) {
좋습니다! 😄

2022-04-25 10:37 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +        showResult(use: sameNumbers)
사용하지 않는 코드는 지우는게 좋습니다. 😄 이번 스텝에서 추가된 내용을 순서도에 반영하는 과정이 없었기 때문에, 지난 스텝까지의 순서도라고 생각하시면 될 것 같아요!

2022-04-25 11:03 UTC, merged