Week2 [Step 3] Onestar
yagom-academy/swift-starter-week2 pull request #186
Opened 2022-04-21 07:58 UTC by oneStar92

@oksunwoo 

# Step 3: 로또 당첨 번호를 회차별로 저장하고, 확인하자!

# Todo
- [x] 회차와 Lotto번호들을 저장하는 Dictionary 타입 변수를 생성합니다.
  * "1회차": [1, 2, 3, 4, 5, 6]와 같은 Key와 Value를 가집니다.
  ```swift
  var pastWinningLotteries = [String: [Int]]()
  ```
  위 코드는 Dictionary타입의 컬렉션의 변수를 pastWinningLotteries즉 지나간당첨복권들로 Naming하였습니다.
- [x] Step 2의 로또 당첨 번호 생성 함수를 호출할 때마다, 회차의 로또 번호를 Dictionary에 저장하고자 합니다.
  * 새로운 로또 당첨 번호를 생성하면, 직전 회차에 1을 더해 금번 회차를 만들어냅니다.
  * 회차를 Key로, 새로운 로또 당첨 번호를 Value로 하는 Dictionary에 저장합니다.
  ```swift
  func appendWinngLottery(to pastWinningLotteries: inout [String: [Int]], by key: String, and value: [Int]) {
    pastWinningLotteries[key] = value
  }
  ```
   우선 appendWinningLottery to pastWinningLotteries by key and value로 Naming한 함수입니다. 즉 당첨복권을 지나간 당첨 복권들에 키와 값으로 첨부한다라는 의미를 가지고 있습니다. 해당 함수는 전달받은 pastWiiningLotteries의 주소값에 해당하는 Dictionary컬렉션에 전달 받은 Key로 Value값을 추가합니다.
   또한 요구사항인 새로운 로또 번호를 생성하고 해당 회차의 로또 번호를 Dictionary에 저장하는 기능을 추가하기위해 이전에 작성한 generateWinningLottery함수에 코드를 추가적으로 아래와 같이 작성하였습니다.
  ```swift
  func generateWinningLottery(times: Int, appendTo pastWinningLotteries: inout [String: [Int]]) -> Array<Int> {
    var winningLottery = Set<Int>()
    var sortedWinningLottery = [Int]()
    for _ in 1...times {
      while winningLottery.count < 6 {
        winningLottery.insert(Int.random(in: 1...45))
      }
      sortedWinningLottery = winningLottery.sorted()
      appendWinngLottery(to: &pastWinningLotteries, by: "\(pastWinningLotteries.count+1)회차", and: sortedWinningLottery)
    }
    return sortedWinningLottery
  }
  ```
   times파라미터는 몇번의 당첨 번호를 생성할 것인지 결정하는 파라미터 입니다. 당첨번호가 생성되면 appendWinngLottery함수를 호출합니다. 값을 추가 할 Dictionary 컬렉션의 주소를 to 파라미터로 전달하고, key 파라미터는 "\(pastWinningLotteries.count+1)회차"로 전달합니다. 그 이유를 예를 들어 설명하면, 현재 pastWinningLotteries에 2회차 까지 저장되어 있으면 해당값은 "\(2+1)회차"입니다. 즉, 직전의 회차 = Dictionary Count랑 일치함으로 위의 요구사항인 직전 회차에 1을 더해 금번 회차를 만들어 낸다는 것은 Dictionary Count에 1을 더해서 금번 회차를 만드는 것과 같다고 생각하여서 위와같이 코드를 작성했습니다. 생성된 당첨 번호는 value 파라미터로 전달됩니다. 이렇게 하여서 당첨 번호가 생성될 때마다 해당 값을 Dictionary 컬렉션에 추가하게 됩니다.
- [x] 로또 당첨 번호를 생성한 후 Dictionary에 저장된 로또 당첨 번호를 확인해봅니다. 
  * 로또 당첨 번호를 5번 생성합니다.
  ```swift
  let winningLottery = generateWinningLottery(times: 5, appendTo: &pastWinningLotteries)
  ```
  * Dictionary에서 2회차의 로또 당첨 번호를 찾습니다.
    * Optional 값을 안전하게 추출합니다.
  ```swift
  if let lotteryNumbers = pastWinningLotteries["2회차"] {
    print("2회차의 로또 당첨 번호는 \(changeIntArrayToString(target: lotteryNumbers)) 입니다.")
  } else {
    print("해당 회차는 아직 추첨되지 않았습니다.")
  }
  ```
  위 코드는 옵셔널 바인딩을 이용해서 안전하게 값을 추출하는 코드입니다. 상수 lotteryNumbers에 "2회차" 키에 해당하는 값이 입력되게 되는데 만약에 "2회차"키에 해당하는 값이 있으면 if문 안에 코드를 수행하게 되고 값이 없는 경우에는 else문 안의 코드를 수행하게 됩니다.
  * Dictionary에서 추출한 2회차 로또 당첨 번호를 6개를 아래와 같이 출력합니다.
  ```  
  2회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다.
  ```
  위와 같은 형태로 출력하게 코드를 작성했습니다.

# 궁금한점
 Step2에서 마지막에 코멘트 주신 것에 대해 생각을 많이 했습니다. 변수,상수의 선언에도 컨벤션을 정하고 해당 컨벤션을 지켜야 한다고 하셔서 저도 제가 편한 방법으로 사용하고자 현재 코드에서 선언과 파라미터 그리고 반환값에 저만의 컨벤션을 정하고 지키려고 노력해봤습니다. 그런데 지금 제가 작성한 코드가 일치하는지 헷갈려서 질문드립니다.
 우선 12, 13번 줄을 보면 var winningLottery = Set<Int>()와 var sortedWinningLottery = [Int]() 형태로 선언 하였는데 Set 컬렉션은 선언문이 저런 방법밖에 되지 않더라고요. 변수 뒤에 :를 붙여서 선언하는 형식은 사용하지 않고 = 뒤에 값을 넣어주거나 선언하는 형식을 사용하려고 위와 같이 코드를 작성하였습니다. 근대 Set 컬렉션 때매 뭔가 컨벤션이 어긋나 보이는데 어떻게 해야 될지 잘 모르겠습니다. 현재 사용하는 방법이 맞는지 아니면 Set<Int>() 때문에 전부 Array<Int>()형식으로 바꿔야 하는지 잘 모르겠네요...
 저도 함수 파라미터 같은 경우는 컨벤션을 잘 지켜서 작성한것 같습니다. 반환 값은 정확하게 명시하는게 좋을 것 같아서 그렇게 작성하였습니다.

2022-04-22 09:11 UTC, oksunwoo requested changes
### 질문에 대한 답변
그렇게 Set과 같은 경우는 예외를 둬도 괜찮습니다! 전반적인 원스타만의 코딩 컨벤션을 확립해나가고, 또한 추후에 있을 협업 시 서로 컨벤션 규칙을 정하고 그것을 지키는 것을 목표로 하고 있기에, 코드에서의 통일성이 있고 왜 그렇게 했는지에 대한 이유가 있다면 괜찮습니다! Set과 같은 경우는 축약형이 없어서, 원래 형식을 가져다 썼다는 이유가 되겠죠?!

---
전반적으로 코드의 논리는 좋은 것 같습니다만, 이번 코드 자체는 틀린코드 같네요 ^^;
수정 부탁드리겠습니다!
그리고 커밋단위는 메서드 별로 잘게 쪼개보는 것도 좋을 것 같습니다!
refactor를 하게 된다면, refactor 단위 별로 쪼개는 것도 좋겠죠?
고생하셨습니다 원스타!

2022-04-22 10:19 UTC, oneStar92 commented on CodeStarterCamp_Week2/main.swift
>      }
헉..! 초기화를 다시 안해줬네요... 해당 부분 수정하였습니다!

2022-04-22 10:29 UTC, oneStar92 commented on CodeStarterCamp_Week2/main.swift
> +func generateWinningLottery(times: Int, appendTo pastWinningLotteries: inout [String: [Int]]) -> Array<Int> {
inout 키워드가 저는 C언어에서 사용 되는 포인트 개념으로 접근하고 이해하고 있습니다.
설명을 하자면 Inout은 값에 의한 전달이 아닌 참조에 의한 전달로 swift는 파라미터가 상수이며 전달 받은 파라미터의 값을 변경할 수 없는데 이를 변경할때 Inout을 사용하면 값이 전달된게 아닌 해당 파라미터의 메모리 주소자체를 전달하기 때문에 이를 통해서 전달된 파라미터의 값을 수정할 수 있는 것 으로 알고있습니다.
&의 경우는 참조 타입. 즉, 메모리의 주소를 나타내는 것으로 같습니다!
현재 inout없이 코드를 작성하였습니다

2022-04-22 10:30 UTC, oneStar92 commented on CodeStarterCamp_Week2/main.swift
> +}
messageWithExtractedNumbers에 담아서 프린트하는 방식으로 다시 코드를 작성하였습니다.

2022-04-22 10:38 UTC, oneStar92 commented
# 수정사항
- [x] 모든 회차가 다 같은 번호로 입력되는 현상. var winningLottery = Set<Int>()를 함수 호출 시 선언하는 방식에서 for문에서 선언하는 방식으로 변경 후 해당 현상 해결.
- [x] inout 사용. inout없이 반환값을 [[Int]]로 변경하여서 생성된 복권번호를 Array 컬렉션에 담은 후 반환하는 방식으로 바꿈. 이를 활용하여 함수 호출 후 반환되는 값에서 for 문을 활용하여 내부에 담겨온 복권번호를 회차에 따라 추가하는 형태로 변경.
- [x] 반환값 컨벤션. 해당 comment확인 후 comment의 의견을 반영하여 코드를 다시 작성.
- [x] 프린트 부분 메서드를 활용. messageWithExtractedNumbers에 메시지를 답아서 프린트 하는 형태로 코드 수정.
위 와 같이 comment 주신 부분 수정하였습니다.

2022-04-25 08:04 UTC, oksunwoo reviewed
우선 코드의 논리적인 부분은 훌륭합니다! 아주 잘 해주셨는데, 51~65번 라인까지의 가독성이 많이 떨어져보입니다.
그 전 50번라인까지의 부분들은 func() 이용해서 잘 분리해주셨는데, 해당 부분도 한번 분리해보시는게 어떨까요? 어떻게 하는 것이 좋을까요? 이 부분은 많은 고민이 필요할 것 같기도 하네요! 메서드 작성할 때 가장 중요한 부분이기도 한 부분인데요. 힌트를 드리자면 기능별, 역할별로 잘 분리해보세요! 그렇게 된다면, 이미 훌륭한 코드에서 더 짜임새 있는 코드가 완성될 것 같습니다.

2022-04-25 10:05 UTC, oneStar92 commented on CodeStarterCamp_Week2/main.swift
> +}
코드 작성 당시 guard를 사용하여 옵셔널 바인딩을 하려고 사용하였습니다.
현재는 guard를 사용하지 않아서 해당 부분은 삭제하였습니다.

2022-04-25 10:12 UTC, oneStar92 commented
일단 나누어서 Commit을 못했네요... 생각한 후 한참 막 코드를 작성하고 나니 commit생각이 나서... 너무 늦어서 그냥 한번에 다 commit하였습니다. 
* attachWinningLotteries 함수를 추가하여서 dictionary 컬렉션에 append해주는 식의 기능을 구현 하였습니다.
* checkMyWinningResults 함수는 Step2의 출력 결과를 받는 함수입니다.
* receiveMessage 함수는 원하는 회차의 당첨 번호를 받아오는 Step3의 출력 결과를 받는 함수입니다.
제 나름대로 작성은 해봤습니다...

2022-04-25 14:48 UTC, oksunwoo reviewed
<img width="559" alt="스크린샷 2022-04-25 오후 11 45 30" src="https://user-images.githubusercontent.com/55880539/165113665-ad41a89d-9f2a-44fc-9523-55d14d635e2c.png">

예상 결과가 다르군요! 코드에 오류가 있네요^^;
이 부분과 34번 라인 present 오타 수정하고 DM 주세요ㅎㅎ

2022-04-26 08:16 UTC, merged