Week2 [STEP2] jeongmin(정민)
yagom-academy/swift-starter-week2 pull request #190
Opened 2022-04-21 10:09 UTC by jeongmin-l

@jaemuYeo 

잼킹! 안녕하세요! 😊
2주차 스텝2 PR요청 드립니다

순서도의 수정이 조금 있었고
당첨번호와 찍은번호를 확인하는 함수의 네이밍과 인자레이블 네이밍,
반복문의 변수 이름에 대해서 number라는 이름보다 좋은 이름은 없을지,
맞춘 번호를 출력하는 부분에서 좀 더 간단하고 명확한 방법이 없을까 고민 했습니다.

저로서는 최대한 명확하고 간단하도록 짜봤는데 더 좋은 방법이 있지 않았을까 궁금합니다! 🤔

2022-04-21 15:45 UTC, jaemuYeo requested changes
안녕하세요 정민님 !! Week2의 스텝2도 고생하셨습니다!
네이밍과 띄어쓰기, 줄바꿈 등이 많이 발전된 것이 보여요 👍

좀 더 간결하게 작성할 수 있는 방법에 대한 제 생각은
랜덤한 숫자를 생성할 때 Set을 통해 중복된 값을 담지않고 6개의 숫자를 담았죠?
그럼 유저가 선택한 숫자와 로또당첨번호와도 Set을 통해 구현할 수 있을 거 같아요!
그리고 `joined(separator:)` 메서드에 대해 알아보시면
불필요한 for문도 제거할 수 있을 거 같습니다!

2022-04-21 15:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    var lottoTray = Set<Int>()
함수 네이밍에는 numbers라는 복수형을 사용하였는데
이 Set타입의 변수는 복수형을 사용하지 않으신 이유가 있으신가요!!

2022-04-21 15:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    repeat {
while 문이 아닌 repeat-while문을 사용하신 이유가 궁금합니다!🤔

2022-04-21 15:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +func checkMyLottoNumbers(from myNumbers: Array<Int>, to winNumbers: Set<Int>) {
checkMyLottoNumbers함수가 너무 많은 기능을 담고 있는거 같아요!
최소 2개 이상의 작업을 하는 거 같습니다!
더 쪼개볼 수 있을까요??

2022-04-21 15:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: Array<Int> = [1,2,3,4,5,6]
배열에 값을 넣을 때 `[1, 2, 3, 4, 5, 6]` 와 같이 쉼표뒤에 한칸 띄어쓰기를 한답니다 😉

2022-04-21 15:54 UTC, jeongmin-l commented on CodeStarterCamp_Week2/main.swift
> +    var lottoTray = Set<Int>()
generateLottonumbers함수에서 6개의 넘버들을 생성하니 number들을 담아주는 그릇 이라는 느낌으로 Trays가 아닌 Tray를 사용했습니다. 여러 로또회차를 생성한다면 Trays를 썼을 것 같은데 조금 잘못된 접근 방법 이었을까요..?🥲

2022-04-21 16:01 UTC, jeongmin-l commented on CodeStarterCamp_Week2/main.swift
> +    repeat {
그렸던 순서도에서 먼저 번호를 생성해서 집어 넣었기 때문에 순서도 대로 구현을 하려고 해 보았습니다.
이번주에 새로 배워본 repeat-while문도 한번 써보고 싶었구요..👍 사실 이게 조금 더 컸던 것 같습니다... 수정하는 것이 좋을까요?

2022-04-21 16:04 UTC, jeongmin-l commented on CodeStarterCamp_Week2/main.swift
> +        let pickedRandomNumber = Int.random(in: 1...45)
기능 별로 함수를 쪼갠다! 다시 한번 명심하겠습니다!

2022-04-21 17:05 UTC, jeongmin-l commented on CodeStarterCamp_Week2/main.swift
> +func checkMyLottoNumbers(from myNumbers: Array<Int>, to winNumbers: Set<Int>) {
생각하지 못했던 부분입니다 😭 확실히 두가지 이상의 기능을 하는 것 같습니다
쪼개보겠습니다! 👍

2022-04-21 17:05 UTC, jeongmin-l commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: Array<Int> = [1,2,3,4,5,6]
좋은 피드백 감사합니다!! 😊

2022-04-22 13:18 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    var lottoTray = Set<Int>()
이유에 대해 궁금했었습니다!! 😉

2022-04-22 13:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    repeat {
아주 좋은 시도였어요! 👍
다만 순서도와 코드의 흐름을 봤을 때 while문이 더 좋은 방법인 것 같습니다!
혹여나 repeat-while문을 사용할 때 연산이 들어가면 결과값도 바뀔 수 있다는 점도 주의해주세요!

2022-04-22 13:30 UTC, jaemuYeo reviewed
정민님 Step2 정말 고생많으셨습니다!
몇 가지 내용들은 코멘트를 통해 남겨놓았어요~
처음 작성한 코드보다 가독성도 훨씬 좋아지고, 함수의 기능분리도 아주 멋져요!!
이번 스텝 머지 진행하겠습니다!! 수정하실 내용 있으시면 수정 후 
다음 스텝으로 넘어가주세요🙂

2022-04-22 13:30 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    return Int.random(in: 1...endNum)
return 값은 상수 또는 변수에 담아 return 하는 방법도 좋은 방법입니다! 참고만 해주셔요 !
또하나의 팁은 특별한 기능없이 이렇게 단일 return문일 경우 return 키워드를 작성하지 않아도 된답니다!
다만 한 곳이 아니라 전체적인 통일성을 지켜주세요!

2022-04-22 13:30 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    return winNumbers.intersection(myNumbers).map { String($0) }.sorted(by: <)
sorted()로만 작성해도 오름차순이 되지 않을까요?
map의 활용 아주 멋집니다 !👍

2022-04-22 13:30 UTC, merged