Week2 [Step2] 윤세영
yagom-academy/swift-starter-week2 pull request #191
Opened 2022-04-21 10:51 UTC by ssyoun4092

@oksunwoo 

> ## 6자리 로또 당첨번호 생성
+ week2 Optional 수업에서 '!'으로 강제추출하지 않는다고 되어있었네요ㅠ 강제추출한 부분은 수정해보겠습니다!

> ## 찍은 번호와 로또 당첨 번호가 일치하는지 검사하기
+ 가장 고민했던 점은 겹치는 번호를 print 할 때 배열타입으로 나오는 문제를 해결하는 것이었습니다.
+ 예를 들면 "겹치는 번호는 [1, 3, 4] 입니다!"라고 출력되었습니다. 따라서 배열에 있는 숫자를 String타입으로 변환하고 출력하였습니다.
    + 'func convertStringArray' 부분인데.. 뭔가 코드가 깔끔하다는 느낌은 받지 못했습니다. 좀 더 나은 코드가 있는지 여쭤보고 싶습니다!

> ## 고민사항
+ compare 함수내에 for문도 있고, 별도의 다른 함수가 있고, if문까지 있는데 이러한 부분들은 함수 밖으로 빼내서 별도의 함수로 만들고, compare 함수 내에서는 밖으로 빼낸 함수를 호출하는 식으로 코드를 작성하는게 더 유리한지 알고 싶습니다!
+ 예를 들면
```swift
func A() {
    
    func B() {
        
    }
    
    func C() {
        
    }
}
```
에서 
```swift
func A() {
    
    B()
    
    C()
}

func B() {
    
}

func C() {
    
}
```
이런식으로요!

2022-04-22 10:41 UTC, oksunwoo requested changes
세영님 이번스탭도 고생많으셨어요!

### 고민사항
convert 부분이 자연스럽다고 느끼지 못하신 것은 2가지 중 하나 같은데
1. `"\(num)"` 의 사용이라고 생각이 듭니다! 문자열 보간법이 어떤 용도인지에 대해 공부해보시길 추천드릴게요! 타입을 바꾸는 방법에는 무엇이 있을지 한번 검색해보시길 추천드립니다!
2. 고차함수의 사용으로 인한 것 같으신데요! 고차함수는 정말 어려운 개념입니다... 만약 잘 알고계신다면 상관없지만, 잘 모르시겠다면 해당 부분 for문으로 바꾸시는 거 추천드릴게요!

세영님께서 어색하실 것 같은 이유 2가지를 제가 생각해보았는데, 해당 부분이 아니라면 편하게 DM 주시거나 코멘트 달아주세요!

---
### 질문 사항
함수에 대해 적어주셨는데요!
음.. 일반적으로 중첩시키기보단  아래와 같은 방식으로 많이 사용합니다!
a안에서 함수를 생성,호출을 다 한다면, 추후 b기능만 필요한 경우, 불필요하게 a를 호출하는 경우가 생길 수 있겠죠? 좋은 질문입니다!

```swift
func a() {
b()
c()
}

func b() {
}

func c() {
}

```

마지막으로 커밋은 메서드 단위로 잘게 쪼개서 해보는 것은 어떨까요?? 지금은 조금 번거로울 수 있겠지만, 한번 추천드릴게요!

2022-04-22 10:41 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +    }
여기서 고차함수를 사용해주셨네요! 고차함수가 무엇인지 알고 계신가요? 더불어, map이 어떤 것인지 설명 부탁드릴게요~

2022-04-22 10:41 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +compare(myLottoNumbers, with: lottoNumbers)
보통 실행부분의 흐름대로 코드를 읽어내려가는 편인데, myLottoNumbers와 lottoNumbers를 찾으려하니까 코드의 맨위에 위치하더라구요! 이렇게 짧은 코드의 경우는 금방 찾을 수 있지만, 1000줄이 넘어가는 코드일 경우에는 맨위에까지 올라갔다가 다시 내려오는 것이 조금 번거롭게 느껴질 것 같은데요~
어디쯤 위치하면 좋을지 한번 생각해보시는 것도 좋을 것 같네요!

2022-04-22 10:41 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +let totalLottoNumbers: [Int] = Array(1...45)
totalNumbers를 전역으로 선언해주셨는데, 현재 코드에서는 쓰이는 곳이 특정 함수내부에서만 사용을 하고 있습니다! 혹시 이렇게 전역으로 선언하신 이유가 있으실까요?

2022-04-22 10:41 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +
여기만 띄어쓰기 컨벤션이 다른 것 같은데요!

2022-04-22 10:41 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(containNumbersWithString.joined(separator: ", "))입니다!")
요구사항과 띄어쓰기가 살짝 다른 것 같아요~

2022-04-25 04:27 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +        let newNumber = totalLottoNumbers.randomElement()
넵 shuffled이라는 함수를 사용했더니 Optional없이 사용가능했습니다!

2022-04-25 04:31 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +            lottoNumbers.append(newNumber!)
언랩핑하는 방법 중에 강제 언랩핑을 하는 방법이 있고, 옵셔널 바인딩이라는 방법이 있습니다
강제 언랩핑은 위의 코드처럼 뒤에 '!'를 사용하는 방법인데, 이 방법의 문제점이라면, Optional을 언랩핑 했을 때 nil값이 존재한다면 'fatal Error'의 에러가 발생하여 앱이 꺼지는 사태가 발생합니다.

반면 옵셔널 바인딩을 사용하면 nil값이 있을 때와 없을 때 두 상황을 고려하여 코드를 작성할 수 있기 때문에 혹시나 nil값이 존재하더라도 유연하게 대처가 가능합니다. 따라서 안전한 옵셔널 바인딩 방법을 사용하여 Optional 타입을 언랩핑 하는것이 좋습니다!

2022-04-25 04:43 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +    }
고차함수란, 매개변수를 함수로 갖는 함수를 뜻합니다. 지금까지 함수를 구현할 때 함수의 매개변수는 string, Int와 같은 타입으로 받았지만, 사실 함수라는 타입으로 매개변수를 받을 수 있습니다. 이는 스위프트에서 함수를 일급객체로 취급하기 때문입니다!

+ Map
map은 매개변수로 전달된 함수를 실행하고, 결과를 반환해주는 함수입니다. 제가 작성한 map을 예로 들면, (num: Int) -> String 이라는 타입을 매개변수로 받고, "\(num)"이라는 결과를 반환하고 있습니다.사실 for 문으로도 구현이 가능하지만, 코드의 재사용 측면이나 컴파일러 최적화 측면에서 map이 for문보다 유리합니다!(야곰님의 책을 참고했습니다!)

+ map을 for문으로 구현
```swift
func convertStringArray2(from array: [Int]) -> [String] {
    var convertedStringArray: [String] = [ ]
    for num in array {
      convertedStringArray.append(String(num))
    }
    return convertedStringArray
  }
```

2022-04-25 04:44 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +compare(myLottoNumbers, with: lottoNumbers)
실행되는 함수 위에 위치하는 것이 보기 좋을 것 같습니다!

2022-04-25 04:45 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +let totalLottoNumbers: [Int] = Array(1...45)
따로 이유는 없고, 우선 코드를 작성할 때 반드시 있어야 하는 것부터 작성하다보니 전역으로 선언된 것 같습니다. 특정 함수 내부에서만 쓰이는 변수/상수는 함수 내부에 작성하는게 나을 것 같습니다!

2022-04-25 04:45 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +
이 부분.. 이해를 못하겠습니다ㅠ 아무리봐도 띄어쓰기 컨벤션이 여기만 다른게 어느 부분인지 찾지를 못하겠습니다ㅠ

2022-04-25 04:45 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(containNumbersWithString.joined(separator: ", "))입니다!")
넵! 수정했습니다!

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
>  var lottoNumbers: [Int] = []
여기에서 lottoNumber 배열은 왜 맨위에 두셨나요~

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +
현재 이 메서드는 중첩이 되어있는데요~
혹시 중첩하신 이유가 있으신가요?

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +  lottoNumbers = totalLottoNumbers
새로운 방식으로 구현을 하셨네요!
 shuffle과 removeSubrange 두개의 역할을 간단하게 설명부탁드립니다!

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +  print(lottoNumbers)
현재 메서드의 이름은 pick으로 로또번호를 추첨하는 곳으로 예상이 되는데요!
print는 출력의 기능으로 pick 과는 관계가 없어보이네요!

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +
pickLottoNumbers 메서드를 살펴보면 공백이 없는 것을 확인할 수 있는데요!
해당 compare함수는 16, 18, 24.. 등등 공백이 있네요!
세영님만의 컨벤션은 무엇인가요?

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +  }
이 부분 역시 compare 메서드 내부에 있는 것으로 보이는데, 해당 기능들은 compare를 하는 것처럼은 안보입니다!
지금은 좀 번거로우실 수 있어도, 코드를 작성할때 이렇게 메서드를 역할별, 기능별로 분리하고 고민하는 연습을 하신다면 추후에는 짜임새있는 코드를 완성하실 수 있으실거에요!

2022-04-25 08:26 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> -pickLottoNumbers()
pickLottoNumbers()는 해당 메서드를 `실행`하는 코드죠!
코드의 순서가 pick `구현` -> pick `실행` -> compare `구현`
이러한 순서로 되어있는데요! 얼핏 보기에는 오류를 바로 찾을 수 있을 것 같아보입니다
만약 로또번호를 30번 추첨하게 되면 pick의 실행코드는 어디에 위치해야할까요? 구현부 중간중간에 실행코드를 작성해놓으면 나중에는 찾기 힘들어질수도있고, 실행부분에서 오류가 발생했는지 찾기 힘들어질 수도 있습니다! 
구현부 --> 실행부 이렇게 작성해보는 것은 어떨까요? 메서드가 기능별로 잘 작성되어있고, 네이밍까지 완벽하다면, 실행부만 읽고서도 어떤 역할을 하는 프로그램인지도 대충 짐작할 수 있게되지않을까요?

2022-04-25 10:34 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
>  var lottoNumbers: [Int] = []
lottoNumber은 바로 아래 pickLottoNumbers라는 함수에서 사용하기 때문에 맨 위에 두었습니다. 
또한 마지막에 compare함수에서 호출 할때에도 전달인자로 사용하기 때문에 사용하였습니다!

맨위에 두지 않는다면
```swift
func pickLottoNumbers() {

  var lottoNumbers: [Int] = []
  var totalLottoNumbers: [Int] = Array(1...45)

  totalLottoNumbers.shuffle()
  totalLottoNumbers.removeSubrange(6...(totalLottoNumbers.count-1))
  lottoNumbers = totalLottoNumbers
}
/*
생략
*/
compare(myLottoNumbers, with: pickLottoNumbers())
```
이렇게 작성해야 될것 같은데 이런 방법이 조금 더 나을까요?

2022-04-25 10:41 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +  lottoNumbers = totalLottoNumbers
shuffle은 해당 배열에 들어있는 값을 무작위로 섞고 재배열하는 메소드입니다!
즉, 여기서는 45개의 숫자가 배열안에서 무작위로 섞이고 다시 배열됩니다. 또한 기존에 있는 값들로만 섞는 것이기 때문에 Optional타입으로 반환되지 않습니다.
removeSubrange는 해당 배열의 인덱스의 범위를 지정하여 그 범위에 있는 값들을 삭제합니다.

정리하자면, 저는 shuffle()을 통해 무작위로 숫자를 배열하고, 
로또 번호는 총 6자리이기 때문에 removeSubrange를 이용하여 index가 6부터 마지막 인덱스까지 삭제하였습니다.
이를 통해 0, 1, 2, 3, 4, 5번의 인덱스를 가진 무작위 숫자 6개를 생성하였습니다!

2022-04-25 10:42 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +  print(lottoNumbers)
넵!! 수정하겠습니다!

2022-04-25 10:47 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +
아하...!! 저는 띄어쓰기를 변수, 함수, if나 for문 등 덩어리(?) 별로 띄어서 쓰는게 개인적으로 깔끔해 보여서 그렇게 하고 있습니다!
또한 함수 생성하고 첫줄은 띄우고, return할 때는 return 전에 한칸 띄우고 사용하고자 합니다!

2022-04-26 05:17 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +  }
넵! 출력하는 함수로 별도로 만들어서 compare 메소드 안에서 호출하는 식으로 수정해보았습니다

2022-04-26 05:17 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +
compare 함수를 호출할 때 반드시 숫자배열의 array를 string으로 변환해줘야 필요한 반환값이 생성되기 때문에 넣었습니다.
따로 함수를 밖으로 빼서 compare함수에서는 호출만 하는게 나을까요?

2022-04-26 05:18 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> -pickLottoNumbers()
훨씬 좋은 생각인것 같아요! 구현부 -> 실행부 순으로 다시 함수들을 배치해보았습니다!

2022-04-26 08:47 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
>  var lottoNumbers: [Int] = []
아니면 실행부로 위치를 옮겨도 되겠죠? 저는 구현부와 실행부의 분리를 말씀드리고 싶었습니다!

2022-04-26 08:49 UTC, oksunwoo commented on CodeStarterCamp_Week2/main.swift
> +
저는 굳이 compare안에서 print랑 convert 역할을 하지 않아도 될 것 같은데요~
어떻게 전달할 지 방법에 대한 고민이 있으시다면 return 타입의 활용도 괜찮을 것 같아요

2022-04-26 09:06 UTC, oksunwoo reviewed
고생하셨습니다 세영님!

코드의 논리도 좋고, 구현부와 실행부가 분리되어 있는 모습도 좋습니다. 읽고 따라가기 좋은 코드였습니다. 다만, 컨벤션에 관해 한말씀 드리고 싶은데, 너무 많은 공백은 가독성을 저하시키기도 합니다. 현재 세영님의 코드에는 시작 시 두칸, 메서드 명 뒤 한칸, 변수선언 한칸, for 또는 if 뒤 한칸, return 전 한칸 이런 식으로 꽤 많은 공백을 볼 수 있는데요.. 
여기서 메서드정도는 공백을 줄여보는 게 어떨까요?
<img width="610" alt="스크린샷 2022-04-26 오후 5 28 17" src="https://user-images.githubusercontent.com/55880539/165263970-610bd301-98a1-40fe-ad69-f83be6633439.png">

해당 사진은 swift 공식문서에서 발췌한 사진인데요! 한번 참고해보세요!

2022-04-26 10:16 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +  for num in array {
넵 수정하였습니다!

2022-04-26 10:16 UTC, ssyoun4092 commented on CodeStarterCamp_Week2/main.swift
> +      containNumbers.append(lottoNumbers[i-1])
number로 수정했습니다!

2022-04-26 10:28 UTC, merged