Mission2: Step3: 로또 당첨 번호를 회차별로 저장하고, 확인하자!
yagom-academy/swift-starter-week2 pull request #194
Opened 2022-04-21 12:15 UTC by wolframhwang

@llghdud921 
안녕하세요 제리!

Mission2 의 마지막 Step3를 작성했습니다.

-  getWinningLottoNumberAllRound 함수에 지역 변수로 선언하고, 사용할때는 return 값에 담아서 사용할수 있게 만들었습니다!
- extractNRoundLottoNumber의 반환값으로 특정 회차의 당첨 번호를 알수 있게 했습니다.
- map + joined 내장 함수를 통해 String을 바로 출력할수 있게 구성했습니다.

감사합니다!

2022-04-22 05:43 UTC, llghdud921 requested changes
안녕하세요! 제리입니다~
이번주 마지막 스텝까지 너무 잘해주셔서 좋습니다 👍  
정말 너무너무너무 코드를 잘짜셔서 고칠게 별로 없어보였어요ㅎㅎ 

이번에는 코드부분에서 조언드릴 부분은 다 코멘트에 남겨드렸구요!
한가지 말씀드릴 점이 있는데용 제가 남겨주신 코멘트에 어떻게 개선되었는지 혹은 개선하지 않았으면 그 이유가 무엇인지 적어주셨으면 합니다!
이전에 Step2에서 남겨드린 코멘트가 있었는데 개선을 안해주셨더라구요! 하지만 개선하지 않은 이유가 적혀져있지 않았기 때문에 저는 그 부분을 다시 말씀드릴 수 밖에 없었어요ㅠ
그러니 코멘트에는 꼭 답변을 달아주셨으면 합니다 :) 감사합니다~!!

2022-04-22 05:43 UTC, llghdud921 commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +func getWinningLottoNumberAllRound() -> [String: [Int]] {
`getWinningLottoNumberAllRound`라는 네이밍을 지어주셨는데 현재는 겹치는 번호를 찾는 것이 아니기때문에 `Winning`이라는 단어가 포함되지 않아도 될 것 같아요!
이런 경우 기능 파악에 혼란을 주게 되는 것 같아요ㅎㅎ

추가로 getAllRoundLottoNumbers가 더 자연스러워보입니다. 단어의 순서가 바뀌어서 더 명확해지고 로또 번호가 하나가 아니라 여러개를 반환하므로 복수 표현식이 적절해보이네요!

2022-04-22 05:43 UTC, llghdud921 commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +        let NthRoundMessage = "\(round)" + roundMessage
여기서 NthRoundMessage는 대문자로 시작하게 되는데요! 
Swift는 대체적으로 변수명에는 lowerCamelCase를 권장합니다 :)

추가적으로 또 말씀드리고 싶은 것은 `extractNRoundLottoNumbers`함수에서는 `roundMessage`를 문자열 보간법으로 회차까지 포함하셨는데 두 개의 변수가 이름은 같은데 다르게 표현되어서 통일하는 의미로 해당 변수도 그냥 `roundMessage`로 변수명 지어도 괜찮을 것 같아보입니다~

2022-04-22 05:43 UTC, llghdud921 commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +        winningNumberAllRound[NthRoundMessage] = generateLotto()
이전 Step2에서 피드백을 드렸었던 것 같은데요!
generateLotto라는 네이밍보다 [Int]배열을 반환하므로 generateLottoNumbers로 개선해보는 것을 제안드렸었어요
그 이유가 지금 코드에서 나타나있는데 "로또를 발생시킨다"가 저는 어색하게 느껴져요 🥲  `generateLotto`라는 함수가 무엇을 반환하는지 무엇을 발생시키는지 명확하지가 않은 문제점이 나타납니다. 
개선해볼 수 잇을까요?

2022-04-22 05:43 UTC, llghdud921 commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +    guard let lottoNumbers = winningNumberAllRound[roundMessage] else {
guard문을 통해서 안전하게 옵셔널 값을 추출하셨네요!
왜 guard문을 사용하신 건가요?

2022-04-22 06:12 UTC, wolframhwang commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +func getWinningLottoNumberAllRound() -> [String: [Int]] {
엄.. 개선하지 않은게 있는지 못 본 것 같아요;; 고의성은 없었습니다

일단 이 부분 코멘트 주신 것을 확인해 보면 getAllRoundLottoNumbers라고 하셨는데 저는, WinningLottoNumber "당첨번호" 라는 것이 명시적으로 먼저 드러나야 된다고 생각해서 네이밍을 저런 방식으로 진행했습니다.

getAllRoundWinningLottoNumbers로 하는건 괜찮을까요?

2022-04-22 06:13 UTC, wolframhwang commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +        let NthRoundMessage = "\(round)" + roundMessage
loweCamelCase 인 부분에 대해서 다시 한번 리마인드 시켜주셔서 감사합니다.
음.. 다만, N 회차의 메세지 라는 것 을 조금 명시적으로 남겨 두고 싶어서 저런식 으로 구성을 했는데요,
이 부분은 리팩토링을 진행하도록할게요.

2022-04-22 06:14 UTC, wolframhwang commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +        winningNumberAllRound[NthRoundMessage] = generateLotto()
이 부분에 대해서는 제리의 말에 동감합니다.
제가 지난번에 그 코멘트를 보지 못한 것 같아요.
리팩토링시 반영하도록하겠습니다.

2022-04-22 06:27 UTC, wolframhwang commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +    guard let lottoNumbers = winningNumberAllRound[roundMessage] else {
guard를 통해 옵셔널을 추출한 이유는 가독성 때문이에요.
옵셔널 바인딩하는 이유 자체가, 안전성을 바탕으로 nil 여부를 판단하는게 가장 큰 이유인데,
이러한 명확성을 코드로 제공해주는데는 guard가 제일 좋다고 생각을했어요.

아마도 dicitionary[key, default: []] 나, if let을 사용하는 방법도 있겠지만, 목적성을 코드로 전달해주지 못한다는 단점이 있다고 생각을했습니다 !

2022-04-22 10:06 UTC, wolframhwang commented on CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
> +func getWinningLottoNumberAllRound() -> [String: [Int]] {
집에와서 코드 짜려고 보니 제리가 언급한 부분이 조금 더 적합한것 같다고 생각이 드네요 ㅎㅎ;

2022-04-22 10:17 UTC, wolframhwang commented
@llghdud921 
안녕하세요. 제리
말씀하셨던 부분을 Refactoring을 진행했어요

> getWinningLottoNumberAllRound라는 네이밍을 지어주셨는데 현재는 겹치는 번호를 찾는 것이 아니기때문에 Winning이라는 단어가 포함되지 않아도 될 것 같아요!
이런 경우 기능 파악에 혼란을 주게 되는 것 같아요ㅎㅎ

> 추가로 getAllRoundLottoNumbers가 더 자연스러워보입니다. 단어의 순서가 바뀌어서 더 명확해지고 로또 번호가 하나가 아니라 여러개를 반환하므로 복수 표현식이 적절해보이네요!

이렇게 언급 주신 부분이 있는데, 처음에는 **당첨 번호** 라는 단어에 꽂혀서 WinningNumbers에 꽂혔었는데요,
이 부분은 단순하게 로또 번호가 몇번이였는지에 대한 정보를 담고 있기 때문에 getAllRoundLottoNumbers가 조금 더 적절해 보인다고 후에 생각이 들어서 함수를 리네이밍 했습니다.

> 여기서 NthRoundMessage는 대문자로 시작하게 되는데요! Swift는 대체적으로 변수명에는 lowerCamelCase를 권장합니다 :)

> 추가적으로 또 말씀드리고 싶은 것은 extractNRoundLottoNumbers함수에서는 roundMessage를 문자열 보간법으로 회차까지 포함하셨는데 두 개의 변수가 이름은 같은데 다르게 표현되어서 통일하는 의미로 해당 변수도 그냥 roundMessage로 변수명 지어도 괜찮을 것 같아보입니다~

위와 같이 언급 주셨는데요, 

- NthRoundMessage는 제가 코드를 짤 때 생각한 것은 몇 회차의 메세지를 담을 것이라는 목표를 가지고 생성했는데, 네이밍 규칙을 깨면서 굳이 저렇게 만들 필요는 없고, 보간법을 통해 코드의 일관성을 보충해주고 명확한 이름을 써주는 방법이 좀 더 좋은 개선 방안이라고 생각이 들어 언급 주신 대로 리팩토링을 진행했어요

> 이전 Step2에서 피드백을 드렸었던 것 같은데요!
> generateLotto라는 네이밍보다 [Int]배열을 반환하므로 generateLottoNumbers로 개선해보는 것을 제안드렸었어요
> 그 이유가 지금 코드에서 나타나있는데 "로또를 발생시킨다"가 저는 어색하게 느껴져요 🥲 generateLotto라는 함수가 무엇을 반환하는지 무엇을 발생시키는지 명확하지가 않은 문제점이 나타납니다.

- 이 부분을 제안 주셨다고 했는데.. 제가 그 제안을 못본것 같아요;;;
- 말씀 주신대로 generateLotto라는 것은 로또를 만든다는 것인지, 로또 넘버를 생성한다는 것인지 불분명함이 보인다고 생각합니다.
- 그래서 명확히 어떠한 것을 만드는지 알려주기 위해 뒤에 접미어로 Numbers를 붙혀서 리팩토링을 진행했습니다.

> guard문을 통해서 안전하게 옵셔널 값을 추출하셨네요!
> 왜 guard문을 사용하신 건가요?

위에서 이미 답변을 드렸지만,
- guard를 통해 옵셔널을 추출한 이유는 가독성 때문이에요.
- 옵셔널 바인딩하는 이유 자체가, 안전성을 바탕으로 nil 여부를 판단하는게 가장 큰 이유인데,
- 이러한 명확성을 코드로 제공해주는데는 guard가 제일 좋다고 생각을했어요.

- 아마도 dicitionary[key, default: []] 나, if let을 사용하는 방법도 있겠지만, 목적성을 코드로 전달해주지 못한다는 단점이 있다고 생각을했습니다 !

리뷰 언제나 감사합니다!
확인 부탁드릴게요

2022-04-23 05:38 UTC, llghdud921 commented
네~ 좋습니다!!! 코드에 이유도 적절하고 답변 남겨주신 것을 통해 해당 코드가 작성되는 과정도 잘 알게되었습니다 👍 
이번 스텝 머지하겠습니다!! 즐거운 주말 보내세요 ~~ 😄

2022-04-23 05:38 UTC, merged