Week2 [Step 2] som
yagom-academy/swift-starter-week2 pull request #195
Opened 2022-04-21 13:49 UTC by jsa0224

@Jager-yoo 

# Step 2를 진행하며...
아까 만든 순서도처럼 간단한 코드인줄 알았는데, 생각보다 복잡하더라고요...
그래서 막히는 부분도 많이 있어서 같이 스터디하시는 분께 도움을 많이 받았습니다.

## 1. 로또 숫자 생성하기
처음에는 배열 안에 1부터 45의 숫자를 다 넣을 생각이었어요.
```swift
let numbers = Int.random(in: 1...45)
```
'랜덤 숫자 생성하기'를 구글에 서치해보니 저렇게 .random을 붙여서 생성할 수도 있더라고요! ~역시 컴퓨터가 저보다 똑똑한 거 같아요~

그래서 배열 안에 해당 숫자가 없다면 들어가게 하는 코드를 만들었습니다.
```swift
 if !lottoNumbers.contains(numbers) {
            lottoNumbers.append(numbers)
        }
```
그런데 if문을 선언하고 !를 달아주면 자동으로 '~가 아닌'으로 선언해준다고! 코드를 한결 간편하게 만들어주는 기능인 거 같아요!

여기까지는 정말 생각하기 쉬웠는데... 다음부터 꼬이기 시작하더라고요.

## 2. 로또 숫자가 찍은 숫자와 맞는지 확인하기
```swift
func matchNumber(_myLottoNumbers: [Int], lottoNumbers: [Int]) {
    for num in myLottoNumbers {
        if myLottoNumbers.contains(lottoNumbers[num-1]) {
            coincideNumbers.append(lottoNumbers[num-1])
        }
    }
}
```
저는 여기서 num이 myLottoNumbers의 배열 수만큼 돈다고 생각했는데, 아니었더라고요...
Week2의 반복문 파트를 자세히 보니까 배열의 for~in 구문은 배열을 하나씩 꺼내주는 역할이라고...ㅠㅜ 
```swift
func matchNumber(_myLottoNumbers: [Int], lottoNumbers: [Int]) {
    for num in myLottoNumbers {
        if lottoNumbers.contains(num) {
            coincideNumbers.append(num)
        }
    }
}
```
그래서 이렇게 myLottoNumbers에 있는 숫자(num)이 lottoNumbers에 담겨 있다면 coincideNumbers에 추가하라는 코드로 변경했습니다. 이 부분을 같이 스터디하신 분께 도움 받았는데, 다음에는 혼자 힘으로 해결해보겠습니다💪!

## 3. 찍은 번호와 로또 당첨 번호의 겹치는 숫자를 확인하는 함수 생성하기
여기서 저는 배열.isEmpty라는 코드를 사용했는데요. 엄청 막혔을 때... 배열 관련해서 다 찾아보니까 이런 코드가 있더라고요!
배열이 비었는지 확인해주는 코드라고 하네요 ㅎㅎ...ㅠㅜ...

## + 여담
코드 작성하고 run할 때 계속 *아쉽지만 겹치는 번호가 없습니다.* 가 떠서 처음에는 어디서 또 잘못 되었나? 싶었는데 몇 번 하니까 나오더라고요 ㅎㅎ... 이래서 로또 당첨될 때 몇 억씩 가져갈 수 있는 거구나 싶었어요

2022-04-21 17:32 UTC, Jager-yoo commented
안녕하세요 솜~!!
금방 `Step 2` 제출하셨군요!! 수고하셨어요 ㅎㅎㅎ

이제부터 난이도가 슬슬 올라가죠~?
저도 `요구 사항` 읽으면서 조금씩 난이도가 오르는 걸 체감하고 있어요. ㅎㅎ
혼자 해결하든, 같이 해결하든 결국엔 해결해서 PR 제출하신 점 만으로도 엄청 잘 하신겁니다!! 👏🏻 

간단하게 전체 코멘트 드리고, 코드 단계로 들어가겠습니다!

- Bool 타입이 결과로 나오는 메서드나 연산 프로퍼티의 결과를 반대로 뒤집고 싶을 때 `느낌표(!)`를 앞에 붙인다는 점!!
잘 찾아주셨습니다. 😄 
조금 어렵지는 않으셨나요? 저는 이걸 처음 알았을 때, 왜 느낌표가 contains 바로 앞에 붙는 게 아니라, 저~ 앞에 상수 앞에 붙는 걸까.. 🤔 
그런 생각을 하기도 했어요. ㅎㅎ

```swift
lottoNumbers.!contains(numbers) // 이게 아니고
!lottoNumbers.contains(numbers) // 이거라는 점
```

<br>

- `for문`의 작동 방식도 시행착오를 통해 잘 배우셨다고 생각합니다. 👍🏻 
오히려 한 번 에러가 나고 → 왜 이러지 → 아 이렇게 작동하는 게 아니구나 → 이런 식으로 학습하는 게 더 오래 기억에 남더라구요. 😄 
그리고 오히려 수정한 코드가 훨씬 가독성이 좋고 간결하네요~~ ㅎㅎ

<br>

- `isEmpty` 를 ⛏️ 발굴하셨군요!
앞으로 Swift 공부하면서 정~말 많이 쓰게 될 `연산 프로퍼티` 입니다.
재밌는 건, isEmpty 는 단순히 Array(배열)에서만 사용할 수 있는 게 아니라, Array, Set, Dictionary 같은 `Collection 타입` 전부에서 사용할 수 있습니다.
더 재밌는 건, String 타입에도 써먹을 수 있습니다. "문자열이 비었니?" 를 쉽게 따질 수 있는 것이죠. 😄 
아래 예시를 좀 만들었으니, 한 번 읽어보세요. ㅎㅎ

```swift
if coincideNumbers.count == 0 { ... } // 초보적 로직 → count 를 따져서 0개 인지 확인하기
if coincideNumbers.isEmpty { ... } // 권장하는 로직 → "비었니?" 를 의미하는 isEmpty 프로퍼티 사용하기
```

<br>

- 저는 솜 코드 다운 받아서, 첫 시도에서 로또 번호 3개 맞았습니다..ㅋㅋㅋ
내일 진짜 로또 사야하나 싶네요. 🤔 

<img width="389" alt="스크린샷 2022-04-22 오전 1 02 15" src="https://user-images.githubusercontent.com/71127966/164515453-78f18f25-a7f3-4d0e-9a8b-1bc1e594276d.png">

2022-04-21 18:37 UTC, Jager-yoo requested changes

2022-04-21 18:37 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +
솜이 작성하신 `main.swift` 파일의 코드 구조는 대략 이렇습니다.

- 변수 선언 → 메서드 정의함 → 호출함 → 다른 변수 선언 → 다른 메서드 정의 → 다른 메서드 호출 → ...

왜 이런 구조가 되셨을까요?
제 생각엔 여기가 `main` 이어서 그런 것 같아요.

[지난 PR 에서도 이야기](https://github.com/yagom-academy/swift_starter-week1/pull/88#discussion_r852568670)했지만, 이 파일은 🟢 `entry-point`를 의미하는 특별한 파일이죠?
여기서는 `위에서부터 순서대로` 코드를 실행시키잖아요?

그렇기 때문에, 어쩔 수 없이 위와 같은 순서를 `강제`로 할 수밖에 없으셨을 거라 생각해요.
변수 선언을 먼저 하지 않으면, 메서드에서 부를 수가 없고, 메서드 정의를 끝내야지 그 아래에서 호출할 수 있으니까요. 🥲 

그렇다면...
이렇게 `제약`을 받으면서 코딩을 하는 게 맞는 걸까요?
분명 더 예쁘게 코드를 모아둘 방법이 있을 겁니다.

어떻게 하면 예쁘게 코드를 모아둘 수 있을까요?
`메서드 정의`는 다른 파일에 모아두고, main.swift 에서는 그 만들어진 메서드를 `호출`만 하면 어떨까요? 😄 

### 🎯 결론 : 별도 파일을 만들어서 메서드 정의 부분을 옮겨보세요.

2022-04-21 18:37 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +var coincideNumbers: [Int] = []
처음에 이 네이밍을 보고, 솔직히 이렇게 생각했습니다.
coincide 는 뭐지..? `우연`이란 뜻의 coincidence 단어는 아는데.. 그거의 동사원형인가보네.
그러면 "우연한 숫자들" 인가? ...

네이밍은 정말 어렵죠. 🤔 
저도 항상 어려워하지만, 그래도 개인적으로 이런 생각을 하면서 지으려고 해요.

"자주 안 쓰이거나 난이도가 높은 단어보다는, 사람들에게 익숙한 단어를 사용하면서, 코드의 `역할`을 충분히 담아내자."

주석에 솜이 직접 `"일치하면"` 이라고 쓰셨잖아요?
저는 저 표현을 보고 `match` 라는 단어가 떠올랐어요.

하지만 저 동사원형 그대로 `matchNumbers` 라고 쓰면.. 상수/변수 네이밍이 아니라, 마치 `메서드` 네이밍 같아지죠.
그러니까 동사에 -ing 를 붙이거나 -ed 를 붙여서 `분사` 형태로 만들어서 쓰면 될 것 같아요.

숫자들 입장에선 `매칭을 당한 것` 이기 때문에 피동의 늬앙스를 담아 `matched` 로 표현하면 되겠군요. 😄 

```suggestion
//찍은 번호와 로또 번호가 일치하면 들어가는 배열
var matchedNumbers: [Int] = []
```

2022-04-21 18:37 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +}
메서드의 첫 번째 파라미터인 `myLottoNumbers` 앞에 `언더스코어(_)`가 어색하게 붙어있는데요. ㅎㅎ
제 생각엔 솜은 `Omitting Argument Labels` 라는 스킬을 사용하려고 하셨던 것으로 파악했어요! 👍🏻 

![image](https://user-images.githubusercontent.com/71127966/164527340-f70cc420-32d6-4ea6-a125-adb76fd807fb.png)

[공식 문서](https://docs.swift.org/swift-book/LanguageGuide/Functions.html)에서 해당 부분을 찾아보시면, 언더스코어(_) 뒤에 한 번의 스페이스바로 여백이 들어가는 걸 확인할 수 있습니다. 😄 

파라미터가 2개인데, 왜 하나만 생략해주려고 하셨을까 봤는데
어차피 Number 라는 단어가 계속 나오기 때문에, 불필요하게 반복할 필요가 없고
왼쪽은 사용자(유저)가 뽑은 숫자고, 오른쪽이 기계가 뽑은 결과니까
둘을 구분해주시려고 그런 것으로 이해했어요.

스위프트 네이밍 가이드를 정말~~ 잘 이해하신 것 같아요.
분명 `메서드 파라미터를 읽을 때의 가독성` 까지 고민하신 거겠죠. 벌써 이 정도 수준이라니.. 놀랍습니다. 😲 

그리고 `for문`에서 for ~ in 사이에 들어가는 임시 상수 이름으로 `num`을 사용해주셨는데요!
스위프트의 [API Design Guidelines - Avoid abbreviations.](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage) 부분을 한 번 더 읽고 오시면 좋겠어요!

물론 여기 읽어보면.. `non-standard 축약어`의 경우는 사용하지 말고 전체 단어로 사용하라고 쓰여있고
사실 number → num 줄여쓰는 건 흔한 것이기도 하지만..
그래도 저는 웬만하면 축약어를 안 쓰는 게 좋다고 생각하는 편이에요. 😄 

```suggestion
func matchNumber(_ myLottoNumbers: [Int], lottoNumbers: [Int]) {
    for number in myLottoNumbers {
        if lottoNumbers.contains(number) {
            coincideNumbers.append(number)
        }
    }
}
```

2022-04-21 18:37 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +    if coincideNumbers.isEmpty {
최종 결과 출력 부분 메서드 아주 로직이 깔끔하네요. 👍🏻 

다만, 결국 확인하는 건 하나의 숫자가 아니라 `여러 숫자들` 이죠!?
내부 `if문`에서 체크하는 것도 숫자들의 배열이구요. 😄 

컨셉을 정확하게 유지하려면, 메서드의 네이밍도 `복수형`으로 변경되어야 할 것 같습니다!
참 어렵죠 네이밍? ㅎㅎㅎ..

자신만의 기준을 갖고 `일관성`을 유지하는 게 중요하겠습니다!!

```suggestion
func comfirmNumbers() {
    if matchedNumbers.isEmpty {
```

2022-04-21 18:37 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(coincideNumbers.sorted()) 입니다!")
여기 겹치는 번호 출력되는 부분이, 아쉽지만 `요구사항` 하고 다르더라구요. 😢 

어떻게 하면 배열의 `[대괄호]`를 벗겨서 출력할 수 있을까요!?
`구글링`으로 직접 문제 해결 해보시죠 ㅎㅎ 화이팅입니다!

<img width="528" alt="image" src="https://user-images.githubusercontent.com/71127966/164530296-0fba43d7-bbad-470b-8b70-aebc1677ce4b.png">

2022-04-22 07:39 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +        }
무조건 짧은 코드가 효율적이라고 생각했는데, 다른 사람이 보기에는 헷갈릴 수도 있는 부분일 거 같아요. 그리고 numbers 상수도 '6개의 번호들을 뽑는다'라는 생각으로 s를 붙인 것인데, 반복문 안에서 돌아가는 거니까 1개씩 나오기 때문에 s를 지우는 게 맞는 거 같아요! 수정했습니다:)

2022-04-22 07:45 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +        }
맞습니다 ㅎㅎㅎ

6개의 숫자를 한 번에 리턴하는 거면, 복수형인 numbers 라고 해도 되겠지만, 여기서는 숫자 1개를 6번 혹은 *6번 이상* 뽑는 상황이니까 단수형인 number 라고 칭하는 게 맞죠!

정확하게 잘 파악하셨습니다. 😌

2022-04-22 07:46 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +var coincideNumbers: [Int] = []
이 배열 이름 짓는 것에서 저도 좀 고민을 많이 했습니다. match(비교하다) 자체는 이미 함수명으로 쓰고 있어서 배열명으로 쓰자니 제 스스로 헷갈리더라고요. 그래서 이 배열에는 앞의 두 배열의 숫자가 *일치하면* 추가가 되게 설정을 해둬서 일치하다, 라는 coincide 라는 명을 붙였습니다. 저도 구글에서 찾아본거고 처음 보는 영단어라ㅎㅎ 다른 분들이 혼란이 오실 거 같아요! 
근데 예거처럼 ed를 붙인다면 덜 헷갈릴까요?? 변수명을 제가 직접 치는 것보다 Xcode 내의 자동완성 기능을 사용할 때가 많아서 조금 고민이네요🧐
수정했습니다:)

2022-04-22 07:52 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    if coincideNumbers.isEmpty {
수정했습니다!

2022-04-22 08:20 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(coincideNumbers.sorted()) 입니다!")
수정했습니다!
for in 문으로 배열을 다시 꺼내서 String으로 변환하려 했는데, 더 좋은 방법이 있더라고요!
구글에 검색해보니 .map이 배열의 요소들에 접근해주는 메소드라 변환할 때 자주 쓴다 하더라고요! 이것도 앞으로 많이 쓰지 않을까 싶어요 ㅎㅎ!

2022-04-22 08:27 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +
수정했습니다!
뭔가 빼빼로의 연장선...? 같으면서도 확실히 Step3에서 딕셔너리 개념까지 들어가면 더 복잡해질 거 같아요! 앞으로는 더 복잡한 코딩이 기다리고 있으니😵‍💫 별도의 스위프트 파일을 생성하는 것을 습관화 해야겠어요!

2022-04-22 08:34 UTC, jsa0224 reviewed
@Jager-yoo 

코드 수정했습니다!
2시에 시작한 거 같은데 벌써 시간이...ㅇ0ㅇ..
이번에는 머리를 많이 써야하는 과제였던 것 같아요...
Int -> String 으로 변환하는 건 할 수 있지만 배열의 요소 타입을 변환하는 것은... 매우 어려웠습니다.

그리고 앞으로 과제할 때 야곰 아카데미의 코스도 꼼꼼히 읽어봐야겠어요!
말씀해주신 덕분에 결과 출력이 배열이 아니라 문자열 형태였다는 것을... 이제 깨달았네요🤭

2022-04-22 08:41 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +
나중에 UI 있는 앱개발을 시작하시면, 파일이 너무 많아져서, 이 많아진 파일들을 어떻게 `그룹핑(Grouping)`해야 할까?
그리고 파일 수준을 넘어선 `그룹의 네이밍`은 어떻게 지어야 할까..?

같은 고민으로 확장되실 겁니다. ㅎㅎㅎ

2022-04-22 09:06 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +var coincideNumbers: [Int] = []
`matchedNumbers` 변수와 `matchNumber` 라는 메서드의 이름이 유사하기 때문에, 추후 더 헷갈리지 않을까 고민하셨군요!
반드시 필요한 고민이구요. 오히려 마냥 수용하지 않고 이렇게 한 번 더 고민해보시는 점 너무나 좋습니다. 😄 

저는 `하나의 기능`을 이루는 요소들이라면 비슷한 이름이나 알파벳으로 시작하는 게 '오히려' 좋다고 생각해요. ㅎㅎㅎ
`자동완성` 이야기 해주셨는데, 자동완성 때문에 더더욱 그래요!

이렇게 생각해볼게요...
Xcode 의 `main.swift` 파일에서 `"mat"` 을 쳤어요. (여기까지 쳐야 자동완성이 뜨네요!)
그러면, 아래 캡쳐와 같이 변수와 메서드가 동시에 보여지죠? 

<img width="448" alt="image" src="https://user-images.githubusercontent.com/71127966/164654975-9d8f931b-19f4-4fcc-9176-42983422c966.png">

지금이야 둘의 네이밍이 비슷해서 혼란스러우실 수 있지만...
코드를 더 많이 작성하다 보면, 전~~혀 헷갈리지 않고 오히려 같은 기능을 이루는 2가지 요소가 함께 자동완성되게 만든 개발자의 센스를 고마워하게(...) 되실 수도 있습니다. 😅 

좀 더 팁을 드리자면요!
이렇게 파악하는 것도 도움이 돼요.

- 네이밍 끝에 괄호`(`가 있네? → `메서드`
  - 심지어 네이밍 왼쪽에 초록색 박스 🟩 안에 function 을 의미하는 **_f_** 글자가 찍혀있죠? ㅎㅎ

- 그럼 초록색 박스 안에 있는 `L`은 뭘까요? → "Local variable" 을 의미한다고 합니다. [출처](https://stackoverflow.com/questions/6662395/xcode-intellisense-meaning-of-letters-in-colored-boxes-like-f-t-c-m-p-c-k-etc%29)
  - 참고로, 저장(stored) 프로퍼티와 연산(computed) 프로퍼티 모두 초록색 `L`로 찍힙니다.
  - 그럼 어떻게 구분할까요? 네이밍을 명확하게 해서 딱 봐도 구분할 수 있게 하거나, `Documentation Comments` 기능을 이용하는 겁니다.

- [Documentation Comments](https://sarunw.com/posts/swift-documentation/) → 링크는 다 읽지 말고 간단하게만 슥 보세요.
  - 이거는 사용 방법과 그 결과가 매우 직관적이니까, 아래 코드 예시랑 캡처만 봐도 충분합니다.
  - Xcode 에서 주석은 `//` 죠? 여기에 슬래시 하나 추가해서 3개로 `///` 만들어보세요 😄 
  - 그리고 어딘가에서 그 변수를 자동완성시켜보세요. ㅎㅎ

```swift
/// 찍은 번호와 로또 번호가 일치하면 들어가는 배열
var matchedNumbers: [Int] = []
```

![image](https://user-images.githubusercontent.com/71127966/164674622-4320f8f5-61fe-4950-beb6-e4dd05b42c5e.png)

2022-04-22 09:42 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +var matchedNumbers: [Int] = []
코드 정의부를 `main.swift`가 아니라 → 별도로 파일로 분리하셨기 때문에, 이제 `코드의 순서`가 바뀐다고 작동을 안 하고 그러지 않습니다. 😄 

굳이 변수와 메서드가 섞여 있을 필요가 없어요.
오히려 변수는 변수 끼리, 메서드는 메서드 끼리 뭉쳐 있으면서도, 그 사이에서도 우선순위/중요도에 따라 정렬 순서를 결정해두면 최고입니다. 👍🏻 

일단 여기 혼자 있는 `matchedNumbers` 변수는 위로 이동시켜서, 다른 변수들하고 함께 보이도록 해주면 좋겠습니다!

2022-04-22 09:42 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +}
로또 게임에 필요한 모든 메서드를 한 번에 묶어서, 딱 하나의 메서드만 `main.swift` 에서 호출해도 되도록 만드셨군요!
아주 훌륭하고 깔끔합니다. 😄 

결국 제일 중요한 메서드니까, 파일의 최상단에 올려두셨구요. ㅎㅎ
엄청 빠르게 성장하고 계시네요 솜~~ 💯

2022-04-22 09:42 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +}
이 부분 메서드 정말 멋진데요~!
리턴하는 게 `[String]`이 아니라, 여기서 메시지로 바로 내보낼 수 있게 모든 편집을 끝내서, `String` 으로 내보내는 게 훨씬 좋을 것 같아요. 😄 

그리고 메서드 이름은 기존 convertArray 에서 → convertToString 으로 바꿨어요. 왜냐면 결국 리턴되는 건 String 타입이니까요. ㅎㅎㅎ
무엇으로 부터 만들어낼 건지는 뒤에 따라오는 전치사 `from` 뒤에 들어갈 배열이겠죠! 👍🏻 

그리고 메서드 내부에서 임시 상수 네이밍할 때 제가 `As` 라는 전치사를 사용했는데요.
`To` 와 `As` 는 어떤 늬앙스 차이가 있을지 한 번 꼭!!! 고민해 보셨으면 좋겠어요! 🔥 
답을 알려드리진 않을테니, 솜이 고민해보시고 다시 코멘트 달아주세요. 😄 

그리고 출력할 때 숫자들 사이에 콤마(,) 뿐만 아니라, 콤마 뒤에 여백도 있어야 해요!
그래서 separator 또한 살짝 고쳤습니다~ ㅎㅎ

고차함수 map 뒤에 오는 저 `딸러($) 표시` 뭐지...? 싶으실 수 있지만
이건 나중에 알게되실 겁니다! 천천히 공부해요 ㅎㅎ

```suggestion
func convertToString(from array: [Int]) -> String {
    let numbersAsString = array.sorted().map { $0.description }
    let joinedMessage = numbersAsString.joined(separator: ", ")
    return joinedMessage
}
```

2022-04-22 09:42 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +let matchedNumbersToString = convertArray(from: matchedNumbers)
이 상수는 굳이 필요하지 않을 것 같아요. ㅎㅎ
단순히 `변환` 결과를 잠깐 저장만 할건데, 굳이 `전역 변수`를 하나 늘릴 필요는 없겠죠!

2022-04-22 09:42 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +    }
위에서 메서드를 고쳤다면, 여기는 아래와 같이 `문자열 보간법` 안에 메서드를 호출하면서 바로 변환 결과를 내보내는 식으로 처리하면 됩니다. 😄 

```suggestion
    } else {
        print("축하합니다! 겹치는 번호는 \(convertToString(from: matchedNumbers)) 입니다!")
    }
```

문자열 보간법 부분이 너무 코드가 긴 것 같아요. 😢 
라는 생각이 드신다면...
`임시 상수`로 담아주면서 이게 "메시지" 라는 걸 강조해주고, 문자열 보간법은 깔끔하게 가져가는 방법도 있습니다.

```swift
let message = convertToString(from: matchedNumbers)
print("축하합니다! 겹치는 번호는 \(message) 입니다!")
```

2022-04-22 11:31 UTC, jsa0224 commented on CodeStarterCamp_Week2/PlayLotto.swift
> +}
```swift
func convertArray(from array: [Int]) -> [String] {
```
이 부분 저도 ```String 타입```으로 반환받고 싶어서 대괄호 표현 없이 적으니까 오류 메세지가 옆에 뜨더라고요. 그래서 정수 배열을 받아서 문자열로 변환하려 하는 거니까, 문자열도 배열로 만들어야 하는 걸까? 싶어서 대괄호를 삽입하니까 오류가 사라졌어요... 
뭔가 예거가 제안해주신 코드는 ```$0``` 역할 때문에(?) ```String 타입```으로도 변환되는 건가 궁금증이 생기네요! 
더 찾아보겠습니다✨✨

```as``` 와 ```to```의 차이... 갑자기 학창시절로 돌아가 전치사를 배우던 때가 생각났어요ㅎㅎ
~저는 수학이랑 영어를 제일 싫어했는데 지금은 둘 다 하게 되었네요 ㅎㅎㅠㅜ~
```to```는 어디서 어디로 이동하는 느낌의 전치사고, ```as```는 '~처럼' 이라는 전치사니까, ```numbersAsString```은 곧 숫자가 문자처럼 바뀐다는 뜻의 상수인 거 같아요! as의 뜻을 찾아봤는데, 여러개의 뜻 중에 '~처럼' 이 제일 적합할 거 같아요ㅎㅎ

수정했습니다:)

2022-04-22 11:39 UTC, jsa0224 commented on CodeStarterCamp_Week2/PlayLotto.swift
> +    }
와우!!!! 저런 방법이 있을 수도 있겠군요!
저도 ```print 함수``` 출력되는 부분이 너무 복잡하다 싶었는데... 혹시 제 마음 속을 들여다보시는 건 아닌가요??
덕분에 문자열 보간법을 깔끔하게 만들었어요:)

2022-04-22 11:50 UTC, jsa0224 reviewed
@Jager-yoo 

코드 2차 수정 완료했습니다.
제가 1차 코드 수정 때, 놓쳤던 ```.sorted()```도 다시 추가해주셔서 감사합니다...!
아까 코멘트 달 때 말씀 못 드린 거 같아서요😉

2022-04-22 15:54 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +}
솜이 저 메서드를 구현하실 때, 리턴 타입에 `String`을 하면 에러가 났던 이유는,
`map` 고차함수의 작동 방식이, Array 내부를 하나로 합쳐서, 뱉어내는 게 아니라
Array 내부의 원소들을 하나하나 `"\(number)"` 처리한 거에요.

즉, [1, 5, 7, 9, 11, 13] 라는 [Int] 가 들어가게 되면, map 처리를 끝내고 나올 때는
`["1", "5", "7", "9", "11", "13"]`가 되어서 나오는 거에요. 즉, `[String]` 인 거죠 ㅎㅎ

아직은 이해가 잘 안 되더라도, 그냥 그런 게 있나보다 하고 넘어가셔도 괜찮아요!
딸러 표시도 마찬가지구요 ㅎㅎㅎ 궁금하시면 [Shorthand Argument Names](https://docs.swift.org/swift-book/LanguageGuide/Closures.html) 찾아보시면 됩니다!

![image](https://user-images.githubusercontent.com/71127966/164750552-4ed7cc91-ca35-4032-bc20-f4a720069a72.png)

2022-04-22 16:03 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +}
제가 전치사 `To` 하고 `As`에 대해 질문드렸는데요. 😄 
제가 생각하는 것과 똑같이 대답해주셨어요! 👍🏻 

아래 메서드를 보면, 메서드 이름에는 `To`가 쓰이고
내부에서 sorted() 처리하고, map 고차함수를 통해 [String] 으로 변환된 array 를 잠시 저장해두는 `지역 상수` 네이밍에는
`As`를 썼죠.

사실 메서드 네이밍을 `convertAsString` 으로 지었어도, 솔직히 늬앙스 차이는 거의 없는 것 같긴 해요 😅 
이렇게 애매할 때는 `숙어 표현`을 참고하면 좋아요!

"convert A as B" 하고 "convert A to B" 각각 구글링을 해보는 거죠.
그래서 어떤 표현이 더 많이 쓰이는지 확인한 후, 어떤 `전치사`를 쓸 건지 고르면 됩니다!

- 방금 알았는데, 정확한 숙어 표현은 `convert A into B`군요. ㅎㅎㅎ
그러면 `convertIntoString(from ~)` 으로 지었어도 괜찮았을 거 같아요!
이런 식으로 숙어 표현을 참고하면 전치사 때문에 골치 아플 일이 줄어듭니다. ☺️ 

```swift
func convertToString(from array: [Int]) -> String {
    let numbersAsString = array.sorted().map { $0.description }
    let joinedMessage = numbersAsString.joined(separator: ", ")
    return joinedMessage
}
```

2022-04-22 16:05 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PlayLotto.swift
> +    }
ㅎㅎ 비교를 위해, 보간법 안에 직접적으로 메서드를 호출해봤어요! (일부로요)
근데 솜도 느끼셨겠지만, 저렇게 사용하면 가독성 별로죠. 😅 

한 번 임시 상수로 받아준 뒤에, 깔끔한 표현으로 넣어주는 게 센스 있는 방법입니다. 👍🏻

2022-04-22 16:15 UTC, Jager-yoo commented
꽤나 까다롭게(?) 수정 요청 드린 것 같은데, 잘 따라와주셔서 감사합니다 솜! 🙏🏻 
이번 스텝에서 알려드린 여러 팁이나 고민거리들을 잊지 말고, 남은 기간에도 계속 반영하기 위해 신경써보세요!! 😄 

수고하셨습니다. 머지합니다! 🪄

2022-04-22 16:15 UTC, Jager-yoo approved these changes

2022-04-22 16:15 UTC, merged