Week2 [STEP 2] wonbi
yagom-academy/swift-starter-week2 pull request #203
Opened 2022-04-22 17:14 UTC by wonbi92

@ye-ha 

## 고민한 부분

### 로또 당첨 함수 만들기
- 이번 과제에서는 순서도에 맞게 함수 만들기, 하나의 함수가 하나의 역할을 하기 이 두가지를 중점적으로 생각하며 과제를 진행하였습니다.

- 전역변수 보다는 지역변수를 사용하는것을 주 목표로 작업하였습니다.

### 전역변수
- 실제 이런 앱을 협업하며 만든다고 생각하고 작업을 해보았습니다. '내 로또 번호'에서 문제가 좀 있었는데 앱이라면 사용자가 입력 한 값이 이 변수로 들어올텐데, 아직 이부분은 당연히 모르는 부분인지라.. 일단 상수에 제가 직접 입력하는 방식을 사용자가 입력한다라고 생각하고 상수 하나를 전역으로 선언했습니다. 과제에도 그렇게 선언하라고 했구요..!

### 콤마의 딜레마
- 사실 상상도 못한 부분이었습니다. 겹치는 번호를 `a, b, c, ...` 이런식으로 표현해야 했습니다. 문제는 겹치는 번호가 반드시 6개가 아니라는 점이었습니다. 
- 처음에는 *'이거 그냥 separator 쓰면 해결되는 문제 아니야?'* 라고 생각했죠.
```Swift
print(sortedComparedNumbers[0], sortedComparedNumbers[1], sortedComparedNumbers[2], sortedComparedNumbers[3], sortedComparedNumbers[4], sortedComparedNumbers[5], separator: ", ")
``` 
- 하지만 이렇게 함수를 사용하니, 너무 길어지는데다가 겹치는 번호의 갯수가 정해지지 않아서 1등 당첨이 아닌이상 런타임 오류가 생기는 치명적인 결함이 있었습니다.

- 그렇다고 switch문을 사용해서 각 배열의 데이터 갯수에 따라 다르게 설정하는 것도.. 가능은 하지만 너무 비효율적인 방법이라 생각했습니다. 

- 제가 선택한 방법은 일단 0번 인덱스에 있는 값을 출력해주고 terminator 값을 ", "으로 선언한 후, 첫번 째 인덱스를 removeFirst() 메소드를 통해 지우는 동작을 배열 안에 데이터가 1개가 남을 때 까지 while문을 통해 반복한 후, 마지막 1개 남은 값을 바로 출력해주는 방법을 사용했습니다.
```Swift
 while sortedComparedNumbers.count != 1 {
            print(sortedComparedNumbers[0], terminator: ", ")
            sortedComparedNumbers.removeFirst()
        }
        print(sortedComparedNumbers[0], "입니다!", separator: " ")
```
- 바로 이 부분입니다. 이렇게 하면 겹치는 숫자의 갯수가 달라도 그에 맞게 표현이 가능했습니다.

## 해결 안된 부분

### 그럼에도 만족스럽지 않은 콤마의 딜레마
- 배열의 맨 첫번째나 맨 뒤에 있는 값을 지워주는 메소드인 `removeFirst()`, `removeLast()`는 수업을 통해 알고 있었지만, 구글에 'array 메소드'를 검색하고 공부하는 과정에서 이 메소드가 삭제한 값을 리턴해주는 'Non-Optional Type' 메소드라는 사실을 알게 되었습니다. ~문제는 이걸 커밋이랑 푸쉬까지 끝내고 나서 PR을 정리하는 과정에서 알게 되었다는 것..~
```Swift
 while sortedComparedNumbers.count != 1 {
            print(sortedComparedNumbers.removeFirst(), terminator: ", ")
        }
        print(sortedComparedNumbers[0], "입니다!", separator: " ")
```
- 이런 식으로 수정이 가능하다는 사실을 알게 되었습니다. 이건 피드백을 주셨을 때 같이 수정하겠습니다.

### Array 컬렉션을 Set 컬렉션으로
- 저는 '내 로또 번호'라는 상수를 Int 타입의 데이터를 가지는 Array 컬렉션 타입으로 지정했습니다. 과제에서도 그렇게 지정을 했구요.

- 하지만 내 로또 번호가 겹치는 번호가 무엇인지 찾는 함수 내에서는 이 상수가 Array가 아닌 Set로 바뀌여야만 했습니다. 저는 '당첨 번호'와 '내 로또 번호'의 교집합을 구하는 방법을 통해 겹치는 번호를 알아내려고 했기 때문입니다.

```Swift
let setTypeBettedNumbers = Set<Int>(bettedNumbers) 
let comparedNumbers = winnerNumbers.intersection(setTypeBettedNumbers)
```
- 그래서 위와 같이 Set 컬렉션 타입의 배팅 넘버를 다시 지역상수(이런 표현도 사용하나요??)로 선언해서 활용했는데..

- 이 역시 상수로 선언할 필요 없이 바로 사용해도 될것이라고 생각했습니다. ~이 역시 PR을 정리하는 과정에서 생긴 생각이라는게.. 문제지만요.~
```Swift
  let comparedNumbers = winnerNumbers.intersection(Set<Int>(bettedNumbers))
```
- 다음과 같이 수정할 수 있을것입니다. 

## 조언을 얻고 싶은 부분

### 겹치는 번호를 한줄로 표현하기?

- 디스코드 질문방에 다른분이 같은 내용을 질문하셨었는데, 이 문구를 한줄로 표현하고 싶다는 질문이 이었습니다. 저도 같은 질문이 머리속에 떠오르더라구요. 

- 하지만 이부분은 일단 여기서 마무리 하기로 했습니다. 물론 질문의 과정에서 `map`, `joined`등의 내용들이 나왔었지만, 일단은 넘어갑니다. 저는 이걸 몰라도 해결 할 수 있을거라 생각했거든요. 이런식으로 찾아다니다가 결국 빼빼로 사태가 일어나서 고생했던 경험도 있었구요.. 그리고 말씀해주신대로 커리큘럼 내에서 완벽하게 이해하는걸 목표를 잡았기 때문입니다.

2022-04-25 11:43 UTC, ye-ha requested changes
> 로또 당첨 함수 만들기
> 이번 과제에서는 순서도에 맞게 함수 만들기, 하나의 함수가 하나의 역할을 하기 이 두가지를 중점적으로 생각하며 과제를 진행하였습니다.
전역변수 보다는 지역변수를 사용하는것을 주 목표로 작업하였습니다.

함수를 분리하시려고 노력하신게 느껴졌습니다! 👍

> 전역변수
> 실제 이런 앱을 협업하며 만든다고 생각하고 작업을 해보았습니다. '내 로또 번호'에서 문제가 좀 있었는데 앱이라면 사용자가 입력 한 값이 이 변수로 들어올텐데, 아직 이부분은 당연히 모르는 부분인지라.. 일단 상수에 제가 직접 입력하는 방식을 사용자가 입력한다라고 생각하고 상수 하나를 전역으로 선언했습니다. 과제에도 그렇게 선언하라고 했구요..!

해당 부분은 잘하셨어요. 👍

> 콤마의 딜레마

어떤 고민을 하셨는지 잘 느껴졌습니다. PR메세지 양식대로 잘 적어주시고, 코드도 첨부해주셔서 보기도 편했어요. 👍 

> 해결 안된 부분
그럼에도 만족스럽지 않은 콤마의 딜레마
배열의 맨 첫번째나 맨 뒤에 있는 값을 지워주는 메소드인 removeFirst(), removeLast()는 수업을 통해 알고 있었지만, 구글에 'array 메소드'를 검색하고 공부하는 과정에서 이 메소드가 삭제한 값을 리턴해주는 'Non-Optional Type' 메소드라는 사실을 알게 되었습니다. 문제는 이걸 커밋이랑 푸쉬까지 끝내고 나서 PR을 정리하는 과정에서 알게 되었다는 것..

무엇이 문제인지 잘 파악하지 못했습니다. 😭

> 이 역시 상수로 선언할 필요 없이 바로 사용해도 될것이라고 생각했습니다. 이 역시 PR을 정리하는 과정에서 생긴 생각이라는게.. 문제지만요.

제가 보고 있는 코드에서는 상수에 따로 할당해서 사용해주셨는데요. 상수로 따로 선언하지 않고 바로 사용할 수 있겠고, 그렇게 바꿔보겠다는 말씀이 맞을까요? 
추가로 내 코드를 남이 읽는다고 생각했을 때, 
1. 상수로 따로 할당하는 코드 
2. 할당하지 않는 코드 

둘 중 어떤 코드가 더 읽기 편할까요? 

> 조언을 얻고 싶은 부분
겹치는 번호를 한줄로 표현하기?
저는 이걸 몰라도 해결 할 수 있을거라 생각했거든요. 이런식으로 찾아다니다가 결국 빼빼로 사태가 일어나서 고생했던 경험도 있었구요.. 그리고 말씀해주신대로 커리큘럼 내에서 완벽하게 이해하는걸 목표를 잡았기 때문입니다.

잘하셨습니다. 지금은 이해하지 못하고 넘어가도 괜찮습니다. 다음 기회에 반갑게 배워보도록 합시다. 😄

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +matchLottoNumber(what: myLottoNumbers)
호출하는 부분이 어색하게 읽혀요. `match LottoNumber what myLottoNumbers` 어떻게 바꿔볼 수 있을까요?

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
이 부분을 전역변수로 주신 거군요. 인풋이라고 가정하고 진행하셨다면 두셔도 괜찮습니다! 😄

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +func matchLottoNumber(what bettedNumbers: Array<Int>) {
betted 가 무슨 뜻인가요? 🤔

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +func makeWinnerLotto() -> Set<Int>{
리턴값 뒤에 띄어쓰기가 빠졌습니다.

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +func makeWinnerLotto() -> Set<Int>{
lotto 자체가 복권의 의미가 있으니 lotto number 나 number 처럼 구체적으로 짓는건 어떤가요?

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +    let comparedNumbers = winnerNumbers.intersection(setTypeBettedNumbers)
Set과 intersection 함수를 사용하셨군요! 👍

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +    if  comparedNumbers.isEmpty {
if 뒤 띄어쓰기가 두 개 이상 들어갔네요!

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +        var sortedComparedNumbers: [Int] = comparedNumbers.sorted()
정렬 후 sorted 붙여주셨군요. 저도 이름 지을 때 자주 사용하는 방법입니다.😄

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +    }
배열의 요소만 출력하기 위해 이런 방법을 사용하셨군요. 😄

2022-04-25 11:43 UTC, ye-ha commented on CodeStarterCamp_Week2/Lottery.swift
> +    let setTypeBettedNumbers = Set<Int>(bettedNumbers)
하나의 상수에만 타입을 명시해주었네요. 선언하는 부분은 통일해주는 것이 좋습니다!

2022-04-25 15:30 UTC, wonbi92 commented
@ye-ha 

## 고민한 부분

### 이름짓기.. 너란 녀석..
- 사실 작업하면서 네이밍이 좀 깔끔하지 않았다는 생각은 조금 했었는데 지금보니 통일성도 없고 조금 엉망진창이라서 말씀하신 부분들 포함해서 수정을 했습니다. 
- 영알못이라서.. 네이밍도 참 어렵네요.. ㅋㅋ 
- 몇몇 띄어쓰기 오류들은 코딩하면서 찬찬히 살펴보지 못했습니다.. ㅠㅠ 관련부분들 수정했습니다.

### Betted? 그 외의 네이밍
- 그 도박에서 배팅한다는 표현을 쓰잖아요? 그 배팅을 생각하고 이름을 이렇게 지었는데.. 지금 다시보니 로또를 도박처럼 생각하는 저의 삐뚤어진(?) 시선을 나타낸 단어였더라구요.. 
-  `player`라는 표현도 약간 비슷한 뉘앙스를 풍기기는 하지만, 이 프로그램을 사용하는 사용자의 번호라는 느낌으로 로또라는 일종의 소소한 즐거움을 즐기는 사람이라는 느낌으로 플레이어라고 네이밍 해봤습니다.

- `makeWinnerLotto` 역시 통일감을 주고 싶어서 `makeWinnerNumber`로 교체하였습니다.

- `match LottoNumber what myLottoNumbers` 이 부분에서 조금 고민을 했는데 "로또를 확인하는데 어떤 번호를 확인할꺼니?" 이런 흐름이면 자연스럽지 않을까 생각해서 `checkLotto(whatNumber: myLottoNumbers)` 와 같이 네이밍을 해 보았습니다.

- 상수 선언부분 역시 전체적으로 깔끔하게 통일하였습니다.

## 조언을 얻고 싶은 부분

### 전달인자 레이블, 이대로 괜찮은가?
- 첫번 째 수정 커밋을 보시면 `checkLotto(whatNumber: myLottoNumbers)` 이 함수의 전달인자를 `whatNumber`라고 지었는데요!

- 이 부분에 이런식으로 두 단어가 합쳐진, 즉 "**어떤 번호?**" 라는 느낌으로 전달인자 레이블을 사용하는건 뭔가 이상한 느낌이 들어서 API 문서를 찾아봤습니다.

> When the first argument forms part of a [prepositional phrase](https://en.wikipedia.org/wiki/Adpositional_phrase#Prepositional_phrases), give it an argument label. The argument label should normally begin at the [preposition](https://en.wikipedia.org/wiki/Preposition), e.g. x.removeBoxes(havingLength: 12).

> An exception arises when the first two arguments represent parts of a single abstraction.
>>a.move(toX: b, y: c)
>>a.fade(fromRed: b, green: c, blue: d)

>In such cases, begin the argument label after the preposition, to keep the abstraction clear.
>>a.moveTo(x: b, y: c)
>>a.fadeFrom(red: b, green: c, blue: d)

- API 문서를 봤을 때는 이렇게 사용할 수도 있고, 두번 째 
`modifty Argument Labels` 커밋 처럼 what을 밖으로 빼내어서 사용하기도 한다고 했는데, 제가 영어를 잘 몰라서... 정확하게 이해가 잘 안가네요.. ㅠㅠ 둘 중 현 상황에 맞는 표현법은 무엇인지 궁금합니다!

-  아 그리고 제가 PR올리고 나서 보니 전달인자에 오타가 있어서 그걸 수정하느라.. 커밋을 한번 더 했습니다

2022-04-26 01:30 UTC, ye-ha commented
> 하지만 그렇게 수정하지 않고 그대로 두기로 결정했습니다. 다른 사람이 볼 때 removeFirst()메소드가 바로 print문 안에 들어가 있으면 헷갈릴 수도 있다고 판단했기 때문입니다. 한줄이 더 늘어나긴 했지만 이 코드를 처음 보는 입장에서는 좀 더 직관적으로 알 수 있을거라 생각했습니다.

좋은 선택입니다. 변수와 상수, 함수의 네이밍을 구체적으로 지으면 해당 과정에 대한 설명이 됩니다. 

> 전달인자 레이블

네이밍은 항상 고민되죠.😄 [API Design Guidelines의 Strive for Fluent Usage 파트] (https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)를  참고해보세요. [야곰 아카데미에서 만든 번역본](https://yagom-academy.github.io/swift-doc-kor/)도 있습니다. 

저는 항상 `호출할 때 마치 문장처럼 자연스럽게 연결되는가` 를 생각합니다. 영어 문장처럼 표현되지 않을 때는 아규먼트 레이블을 사용하지 않기도 합니다. 가끔 어려울 때는 내가 표현하고 싶은 내용을 한국어로 만들어 놓고 영어로 바꾸는 방법을 사용합니다. 
`check Lotto What number  myLottoNumbers ` 원비님이 보시기에 어떤가요?

2022-04-26 01:32 UTC, merged