Week2 [step2] duck
yagom-academy/swift-starter-week2 pull request #205
Opened 2022-04-23 02:11 UTC by Hong-seungju

@llghdud921  안녕하세요 제리
Week2 [step2] 입니다.
이번 step2는 Int형에서 String으로 배열 변환하는 것에 어려워서 인터넷을 찾아보고 해결했습니다.

2022-04-23 06:32 UTC, llghdud921 requested changes
안녕하세요! 제리입니다~~~!!
주말인데도 열심히 코드 작성해주셨네요 👍  너무 좋습니다!!!

### Good
- 순서도에 맞게 코드 작성이 잘 이루어져있어요 💯 
- Set의 장점을 잘 살려서 로직을 잘 구현하신 것 같아요 💯 
- 코드를 너무 잘 작성하셔서 별로 코멘트 드릴 것이 없네요..ㅎㅎ 완벽... 💯

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +func makeLottoNumbers() -> Set<Int> {
`makeLottoNumbers`보다는 `generateLottoNumbers`가 더 좋을 것 같아요!
저 같은 경우는 `make`는 파라미터를 받아서 객체를 반환하는 경우 사용하고 해당 함수처럼 단순하게 숫자를 발생시키는 경우 `generate`를 사용합니다!

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +    let sortLottoNumber = lottoNumbers.sorted()
sortLottoNumber보다는 sortedLottoNumbers가 더 명확할 것 같아요
- lottoNumbers를 정렬한 값이니 복수형을 사용하고
- sort는 동사이기때문에 변수명에는 적합하지 않고 "정렬된"이라는 키워드가 더 적절해보입니다

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +    var winLottoNumbers: [Int] = []
여기도 win보다는 winning, winned가 좋아 보여용

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +    for num in 0...5 {
약어를 지양합시다~~!!!

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +var lottoNumbers: Set<Int> = Set<Int>()
전역변수를 사용해주셨는데 전역변수의 장점과 단점은 무엇이 있을까요?

2022-04-23 06:32 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoMaking.swift
> +        var winLottoNumberToString = winLottoNumbers.map{ String($0)}
해당 변수의 경우 변경되지 않는 변수이므로 let으로 정의하는 것이 좋을 것 같아욥

2022-04-23 09:12 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoMaking.swift
> +func makeLottoNumbers() -> Set<Int> {
넵 수정하겠습니다.

2022-04-23 09:13 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoMaking.swift
> +    let sortLottoNumber = lottoNumbers.sorted()
수정하겠습니답!

2022-04-23 09:18 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoMaking.swift
> +var lottoNumbers: Set<Int> = Set<Int>()
장점은 전역적으로 사용가능하다는점과 함수내의 지역변수와 달리, 지정된 값이 사라지지 않는다는 점이 장점인 것 같습니다.
단점은 사용범위가 넓어 처음에는 쉽게 사용가능 하지만 자주 사용하게 되면 결과를예측하기가 어렵습니다. 많은 곳에서 사용되므로 가독성과 신뢰성이 감소 됩니다.

2022-04-23 09:21 UTC, Hong-seungju commented
@llghdud921 수정본입니다.
이 수정본은 전역변수를 선언하지 않고 함수내에서 지역변수로 선언을 하였습니다.
네이밍을 잘지어보려고 열심히 하고 있지만 쉽지 않은 것 같습니다.

2022-04-24 15:14 UTC, llghdud921 approved these changes
수정사항 잘 확인했습니다!
어렵다고 하셨는데 굉장히 잘 하셨는데요?? 
이번스텝 머지하겠습니다~ 고생하셨어요~~~

2022-04-24 15:14 UTC, merged