Week2 [Step3] som
yagom-academy/swift-starter-week2 pull request #211
Opened 2022-04-25 05:15 UTC by jsa0224

@Jager-yoo 

즐거운 월요일(?)입니다! 
지난 주말에 하려고 했지만... 어찌저찌 월요일로 미뤄버렸습니다...:)

# 막혔던 부분
- 옵셔널 개념
아직도 옵셔널에 대한 개념이 제대로 잡혀있지 않은 것 같습니다.
값이 있을 수도 있고 없을 수도 있는 변수에 대한 이해부터 서지 않는 것 같습니다.
이번에 만든 로또로 예를 들면, 이미 1~45에서 숫자 6개를 뽑는다, 라는 코드를 만들어 배열에 담고, 그 결과를 다시 딕셔너리에 담았습니다.
이미 딕셔너리 안에는 회차마다 6개의 수가 들어있는 것을 알고 있는 상태에서 옵셔널 값으로 추정하여 옵셔널 바인딩을 해야한다는 개념이... 저에게는 와닿지 않습니다. 야곰은 강의에서 옵셔널이 값의 보호막 역할을 한다고 하시던데, 여전히 보호막이 필요한 이유도 모르겠습니다.. 

# 부족한 부분
- 코드 네이밍의 복잡성
스위프트 가이드의 코드 이름 짓는 걸 아무리 유심히 보아도... 저는 몇 번 더 시행착오에 부딫혀봐야할 거 같아요.
도무지 감이 오지 않습니다... 어쨌든 코딩에서 함수는 '행위'를 하니, ```행위 + 행위의 결과물```로 이름을 짓기로 했어요...
그랬더니 코드 네임이 점점 길어지는 건 기분탓일까요...? 맞게 하는 건지 헷갈리기 시작했습니다😩

# 새롭게 알게 된 부분
- @discardableResult
메인 파일에 ```printSecondWinningLotto(from: 2)``` 함수를 호출하니, ```Result of call to ... is unused```라는 노란 경고문이 떴습니다. 서치해보니 리턴값을 받지 않는 함수를 호출하면 나타나는 경고문이라고 합니다.
```swift
func printSecondWinningLotto(from round: Int) -> String {
    let secondWinningLottoNumbersAsString = findSecondWinningLotto(round: round).sorted().map{ $0.description }
    let joinedNumbers = secondWinningLottoNumbersAsString.joined(separator: ", ")
    let message = "\(round)회차의 로또 당첨 번호는 " + joinedNumbers + " 입니다."
    print(message)
    return joinedNumbers
}
```
리턴을 ```joinedNumbers```로 받고, ```printSecondWinningLotto```는 리턴 받지 않아서 생긴 경고 같습니다.
그런데 굳이... ```printSecondWinningLotto```이 리턴 받을 필요는 없어서 @discardableResult 를 사용해주었습니다.
직역해보니 무시가능한 결과(?) 혼자 이해하긴 애매해서 따로 찾아보니, 결과와 관계 없이 Warning을 띄우지 말라는 역할을 한다고 합니다:)

2022-04-25 16:56 UTC, Jager-yoo requested changes

2022-04-25 16:56 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PrintSecondWinningLotto.swift
> +}
- 먼저, 메서드 네이밍을 수정했습니다.
  - 개인적으로, `로또`와 같은 실생활 개념을 갖고 코드를 만들 때는, `실생활에서 쓰는 단어`를 사용하면 이해가 쉽다고 생각해요.
  - 우리가 로또를 5장 구매한다고 해볼까요? → "나 로또 5장 저장했어" 말하기 보단 `"나 로또 5장 샀어"` 라고 하잖아요? 그래서 "save" 보다는 "buy" 동사로 바꿔봤어요. 🤔 
  - 그리고 요구사항에서 얘기하는 것이 `로또 당첨 번호` 이기 때문에, 그걸 정확하게 묘사해주기 위해 솜님이 `winningLottoNumbers`라고 표현하는 건 좋아요!
  - 하지만, 개인적으로 했다면 winning 이란 단어는 그냥 빼고, Numbers 는 간단하게 `ticket`으로 바꿔서 사용할 것 같아요. 그럼 직관적이더라구요. 😄 티켓 하나에 번호가 6개 있는 거니까요.

- `let playLottoRound = 5` → 이거는 파라미터로 값을 받을 수 있도록 수정했습니다.
  - 왜냐면, 훨씬 편리하고 나중에 수정하기 편리해서입니다. ㅎㅎㅎ
  - 게임의 규칙이 바껴서, 로또 티켓을 5개 사는 게 아니라, 10개 사라고 할 수도 있잖아요?
  - 그때마다 메서드 내부의 프로퍼티를 고쳐주는 건 불편하니까, `파라미터`로 `인터페이스를 노출시켜두는`거죠. 😄 
    - 예를 들어볼까요!? → ⏰ [아날로그 알람 시계](http://image.mujikorea.net/goods/31/12/63/38/4550182114300_5_400.jpg)는, 사용자가 특정 시간에 알람이 울리도록 `파라미터(노란색 침)`를 조정할 수 있죠. 이게 `노출된 인터페이스`라고 볼 수 있어요.
    - 만약 알람 시계가 디폴트로 `오전 7시`에 알람이 맞춰져있고, 사용자는 그걸 수정할 수 없으면 어떨 것 같아요?
    - 만약 알람 시간을 수정하기 위해선, 시계 뒷편의 나사를 풀고, 패널을 열어서, 복잡한 기계 장치를 직접 사용자가 고쳐야 한다면요? 짜증나겠죠!?
    - 메서드 설계도 비슷하다고 생각하시면 됩니당. 😄 

- 그 외에 바꾼 거
  - [String: Array<Int>] → 이 표현보다는 `[String: [Int]]` 가 많이 쓰이고 가독성 좋습니다.
  - 솜이 쓰신 표현은 [대괄호] 표현과 Array<타입> 표현이 반반씩 섞인 거라.. 좀 애매해요!
  - 메서드 내의 `showRound` 같이 임시 상수도 굳이 필요하지 않습니다. 간단한 건 굳이 분리하지 않는 게 가독성 좋고, 개발 속도도 빨라져요! (네이밍 고민을 안 해도 되니까)

- 딕셔너리 타입의 인스턴스 메서드인 [updateValue](https://developer.apple.com/documentation/swift/dictionary/3127179-updatevalue) 는 무슨 기능을 하는지, 한 번 공부해보세요! 👍🏻 

```swift
func buyLottoTicket(count: Int) -> [String: [Int]] {
    var lottoTickets = [String: [Int]]()
    
    for round in 1...count {
        // Dictionary 타입의 인스턴스 메서드인 `updateValue`는 직접 찾아서 공부해보세요!
        // 스텝2 에서 구현해둔 `pickLottoNumbers()`는 리턴값이 [Int] 가 되도록 수정해서, 재사용해보세요.
        lottoTickets.updateValue(pickLottoNumbers(), forKey: "\(round)회차")
    }
    
    return lottoTickets
}
```

2022-04-25 16:56 UTC, Jager-yoo commented on CodeStarterCamp_Week2/PrintSecondWinningLotto.swift
> +}
- 요구사항에서는 `2회차` 로또 번호만 출력하는 것으로 얘기했지만, 사실 이런 것도 인터페이스 노출시켜두면 편해요.
  - 아까와 같은 논리로, 갑자기 `3회차` 또는 `5회차`를 출력하는 메서드로 바꿀 필요가 생길 수도 있으니까요. 😄 
  - 그리고 `main.swift`에서는 이 메서드 하나만 부를 거니까, `몇 회차의 로또 출력할지` 랑 `로또 티켓 몇 개 살건지` 둘 다 이 메서드의 파라미터로 넣어주는 게 좋겠어요.
  - `리턴값`은 필요 없어서 삭제했어요.

- 옵셔널 바인딩에는 `guard-let` 하고 `if-let`이 대표적이죠? ㅎㅎ
  - guard-let 잘 사용해주셨는데, `else절` 내부에서는 `예외처리`를 추가해보면 더 좋을 것 같아요!

```swift
func showLottoTicket(round: Int, totalCount: Int) {
    let lottoTickets = buyLottoTicket(count: totalCount)
    
    guard let ticketToShow = lottoTickets["\(round)회차"] else {
        // 예외 처리 해주는 센스
        print("해당 회차의 로또 당첨 번호를 찾을 수 없습니다.")
        return
    }
    
    print("\(round)회차의 로또 당첨 번호는 \(convertToString(from: ticketToShow)) 입니다.")
}
```

2022-04-25 16:56 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
>  playLotto()
이건 지난 스텝 꺼니까, main.swift 에서 꼭 불러주지 않아도 됩니다.
삭제해도 좋겠습니다! 😄

2022-04-25 16:56 UTC, Jager-yoo commented on CodeStarterCamp_Week2/main.swift
> +printSecondWinningLotto(from: 2)
저희는 위에서, 핵심 파라미터 2개가 노출된 하나의 메서드를 만들어냈습니다.

이 메서드만 갖고 놀면, 다양한 사례들을 다룰 수 있고
심지어 에러 처리까지 됩니다. 😄 

변화에 훨씬 유연하게 적응하는 메서드를 만들어낼 수 있겠죠?

```swift
// 로또 티켓 5장 구매 → 2번째 표 확인
showLottoTicket(round: 2, totalCount: 5)

// 로또 티켓 10장 구매 → 5번째 표 확인
showLottoTicket(round: 5, totalCount: 10)

// 에러 처리 확인
showLottoTicket(round: 10, totalCount: 5) // "해당 회차의 로또 당첨 번호를 찾을 수 없습니다."
```

2022-04-26 09:38 UTC, jsa0224 commented on CodeStarterCamp_Week2/PrintSecondWinningLotto.swift
> +}
앗!!!! 저도 ```convertToString``` 메서드를 다시 활용하고 싶은데, 저 메서드를 그대로 복붙해서 사용할려니까 뭔가 계속 꼬여서 저렇게 된 것 같습니다... 
어차피 배열 요소를 꺼내든, 딕셔너리 요소를 꺼내든 요소의 타입만 String으로 바꾸면 되는 메서드였는데... 
배열과 딕셔너리 특징에 차이가 있어서 ```convertToString``` 메서드를 수정해서 따로 써야된다고 생각했었나봐요.
지금 보니 일을 2번 했지만... 그래도 뭔가 알아갔다는 사실에 만족합니다... 또르륵...😞

2022-04-26 09:55 UTC, jsa0224 commented on CodeStarterCamp_Week2/PrintSecondWinningLotto.swift
> +}
- 파라미터 
오! 생각해보니 그렇네요. 
제가 너무 '5번의 로또 생성, 2회차의 로또 번호 출력' 이것만 생각했던 것 같아요.
만약에 이게 시스템이면 유저들이 다른 결과값을 얻고 싶을 수도 있는데, 제 코드는 5번의 로또 생성. 이렇게 제한을 두니까 편리한 코드는 아니라는 생각이 드네요. (물론 5라는 프로퍼티를 바꿀 수 있지만 예거의 말씀대로 불편하니까요!)

- updateValue
insert와 update 를 동시에 하는 기능인 거 같아요.
키값의 유무에 따라, 
키가 있다면 update, 키가 없다면 insert!
그런데 insert는 배열에서는 끼워넣기의 의미라 추가된다는 의미의 append로 표현하는 게 맞을까요...🧐

코멘트를 달 때, 공부를 어느정도 했다고 생각해서 쓰다보면 항상 부족한 개념들이 보이는 거 같아요 ㅎㅎ
더 공부하겠습니다!

2022-04-26 09:55 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +printSecondWinningLotto(from: 2)
ㅇ0ㅇ...!

2022-04-26 10:07 UTC, jsa0224 commented on CodeStarterCamp_Week2/PrintSecondWinningLotto.swift
> +}
헐 예외처리 너무 좋은 것 같습니다👍

2022-04-26 11:48 UTC, Jager-yoo approved these changes

2022-04-26 11:49 UTC, merged