Week2 [step3] duck
yagom-academy/swift-starter-week2 pull request #215
Opened 2022-04-25 12:47 UTC by Hong-seungju

@llghdud921 안녕하세요 제리
step3입니다.

이번 스텝은 저한테 어렵게 다가 왔어요ㅠ
딕셔너리 키값을 정렬하다가 키를 배열로 받고 하다가 안되고 String으로 받으려다 안되서 결국 Int로 받고 겨우 정렬 했네요...
옵셔널에 대해서도 더 많이 공부를 해야겠다는 생각이 드는 미션이었습니다.

2022-04-26 07:50 UTC, llghdud921 requested changes
안녕하세요 duck
이번 스텝도 고생하셨습니다 👏

코멘트를 남겨두었으니 확인 해주시고 단순하게 코드를 작성하는 것이 아니라 왜 이런 코드를 작성했는지 코멘트를 토대로 고민해보시는 것도 실력향상에 도움이 되실 거에요!

아 그리고 코멘트에 답장을 꼭 남겨주세요!! 
코드 개선이 되었으면 개선되었으며 개선이 필요없다고 생각하신 부분은 그 이유를 달아주셧으면 해요 ☺️
화이팅!

2022-04-26 07:50 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +storgedLotto(lottoRound: 5)
해당 함수는 `[Int: Set<Int>]` 딕셔너리를 반환하는데요! 반환하는 값을 쓰이지 않네요!
개선해볼까요?

2022-04-26 07:50 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +    if let printLottoInfo = storgedLottoInfo[findRound] {
`if let` 구문을 이용해서 옵셔널 처리를 하셨네요! 👍 
`guard`문을 사용하는 방법도 잇는데 `if let` 구문을 사용하셨는지 여쭤볼수 잇을까요?

2022-04-26 07:50 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +func findLottoRound(findRound: Int) {
findRound라는 매개변수 명이 어색합니다,,ㅠ 그냥 round만 사용해도 괜찮을 것 같아요!

2022-04-26 07:50 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +var storgedLottoInfo: Dictionary<Int, Set<Int>> = [Int: Set<Int>]()
현재 [Int: Set<Int>] 타입의 딕셔너리를 정의하셨는데요!
요구사항에서는 `"1회차": [1, 2, 3, 4, 5, 6]` [String: [Int] 타입 즉, key는 String, value는 Int 배열로 나타나있습니다!
이 부분 요구사항에 맞추어 수정해봅시다!

2022-04-26 07:50 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +
의미없는 줄바꿈은 없애는 게 좋을 것 같아요~

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +        let round = number
어.... 실수입니다.
코드 다시 보면서 그게 왜 들어가있지 했었는데 다시 수정하겠습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +var storgedLottoInfo: Dictionary<Int, Set<Int>> = [Int: Set<Int>]()
storage인데 오타인것 같습니다.
약어를 지양하겠습니다. 수정하겠습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +storgedLotto(lottoRound: 5)
넵 개선하겠습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +    if let printLottoInfo = storgedLottoInfo[findRound] {
guard문을 쓰게 되면 전역변수로 사용할 수 있어서 단순히 전역변수보다 지역변수를 사용하는 if let을 사용하는게 더 좋다고 판단을 하게 되어 if let을 사용하게 되었습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +func findLottoRound(findRound: Int) {
넵 수정하겠습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +var storgedLottoInfo: Dictionary<Int, Set<Int>> = [Int: Set<Int>]()
단순히 보자마자 Set을 넘기면 되겠다고 생각했습니다.
수정하겠습니다.

2022-04-26 08:15 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +
넵 수정하겠습니다.

2022-04-26 11:36 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +        let round = number
어.... 다시 보니 왜 그랬지?? 했습니다.
수정했습니다.

2022-04-26 11:36 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +var storgedLottoInfo: Dictionary<Int, Set<Int>> = [Int: Set<Int>]()
네 약어를 항상 지양하도록 하겠습니다.
save로 수정하였습니다.

2022-04-26 11:36 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +storgedLotto(lottoRound: 5)
넵 개선했습니다.

2022-04-26 11:37 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +    if let printLottoInfo = storgedLottoInfo[findRound] {
if let을 쓰면 블록안의 변수가 지역변수로만 사용이 되어서 guard문의 블록안의 전역변수보다 더 괜찮을 듯 하여 if let을 사용하였습니다.

2022-04-26 11:37 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +func findLottoRound(findRound: Int) {
넵 수정했습니다.

2022-04-26 11:38 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +var storgedLottoInfo: Dictionary<Int, Set<Int>> = [Int: Set<Int>]()
요구사항에 맞추어 수정을 하다보니 로또번호를 랜덤으로 생성하는 함수의 반환 부분을 Array<Int>로 변환을 해주었습니다.

2022-04-26 11:38 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +
넵 수정하였습니다.

2022-04-26 11:50 UTC, Hong-seungju commented
@llghdud921  Step3 수정본 입니다.

2022-04-26 16:03 UTC, llghdud921 requested changes
정말 잘해주셨어요!! 👍 
변수명이 너무너무 아쉬워서 변수명에 대해 생각하고 개선해보고 넘어가봅시당! 화이팅 😄

2022-04-26 16:03 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +func saveLotto(lottoRound: Int) -> () {
`lottoInformation` 변수에 값을 저장하는 역할을 하니 `saveLottoInformation`이라는 변수명도 좋을 것 같아요!!

2022-04-26 16:03 UTC, llghdud921 commented on CodeStarterCamp_Week2/LottoRound.swift
> +    if let printLotto = lottoInformation["\(round)"] {
로또 번호를 나타내는 변수가 printLotto는 맞지 않는 것 같습니다!! 개선해볼까요?

2022-04-26 22:39 UTC, Hong-seungju commented
@llghdud921 
안녕하세요 제리
변수명 개선 수정본 입니다.

2022-04-26 22:39 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +func saveLotto(lottoRound: Int) -> () {
넵 개선하였습니다.

2022-04-26 22:39 UTC, Hong-seungju commented on CodeStarterCamp_Week2/LottoRound.swift
> +    if let printLotto = lottoInformation["\(round)"] {
넵넵 개선하였습니다.

2022-04-27 00:50 UTC, llghdud921 commented
넵 고생하셨습니다~!!
머지하고 넘어갈게용~~

2022-04-27 00:50 UTC, merged