Week2 step3
yagom-academy/swift-starter-week2 pull request #23
Opened 2021-12-19 02:09 UTC by JungmoYu

@Neph3779  안녕하세요! 주말 잘 쉬고 계신가요?
Step3의 내용 PR발행합니다!

네이밍 관련하여 수정사항을 몇번 만들어서, 커밋이 여러차례 있습니다.
그리고 함수를 만들다보니, 전역변수의 속성을 이용해서 함수 input을 줄이는 방법으로 최종적으로 수정하였습니다.

전역변수임을 알고 사용하는 함수이기에 이렇게 만들어도 되는것인지, 아니면 함수의 인풋으로 어떤 변수가 오더라도 사용할 수 있도록 기존의 방법대로 함수를 구현한게 더 좋은코드인지 궁금합니다!

감사합니다.

2021-12-20 00:29 UTC, Neph3779 requested changes
안녕하세요 정모님!
조금 더 개선해볼 수 있는 곳들이 보이네요 🥲
<img width="852" alt="스크린샷 2021-12-20 오전 9 23 30" src="https://user-images.githubusercontent.com/67148595/146696471-dabb801f-f061-4a8b-80b2-24877c6be294.png">
출력도 요구사항과 다른 부분들이 나오고 있는데 이 부분도 체크해주시면 감사하겠습니다!

2021-12-20 00:29 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +//MARK: - Step3
PR을 보내는 코드에 필요없는 주석들인 것 같아요
Step2에서 사용되었던 코드는 깃을 통해 관리할 수 있으니 굳이 주석으로 남기지 않는게 좋아보입니다!

2021-12-20 00:29 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
>  }
someArrayIndex라는 네이밍이 조금 부적절해 보여요 🥲
전반적으로 가독성도 조금 떨어져보이기도 하는 것 같은데
조금 더 개선해볼 수 있을 것 같습니다!

2021-12-20 00:29 UTC, Neph3779 commented on CodeStarterCamp_Week2/step3.swift
> +//  step3.swift
파일의 네이밍이 부적절해보이네요
위에서도 언급했듯 깃을 쓰는 이유에 대해 다시 생각해봅시다!

2021-12-23 08:04 UTC, JungmoYu reviewed
@Neph3779 안녕하세요 네프님!

체인지 리퀘스트 관련하여 내용수정합니다!

코멘트로 어떻게 생각하여 변경한것인지 적겠습니다.

2021-12-23 08:04 UTC, JungmoYu commented on CodeStarterCamp_Week2/extractLottoNumbers.swift
>  }
인덱싱 방식이 뭔가 이것도 저것도 아니라서 변경을 했습니다.
(어디서는 count - 1 / 어디서는 endIndex - 1)이렇게 사용하는것이 다시보니 좋아보이지 않아서요!

그래서 상수를 하나 할당하여 어레이의 길이를 활용하였습니다!

2021-12-23 08:04 UTC, JungmoYu commented on CodeStarterCamp_Week2/step3.swift
>  }
요 댓글을 저번에 달았는데, 알고보니 리뷰 코멘트 제출을 안해서 pending으로 댓글이 남아있었습니다 ㅜㅜ

2021-12-23 11:54 UTC, Neph3779 commented on CodeStarterCamp_Week2/step3.swift
>  }
보통은 객체에 감싸서 보호하는 형식을 취하지만 이번 스텝에서는 이 부분까진 다루기 어려울 수 있을 것 같습니다
일반적으로 전역변수를 직접 사용하는 것은 최대한 지양하는것이 좋아요!

2021-12-23 11:59 UTC, Neph3779 commented
안녕하세요 정모님! 네이밍도 많이 개선되었고
가독성도 많이 좋아졌네요!
스텝 진행하시느라 고생 많으셨고 이번 스텝은 여기서 머지하도록 하겠습니다!
너무 고생 많으셨어요! ☺️

2021-12-23 12:00 UTC, merged

2021-12-23 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week2/step3.swift
>  }
@Neph3779 감사합니다.

뭔가 전역변수를 많이 쓰는것이 좋지는 않을 것 같았습니다!

죄송하지만, 객체에 감아서 보호하는 형식이라는것을 어떤식으로 제가 키워드를 잡고 공부해보면 될지 여쭤볼 수 있을까요?
추후에 공부해보고 다시 여쭤보도록 하겠습니다. 지금은 이야기만 들어서는 감이오질않아서요 ㅜㅡㅜ

2021-12-23 14:51 UTC, JungmoYu commented
> 

감사합니다!

2021-12-23 14:53 UTC, Neph3779 commented on CodeStarterCamp_Week2/step3.swift
>  }
음.. type을 활용하는거에요!
enum, namespace 등의 키워드로 검색해보면 더 좋을 것 같네요!

2021-12-23 15:04 UTC, JungmoYu commented on CodeStarterCamp_Week2/step3.swift
>  }
앗 그러니까
전역변수를 최대한 쓰지 않고 위와같은 기능을 구현할 때
type을 활용하여 객체에 감아 보호한다!  의느낌을 가지고 공부를 해 보겠습니다!
(여기에 enum, namespace 등의 키워드 활용)
감사합니다.