Week2 [STEP 2] 애쉬
yagom-academy/swift-starter-week2 pull request #230
Opened 2022-04-27 06:33 UTC by ash-you

안녕하세요 호댕! (@yanghojoon)
Week2의 STEP2를 작성하게되어 PR 보내드립니다.

### 📌 작성 세부사항
이번 스텝은 아래와 같이 구성해봤습니다.
1. 기존에 작성했던 순서도와 동일하게 로또번호를 생성하는 함수
2. 당첨 번호와 내 번호를 대조해본 결과를 출력하는 함수

2번 함수는 당첨 번호가 내 번호를 포함하고 있으면 멤버가 append 되는 Array 타입의 변수(matchedNumbers)를 선언해서 확인하는 방식으로 작성해봤습니다.

처음에는 이 배열을 그대로 결과값으로 출력하려고 했는데, 배열이다보니 미션에서 요구한 것과는 다르게 대괄호가 포함되어서 출력이 되더라구요😓
그래서 switch문을 이용해서 matchedNumbers.count 값에 따라 코드를 따로 작성해서 당첨이 되었을 때와 안 되었을 때를 조금 더 명확하게 구분짓는 방식으로 작성하고 -> 당첨번호가 2개 이상일 때 괄호 없이 출력되도록 인덱스 값을 가져와 출력해봤습니다.
#
### 🤥 궁금한 점
추가로 코드를 작성하면서 궁금한 점이 있어 질문드립니다!
1번 함수에서 당첨 번호를 .ramdomElement() 메서드를 사용해서 가져오게 되면 옵셔널 타입으로 값을 가져오게 돼서 nil일 때를 대비해 default 값을 작성해야 하는 것으로 보였습니다.
현재 작성한 함수는 nil이 있을 수 없으니 default값으로 일단 0이라는 숫자를 임의로 기재하였는데, 이렇게 작성해도 되는 걸까요? 혹시 조금 더 안전한 코드를 위해서 생각해 보아야 할 부분이 있는지 궁금합니다!

2022-04-27 13:37 UTC, yanghojoon requested changes
이번 Step도 고생많으셨습니다. 애쉬 @ash-you
반복문과 조건문에 훨씬 익숙해지신 것 같군요 👍 

### 👍 잘하신 부분
- for문 / while 문 등을 익숙하게 사용해주신 점
- switch 문을 통해 분기해주신 점 
- 순서도에 따라 로또 번호를 생성하는 메서드를 작성해주신 점

### 🤔 고민해보시면 좋을 부분 
- 옵셔널 바인딩의 다양한 방법 
- 함수 분리
- 파일 분리

고민해보시면 좋을 부분은 코멘트로 좀 더 자세하게 작성해놓았습니다!!

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +        winningNumbers.insert(allNumberSet.randomElement() ?? 0)
nil 병합 연산자를 사용하여 옵셔널 값을 처리해주셨군요! 
이렇게 옵셔널 값을 처리해줘도 문제는 없습니다! nil이 나오면 항상 기본값으로 0을 반환할테니까요!

다만 옵셔널을 처리하는 다른 방법을 사용할 수는 없을까요? 
다른 방법도 공부해보시고 적용해보셔도 좋을 것 같습니다.

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +var allNumberSet: Set<Int> = Set<Int>()
Set을 사용하여 중복값을 처리해주셨군요! 다만 아직 allNumberSet을 Set으로 만들어야 하는지는 의문입니다. 
단순히 1~45까지의 Collection만 가지면 되는데 Set으로 해주신 이유가 있으실까요?

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +    }
함수를 시작하고 for문 전에 줄바꿈을 하셨는데 마지막에는 줄바꿈을 안해주신 이유가 있으실까요?

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +    switch matchedNumbers.count {
switch 문을 사용하여 분기하신 점 좋습니다! 👍

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +func matchLottoNumbers() {
로또 번호와 겹치는 숫자가 있는지 확인하는 로직과 결과를 보여주는 로직이 함께 있는 것 같아요. 
이를 분리해줄 수는 없을까요??

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +        print("unknown")
default에 print를 하지 않고 처리해줄 수 있는 방법은 없을까요?

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +        for index in 0..<matchedNumbers.count {
마지막 index를 찾기 위해 count를 쓰셨군요! 
혹시 array에 더 적합한 프로퍼티는 없을까요?

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +            if index != (matchedNumbers.count - 1) {
현재는 간단한 코드라 알아보는데 크게 문제가 없지만 코드의 양이 많아지고 협업을 하거나, 코드를 작성한지 오래 지나다 보면 해당 조건이 뭘 의미하는지 한 번에 파악하기 어려울 수 있을 것 같아요. 
이를 해소하려면 어떻게 하는 것이 좋을까요? 🤔

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +var winningNumbers: Set<Int> = Set<Int>()
같은 Set 타입인데 위에는 네이밍에 Set을 붙이고 밑에는 붙이지 않으신 이유가 있으실까요?

2022-04-27 13:37 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +var myLottoNumbers: [Int] = [15, 26, 31, 4, 12, 7]
프로젝트 요구사항과 다른 점이 있는 것 같아요 🧐

2022-04-28 15:27 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +        winningNumbers.insert(allNumberSet.randomElement() ?? 0)
코멘트 주신 것 고려해서 옵셔널 파트에서 배운 옵셔널 바인딩을 이용해서 처리해보았습니다! 
현재 코드 상으로 디폴트값이 들어갈 일은 없겠지만, 이렇게 값이 있는지 없는지 확실히 확인한 후에 값을 insert하는 것이 더 안전할 것 같았습니다!

2022-04-28 15:32 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +var allNumberSet: Set<Int> = Set<Int>()
사실 Array와 Set 둘 중에 고민을 했었는데, 당시 생각으로는 지금 기능 상 둘 중 무엇을 사용해도 딱히 장점이나 단점은 없을 거라고 생각했습니다.
그런데, 이번에 코드를 수정하면서 1부터 45까지의 숫자를 담는 컬렉션이기 때문에 혹시 출력을 하게 된다면 순서대로 보여줄 수 있는 Array가 좀 더 보기 좋을 것 같아서 Array로 수정해봤습니다!
혹시 제가 두 컬렉션 타입에서 고려하지 못한 특징이 있다면 도움을 주시면 좋을 것 같아요 🥲

2022-04-28 15:34 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +    }
보통 반복문을 2개 사용하는 경우에 그 사이에 한칸씩 띄워서 사용하는 것 같아서 함수를 시작하고도 일단... 띄워버린 것 같습니다ㅎㅎ...
다른 곳에서 예제코드를 살펴보니 함수를 시작하고서 반복문을 사용해서 줄바꿈을 하지 않는 것 같아서 앞으로 이렇게 통일해보려고 합니다!

2022-04-28 15:36 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +func matchLottoNumbers() {
로또 번호와 매치해보는 함수와 출력하는 함수를 아예 분리해서 리팩토링 해봤습니다.

2022-04-28 15:37 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +        print("unknown")
디폴트 값이 나올 일은 없을 것 같아서 일단 Week2에서 배운대로 unknown을 출력하는 출력문을 넣었었는데, 아무래도 이것보다 break을 사용해서 아예 조건문을 중지시키는 것이 안전할 것 같아 break으로 수정했습니다!

2022-04-28 15:45 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +            if index != (matchedNumbers.count - 1) {
이 부분은 코드의 구조를 바꾸어볼까 고민을 해봤는데, 명쾌한 답이 나오지 않아서 기존의 조건문을 조금 더 우리가 생각하는 if 문장에 가깝게 수정해봤습니다.

기존: index가 마지막 인덱스가 아니면 ~~, 그렇지 않으면 ~~
수정: index가 마지막 인덱스면 ~~, 그렇지 않으면~~

그리고 주석으로 어떤 코드인지 한줄로 설명하는 방법으로 수정해봤습니다!

2022-04-28 15:50 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +generateLottoNumber()
Week1 미션에서 진행했던 것처럼 추가로 새로운 프로젝트 파일을 추가하고, 그 파일에서 호출문을 사용하게 되면 발생하는 최상위레벨 오류를 방지할 수 있을 것 같습니다.
또, 호출문이 여러 프로젝트 파일에 나누어 구성되어 있더라도 main.swift 에서는 가져와서 실행을 할 수 있으니 원하는 코드만 실행을 할 때에도 간편해질 것 같았습니다!

2022-04-28 15:52 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +var winningNumbers: Set<Int> = Set<Int>()
사실 이 부분에서 Set는 Set 타입이라는 걸 명시하는 것보다는 말그대로 숫자의 세트다! 라는 걸 알리고 싶어서 기재를 했던 것이었는데, 이번에 코드를 수정하면서 Array 타입으로 수정되기도 하였고, 굳이 필요한 단어는 아닌 것 같아서 네이밍을 수정했습니다. 😀

2022-04-28 15:52 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +var myLottoNumbers: [Int] = [15, 26, 31, 4, 12, 7]
수로 선언을 하였었네요 😂 상수로 수정했습니다!

2022-04-29 01:44 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +var allNumberSet: Set<Int> = Set<Int>()
말씀해주신대로 Set은 순서가 없고 Array는 순서가 있다는 점도 둘의 큰 차이점 중 하나라고 생각합니다. 
해당 Collection에 특정 요소를 삽입 / 교체 / 추가하는 방법에도 차이가 있는데 이 부분은 애쉬가 찾아보셔도 좋을 것 같아요! 😆

제가 생각했을 때에는 단순히 for문을 통해 1~45까지의 Int 값을 넣어주기만 하는데 굳이 Set으로 사용할 필요가 있을까 해서 질문드렸었습니다. 

다만 단순히 `보기 좋아서` 특정 코드를 선택하기 보단 둘의 장단점을 비교해보고 선택하는 것이 좋을 것 같아요! 

저는 
1. 중복값을 사용할 필요가 없다. 
2. Set의 intersection, subtracting 같은 메서드를 사용할 필요가 없다. 
3. Set은 subscript로 쉽게 요소에 접근할 수 없다. 
의 이유로 굳이 Set을 사용할 필요가 없다고 판단했습니다.

2022-04-29 01:48 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +    }
물론 줄바꿈은 개인의 취향(?)인 경우가 많아 어떻게 해도 잘못된 것은 아니지만, 애쉬만의 줄바꿈 기준이 있으시면 좋죠 👏

2022-04-29 01:50 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +var myLottoNumbers: [Int] = [15, 26, 31, 4, 12, 7]
상수로 선언할 수 있는 부분은 꼭 var로 선언하지 않도록 주의해보시면 좋은 습관이 될 것 같습니다!

2022-04-29 02:04 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +        for index in 0..<matchedNumbers.count {
아하 저는 count대신 endIndex를 사용하는 것을 생각했었는데 index(before:)까지 찾아보셨군요!
수정한 코드가 이전보다 눈에 잘 들어오는지에 대해선 밑에 작성했습니다.

2022-04-29 02:08 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +            if index != (matchedNumbers.count - 1) {
아하 index(before:) 메서드를 사용해서 endIndex 직전 인덱스면 끝나게 하도록 구현하셨군요 ㅎㅎㅎ
제가 생각했던 방향은 마지막 index를 함수 내 상수로 분리를 해두고 사용하는 것이었습니다! 

```swift
func printLottoResult() {
    let lastIndex = matchNumbers.endIndex - 1

    switch matchedNumbers.count {
    case 0:
        print("아쉽지만 겹치는 번호가 없습니다.")
    case 1:
        print("축하합니다! 겹치는 번호는 \(matchedNumbers[0]) 입니다!")
    case 2...winningNumbers.count:
        print("축하합니다! 겹치는 번호는 ", terminator: "")
        for index in 0..<lastIndex {
            if index == lastIndex {
                print(matchedNumbers[index], terminator: "")
            } else {
                print(matchedNumbers[index], terminator: ", ")
            }
        }
        print(" 입니다!")
    default:
        break
    }
}
```

2022-04-29 02:16 UTC, yanghojoon commented on CodeStarterCamp_Week2/main.swift
> +        print("unknown")
break를 사용해 조건문을 중지시키는 것이 왜 안전하다고 생각하셨나요??
(진짜 단순하게 이유가 궁금해서 여쭤봐요!)

2022-04-30 16:17 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +var allNumberSet: Set<Int> = Set<Int>()
Set의 집합 관련 메서드 사용여부, Array 처럼 인덱스를 사용해서 쉽게 요소에 접근할 수 없다는 점은 생각해보지 못한 부분이었던 것 같습니다! 코드에서 당장 사용되지 않더라도 좀 더 확장해서 생각해보도록 노력해야 할 것 같습니다 (아직은...많이 어렵지만요😭)
추가로 컬렉션 타입별로 요소의 삽입 / 교체 / 추가 방법에 대해서는 조금 더 알아보고 TIL에 정리해 봐야겠습니다. :)

2022-04-30 16:20 UTC, ash-you commented on CodeStarterCamp_Week2/main.swift
> +            if index != (matchedNumbers.count - 1) {
앗 선언해서 상수명을 사용하는 방법을 생각을 못했다니 코멘트 주신대로 수정했더니 훨씬 한번에 읽히는 느낌입니다 😀
수정해서 커밋해보았습니다!

2022-05-02 09:00 UTC, yanghojoon approved these changes

2022-05-02 09:01 UTC, merged