Week2 [STEP 3] wonbi
yagom-academy/swift-starter-week2 pull request #233
Opened 2022-04-27 18:47 UTC by wonbi92

## 고민한 부분

### 전역변수
- 이 문제에서도 전역변수를 하나 추가 했습니다. 
> 회차와 Lotto번호들을 저장하는 Dictionary 타입의 변수를 생성합니다.
- 이 `로또 번호를 저장하는 변수`인데요. 이걸 전역 변수로 설정한 이유는, 각 함수 내부에 지역변수로 이를 할당하면 각 함수가 실행될 때마다 각각 다른 값을 가지는 딕셔너리가 만들어지기 때문이었습니다.

- 예를 들어, `로또 번호를 만드는 함수`, `당첨 로또 번호를 확인하는 함수` 안에 지역변수로 들어가 있으면, 각 함수 안에 당첨 로또번호가 따로 존재하게 되는 결과가 생겼기 때문입니다.

- 사실, `로또 번호를 만드는 함수`의 반환 값을 딕셔너리로 한 다음, 이 함수를 `당첨 로또 번호를 확인하는 함수`의 매개변수로 넣을까 생각도 했었는데요. 
```Swift
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)
```
- 위와 같은 느낌으로 말이죠. 근데 이건 가독성도 안좋고, 실행할 때마다 `로또 번호를 저장하는 변수`를 자꾸 초기화 시키는 문제가 있었습니다.

```Swift
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)    // 
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)    // 윗줄의 결과와 다른 값이 나옴
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 4)    //
```
- 위와 같이 각 회차별로 여러번 확인하고 싶어서 `checkWinnerNumbers`함수를 여러번 호출하면 각각 독립된 `로또 번호를 저장하는 변수`가 생성되서 2회차를 두번 확인하면 번호가 바뀌는 이상한 결과가 나왔습니다.

- 그래서 전역변수로 선언을 해서 한번 정해진 로또 번호는 바뀌지 않게 하였습니다.

### 옵셔널 바인딩을 통해 안전하게 추출하기
- if let 구문을 사용하여 바인딩한다는 것은 알았지만, 한가지 문제가 있었습니다.
```Swift
if let winnerNumbers = winnerNumbersStorage["\(round)회차"] {
        print("\(round)회차의 로또 당첨 번호는", terminator: " ")
        while winnerNumbers.count > 1 {
            print(winnerNumbers[0], terminator: ", ")
            winnerNumbers.removeFirst()
        }
        print(winnerNumbers[0], "입니다.", separator: " ")
}
```
- 위와 같이 `winnerNumbersStorage`변수의 옵셔널 값을 Unwrapping하는 것 까지는 좋았으나, 이후 로또 번호를 출력하는 과정에서 `removeFirst`메소드를 이용해 배열의 첫번째 값을 지우는데서 발생하였습니다.

- let은 상수이기 때문에 `winnerNumbers`의 값을 수정할 수 없었던 것입니다.

- 이거 맵핑을 사용해야 하나 고민했지만, `if let`이 있으면 `if var`도 있지 않을까? 라는 생각이 들어서 바로 적용시켜 보았습니다.

- 다행히 `if var`도 사용 가능했습니다.

- 마지막으로 아직 번호가 생성되지 않아 `nil`을 반환할 경우, 그에 맞는 문구가 출력되게 설정하였습니다.

## 조언을 얻고 싶은 부분

### 다양한 메소드와 map, 그리고 joined
- 사실 코드를 짤 당시 처음부터 조금 맘에 들지 않는 부분이 있었습니다.
```Swift
var winnerNumbers: Set<Int> = []
while winnerNumbers.count != 6 {
    winnerNumbers.insert(Int.random(in: 1...45))
}
```
- 바로 이 부분인데요. 사실 문제는 없었습니다만.. 6개가 채워질 때 까지 중복 값은 무시하기 때문에 가끔씩 6번을 넘기면서 while문이 반복되는 것이 맘에 들지 않았습니다.

- 이부분을 해결할 방법이 없을까 고민하다가, *정렬하는 메소드가 있는데 섞는 메소드도 있지 않을까?* 라는 생각이 들어서 메소드를 찾아봤습니다.
```Swift
func makeWinnerNumbers(time: Int){
    let allNumbers: Array<Int> = Array<Int>(1...45)
    for timeCounter in 1...time {
        var winnerNumbers: Array<Int> = []
        winnerNumbers = Array<Int>(allNumbers.shuffled().prefix(6))
        winnerNumbersStorage["\(timeCounter)회차"] = winnerNumbers.sorted()
    }
}
```
- 그 결과로 다시 짠 코드입니다. `shuffled`와 `prefix`를 통해 while문 반복 없이 랜덤한 6자리 수를 뽑아왔습니다.

- 하지만 이코드를 적용시키진 않았습니다. 그 이유는 prefix에서 `ArraySlice`라는 새로운 개념이 나왔고, 이 부분이 정확히 이해가 되지 않아서 이유없는 코드가 되어버렸다고 생각해서 였습니다.
```Swift
let stringOfWinnerNumbers = winnerNumbers.map{ String($0) }.joined(separator: ", ")
```
- 사실 map과 joined도 같은이유로 코드를 짜보긴 했지만 적용시키진 않았습니다. 맵핑은 확실히 컴파일러의 부담도 줄여주고, 코드 가독성도 올려주었지만, 제가 이해 못하면 사용할 수 없다 판단했기 때문입니다.

- 위와 같이 생각하며 적용시키는 것이 잘한 판단인가? 에 대한 고민은 아직 있습니다만, 일단 이런것도 있다는 것만 알고 넘어가기로 했습니다. 다 이해되는 날이 오면 그 때 사용하려 합니다.

2022-04-28 07:51 UTC, ye-ha requested changes
> 위와 같은 느낌으로 말이죠. 근데 이건 가독성도 안좋고, 실행할 때마다 로또 번호를 저장하는 변수를 자꾸 초기화 시키는 문제가 있었습니다.

가독성이 안좋은 문제는 변수에 할당해주는 것으로 해결할수도 있죠. 함수가 계속 호출되어 초기화되는 문제를 발견하셨군요. 좋습니다! 

> 바로 이 부분인데요. 사실 문제는 없었습니다만.. 6개가 채워질 때 까지 중복 값은 무시하기 때문에 가끔씩 6번을 넘기면서 while문이 반복되는 것이 맘에 들지 않았습니다.

`가끔 6번을 넘기며` 가 6보다 커진다는 의미 맞나요? 해당 부분은 조건을 바꿔주며 해결할 수 있습니다. 

> 위와 같이 생각하며 적용시키는 것이 잘한 판단인가? 에 대한 고민은 아직 있습니다만, 일단 이런것도 있다는 것만 알고 넘어가기로 했습니다. 다 이해되는 날이 오면 그 때 사용하려 합니다.

좋습니다. 원비님의 판단을 존중하고, 학습을 응원합니다.😄👍

2022-04-28 07:51 UTC, ye-ha commented on CodeStarterCamp_Week2/Step 3.swift
> +func makeWinnerNumbers(time: Int){
괄호 앞 띄어쓰기가 빠졌습니다! 컨벤션 아주 중요해요. ⭐️

2022-04-28 07:51 UTC, ye-ha commented on CodeStarterCamp_Week2/Step 3.swift
> +}
주요한 로직이 비슷해보여요. step2에서 만든 함수를 재사용할 수 있을까요?

2022-04-28 07:51 UTC, ye-ha commented on CodeStarterCamp_Week2/Step 3.swift
> +    if var winnerNumbers = winnerNumbersStorage["\(round)회차"] {
안전하게 옵셔널 바인딩하셨군요. if var 사용! 👏👏 
if var도 있을 거라고 추측하시고 사용해보신 점 좋아요. 
if let 과 어떤 차이가 있는지, 확실히 감 오셨나요? 😄

2022-04-28 07:51 UTC, ye-ha commented on CodeStarterCamp_Week2/main.swift
두 줄이 개행되었어요. 보통 개행은 한 줄만 합니다!

2022-04-28 07:51 UTC, ye-ha commented on CodeStarterCamp_Week2/Step 3.swift
> +}
이 부분도 스텝2와 중복되는 코드가 꽤 있습니다. 기존 코드를 재사용해볼 수 있을까요?

2022-04-28 07:52 UTC, ye-ha commented on CodeStarterCamp_Week2/Step 3.swift
> +    for timeCounter in 1...time {
for문 내에서 의미있는 네이밍을 해주신 점, 좋습니다. 👍👍👍👍

2022-04-28 13:59 UTC, wonbi92 commented on CodeStarterCamp_Week2/Step 3.swift
> +}
네! step2의 함수를 재사용하여 더 깔끔하게 수정했습니다!

2022-04-28 14:00 UTC, wonbi92 commented on CodeStarterCamp_Week2/Step 3.swift
> +    if var winnerNumbers = winnerNumbersStorage["\(round)회차"] {
if let 구문 안에서 다시 변수를 선언해서 값을 넣어줄 필요없이 바로 사용할 수 있었습니다. 안에서 바인딩한 값을 이리저리 만져야 할 때 if var를 사용하면 좋을거 같네요!

2022-04-28 14:01 UTC, wonbi92 commented on CodeStarterCamp_Week2/main.swift
요게.. 무슨 뜻인지 잘 이해가 안되네요.. 😳😳 엔터를 두번 친건가요??

2022-04-28 14:02 UTC, wonbi92 commented on CodeStarterCamp_Week2/Step 3.swift
> +}
처음에는 몇가지 기능이 달라서 재사용이 힘들까 하다가, 두 기능을 다 하는 함수를 만들자! 로 바꿔서 조금 수정을 하고, 새 함수를 만들어 봤습니다. 자세한 과정은 밑에 따로 코멘트 하였습니다!

2022-04-28 14:03 UTC, wonbi92 commented on CodeStarterCamp_Week2/Step 3.swift
> +    for timeCounter in 1...time {
```Swift
for time in 1...time {   }
```
보통 이런 느낌으로 많이 쓰던데, 이것도 for문 안에서 하나의 변수로 쓰이기에, 이름이 있으면 좋을거 같아서 지었습니다!

2022-04-29 13:30 UTC, ye-ha reviewed
고생하셨습니다! 😄

2022-05-02 09:24 UTC, merged