Week2 [Step 01] Oh Sung Ah
yagom-academy/swift-starter-week2 pull request #242
Opened 2022-04-30 08:17 UTC by delight010

Set의 함수 intersection을 이용하여 로또당첨번호와 myLottoNumbers의 중복되는 부분만 추출했습니다.

Set의 값들을 괄호([])가 없는 1줄의 문자열로 표현하고싶어서 이것저것 찾아봤는 데요.
문자열 배열을 1줄의 문자열로 바꿔주는 joined라는 함수가 있다는 것을 알게 되었습니다.

다만, intersection Set을 문자열 배열로 바꿔주는 작업이 필요해서 
고차함수 map을 이용하여 문자열 배열로 바꿔주었습니다.

print문을 사용하여 출력할 때, 문자열을 넣어서 그대로 출력하기보다는
재사용할 수 있는 변수 resultOfLotto를 이용하여 출력하였습니다!

2022-04-30 13:55 UTC, jaemuYeo requested changes
스텝2도 빠르게 진행하셨군요 👏
구현에 필요한 코드를 적절하고 간결하게 잘 표현하신 것 같아요!
몇 가지 코멘트 남겼으니 확인해주셔요!

2022-04-30 13:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +func pickedLottoNumbers() -> Set<Int>{
이 함수의 네이밍이 조금은 부자연스럽다 생각이 들어요!🤔
`생성하다`와 같은 동사로 시작하는게 어떨까 생각하는데 성아님은 어떠신가요??

2022-04-30 13:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +        let num = Int.random(in: 1...45)
num이라는 축약된 네이밍보다는 number라고 명확하게 표현하는 것이 좋을 것 같아요 ☺️

2022-04-30 13:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(winTheLotteryNumbers: Set<Int>, myLottoNumbers: Set<Int>) {
함수명에 LottoNumbers라는 네이밍이 들어가있는데 매개변수명에도 LottoNumbers 또는 Numbers가 겹치네요!
중복되지 않게 수정해볼 수 있을까요??
예를들면 func 로또번호체크(당첨의:나의것과:) 처럼요!

2022-04-30 13:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    let arrayIntersectionNumbers = intersectionNumbers.map { String($0) }
고차함수 사용 멋집니다 👍

2022-04-30 13:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    var resultOfLotto = String()
저는 print문 자체가 재사용하기 편하게 나온 함수라 생각이듭니다🤔
그래서 지금과 같은 형식보다 바로 print를 사용해서 출력하는 것을 더 선호하는데
성아님은 어떻게 생각하시나요??

2022-05-01 13:31 UTC, delight010 commented
함수,매개변수 등 가급적 길게길게 쓰는 편인 데.
잼킹님 말씀을 듣고보니 로또번호를 중복체크하는 함수의 매개변수명은 짧게 써도 문제가 없네요.
가독성있게 네이밍하는 법을 좀 더 강구하게 되는 것 같아요.

로또당첨 print하는 부분도 수정하였습니다!
많이 사용하지않는 변수를 굳이 만들필요는 없을 것 같습니다

2022-05-01 14:51 UTC, jaemuYeo reviewed
제가 남긴 코멘트들은 절대로 정답이 아니니 성아님의 생각이 맞다싶으면
수정하지 않으셔도 좋아요!! 단, 제가 남긴 코멘트에 대해 반대되는 이유를 
작성해주시면 좋은 것 같습니다 😉
그래도 저의 의견에 설득되어서 수정해주신거라 생각할게요!! ☺️
이번 스텝은 여기서 머지할게요~~ 스텝3에서 만나요!

2022-05-01 14:51 UTC, merged