Week2 [Step 2] OneE
yagom-academy/swift-starter-week2 pull request #244
Opened 2022-05-01 08:11 UTC by One-E12

@jaemuYeo 

안녕하세요 잼킹! 잼킹이 주신 힌트 덕분에 해결하고 왔답니다. :) 
사실 어제 joined(separator: )이걸 보긴 했는데..., 제가 계속 새로운 변수(상수)를 선언해주지 않아서 작동하지 않았던 거라는 걸 깨달았습니다! 
어제 스터디에서 String 타입으로 바꿔보라는 힌트를 듣고 
혼자 해결해보려고 했는데 역시...👍 
잼킹과 다른 분들의 도움이 최고인 것 같습니다.👍

띄어쓰기나 문법 최대한 신경써봤는데 이번엔 잘 했는지 모르겠네요🤔

2022-05-01 14:46 UTC, jaemuYeo requested changes
컨벤션에 신경많이써도 곳곳에 실수한 부분이 보이죠??😫
그래도 너무너무 많이 좋아지셨어요 👏👏
코드도 많이 고민한게 보입니다 !!
코멘트 몇 가지 적어놓았으니 코드로 확인해주셔요!
한 번만 더 수정해봅시다☺️

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
타입을 명시해도 되지만 swift는 타입추론이 가능하답니다 !😀

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    let convertMyNumArrayToSet = Set(myLottoNumbers)
굳이 Set으로 convert를 하지 않아도 intersection이 가능할텐데 형변환 하신 이유가  있나요??🤔

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    while newLottoNum.count != 6 {
이 조건도 작동은 하지만 6이 아닐 경우보다 6보다 작은 경우가 더 맞는 문장이 될 것 같아요!

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    print(newLottoNum)
여기 print는 로또번호를 확인하려고 작성해 주신 것 같은데 이제는 없애도 될거같습니다!

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +var newLottoNum = Set<Int>()
어떤 곳은 Num으로 네이밍하셨고 어떤 곳은 Number로 되어있네요!
같이 맞춰주는게 좋을 것 같아요! 개인적으로 축약보다는 number로 해주는게 좋을 것 같아요☺️
그리고 set도 컬렉션이니 복수형이 좋을 것 같습니다!

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    var randomNumber: Int
이 곳에 변수를 선언해서 while문에서 사용하는 방법보다
while문 안에 
```swift
let randomNumber = Int.random(in: 1...45)
```
와 같은 방법은 어떨까요??

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +        if newLottoNum.contains(randomNumber) != true {
if문을 통해 중복된 값을 확인하지 않아도 set은 자동으로 중복된 값은 추가하지않고,
set의 카운트가 6이될때까지 반복해줄거예요!

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +
이 곳에는 줄바꿈 안해주셔도 돼요 ☺️

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +        let convertIntToString = winLottoNumber.map { String($0)}
map의 스코프에 띄어쓰기가 한쪽은 안되어있네요!

2022-05-01 14:46 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +makeNewLottoNumber()
두개의 함수를 호출하지않고 matchingLottoNumber 함수만 호출해서 작동되도록 구현해보면 좋을 것 같아요!

2022-05-02 07:03 UTC, One-E12 commented on CodeStarterCamp_Week2/main.swift
> +    let convertMyNumArrayToSet = Set(myLottoNumbers)
엇...! 이건 같은 Set만 되는 줄 알고 바꿨었어요!

2022-05-02 07:03 UTC, One-E12 commented
다시 한 번 수정해봤습니다!

2022-05-02 08:02 UTC, jaemuYeo reviewed
코드가 훨씬 간결해지셨네요 👍
고생하셨습니다 👏
swift의 컬렉션과 조금은 친해지셨나요?? ㅎㅎ
스텝2 머지 진행하겠습니다!!
스텝3에서 만나요~~

2022-05-02 08:03 UTC, merged