<feat> : week2 step1 순서도
yagom-academy/swift-starter-week2 pull request #247
Opened 2022-05-02 04:19 UTC by Sonshinwoo

1주차에 잘못 커밋한 뺴뺴로 순서도도 같이 첨부합니다 ㅎ;
2주차 순서도는 while문을 돌면서 랜덤 숫자를 생성하고 배열 내부에 중복된 함수를 체크하면서 중복된 숫자를 생성하면 저장하지 않고 다시 while 문으로 돌아가며 6개의 숫자가 만들어질 떄 까지 반복합니다.

2022-05-02 11:38 UTC, yeahg-dev requested changes
안녕하세요! 신우님
빼빼로 만들기 순서도와 로또 당첨번호 만들기 순서도 모두 잘 작성해주셨네요~👍

다만, 로또 번호 만들기 순서도는 스위프트 코드가 아닌 실제 문장을 바탕으로 재작성해볼까요?
예를 들면 `randomNumber = randomNumber.random(1...45) 생성`이 아닌 "1부터 45중 랜덤한 정수를 하나 뽑는다"와 같이요!😃
코드를 사용하지 않고 문장으로 서술해주세요~
그리고 프로그램 종료도 다른 기호를 사용하면 좋을 것 같습니다.

+ PR 제목 양식 다시 한번 확인해주세요

수정하시고 재리뷰 요청 주세요~
재리뷰 요청은 아래 버튼 클릭해주시고 디엠 한번 주시면 빠르게 리뷰드리겠습니다
<img width="404" alt="image" src="https://user-images.githubusercontent.com/81469717/166227672-a77d457d-4d20-4db8-9787-11c5d534091f.png">

2022-05-03 01:38 UTC, Sonshinwoo commented
@yeahg-dev 
릴리! 이렇게 부르는게 맞나요...? ㅎㅎ 처음 쓰는 호칭이라 약간 어색하네요. 말씀해주신 내용 전부 피드백에 반영했습니다 ㅎㅎ 확인 한번 부탁드리겠습니다 ㅎ

2022-05-03 06:30 UTC, yeahg-dev requested changes
순서도의 마지막 부분의 설명이 모호한 것이 고민되어, while문의 최종 결과값의 형태를 넣어주셨다고 말씀주셨는데요~ 잘 해주신 것 같습니다.
이번 순서도는 로또 당첨번호를 만드는 함수만 순서도화 시키는 것이기 때문에 결과 값을 리턴하는 것은 자연스러워 보여요!

`rottoNumber에 randomNumber값 삽입` 후 다시 `rottoNumber: [Int] = []`로 돌아오면 배열이 초기화되는 것으로 이해됩니다. 그럼 다음 조건문에서 항상 yes가 나올 것 같아요.
이 흐름 다시 확인 부탁드립니다!

그리고 궁금 한 점이 있는데요,
"서로 다른 6개의 양의 정수를 가진 array타입의 컬렉션을 생성" 이라는 것은 기존의 `rottoNumber`를 사용하는 것이 아닌 새로운 배열을 만들어서 리턴하는 것으로 이해되는데, 한번 더 배열을 만들어준 이유가 궁금합니다..!

그리고 오타가있어요😲 (countr)

2022-05-04 03:41 UTC, Sonshinwoo commented
"서로 다른 6개의 양의 정수를 가진 array타입의 컬렉션을 생성" 이라는 것은 기존의 rottoNumber를 사용하는 것이 아닌 새로운 배열을 만들어서 리턴하는 것으로 이해되는데, 한번 더 배열을 만들어준 이유가 궁금합니다..!
A:  새로운 배열을 생성하는게 아니라 rottoNumber에서 6개의 값을 받아 리턴 한다는 말이였는데 제가 설명을 잘못했네요 ㅎ;

2022-05-04 04:07 UTC, yeahg-dev approved these changes
흐름에 맞게 잘 수정해주셨습니다👍

다음 스텝 바로 진행해주세요!

2022-05-04 04:07 UTC, merged