WEEK2 <STEP2> sonshinwoo
yagom-academy/swift-starter-week2 pull request #257
Opened 2022-05-04 06:03 UTC by Sonshinwoo

코드의 큰틀은  로또 번호를 생성하는 코드와 중복값을 확인하는 코드, 총 2가지로 나눠 제작했습니다. 로또 번호를 생성하는 코드는 기존에 제출했던 순서도의 메커니즘을 따라 제작했으며  중복값을 확인하는 코드의 형태는 아래와 같습니다.

중복체크 코드

myrottonNumbers와 rottoNumbers의 중복값을 찾는 코드를 짤 때 처음엔 for 문과 while 문을 사용하여 myrottonumbers의 전체 배열값을 하나씩 rottonumbers 값에 대입해 중복값을 체크하는 코드를 구현하려 했으나 이렇게 코드를 짜게되면 시간복잡도가 크게 증가하는 코드이며 좋은 코드가 아니라고 생각해  set의 중복값을 체크해주는 intersection을 활용하면 시간복잡도를 줄일수 있을거라 판단해 코드에 적용했습니다.

2022-05-04 13:19 UTC, yeahg-dev requested changes
안녕하세요 신우님!

스텝이 나날이 갈수록 신우님께서 성장하는 것이 눈에 띄게 보이네요👏🏻👏🏻

시간 복잡도를 고려하여, 타입을 결정할 때도 이유를 생각한 점이 훌륭합니다!💯
말씀해주신 것 처럼 로또 숫자는 겹치는 숫자가 없고, 순서가 중요하지 않은 컬렉션이기 때문에 집합을 사용하는 것은 좋은 선택이라고 저도 생각합니다.

그리고 전반적으로 네이밍도 역할과 의미를 고려하여 잘 작명하셔서, 코드도 쉽게 읽혔습니다👍

요구사항에 안맞는 몇가지 부분과 고민해볼 거리 코멘트 남겨두었으니
확인해보시고 수정부탁드립니다.
하시다가 궁금한 점이나 질문 거리 있음 언제든 메시지 주세요😊

2022-05-04 13:19 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +}
함수로 만들어보면 어떨까요?

2022-05-04 13:19 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +    let rottoNumber_set : Set<Int> = Set(rottoNumbers)
스네이크케이스와 카멜케이스를 섞어서 사용하셨네요.
종종 이렇게 역할은 동일하지만 타입이 다를 경우 이름을 짓기가 애매한 경우가 있지요🤨
그럴때 저도 참 고민이 된답니다...

그럼에도 스위프트에서는 카멜케이스 컨벤션에 따라 네이밍을 하는 것이 국룰이고, 또 API가이드라인에 아래와 같이 명시 되어있어 따르는 습관을 들이는 것이 좋을 것 같습니다:)

>Follow case conventions. Names of types and protocols are UpperCamelCase. Everything else is lowerCamelCase.

다시 한번 고민해봐주세요!

2022-05-04 13:19 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +    if intersectionSet.count > 0 {
배열과 동일하게 세트에도 `isEmpty` 라는 프로퍼티가 있답니다!
꼭 수정하라는 것은 아니고, 있다는 것!도 알아두시면 좋을 것 같습니다:)

2022-05-04 13:19 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +        print("축하합니다! 곂치는 번호는 \(intersectionSet) 입니다!")
출력시 요구사항과 다르게 배열 형태로 그대로 출력됩니다.
`[]` 없이 숫자만 출력하는 방법으로 수정해주세요~

2022-05-04 13:19 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +    let rottoNumber_set : Set<Int> = Set(rottoNumbers)
처음부터 Set타입으로 만들어서 사용할 수도 있었을 것 같습니다. 이렇게 작성해주신 이유가 궁금합니다😊

2022-05-06 07:49 UTC, Sonshinwoo commented on week2  /week2 step2/week2 step2/main.swift
> +}
넵 자꾸 한 두개씩 빼먹네용 코드에 반영했습니다 ㅎ

2022-05-06 07:55 UTC, Sonshinwoo commented on week2  /week2 step2/week2 step2/main.swift
> +    let rottoNumber_set : Set<Int> = Set(rottoNumbers)
넵! 피드백 내용 반영했습니다 ㅎㅎ

2022-05-07 05:36 UTC, yeahg-dev requested changes
안녕하세요 신우님~🙂

고민해주신점과 해결안되었던 점에 대한 저의 의견 말씀드립니다!

1. 스네이크케이스와 카멜 케이스의 혼용

`myRottoNumberSet` `rottonumberOfTypeSet` 모두 괜찮아보입니다~ 길이는 길어도 명확한 네이밍이 좋다고 생각해요!


2. 출력시 [] 제거후 숫자만 출력

마지막 원소에는 terminator를 적용하면 안되니 하나의 반복문에서 모두 출력해주려면 index로 분기처리를 해주는 방법이 불가필 할 것 같아보여요! 
다른 방법의 힌트를 드리자면 Array의 [`joined(seperator:)`](https://developer.apple.com/documentation/swift/array/1690077-joined)라는 메서드도 있답니다!

`,` 가 하나 더 출력되는 문제와 함수 분리까지를 필수 수정사항으로 하겠습니다~!
수정완료 되시면 메시지 주세요!

2022-05-07 05:36 UTC, yeahg-dev commented on week2  /week2 step2/week2 step2/main.swift
> +    rottoNumbers.insert(randomNumber)
로또 당첨 번호를 생성하는 **함수**로 감싸주어 코드의 재사용성을 높여봅시다!

2022-07-01 01:35 UTC, merged