Week2 [STEP3] 애쉬
yagom-academy/swift-starter-week2 pull request #258
Opened 2022-05-04 11:50 UTC by ash-you

안녕하세요 호댕, (@yanghojoon)
Week2 STEP3 PR 보내드립니다!

### 💭 고민해본 점
이번 스텝에서는 추천해주신대로 최대한 전역변수를 쓰지 않고, 지역변수를 써서 진행을 해보려고 했습니다만... 
기존에 만들어둔 당첨번호-내 번호를 대조해보는 함수와 당첨 결과를 출력하는 함수에서 전부 winningNumbers 변수를 사용하고 있어서 결국 다시 전역변수로 사용하게 되었습니다. 🥲
이번 스텝에서 요구하는 기능만 해도 된다면 winningNumbers 변수를 generateLottoNumbers() 함수에서 saveLottoResult() 함수에 매개변수로 넘기는 방법으로는 가능할 것 같았습니다!

### ❓ 궁금했던 점
DM으로 질문드렸던 내용(generateLottoNumber()를 반복 호출해도 같은 번호만 나왔던 것)과 연관되는 점이 있는데요.
전역변수로 선언된 Set이나 Dictionary 타입의 변수는 함수가 호출될 때도 값이 초기화 되지 않고, 이미 저장된 값이 잘 나오는 것 같았습니다.
그런데, 지금은 지역변수로 있는 29번 줄 상수 round를 전역변수로 선언하고 saveLottoResult()-printLottoHistory()를 호출했을 때, 결과가 1회차만 나오는 것으로 보아 계속 0으로 초기화되는 것 같았습니다.
혹시 타입별로 값이 초기화가 되고, 안 되는 차이가 있는 이유가 있을까요?
(아니면 코드의 문제일까요....?...😵)

2022-05-04 14:15 UTC, yanghojoon requested changes
안녕하세요, 애쉬 @ash-you 
이번 스텝도 고생많으셨습니다! 

`generateLottoNumbers`가 반환값을 가지고 있다면 전역 변수를 두지 않더라도 이전 스텝과 현재 스텝을 모두 충족할 수 있지 않을까요?

### 💭 질문해주신 내용 답변 
지역변수로 두는 경우 함수가 호출될 때 새롭게 key와 value가 추가된 `lottoHistory`의 count를 계산하지만 전역변수로 그냥 선언을 해둘 경우 초기에 `lottoHistory.count`는 0이고 거기에 1을 더해 1로서 메모리에 올라가게 됩니다. 이후에는 새롭게 추가가 되더라도 메모리에 올라간 1이 계속 유지가 되는 것이죠! 

이럴 때에도 전역으로 두고 처리할 수 있는 방법은 존재합니다! 
(연산 프로퍼티 - computed property에 대해 찾아보시면 방법을 찾으실 수도 있을 것 같습니다)

`전역 변수로 선언을 해주시더라도 바뀔 때마다 알아서 다시 연산을 하지 않는다`가 문제가 발생한 이유인 것 같습니다.

2022-05-04 14:15 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +var winningNumbers: [Int] = []
generateLottoNumbers 메서드가 반환값을 가진다면 전역변수가 필요없을 수 있을 것 같아요 🧐

2022-05-04 14:15 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    winningNumbers.removeAll()
argument label을 사용한다면 함수 호출 시 조금 더 잘 읽히는 함수가 될 수 있을 것 같습니다.

2022-05-04 14:15 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    saveLottoResult(winningNumbers: winningNumbers)
로또 번호를 생성하는 함수에서 저장까지 해주신 이유가 있으실까요?

2022-05-04 14:15 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    if let value: [Int] = lottoHistory["\(round)회차"] {
if let 바인딩을 통해 옵셔널 바인딩을 잘해주셨군요! 
혹시 타입을 따로 명시해주신 이유가 있으실까요?

2022-05-04 14:15 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +        let lastIndex: Int = value.index(before: value.endIndex)
상수로 분리해서 잘 사용해주셨군요☺️

2022-05-06 07:39 UTC, ash-you commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +var winningNumbers: [Int] = []
return을 사용해서 전역변수를 최소화 하는 방향으로 수정해봤습니다!
다만, winningNumbers 변수를 STEP2의 함수에서 대부분 사용하고 있는 상황이라 기능 순서 상 이어지는 대부분의 함수에서 return값을 주고 받는 형태로 수정하게 되었습니다!

2022-05-06 07:43 UTC, ash-you commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    winningNumbers.removeAll()
코멘트 주신대로 argument label을 조금 더 활용해봤습니다! 변수 네이밍 만큼 어려운 것 같습니다..😂 
matchLottoNumbers에서는 어디서 가져온 숫자와 매치를 해본다 라는 의미로 from을 사용해 보았습니다. 
printLottoResult에서는 코드 상 로또번호의 갯수가 필요한 것이고, 호출 시에는 generateLottoNumbers에서 정해주면 되는 데이터 값이니 굳이 필요하지 않다고 생각되어 생략하는 방식으로 수정했습니다!

2022-05-06 07:49 UTC, ash-you commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    saveLottoResult(winningNumbers: winningNumbers)
로또 번호를 생성하면 이 값을 어쩌피 히스토리에 저장하게 될 것이다 라는 생각으로 바로 저장까지 이어지게 했었습니다! 2가지 기능을 하기 위해 하나의 함수만 호출하면 되면 더 간편하지 않을까 라는 생각도 있었습니다. 지금 상황에서 코드의 유연성에 대한 개념은 명확하지 않지만, 각자 하나의 기능을 하기 위해 만들어진 함수라면 구분하는 게 좋지 않을까 라는 생각에 return 값만 주고 함수의 호출까지는 하지 않는 방향으로 수정해봤습니다.

2022-05-06 07:51 UTC, ash-you commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +    if let value: [Int] = lottoHistory["\(round)회차"] {
이 부분은 오류에 둘러쌓여 약간 어지러울 때 상수 선언하듯이 써버린 것 같습니다... 수정했습니다! 😂

2022-05-06 12:47 UTC, yanghojoon commented on CodeStarterCamp_Week2/generateLottoNumber.swift
> +var winningNumbers: [Int] = []
잘 수정해주셨군요 😁

다만 저는 보통 return 값이 있는 경우 따로 상수에 담아 사용을 하는 편이긴 합니다. 
```swift
let winningLottoNumbers = generateLottoNumbers()
let matchNumbers = matchLottoNumbers(from: winningLottoNumbers)
printLottoResult(matchNumbers)
```

이런 식으로요!

2022-05-06 12:51 UTC, merged