Week2 [STEP2] piuri
yagom-academy/swift-starter-week2 pull request #259
Opened 2022-05-04 15:48 UTC by pi-uri

@llghdud921 

안녕하세요, 제리!
이번 순서도를 작성하면서.. 구글링으로 이래저래 만들어서 돌아가긴 하지만 제가 내부를 이해하고 코드를 짠 것 같지 않아서 찝찝합니다 :(
처음 배우는거라 지금은 단순 구현에 만족해야겠죠..?
항상 딥하게 코멘트 해주셔서 감사해요! :)

2022-05-05 11:57 UTC, llghdud921 requested changes
안녕하세요!!
코드 구성에 맞는지 의문을 가지셨는데요 너무 잘하셨는데요?? 실력이 엄청 늘으신것같아요 👍 👍 
함수 분리도 정말 잘하셨고 네이밍이나 컨벤션이 거의 완벽합니다 💯 

약간의 코멘트를 남겨드렸으니 확인부탁드리고 궁금한거 있으면 언제든 DM 주세요!!!

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    repeat {
repeat - while문을 사용하셨군요! 
저도 해당 반복문이 적절하다고 생각합니다 👍

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func createLottoNumberIndex(indexNum: Int) -> Int {
`indexNum`과 같은 약어는 지양합시다!!

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func createLottoNumberIndex(indexNum: Int) -> Int {
현재 함수는 index를 가지고 for문을 돌아서 일치하는 번호를 맞추는 기능을 하는데요!

우선 indexNum보다 MyLottoNumbers.count-1 이나 그냥 0...5를 넣어도 될것같아요 
그리고 contains내부에 함수를 실행하는 것보다 contains되어있는지 없는지를 체크하여 Bool타입을 반환하는 메서드가 구조상 더 좋을 것 같아요!

혹시 어려우시다면 DM주세요!!

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +func resultOfLotto() {
resultOfLotto는 구조상 명사를 나타내는 것 같은데요! printLottoResult가 더 좋을 것 같습니당

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +var winnerNumber: Set<Int> = Set<Int>()
number의 집합이므로 복수형인 Numbers로 네이밍하는 것이 좋을 것 같아용

2022-05-05 11:57 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    for indexNumber in 0...indexNum{
```suggestion
    for indexNumber in 0...indexNum {
```
for문 내 컨벤션을 알려드립니다..!!

2022-05-05 14:24 UTC, pi-uri commented
@llghdud921 

안녕하세요, 제리!
말씀하신대로 수정하고, Array를 Set으로 변환하여 bool타입 연산자를 써주었습니다!
변환 없이는 bool타입 연산자를 사용할 수 없어서 많이 찾아보다가 수정했습니다..!
주신 피드백이 잘 반영된 것인지 모르겠네요.. ㅎㅎㅎ 
빠른 피드백 정말 감사합니다!

2022-05-07 05:38 UTC, llghdud921 requested changes
안녕하세요!!
리팩토링 정말 잘 해주셨는데요~ 👍  
결과를 나타내는 로직이 제대로 구현하지 못하는 것 같습니다ㅠㅠ
해당 로직은 myLottoNumbers와 winnerNumbers의 번호 모두가 일치해야하는 로직이에요...
제가 제안드린 방법말고 piuri만의 방법으로 다시한번 구현해보시죠!! 제 의도가 잘 전달드리지못해서 죄송한 마음이네요ㅜㅜ

2022-05-07 05:38 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    if arrayToSetConverter == winnerNumbers {
해당 로직은 겹치는 번호를 검증할 수 없을것같아요!!ㅠㅠ

winnerNumbers와 myLottoNumber가 겹치는 번호를 도출하는 함수를 따로 만드는 것을 말씀드린것이에요!!
제가 말씀드린것에 얽매이지 않고 기능을 다시 구현해볼까요?

2022-05-07 16:32 UTC, pi-uri commented on CodeStarterCamp_Week2/main.swift
> +    if arrayToSetConverter == winnerNumbers {
@llghdud921 
안녕하세요, 제리님!
업로드 했던 코드 그대로 돌려보면 제대로 된 결과값이 뜨는데.. 무엇이 잘못되었다고 코멘트를 주신걸까요??

2022-05-08 07:31 UTC, llghdud921 commented on CodeStarterCamp_Week2/main.swift
> +    if arrayToSetConverter == winnerNumbers {
<img width="612" alt="스크린샷 2022-05-08 오후 4 29 20" src="https://user-images.githubusercontent.com/40068674/167286337-5c31ee86-e58c-4f16-97aa-ec76b8fb2a60.png">

제가 winnerNumbers를 print 해보았는데 현재 15라는 숫자가 겹치는데 겹치지 않다고 나와있어요!

2022-05-09 03:24 UTC, pi-uri commented
@llghdud921 
안녕하세요, 제리!
제가 본문을 잘 이해하지 못한 것 같아요!
저는 제가 뽑은 숫자랑 랜덤으로 생성된 숫자가 다 똑같아야만 해당 출력문이 실행되어야하는줄 알았는데
한두개만 있어도 출력이 되었어야했네요..ㅎㅎ 말씀하신대로 다시 수정하였습니다!
감사합니다!

2022-05-09 15:11 UTC, merged