Week2 [STEP 2] 임경인
yagom-academy/swift-starter-week2 pull request #263
Opened 2022-05-08 08:59 UTC by limdumb

@leeari95 
안녕하세요 아리님 ! Step2 진행 완료 하여서 PR 드렸습니다.

우선 이번 Step은 전체적으로 생각할게 너무 많았던거 같아서 감조차도 잡히지 않아서 DM도 드렸었던것 같아요 !!
그래도 말씀해주신거 토대로 코드작성 한번 진행 해봤습니다 :) 그리고 .. 커밋 단위를 쪼개서 진행하는게 아직 습관이 되지 않아서
마지막 코드 다 작성하고 Push했을때 깨달았습니다..ㅠㅠ ... 단위를 쪼개지 않았다는걸... 조금더 신경써서 노력 해보겠습니다!

이번Step도 잘 봐주세요 :) 감사합니다!

2022-05-09 02:53 UTC, leeari95 requested changes
임덤덤님 안녕하세요~ 👋🏻
너무 오랜만이네요! 🤗 
스텝2 구현하시느라 고생많으셨습니다!

커밋은 처음엔 익숙치 않아서 저도 초반엔 그랬던 것 같아요 ㅎㅎ 😊
커밋 단위 쪼개는 연습은 계속 하다보면 감이 오실거에요! 
화이팅입니다! 💪🏻

자세한 피드백은 코멘트를 남겨드렸는데요. 😆
혹시 궁금한 사항이나 어려운점이 있다면
편하게 DM 부탁드립니다!

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +}
만약 운이 정말 나빠서 같은 숫자가 중복으로 뽑히게 된다면...
의도된 횟수만큼 반복할까요?
불필요한 반복을 줄이기 위해서는 어떤 방법이 있을까요?

힌트: [Swift - shuffled()](https://developer.apple.com/documentation/swift/array/2994757-shuffled)

해결이 어렵다면 다음에 고민해봐도 괜찮아요. 😊

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +    for lottoNumber in numbers {
lottoNumbers가 적절한 이름같은데요?
왜 numbers로 선언해주신건지 이유가 궁금합니다! 😁

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sameNumbers) 입니다!")
출력예시와 맞지 않는 것 같네요! 다시 한번 확인해볼까요?

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +print(randomNumber)
이 프린트문이 요구사항에 있던 것인가요?

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +func creatRandomNumbers() -> Set<Int> {
파라미터를 활용해보면 어떨까요?
1부터 45의 숫자가 아니라 다른 범위로도 받을 수 있도록 하면
이 함수가 더 유연해질 것 같아요.

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +func creatWinningNumbers(lottoNumber: Set<Int>, myNumbers: [Int]) -> [Int] {
생성한다~ 라는 의미보다는 체크한다는 의미가 더 명확하지 않을까요?

2022-05-09 02:53 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +func printLottoNumbers(sameNumbers: [Int]) {
로또번호를 출력한다기보다는 당첨 결과를 출력한다는 의미가 더 좋을 것 같아요.

2022-05-09 07:20 UTC, limdumb commented on CodeStarterCamp_Week2/main.swift
> +print(randomNumber)
정확하게 결과값이 출력이 되어서 그 숫자가 정말 겹치는 숫자가 맞는지 확인하기위해서 프린트를 넣었습니다!

2022-05-09 07:22 UTC, limdumb commented on CodeStarterCamp_Week2/main.swift
> +func creatWinningNumbers(lottoNumber: Set<Int>, myNumbers: [Int]) -> [Int] {
그게 조금더 명확한거 같습니다 수정하겠습니다~

2022-05-09 07:29 UTC, limdumb commented on CodeStarterCamp_Week2/main.swift
> +    for lottoNumber in numbers {
특별한 이유가 있다기 보다는 우선 제가 봤을때 반복문이다 보니.. 그냥 같은 lottoNumber가 반복 되면 보는게 조금 보이는게 햇갈릴까봐 저렇게 선언하고 사용 했던것 같습니다. 근데저도 지금와서보니까 딱히 저렇게 선언해줄 필요가 없는거 같아서 수정 진행하였습니다 :)

2022-05-09 07:37 UTC, limdumb commented on CodeStarterCamp_Week2/main.swift
> +func printLottoNumbers(sameNumbers: [Int]) {
확인하고 수정 하였습니다 :)

2022-05-10 11:25 UTC, leeari95 commented on CodeStarterCamp_Week2/main.swift
> +print(randomNumber)
요구사항에는 없는 기능이 추가된 것인데, 이게 현재 프로그램 실행을 위해서 꼭! 필요한 기능일까요?

2022-05-10 11:29 UTC, leeari95 approved these changes
임덤덤님! 수정사항 잘 확인했습니다~~
수정하는 과정에서 시도했던 코드, 불필요하게 추가된 공백이 확인되고 있어요.
이 부분은 다음 스텝에서 꼭 수정해주시기 바랍니다! 💪🏻

그 외에는 큰 문제 없어서 머지 해드리도록 할게요.
출력결과도 예시와 동일하게 나오고 있네요!
고생하셨습니다! 😊

2022-05-10 11:30 UTC, merged