weak2[steo2]
yagom-academy/swift-starter-week2 pull request #27
Opened 2021-12-20 01:06 UTC by suhwj

2021-12-20 07:31 UTC, joey-ful requested changes
@suhwj 

원지님 이번 스텝도 수고 많으셨습니다!
이번 코드에서는 네이밍과 띄어쓰기 등이 정말정말 좋아졌어요 👏🏻 👏🏻 👏🏻 
많이 신경쓰신게 보입니다! 멋져요! 👍
또, Set을 정말 잘 활용해주셨고 함수도 기능별로 최대한 분리하시려는 모습이 보였어요!! 최고👍 👍 👍

#### 다만 아쉽게도 요구사항대로 작동하지 않아서 수정을 요청합니다!
필수 로직 자체는 거의 구현되어 있어서 자잘한 수정만 하시면 될 것 같습니다
- 순서도 파일은 최신 것이 아닌 예전 파일을 제거하신 것 같습니다! 😅  최신 것을 다시 커밋해주세요
- 커멘트에도 남겨드렸지만 전역변수의 장단점은 무엇인지 그리고 언제 사용하면 좋은지 알아보시면 좋을 것 같아요! 그리고 전역변수 대신 함수의 매개변수와 반환값을 활용해보시면 어떨까싶습니다!
- `print()`들이 여기저기 보이는데 요구사항에 맞는 출력함수만 남기시면 좋을 것 같아요! PR은 완성 코드를 머지 요청하는 것이라 테스트용 함수들은 제거해주시는 것이 좋습니다 😁
- 나머지는 커멘트를 확인해주세요!

2021-12-20 07:31 UTC, joey-ful commented on CodeStarterCamp_Week2/main.swift
> +    let correctLottoArray = pickLottoNumberArray.joined(separator: " ,")
배열의 각 숫자를 `,`로 구분해 출력하기 위해 String배열에 `joined(separator:)`메서드를 사용해주셨네요 👍
- `pickLottoNumberArray`가 비어있어서 `corretLottoArray`에도 아무것도 안 들어가는 것 같네요
- separator가 조금 잘못된 것 같습니다

2021-12-20 15:20 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +print(" 내 로또 번호는 : \(myChooseLottoNumber.sorted())")
제거 했습니다

2021-12-20 15:23 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +var pickLottoNumberArray: [String] = []
적용해서 바꾸었습니다

2021-12-20 15:24 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +let myChooseLottoNumber: Set<Int>! = [1, 2, 3, 4, 5, 6]
옵셔널로 적용할려다고  못했어요

2021-12-20 15:25 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다!! 겹치는 번호는 \(myChooseLottoNumber.sorted()) " + "입니다")
우리가 찍은 번호가 로또 당첨 번호와 일치하는지 검사하려면 어떻게 해야할까요? 미션 내용이  이껀데  같은  내용이 아닐까용??

2021-12-20 15:26 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +      printMatchNum()
어떤게  다르가용 ??

2021-12-20 15:28 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +        pickLottoNumberArray.append("\(index)")
changeLottoNumberArray()는 배열  받은걸 저장해서  append로  출력하는  역활입니다
pickLottoNumberArray는 index를 저장하는  배열 입니다

2021-12-20 15:36 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    let correctLottoArray = pickLottoNumberArray.joined(separator: " ,")
그렇다면  수정을  어떻게 해야 하나요??

2021-12-20 15:36 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +
네

2021-12-20 15:46 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +        lottoNumber.insert(Int.random(in: 1...45))
넵

2021-12-20 15:46 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    print("당첨된 내 로또 번호는 : \(lottoNumber.sorted())")
넵 제거 했습니다

2021-12-20 15:51 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    matchedLottoNumberArray = Array(matchNumber)
여기서 Array타입으로 변환해주고 있는데 꼭 그래야하는 이유가 있나요? 🤓  
 ->  그래야 되는 이유는 없습니다

2021-12-20 15:52 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    matchedLottoNumberArray = Array(matchNumber)
전역변수는 물론 유용할 때가 많지만 단점이 많기 때문에 사용을 최소화하시는 것이 좋습니다!
이 기회에 전역변수의 단점에 대해 알아보셔도 좋을 것 같네요! 전역변수의 단점은 어떤 것이 있을까요?

2021-12-20 15:55 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +func createRandomLottoNum() {
감사해여  @joey-ful  덕분이에요

2021-12-21 05:02 UTC, joey-ful commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다!! 겹치는 번호는 \(myChooseLottoNumber.sorted()) " + "입니다")
겹치는 번호만 찾으면 될 것 같습니다!
현재는 겹치는 번호가 아니라 처음에 고른 로또번호들이 담긴 myChooseLottoNumber를 출력하고 있네요
겹치는 번호를 찾는 로직을 짜주시면 됩니다

2021-12-21 05:03 UTC, joey-ful commented on CodeStarterCamp_Week2/main.swift
> +      printMatchNum()
이 줄만 들여쓰기가 다릅니다!

2021-12-22 14:45 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    matchedLottoNumberArray = Array(matchNumber)
여기서 Array타입으로 변환해주고 있는데 꼭 그래야하는 이유가 있나요? 
array 선택한 로또  번호를 체크 하는꺼 때매  이렇게 사용했어요

2021-12-23 04:09 UTC, joey-ful approved these changes
@suhwj

코드 전반적으로 컨벤션을 잘 지켜주셨어요! 
네이밍, 띄어쓰기, 줄바꿈 등 신경을 많이쓰신게 보입니다 👍 👍 👍
아주아주 좋아졌어요! 👏🏻
로직도 다양한 방향으로 시도하신 점 멋집니다
특히 함수를 기능별로 분리하신 것도 너무 좋습니다👍
현재 요구사항대로 잘 작동하고 있어요 👏🏻
제가 리뷰에 반환값 이야기를 많이 적어놨는데 원지님이 이전 커밋에서 하신 것처럼 하시면 됩니다! 그 때 잘 하셨어서 아마 잘 숙지하고 계실거라 생각해요
다음 스텝에서 봬요! 🔥

2021-12-23 10:05 UTC, suhwj commented on CodeStarterCamp_Week2/main.swift
> +    matchedNumbersArray = Array(matchNumbers)
어떻게용 ??

2021-12-24 02:29 UTC, merged