Week2 [STEP 2] dasankim
yagom-academy/swift-starter-week2 pull request #290
Opened 2022-06-30 12:34 UTC by DasanKim

@jsim27 
나무님 안녕하세요! 
오늘 비가 추적추적 오는 것이 코딩 추적하기 좋은 날이네요!....🙄(아무말)
본..본론으로 들어가겠습니다😅

## 고민했던 점
### 1. 랜덤로또번호 생성 함수에 관하여
1. 중복된 값 없이 6개의 랜덤한 숫자를 만들기 위해서 Set를 사용
2. 반복문 어떤 반복문을 사용할까?
  - for-in: 반복횟수를 알고 있을 때 주로 사용, 배열과 함께 주로 사용
  - while: 특정 조건을 만족할 때까지 반복해야하는 경우
  - repeat-while: 특정 조건을 만족할 때까지 반복. 조건문이 false더라도 무조건 한번은 실행 됨
위의 반복문의 특징으로 미루어봤을 때, 무조건 6번만 반복한다면 로또당첨번호가 중복이 나왔을 때 *중복되지 않는 6개의 숫자*를 얻을 수 없다. 따라서 특정 조건(여기서는 `winningLottoNumbers.count < 6`)이 true때까지 반복하도록 while를 사용하였습니다.
=> 이에 따라 *while문에 맞게 순서도를 수정*하였습니다!
3. 랜덤값이 저장되는 `winningLottoNumbers` Set은 전역변수다보니, 랜덤로또번호 생성 함수에 return값을 넣지 않아도 될 것 같아 넣지 않았습니다.

### 2. 찍은 번호와 로또 당첨 번호의 겹치는 숫자를 확인하는 함수
1. 처음에 중첩 for-in 문과 if문을 사용하여 두 컬렉션 값을 비교해보려했습니다.
``` swift
for winningNumber in winningLottoNumbers {
       for myNumber in myLottoNumbers {
            if winningNumber == myNumber {
                hitNumber.append(myNumber)
            }
        }
```
그러다가 컬렉션 메소드에 contains가 있다는 것을 알게 되었고, 이 함수를 사용하면서 중첩반복문을 사용하지 않아도 되었습니다! 
2. 배열(array)의 요소 추가하는 방법 2가지
  - append: 배열 맨 끝에 요소 추가
  - insert: 지정한 인덱스에 요소 추가 => 따라서 오버헤드가 발생할 수 있다.
  - 라고 하여, append를 사용하여 요소를 추가해보았습니다.

### 3. 추첨 결과를 출력하는 함수
본래 아래와 같이 작성하였습니다.
``` swift
    if matchedNumbers.isEmpty {
        print("아쉽지만 겹치는 번호가 없습니다.")
    } else 
        print("축하합니다! 겹치는 번호는 \(matchedNumbers) 입니다!")
    }
```
위 출력 결과는
`겹치는 번호는 [1, 6, 29] 입니다` 라고 나왔습니다.
step2의 설명처럼 `겹치는 번호는 1, 6, 29, 입니다` 라고 출력하고 싶었고, 여기에 집착(?)하여 switch문을 사용하게 되었습니다.

## 조언을 얻고 싶은 부분
### 1. 전역변수는 언제 사용하는 것이 좋은가요?
`winningLottoNumbers`를 전역변수로 선언하다보니, 랜덤번호 생성함수에서 반환값을 주지 않았습니다. 하지만 어디선가 전역변수를 남발하면 좋지 않다는 걸 들은 것 같기도하구요😂  전역변수를 피하기 위해 랜덤번호 생성함수 안에 winningLottoNumbers를 선언하고, return하는 방법이 더 좋을까요?

### 2. printLottoResult 함수
switch 구문을 사용하여 구현은 했지만, 뭔가 더 좋은 방법이 있을 것 같지만 저의 수준에서는 모르겠는. 그런 코드입니다ㅠㅠㅋㅋ
어느 부분을 공부하면 조금 더 나은  printLottoResult 함수를 만들 수 있을지 궁금합니다!

2022-06-30 20:46 UTC, jsim27 requested changes
## 1. 
> => 이에 따라 while문에 맞게 순서도를 수정하였습니다!

순서도 확인했습니다! 그러고 보니, 이전 순서도는 `repeat-while`문의 로직과 비슷하네요!

---
## 2. 
> append: 배열 맨 끝에 요소 추가
insert: 지정한 인덱스에 요소 추가 => 따라서 오버헤드가 발생할 수 있다.
라고 하여, append를 사용하여 요소를 추가해보았습니다.

다산님이 이해하시기에, 이 상황에서 `오버헤드`라 함은 무슨 뜻일까요?

---

## 조언을 얻고 싶은 부분
> 1. 전역변수는 언제 사용하는 것이 좋은가요?
winningLottoNumbers를 전역변수로 선언하다보니, 랜덤번호 생성함수에서 반환값을 주지 않았습니다. 하지만 어디선가 전역변수를 남발하면 좋지 않다는 걸 들은 것 같기도하구요😂 전역변수를 피하기 위해 랜덤번호 생성함수 안에 winningLottoNumbers를 선언하고, return하는 방법이 더 좋을까요?

아주 중요한 고민인 것 같습니다!
전역변수가 좋지 않다는 말을 여러 곳에서 볼 수 있는데, 다산님 코드를 통해 그 이유를 이해할 수 있는 좋은 기회가 된 것 같네요! 다음을 함께 생각해 볼까요?
- 랜덤 로또번호를 **두 세트 이상 생성**하는 것으로 기획이 변경되었을 때, 현재 구현된 `전역변수 + 반환값이 없는 generateRandomLottoNumber()`를 `재사용`할 수 있나요?
  -  대신 반환값이 있는 함수로 구현했다면 재사용할 수 있을까요?
- 현재 `winningLottoNumbers`는 `generateRandomLottoNumber()`를 통해서만 변경될 수 있는 상태인가요? 누군가 `winningLottoNumbers`에 접근하여 값을 변경시키는 코드를 실수로 넣으면, 오류를 찾아내기 쉬울까요?
  - 반면, `winningLottoNumbers`가 `generateRandomLottoNumber()` 내부에 존재하는 **지역변수**라면 함수 바깥에서 `winningLottoNumbers`에 접근하여 변경을 시도할 수 있을까요?

이처럼, `외부에 영향을 끼치지 않고 반환값을 가지는 함수`의 장점은 예기치 않은 접근을 막을 수 있다는 점, 예상치 못한 변경을 추적하기 위해 힘들이지 않아도 된다는 점, 재사용성이 매우 높다는 점이 있겠네요.

전역변수의 단점은 위 내용들을 고스란히 뒤집어서 생각하면 될 것 같아요!
- 어디서든 접근 가능하기에 편할 수도 있지만, 그만큼 변경을 추적하기 어렵고 실수의 여지도 커집니다.
- 전역변수와 관련된 함수는 해당 전역변수를 위해서만 사용되기에, 재사용이 어려워집니다.

납득이 되셨을까요? 아주 영양가있는 주제였던 것 같습니다ㅎㅎ

---

> 2. printLottoResult 함수
switch 구문을 사용하여 구현은 했지만, 뭔가 더 좋은 방법이 있을 것 같지만 저의 수준에서는 모르겠는. 그런 코드입니다ㅠㅠㅋㅋ
어느 부분을 공부하면 조금 더 나은 printLottoResult 함수를 만들 수 있을지 궁금합니다!

코드에서 이 내용에 대해 코멘트했으니 확인해 주세요!

---

이번에는 `printLottoResult(matchedNumbers: [Int])`를 개선해 보시고, 코멘트에 답변을 주신 후에 Merge 진행하도록 할게요!

점점 재밌는 고민을 하게 되는 것 같아요! 저도 덩달아 재밌게 리뷰하고 있습니다ㅎㅎ
수정 기다리고 있겠습니다~~ 화이팅! @DasanKim

2022-07-03 02:20 UTC, DasanKim commented on CodeStarterCamp_Week2/main.swift
> +var winningLottoNumbers: Set<Int> = []
지난번 타입 명시와 타입 추론에 대해 공부한 덕분에, 이해하기가 훨씬 수월해지네요😆
다른 타입과 비슷하게 타입 추론을 통해 초기화를 할 수 있을 것 같습니다.

var winningLottoNumbers: Set = [1, 2, 3, 4, 5] 

빈 값이면 추론을 할 수 없으므로 위처럼 값을 넣어서요! 
이번 코드에서는 랜덤한 값을 하나하나 추가해야하므로 타입 명시를 사용하여 초기화했습니다☺️

2022-07-03 13:19 UTC, DasanKim commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 7, 15, 29, 36, 42]
배열을 **선언**하는 방법에는 아래와 같은 방법이 있습니다! 등호 오른쪽의 ()나 [] 안에 값을 넣어서 초기화를 합니다.
var myLottoNumbers: Array<Int> = [Int]()
var myLottoNumbers: Array<Int> = []
var myLottoNumbers: [Int] = Array<Int>()
var myLottoNumbers: [Int] = [Int]()
var myLottoNumbers: [Int] = []
var myLottoNumbers = [Int]()
---
let myLottoNumbers: [Int] = [1, 7, 15, 29, 36, 42]
같은 경우는, 상수(let)으로 선언하였기 때문에
let myLottoNumbers: [Int] = [] 라고 선언을 해버리면, 배열을 변경(추가 및 삭제)를 할 수 없습니다.
따라서 처음부터
let myLottoNumbers: [Int] = [1, 7, 15, 29, 36, 42]
let myLottoNumbers = [Int]([1, 7, 15, 29, 36, 42])
등으로 초기화를 하면 됩니다!

또 다른 초기화 방법이 있을까요?
그리고 개발자분들 사이에서 가장 많이 통용(?)되는 선언 및 초기화 방법이 궁금합니다!

2022-07-03 13:23 UTC, DasanKim commented on CodeStarterCamp_Week2/main.swift
> +    var matchedNumbers: [Int] = []
빈 배열을 초기화하는 것은 선언하는 방법과 좀 다를까요?

```
myLottoNumbers = [Int]()
myLottoNumbers = []
myLottoNumbers = Array<Int>()
```

위와 같이 하니 빈 배열로 초기화 되는 것이 확인되었습니다! 신기하네요!

2022-07-03 14:26 UTC, DasanKim commented
먼저 오버헤드의 사전적 정의를 찾아보았습니다.
> 오버헤드(overhead): 어떤 처리를 하기 위해 들어가는 간접적인 처리 시간, 메모리 등을 말한다.
A라는 처리를 단순하게 실행한다면 10초가 걸리는데, 안전성을 고려하고 부가적인 B라는 처리를 추가한 결과 처리시간이 15초 걸렸다면,
오버헤드는 5초가 된다.

- append 같은 경우, 배열 맨 뒤에 요소가 추가 되기 때문에 삽입에 별다른 계산이 필요 없음
- insert 같은 경우, 요소를 맨 뒤에 추가하면 append와 같이 삽입에 별다른 계산이 필요 없지만 
문제는 맨 뒤가 아닌 맨앞 또는 중간의 위치에 요소를 추가하려고 할 때입니다.
[1, 2, 3, 4, 5] 에서 맨 앞에 6이라는 숫자를 추가하려고 하면 [6, 1, 2, 3, 4, 5]가 되는데
배열의 경우 index로 접근하기 때문에 1부터 5 모두 위치를 재배열 해야하여 append에 비하여 오버헤드가 발생하는 것입니다!(라고 공부했습니다^^;;)
물론 위와 같은 작은 배열으로는 오버헤드는 체감할 수 없겠지만요👉👈

2022-07-04 04:07 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 7, 15, 29, 36, 42]
와우.. 정말 상세히 연구해보셨네요!! 박수박수!!

### 또 다른 초기화 방법이 있을까요?
<img width="537" alt="2022-07-04_12-59-29" src="https://user-images.githubusercontent.com/72993238/177079429-cd5ab9f5-fb8b-45c4-b7be-3f5cc7a7ed4a.png">

이렇게 `Array<Int>.init`을 입력하고 esc키를 눌러 자동완성 가능한 생성자 목록을 볼 수 있어요! 다양한 경우에 사용할 수 있는 생성자들이 있는데, 지금 이해하기 어려운 내용도 있으니, 이해 되는 부분만 훑어보고 넘어가셔요ㅎㅎ

### 개발자분들 사이에서 가장 많이 통용(?)되는 선언 및 초기화 방법
워낙 여러 상황이 있을 수 있어서 때에 따라 다르겠지만, `let a = [1, 2, 3]` 라고만 표현해도 Int의 배열임을 알 수 있는 상황이 많아서 이렇게 사용하는 빈도가 가장 높은 것 같네요!

2022-07-04 04:10 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +    var matchedNumbers: [Int] = []
적어주신 세 가지 방법이 있음을 알아보시면 좋을 것 같아서 말씀드렸습니다ㅎㅎ 아주 좋아요!

2022-07-04 04:31 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +    }
Int 배열을 String으로 바꾸기 위해서 반복문과 조건문을 활용하셨네요! 멋진 로직인 것 같아요👍 

조금 다른 방법도 있을 것 같은데요, 
```swift
var intToStringNumbers = [String]()
for number in matchedNumbers {
    intToStringNumbers.append(String(number))
}
intToStringNumbers.joined(separator: ", ")
```
이렇게 `joined(separator:)` 메서드를 활용하는 방법입니다.
이런 경우에 자주 쓰이는 메서드라서 참고하시면 좋을 것 같아요!

---

현재 `printLottoResult`의 기능을 살펴보면
1. 매개변수로 전달받은 정수 배열을 문자열로 변환
2. 변환된 문자열에 따라 적절한 결과 메세지 출력

이렇게 두 가지 기능을 갖고 있는 것 같아요. 따라서 위의 변환 부분을 별개의 함수로 분리할 수도 있을 것 같습니다!

2022-07-04 04:40 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +var winningLottoNumbers: Set<Int> = []
```swift
let a = Set<Int>([1, 2, 3, 4, 5])
let a = Set<Int>(arrayLiteral: 1, 2, 3, 4, 5)
let a = Set<Int>(1...5)
```

타입 명시를 사용하고싶지 않다면 이런 방법도 있어요!
`let a = Set<Int>(` 까지만 타이핑하고 esc키를 누르면, 사용할 수 있는 생성자 목록이 쫙 뜬답니다ㅎㅎ 참고해보셔요!

2022-07-04 04:43 UTC, jsim27 commented
수정 모두 검토했습니다!

제가 언급한 부분을 모두 완벽하게 수정해 주시고, 코멘트에 대해서도 정말 잘 학습해 주셔서 감사합니다ㅎㅎ

고생 많으셨습니다, 다음 스텝도 힘내서 진행해 보아요~~~!!😄
@DasanKim

2022-07-04 04:44 UTC, merged

2022-07-04 08:09 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +let myMatchedNumbers = comparedNumbers(winnigNumbers: generateRandomLottoNumber())
함수의 반환값을 전달인자로 쓰는 경우에는, 
`let winningNumbers = generateRandomLottoNumber()`
이런 식으로 변수로 빼 주는 것이, 이 전달인자가 코드에서 어떤 역할을 하는지 표현할 수 있어서 좋을 것 같아요!