WEEK2 [STEP3] 제리
yagom-academy/swift-starter-week2 pull request #292
Opened 2022-06-30 15:05 UTC by gwd0311

@yeahg-dev
주어진 요구사항에 충실하게 하기 위해 노력해보았습니다!

## 고민했던 점

- 이번 과제에서는 각각의 기능들을 함수로 구현해 보고자 노력하였습니다.

---

## 해결이 되지 않은 점

- 이번 과제에서는 막히는 부분은 없었습니다☺️

---

## 조언을 얻고 싶은 부분

- 구현하던중 딕셔너리를 정렬해보고싶어서 dictonary.sorted{$0.0<$1.0} 이런식으로 구현해보았는데 아직 $0의 의미를 명확하게 파악하지 못한것같습니다.
- 제가 구글링하면서 이해한 바로는 dictionary 일 경우 `$0`이 첫번째 요소, `$0.0`은 첫번째 요소의 key값, `$0.1`은 value 값으로 이해했는데 혹시 정확하게 이해한 것이 맞을까요..?😂

2022-07-01 03:03 UTC, yeahg-dev requested changes
안녕하세요 제리님~
- 전반적으로 네이밍을 잘 뽑아주셔서 이해하기가 수월했던 것 같아요👍 
- 요구사항대로 기능도 아주 잘 작동합니다🚀
- 작은 기능별로 함수를 구현해주셨네요! 함수는 하나의 일만 할 때 재사용성과 가독성이 좋아지고, 유지보수도 용이하다고 생각해요. 앞으로도 함수는 한가지의 일만 하도록 구현하는 습관을 길러보아요🥳

추가적으로 공부하고 생각해볼 거리들을 코멘트에 남겨두었으니 확인 한 번 부탁드려요

## 추가적으로 개선할 수 있는 부분
- 추가적으로 swift파일을 만들어볼 수 있을 것 같아요. 실행코드들은 main.swift파일에 있어야되지만, 나머지 함수정의 코드들은 다른 파일에 분리해도 괜찮습니다. 이렇게 파일을 분리하면 얻을 수 있는 이점은 모듈이 커졌을 때 코드를 찾고 관리하기 쉽다는 점이 있어요. 그리고 main.swift에만 실행코드가 있을 수 있는 이유에 대한 설명은 https://developer.apple.com/swift/blog/?id=7 에 설명되어있으니 한번 읽어보세요~(번역한 블로그 글도 있으니 참고해보실 수 있을거에요)
- 함수 정의 부의 순서를 본인의 컨벤션대로 통일 시켜볼 수 있을 것 같아요. 

## 질문에 대한 답변
- $0은 클로져에서 인자의 이름을 지정해주지 않았을 경우, 사용되는 인자명이라고 설명할 수 있겠네요. 스위프트 공식문서의 closure 파트를 한번 읽어보면 도움이 될 것 같네요! 말씀하신대로 $0.0은 key, $0.1은 value를 나타내는 것이 맞아요. $0의 타입을 확인해보시면 (옵션키를 누르고 $0에 커서를 갖다대보세요!) 튜플로 확인되실텐데, 튜플의 첫번째 요소는 .0로, 두번째는 .1로 접근이 가능해요.

2022-07-01 10:30 UTC, gwd0311 commented on CodeStarterCamp_Week2/main.swift
> +    print(" 입니다.")
joined()를 사용하니까 편하게 배열에있는 요소들을 문자열로 합칠수 있네요 ㅎㅎ 과제에 적용해보겠습니다..!!😁

2022-07-01 10:38 UTC, gwd0311 commented on CodeStarterCamp_Week2/main.swift
> +}
사실 guard let이 있는지 몰라서 알고있었던 if let을 사용하였습니다😅

`if let`구문은 nil값이 있을때와 없을때 실행구문을 입력할수 있고,
`guard let` 구문은 조건문이 참이 아니면 `else`문을 실행하는 것으로 알게되었습니다..!

그리고 `guard let`의 경우 구문 밖에서도 해당 변수를 쓸수 있다는 것을 알게되었습니다..!  구문 밖에서 사용해야할 상황이 생길때 사용하면 좋을 것 같습니다 :)

2022-07-04 02:16 UTC, yeahg-dev commented on CodeStarterCamp_Week2/main.swift
> +}
맞습니다~! 차이점을 잘 이해하시고 용도까지 생각해보신 점 최고!
말씀해주신 차이점 외에도 `guard let` 은 early exit의 용도로도 사용될 수 있어요
옵셔널 바인딩외에도 닐 병합 연산자, 묵시적 해제 옵셔널, 옵셔널 체이닝과 같은 다른 방법도 있으니 아래 링크들을 공부해보세요!🧐
https://developer.apple.com/documentation/swift/optional
https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID330

2022-07-04 02:20 UTC, yeahg-dev commented on CodeStarterCamp_Week2/function.swift
> +open class function{
클래스를 정의해주셨네요~! `open`은 어떤 역할을 하나요?

2022-07-04 02:22 UTC, yeahg-dev commented on CodeStarterCamp_Week2/function.swift
> +            print(" 입니다.")
`joined`를 잘 활용해주셨네요!👍
여기서 `lazy`메서드는 어떤 역할을 하나요?

2022-07-04 02:32 UTC, yeahg-dev commented on CodeStarterCamp_Week2/function.swift
> +                }
`guard let` 구문과 `break`를 사용해서 `nil`이 나올 때 반복문을 탈출하도록 설계하셨네요. `else`구문에 `return`대신 `break`를 사용할 수 있다는 점을 저도 처음 알았네요!
만약 세번째 원소가 `nil`이라면 이 함수의 결과값은 어떻게 될지 예상해볼까요??
저도 찾아보다가 각 구문의 차이점을 정리해둔 글을 발견해 공유합니다~
https://medium.com/@mumtaz.hussain/that-return-keyword-in-guard-let-statement-in-swift-eeacf88f6270

2022-07-04 02:34 UTC, yeahg-dev commented on CodeStarterCamp_Week2/main.swift
> +let lottoFunction = function()
`function`보다 더 유의미한 네이밍으로 수정해볼 수 있을 것 같아요!
그리고 클래스, 구조체, 열거형은 첫글자는 대문자로 시작하는 카멜케이스를 사용해요🙂
다음 스텝에서 클래스를 정의할 때 적용해보아요~

2022-07-04 02:37 UTC, yeahg-dev approved these changes
안녕하세요 제리님~
제가 말씀드린 점외에도 많이 찾아보시고 공부하셔서 구현까지 잘 해내셨어요!👍
이번 스텝에서 경험해보고, 공부해야할 주제는 모두 커버한 것 같아서 다음 스텝으로 넘어가도 좋을 것 같습니다
수정하신 코드에 대한 질문과 참고해볼 만한 글 코멘트로 남겼어요. 확인해보시고 댓글만 남겨주세요!🙂
다음 3주차 과제도 화이팅!!

2022-07-04 02:37 UTC, merged

2022-07-04 02:54 UTC, gwd0311 commented on CodeStarterCamp_Week2/function.swift
> +open class function{
구글링해보니 `open`은 모듈 외부에서도 접근 가능하게 해주는 역할을 하는 것으로 알게되어 사용해보았습니다..!

2022-07-04 02:59 UTC, gwd0311 commented on CodeStarterCamp_Week2/function.swift
> +            print(" 입니다.")
`lazy`를 이용하면 오직 그 프로퍼티를 읽을 때만 실행되므로 불필요한 메모리 할당을 미연에 방지할 수 있을것같습니다!

2022-07-04 03:08 UTC, gwd0311 commented on CodeStarterCamp_Week2/function.swift
> +                }
링크주신 문서 잘 읽어보았습니다..! guard let 구문 사용할때 return, break 이외에 continue, throw 등 다양한 방법이 있다는 걸 알게되었습니다🧐
만약 3번째원소가 nil이라면 출력문이 출력된 후의 원소는 출력되지 않을것같습니다..!

2022-07-04 03:09 UTC, gwd0311 commented on CodeStarterCamp_Week2/main.swift
> +let lottoFunction = function()
넵 ㅎㅎ 다음클래스 열심히 수강하여 적용시켜보겠습니다🔥🔥