Week2 [STEP3] SierraJY
yagom-academy/swift-starter-week2 pull request #307
Opened 2022-07-05 04:18 UTC by SierraJY

# 고민했던점
 joined메서드를 사용하기위해 [Int]Array를 [String]Array로 형변환하는 방법을 고민해 보았습니다. 
첫 번째는 map이라는 고차함수를 사용하는 것..! 
두번 째는 새로운 [String]Array를 만들어 Element하나 씩 String으로 캐스팅하여 넣기.
map함수를 사용하기엔 아직 부족한 것 같아 조금더 공부하고 사용해 보아야 겠어요.

* contains함수도 배열원소를 순환한다면, n^2로 시간복잡도가 똑같을 것 같아요!

2022-07-05 14:58 UTC, yeahg-dev commented on CodeStarterCamp_Week2/main.swift
> +    }
`selectedRound`가 이미 배열인데 Int를 String으로 변환하기 위해 배열을 생성하고 있네요. 말씀하신 것 처럼 고차함수를 사용하면 간단하게 변형이 가능해요!  현재 단계에서 고차함수는 난이도가 어렵다고 저도 생각하고요.  고차함수를 풀어서 보면 지금 구현하신 방법과 거의 동일하답니다! 
새로운 방법을 찾아보고 시도하신점 최고입니다👍

2022-07-05 14:59 UTC, yeahg-dev commented on CodeStarterCamp_Week2/main.swift
> +}
기능을 함수로 분리해 볼 수 있을 것 같아요!

2022-07-05 15:01 UTC, yeahg-dev commented on CodeStarterCamp_Week2/main.swift
> +}
위 구문을 함수로 만들어볼 수 있을 것 같습니다.

2022-07-05 15:05 UTC, yeahg-dev requested changes
안녕하세요 시에라님~

이전 스텝에서 작성했던 코드를 아주 잘 재사용하셨고,
또 코드를 개선하기 위해 고차함수를 추가적으로 공부하고 시도해보신 점 멋집니다!💯

로직은 요구사항대로 아주 잘 작동하고요, 가독성도 아주 좋아졌어요~
단 기능별로 함수를 만들어볼 수 있을 것 같아서 아직 머지하진 않을게요
조금 더 수정해보아요!

2022-07-06 05:55 UTC, SierraJY commented on CodeStarterCamp_Week2/main.swift
> +    }
나중에 고차함수도 공부해보겠습니다!

2022-07-06 06:19 UTC, SierraJY commented on CodeStarterCamp_Week2/main.swift
> +}
넵!😆

2022-07-06 06:19 UTC, SierraJY commented on CodeStarterCamp_Week2/main.swift
> +}
넵 구현해보겠습니다!

2022-07-07 11:38 UTC, yeahg-dev approved these changes
시에라님~ 
기능별로 함수 분리 잘해주셨습니다👍

추가적 코멘트 남겼으니 확인해주시고, 머지하겠습니다
다음 스텝에서 만나요!

2022-07-07 11:38 UTC, merged