Week2 [STEP2] Hwieee
yagom-academy/swift-starter-week2 pull request #317
Opened 2022-07-08 05:43 UTC by Hwieee

@jsim27 안녕하세요 ! 오늘도 피드백 해주셔서 감사합니다 ☺️

### 1.효율적인 함수구현에 대해서 

step1에서는 최종목표가 Array, 즉 순서가 중요시되는 컬렉션을 구현하는게 맞다고 생각했지만
step2에서 순서를 고려하지 않는다는 부분을 보고 형변환을 하지않고 Set에서 해결하는게 맞다고 생각이 들어 
Set으로 해결했습니다. 당첨번호와 제 번호간 중복 번호는 반복문을 활용하지 않고 집합연산에 유리한 Set의 특성을 고려해서 교집합 intersection 함수를 이용했고요.
Q. 이게 제가 생각할 수있는 효율적인 함수라고 생각하는데 더 좋은 방법이 존재할까요? 
Q. 또 나무님의 관점에서 볼 때, 효율적인 코드는 어떤 코드일때 말하는 걸까요? (다양한 상황이 있으니까 특정하기 힘드실 건데 저는 그에 대한 관점이 조금 부족한 거같아서요,,)

---

### 2.해결되지 않은 포인트 - 배열단위 ([])출력이 아닌 수 자체의 출력 

**<요구하는 출력>**
<img width="479" alt="Screen Shot 2022-07-08 at 2 31 43 PM" src="https://user-images.githubusercontent.com/86702613/177923566-2edbf449-9a0b-4d75-bb61-cac85922ec13.png">

**<내가 한 출력>**
<img width="220" alt="Screen Shot 2022-07-08 at 2 32 00 PM" src="https://user-images.githubusercontent.com/86702613/177923582-220c227b-50fb-4070-b651-d4b12d0f0046.png">

출력을 해보면 [1,2] 등 이렇게 배열단위로 출력이 되는데 1,2 이런식으로 구현하려면 하나하나 지칭해서 출력해야합니다. 
하지만 Set을 하나하나 지칭해서 출력하려하면 Set은 수의 모임에 순서가 존재하지 않기때문에 개별 출력이 불가능하고, 
이에따라 Array로의 형변환이 이루어지지 않는 이상 해결할 수없는 문제라고 생각합니다. 여기에 대해서 어떻게 생각하세요?

2022-07-08 11:42 UTC, jsim27 requested changes
> 1.효율적인 함수구현에 대해서
step1에서는 최종목표가 Array, 즉 순서가 중요시되는 컬렉션을 구현하는게 맞다고 생각했지만
step2에서 순서를 고려하지 않는다는 부분을 보고 형변환을 하지않고 Set에서 해결하는게 맞다고 생각이 들어
Set으로 해결했습니다. 당첨번호와 제 번호간 중복 번호는 반복문을 활용하지 않고 집합연산에 유리한 Set의 특성을 고려해서 교집합 intersection 함수를 이용했고요.
Q. 이게 제가 생각할 수있는 효율적인 함수라고 생각하는데 더 좋은 방법이 존재할까요?

-> 말씀하신 대로 겹치는 번호를 비교하기 위해서는 꼭 순서가 고정되어야 할 필요가 없고, 구현하신 것 처럼 `intersection` 메서드를 쓰기 위해서라도 처음에는 Set인 상태로도 좋을 것 같습니다!
충분히 효율적인 로직이 맞는 것 같아요!!
다만, 아래 `해결되지 않은 포인트`의 문제가 남아있게 되는데요, 이는 아래에서 마저 답변드릴게요.

> Q. 또 나무님의 관점에서 볼 때, 효율적인 코드는 어떤 코드일때 말하는 걸까요? (다양한 상황이 있으니까 특정하기 힘드실 건데 저는 그에 대한 관점이 조금 부족한 거같아서요,,)

-> `코드의 효율` 은, 참 광범위하게 해석될 수 있는 말인 것 같아요.

좁은 의미로는, 
`논리적으로 최대한 간단한 과정만으로 결과에 이를 수 있는 로직을 구성하는 것`일 수도 있구요. 
(이를 위해서 저희가 코드 작성 이전에 순서도를 통해 로직을 고민해 보는 것이죠!)

조금 다른 관점에서는, `사람의 논리` 뿐만 아닌, `컴퓨터의 작동원리`을 이해하고 컴퓨터가 가장 효율적으로 일할 수 있는 방식으로 짜여진 코드가 될 수 있겠네요.
이런 **성능의 관점**에서 코드를 잘 짜기 위해서는 CS에 대한 다각적인 이해도 필요하고, Swift 언어와 프레임워크, Xcode가 작동하는 방식에 대한 이해도 필요할 것 같아요. 지금 이런 주제들을 고려하기는 어려운 것 같고, 나중에 공부를 하시다 보면 자연스럽게 알게 되는 관련 지식들이 있을 것 같네요! 😄 

넓은 의미로는, `사람 간의 협업을 효율적으로 하게 해 주는 코드` 가 될 수도 있겠어요.
- 가독성이 좋은 코드 
- 기획이 수정되어도 코드 수정을 최소화할 수 있는 방식으로 짜여진 코드
- (함수 등을)재사용할 수 있도록 짜여진 코드

좋은 코드, 효율적인 코드를 쓰기 위한 고민은 계속 하시되, 조급하게 생각하실 필요는 없습니다. 

지식이 늘어감에 따라, 또 다른 사람의 코드를 많이 읽고, 직접 많이 쳐볼수록 의식하지 않고도 자연스럽게 발전할 수 있는 부분이 있어요. 이미 지금 단계에서는 충분히 좋은 코드를 쓰고 계신 것 같습니다! 👍👍 

2.해결되지 않은 포인트 - 배열단위 ([])출력이 아닌 수 자체의 출력
> ...
하지만 Set을 하나하나 지칭해서 출력하려하면 Set은 수의 모임에 순서가 존재하지 않기때문에 개별 출력이 불가능하고,
이에따라 Array로의 형변환이 이루어지지 않는 이상 해결할 수없는 문제라고 생각합니다. 여기에 대해서 어떻게 생각하세요?

랜덤 숫자를 생성하고, 겹치는 숫자를 비교할 때 까지는 Set를 사용하고, 출력할 때가 되어서 Array로 변환하면 되지 않을까요?ㅎㅎ
휘님이라면 충분히 요구사항에 맞게 출력하도록 구현 가능하실 것 같아요!

필요한 수정을 모두 마치신 후에, 다시 DM 주세요!
@Hwieee

2022-07-08 11:42 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +myLottoNumbers = [1,2,3,4,5,6]
요구사항에서 `내가 찍은 번호 배열을 myLottoNumbers 변수에 할당합니다.` 라고 되어있는데, Set를 생성하셨어요. 수정이 필요할 것 같죠..?😅 

또한, 빈 세트를 생성 후에 다음 줄에서 할당하기 보다는, `1,2,3,4,5,6`을 갖고있는 세트를 처음부터 생성하는 것은 어떨까용~!

2022-07-08 11:42 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +}
from이라는 매개변수가 함수 내에서 사용되지 않고 있어요.
매개변수를 통해 전달받는 것이 아닌, 전역변수 `myLottoNumbers`에 직접 접근하고 있네요! 의도하신게 이게 아닌 것 같은 느낌이..^^;;

또한, from을 함수 내에서 쓰면 그 의미가 무엇인지 모호할 것 같네요.
전달인자 레이블을 from으로 두시고, 매개변수 명은 더 구체적인 이름으로 짓는게 좋을 것 같습니다!

2022-07-08 11:42 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +}
checkingMyNumbers의 함수명이 함수의 기능을 충분히 나타내는 것 같지 않습니다!

1. 비교를 통해 겹치는 번호를 도출하고
2. 겹치는 번호가 무엇인지 출력

하는 함수인데, check라는 단어로는 위 내용을 알 수가 없는 것 같아요!

2022-07-12 12:56 UTC, Hwieee commented on CodeStarterCamp_Week2/main.swift
> +}
1. 제 생각에는 이거를 다른방식으로 접근했다가 Set으로 옮기면서 나온 실수같습니다. 수정했습니다 !

2.
타입명시가 저는 무조건 써야하는 기본 tool로 받아들여서 그런지 필요하지 않은 순간에도 쓰게 되네요,, 약간 전에도 나무님이 비슷한 지적해주셔서 그런지 오늘 수정할때도 인지하면서 하니까 익숙해진 것같아요. 감사합니다  ^0^

2022-07-12 12:57 UTC, Hwieee commented on CodeStarterCamp_Week2/main.swift
> +myLottoNumbers = [1,2,3,4,5,6]
한줄로 줄일 수있는 라인을 2줄로 만들어버렸네요 ! 수정했습니다 !!

2022-07-12 13:03 UTC, Hwieee commented on CodeStarterCamp_Week2/main.swift
> +}
비교가 일단 이 함수의 주된 목표이니까 저는 여기서 comparingMyNumbers 라는 함수명으로 수정했는데 나무님이 언급하신 2번기능을 충분히 만족시키는 함수명은 또 아닌것같네요.. 나무님은 comparingMyNumbers라는 수정된 함수명이 충분히 기능을 반영하는 것 같으신가요?

2022-07-12 13:52 UTC, Hwieee commented
안녕하세요 나무님 ! 무탈하신가요 ~! 
오늘도 피드백 감사합니다 ^0^

---

### **1.코드의 효율**
 코드의 효율에 대해서 아직은 배우는 단계라 천천히 생각해 볼 문제이지만, 처음부터 그런 관점으로 
고민하면서, 배우는 것이 많다고 또 생각이 들어서요 !

나무님이 말씀하신 효율적인 코드에 대해서 정리해보았어요 !
1. 사람의 논리적 사고로 이루어질 수있는 효율적인 코드
2. 컴퓨터가 가장 효율적으로 일할 수있는 방식으로 짜여진 코드
3. 사람 간의 협업을 효율적으로 하게 해 주는 코드 
	- 가독성
	- 코드 수정을 최소화할 수 있는 방식으로 짜여진 코드
	- 재사용할수있는, 활용점이 많은 함수 


저는 이번 스텝 수정하면서 느낀건데 swift의 라이브러리에 있는 함수들을 적절히 사용하는 것도 
효율적인 코드를 쓰는 데 도움이 되는 것같아요.
그때 전공수업때 잠시 들었던 얘기였지만 교수님께서 라이브러리를 적절히 사용하는 것도 중요하시다고 말씀하셔서 일회성으로 라이브러리리안의 함수를 쓰고 까먹기 보다는 다시 그것을 활용하려고 노력하는 버릇도 중요하다고 느끼는 계기가 되었던 것같습니다.
이렇게 꼼꼼하게 설명해주셔서 감사해요 

---

### **2.[]제거하는 방법-> 해결 아이디어를 떠올릴 방법(생각의 전환)   (1)**

일단 나무님이 알려주신 아이디어는 2개였습니다 
1. 빈 String으로 만들어 당첨번호와 내번호의 공집합 set을 이제 거기에 차례로 넣는 방법
2. String을 원소로 가지는 Array타입의 메서드를 활용해서 출력하는 방법

일단 저는 1번을 선택했어요. 
먼저 여기에 대한 생각에 있어서 제가 자꾸만 제한점을 두려고한 게 어떤 것이였냐면 
1.무조건 []을 제거하는 것은 컬렉션 내에서만 가능한 문제라고 생각해서 컬렉션의 메소드에서 해결하고자 삽을 팠었고 
2.결론적으로는 대괄호로 묶여진 컬렉션타입이 아닌 String으로 해결하는 거였죠. 대괄호가 없고 그저 문자만 있는, 그래서 문자열간 결합이 좀더 컬렉션보다 편한 tool, String이였죠

Q. 어떻게 이렇게 바로 생각할 수있을까요 ? 보통 본인이 컬렉션에서 걸렸다 그러면 그 문제를 컬렉션에서 보통 찾으려하는데 그것을 비틀어서 다른 타입으로 바꿔서 생각하니까 생각의 전환또한 정말 프로그래밍에서 중요한 것 같습니다 ! 
수정을 다 끝내고 다시 바라보니까 이 것을 낸 아이디어 그 자체에서 얻어가는 게 엄청 많은 것 같아요. 감사해요 나무님 ^0^ 

---

### **2.[]제거하는 방법-> 함수 전체 수정, 디버깅   (2)**
1. 빈 String으로 만들어 당첨번호와 내번호의 공집합 set을 이제 거기에 차례로 넣는 방법
위에 서술한 바와 같이 1번을 선택했고 그렇게 진행했습니다.
1. 우선 공집합 Set을 만들어서 그 원소의 개수가 0개, 0개가 아닐때의 상황으로 나누어
2. 원소의 개수가 0일때는 “아쉽지만 겹치는 번호가 없습니다”
3. 원소의 개수가 0이 아닐때
	(1) commonNumberInRow 라는 빈 스트링을 만들어 
	(2) 반복문으로 공집합 Set의 원소를 차례로 추가해서(“,”도 같이 곁들인) 빈스트링에 잡아넣고 
	(3) commonNumberInRow의 마지막 부분인 “,”를 제거하는 함수로 
	
	(4) 축하합니다! 겹치는 번호는 ~ 입니다!인 함수로 수정완료했습니다 

여기서 제가 맞게 함수를 짰는지 결과만 봐서는 제대로 되었는지 모르겠어서 
디버깅을 따로 했어요 

<img width="811" alt="Screen Shot 2022-07-12 at 9 42 51 PM" src="https://user-images.githubusercontent.com/86702613/178505159-0778c354-0c70-4bc1-a75c-8d15664d40b4.png">

디버깅으로 프로세스를 나누어서 보니까 제대로 했다고 판단이 드네요. (아니면 어쩔수없는데,,,흑흑)
Q. 나무님도 디버깅으로 프로세스를 나누어서 검토하는 시간을 가지시나요? 어떨 때 주로 보시는지 알수 있을까요?


PR보낼때 정말 얻어가는게 많은거같아요,,, 내머릿속에 영원히 남아있길,,,,,,
오늘도 끝내주는 하루 보내세요! ^^^0^^^

2022-07-12 21:00 UTC, jsim27 commented
> Q. 어떻게 이렇게 바로 생각할 수있을까요 ? 보통 본인이 컬렉션에서 걸렸다 그러면 그 문제를 컬렉션에서 보통 찾으려하는데 그것을 비틀어서 다른 타입으로 바꿔서 생각하니까 생각의 전환또한 정말 프로그래밍에서 중요한 것 같습니다 !
수정을 다 끝내고 다시 바라보니까 이 것을 낸 아이디어 그 자체에서 얻어가는 게 엄청 많은 것 같아요.

-> 
현재 내 데이터의 상태(타입) A, 최종적으로 변형할 데이터의 상태(타입) B 가 있다면,
A와 B 중에서 방법을 찾을 수 있겠죠! 
이번 경우에는 `Set(혹은 컬렉션)`인 상태에서, 최종적으로 print문에 들어갈 `String` 형태로 가공할 것이니,
Set(컬렉션), String 중에서 방법을 찾아본 것입니다!

비슷한 상황을 자주 겪어보시면 자연스럽게 생각이 나게 되실 거에요!ㅎㅎ 사실 이렇게 데이터를 내가 원하는 형태로 가공하는 경우가 다 비슷비슷하답니다..! 또, 추후 배우게 되실 `고차함수` 까지 익히신다면, 이런 비슷한 상황들은 쉽게 대처 가능하실 거에요.

+ 언질 드렸던 Array의 메서드는 `.joined(separator:)` 메서드입니다! 알고 계셨죠?😄 

---

> Q. 나무님도 디버깅으로 프로세스를 나누어서 검토하는 시간을 가지시나요? 어떨 때 주로 보시는지 알수 있을까요?

-> 디버깅으로 현재 코드를 이해하려 하는 습관은 참 좋은 것 같아요!!

저는, 말그대로 디버깅할 때 주로 활용하는 것 같아요ㅎㅎ
스스로 짠 코드지만 이해할 수 없는 동작을 할 때가 많죠! 그럴 때마다 내가 어디서부터 잘못 생각했는지 알기 위해서 디버깅을 활용합니다.

LLDB에도 고급(?) 기술들이 있답니다ㅋㅋ 익숙해 지시면 많은 도움을 받으실 수 있을거에요!
https://yagom.net/courses/start-lldb/
지금 말고 나~중에 공부해 보세요! ^^

2022-07-12 21:00 UTC, merged

2022-07-12 23:19 UTC, Hwieee commented on CodeStarterCamp_Week2/main.swift
> +}
오우 !!! 이렇게 분리해서 생각할 수도 있구나 알겠어요 merge는 이미 되었지만 수정해서 반영해 보아야겠어요 !

2022-07-12 23:31 UTC, Hwieee commented
1.   디버깅 공부를 바로하고싶지만 참을게요,,흑휴ㅠㅠ 
2.  .joined(separator:) ,,,, TIL에서 댓글로 알려주신 캠퍼분덕분에 알았지 그전엔 몰랐어요,, 죄송합니다 흑 ㅠㅠ 구글링을 어떻게 하면 나올까,,,

3.
>현재 내 데이터의 상태(타입) A, 최종적으로 변형할 데이터의 상태(타입) B 가 있다면,
A와 B 중에서 방법을 찾을 수 있겠죠!
이번 경우에는 Set(혹은 컬렉션)인 상태에서, 최종적으로 print문에 들어갈 String 형태로 가공할 것이니,
Set(컬렉션), String 중에서 방법을 찾아본 것입니다!

여기서 해결영역을 이렇게 나누어서 판단할 수있겠네요 감사합니다 
아니 일어난지 몇시간만에 이렇게 많은 정보가 휘몰아치네요!!!! 배울게 너무 많아요!!!!!!! 감사해요 흑흑