Week2 [STEP2] jonghwan
yagom-academy/swift-starter-week2 pull request #318
Opened 2022-07-08 07:03 UTC by whdghks8654

@jsim27 
step2 pr입니다!

원하는대로 겹치는 값과 겹치는 값이 출력되지않았을때를 if문을 활용해서 작성했으나
"축하합니다 겹치는 번호는 [a,b,c] 입니다 "식의 대괄호가 덮어진 배열식으로 출력되어
대괄호를 벗겨내는 작업에서 많이 고민했습니다!

2022-07-08 10:13 UTC, jsim27 requested changes
고생하셨습니다, 요구사항에 있는 기능 구현을 잘 해내셨네요!

하지만, 몇몇 중요한 부분에서 코드의 수정이 불가피해 보입니다😭 
코멘트 꼭 확인 부탁드리고, 수정 및 답변까지 해 주세요!

⚠️**미션 요구사항을 잘 검토해 주시길 바랍니다**
`Step1의 순서도를 바탕으로 로또 당첨 번호를 생성하는 함수를 생성합니다.`
`찍은 번호와 로또 당첨 번호 의 겹치는 숫자를 확인하는 함수를 생성합니다.`
함수를 통해 기능을 구현하라는 요구사항이 있었습니다!!

다시한번 요구사항을 정독해 주시고, 수정해 주세요!

---
또한, 
`축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!`
라는 실행 예시를 보면, 종환님 코드의 실행 결과와는 조금 다른 부분이 있습니다.
이 부분도 해결해 주시면 좋겠어요.

수정 후 DM 주세요!
@whdghks8654

2022-07-08 10:13 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +}
- `for _ in intersectionNumber {}` 는 현재 코드에서 어떤 기능을 하고 있나요?

- `else` 대신 `else if`를 사용하신 이유가 무엇인가요?

2022-07-09 05:10 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +var numbers = Set<Int>(1...45)
음 array배열로 바뀌어도 상관이 없을거같네요! set이든 array든 문제없을거같아서 set으로 통일한거같습니닷

2022-07-09 05:16 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    lottoNumber.insert(numbers.randomElement()!)
찾아보니 제가 사용한 randomelement는 collection으로부터 추출하는방법이고 옵셔널값으로 추출된다고 하네욥
그래서 언래핑하라는 에러가 떳던것같습니다 저도 ! 로 강제언래핑하느건 부적절한것같다고 생각했는데
if let 을 사용하는게 익숙치않아서 에러에 같이뜬 fix로 수정하게됬고 ! 강제언래핑을 사용한것같습니다!
Int타입으로 배열없이 추출하는 방법은 random 함수가 적절한것같네욥

2022-07-09 05:24 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +
제가 문제를 해결해나가다 꼭 짚어야하는 부분에서 타입명시를 했던것같습니다 보는이는 좀 헷갈릴수도있을거같은데 전체다 타입명시를 하는게 맞을까욥

2022-07-09 05:29 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +}
for in 문은 저도 왜넣었는지모르겠네욥 이것저것 조합해보다가 지워야될 코드인데 그냥 냅두고 사용한거같아요ㅠ 죄송합니다

intersection 갯수가 있으면 축하합니다
intersection 갯수가 없으면 겹치는번호가 없습니다 를 출력하는걸 의도했는데
' 있으면 o / 아니면 전부 else x  ' 가 아니고
' 있으면 o / 없으면 , else if  intersection = 0이면 '  이런식으로 제가 머릿속으로 계산한것같습니닷

나무님 말씀을 듣고보니 else를 활용해서 ' 있으면o 아니면 전부 x ' 이런식의 로직도 바람직한것같습니다!

2022-07-10 06:11 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +}
넵 맞습니다 저도 구글링을 통해 급하게찾아본거라 map함수를 갖다만 썻지 완벽히 이해하진못한것같습니다
출력할때 대괄호 벗겨내는것에만 초점을 두고 찾다가 joined 함수로 넘어가고 map까지 찾아보게된것같네욥
생각보다 for문으로 수월하게 문제를 해결했습니다
근데 for문 terminator에서 출력하는 숫자 전체에 쉼표가 붙는 에러를 어떻게 수정할지 고민하다가
다른분의 til을 보고 enumerated 함수에 힌트를 얻어 문제를 해결했습니다!

@jsim27

2022-07-10 20:53 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +    lottoNumber.insert(numbers.randomElement()!)
`if let`, `guard let`과 같은 옵셔널 바인딩은 어색하더라도 계속 쓰려고 노력하셔야 됩니다! 
강제 언래핑을 시도했는데 nil값을 만나면 앱이 바로 꺼져버리는 치명적인 상황이 생기기 때문에 꼭 안전하게 처리해 주셔야 하고,
익숙해지시면 그렇게 어려운 작업이 아니기도 합니다!ㅎㅎ 많이 써서 최대한 익숙해지는게 좋겠죠!

2022-07-10 20:55 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +
자신만의 기준을 갖되, `일관적`으로 적용하시는게 좋을 것 같아요.

저는 개인적으로 꼭 필요한 경우 외에는 `항상 생략`하는 원칙을 갖고 있지만, 사람마다 다를 수 있는 부분인 것 같아요!
다만, 이런 작은 부분도 근거를 가지고 일관성 있게 코드를 짜는 것이 좋을 것 같습니다!

2022-07-10 21:03 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +}
확인했습니다! 고차함수 없이 잘 해결하셨네요ㅎㅎ
지금 하신 것처럼, 반복문을 돌면서 print를 여러 번하는 방법도 좋고, 
반복문을 돌면서 문자열을 완성 한 후, 마지막에 한 번에 print하는 방법도 있을 것 같네요!

2022-07-11 07:02 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    lottoNumber.insert(numbers.randomElement()!)
넵 열심히 공부해보겠습니닷!

2022-07-11 07:03 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +
넵 맞습니다 누가보기에도 편한코드가 될수있도록 노력해볼게욥

2022-07-11 07:05 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +}
넵넵 감사합니닷ㅎ

2022-07-11 09:19 UTC, merged