Week2 [STEP3] jonghwan
yagom-academy/swift-starter-week2 pull request #328
Opened 2022-07-13 09:17 UTC by whdghks8654

@jsim27  step3 pr보냈습니다!

회차가 더해진 딕셔너리를 출력하는 함수부분에서
딕셔너리 밸류값부분을 set로 출력되게했었는데
다시 -> 어레이배열 -> 문자열로 출력하는부분에서 좀 막혀있었습니다

회차를 더하는부분도 단순히 더하기함수로 만들어서 밖에꺼내와 반복문을 사용하는방법으로 진행했는데
비효율적인것같아서 고민하다 팀원의 도움을받아
함수내에서 매개변수와 반복문으로 자동으로 더해진 딕셔너리가 출력되게끔 진행했습니다

이번에 문제를 풀면서 매개변수와 함수를 활용하는게 정말 많이 부족하다는걸 느꼈습니다ㅎㅎ,,
제일어려운건 문제를 보고 크게 구조를 먼저 생각해내는게 제일어려운것같습니다
크게 구조가잡히면 어디서 어떤함수를 쓸것이고 결과값을 어떤식으로 출력해야겠다 이런게 생각날텐데 하는 생각이많이들었습니다ㅜ

2022-07-13 14:31 UTC, jsim27 requested changes
> 이번에 문제를 풀면서 매개변수와 함수를 활용하는게 정말 많이 부족하다는걸 느꼈습니다ㅎㅎ,,
제일어려운건 문제를 보고 크게 구조를 먼저 생각해내는게 제일어려운것같습니다
크게 구조가잡히면 어디서 어떤함수를 쓸것이고 결과값을 어떤식으로 출력해야겠다 이런게 생각날텐데 하는 생각이많이들었습니다ㅜ

-> 초반 미션에서 순서도를 강조했던 이유이기도 합니다.
코드를 쓰기 전에 미션 요구사항을 잘 읽어보고, 코드가 어떤 순서로 실행되어야 하는지 문장과 그림으로 스스로 표현해 보는 과정에서 큰 구조를 잡아갈 수 있는 것 같아요..!

---

Step3 구현하시느라 고생하셨습니다!

항상 구현은 잘 하시는데, **미션 요구사항을 제대로 숙지하지 않은 부분들**이 아쉬워요ㅜㅜ

코멘트에 남겨드린 부분들과 더불어, 현재 종환님 코드의 실행결과가 요구사항과 형식이 다릅니다.
`2회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다.` 와 같이 출력형식을 맞춰주시기 바라요.

로직을 구현하는 것 보다 어쩌면 더더욱 중요한 것이 `정확한 요구사항 숙지`입니다. 또한, 코드 컨벤션이 지켜지지 않거나 오타가 있는 부분들도 조금 더 꼼꼼히 챙겨 주시면 좋을 것 같아요.

어려움을 느끼시는 부분도, 요구사항을 자세히 읽으면 자연스럽게 개선될 수 있을 것도 같네요!


수정 요청 드린 부분들 개선 및 코멘트하시고 DM 주세요!
@whdghks8654

2022-07-16 04:40 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    var arraylottoNumbers: [String] = []
음 Set타입을 받아와서 스트링으로 출력하는 함수라는걸 명시하는걸 목적으로했는데 혹시
Set<Int>타입표기를 다른방법으로 하거나 생략해도 되는걸까요?

넵 함수명은 수정했습니다! 그런데 from 전달인자? 는 함수명에서 어떤기능을 하는지 물어봐도될까요
한번들었던거같은데 저부분에 대한 개념이 아직 부족한거같습니다

2022-07-16 04:42 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    }
넵 저부분은 저도 실수한거같습니다! 수정하겠습니다ㅎㅎ

2022-07-16 04:46 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
>  }
넵 아직 익숙하지않아서 그런거같네욥 작업끝내고 한번 전체적으로 수정하고 다시해보내도록 노력해보겠습니닷!

2022-07-16 04:48 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    }
감사합니당ㅎ

2022-07-18 11:37 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +    var arraylottoNumbers: [String] = []
>음 Set타입을 받아와서 스트링으로 출력하는 함수라는걸 명시하는걸 목적으로했는데 혹시
Set타입표기를 다른방법으로 하거나 생략해도 되는걸까요?

-> 소괄호를 씌우신 것이 불필요한 것 같다는 말이었어요! `Set<Int>`라고 타입만 표기하는 것이 일반적이지요!!

> 넵 함수명은 수정했습니다! 그런데 from 전달인자? 는 함수명에서 어떤기능을 하는지 물어봐도될까요
한번들었던거같은데 저부분에 대한 개념이 아직 부족한거같습니다

-> https://docs.swift.org/swift-book/LanguageGuide/Functions.html#ID166
Swift Language Guide의 Functions 파트에 해당 내용에 대해 설명되어있네요!
모르는 것이 생겼을 때 공식문서를 적극적으로 찾아보는 것이 정말 중요합니다!!

2022-07-18 12:11 UTC, jsim27 commented on CodeStarterCamp_Week2/main.swift
> +          }
`haslottoNumber` 는 해석하자면 "로또 번호를 가지고 있는지" 입니다. 이런 네이밍은 해당 변수가 Bool타입일 때 적합합니다.
https://soojin.ro/blog/naming-boolean-variables 이 링크를 참고해 보세요!!

2022-07-18 12:19 UTC, jsim27 commented
로직 수정 및 컨벤션 수정하시느라 고생하셨습니다! 전반적으로 코드가 많이 개선된 것 같아요 :)

머지하겠습니다 다음 미션으로 가보아용!!!

@whdghks8654

2022-07-18 12:19 UTC, merged

2022-07-19 05:21 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +    var arraylottoNumbers: [String] = []
넵넵 영문으로 이해하기어려워서,, 그냥 구글번역으로라도 꼭 찾아보도록 할게요!

2022-07-19 05:21 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
>  }
넵 약간의 구조변경과 전역변수부분에서 좀 헷갈렸는데 수정마쳤습니다!

2022-07-19 05:22 UTC, whdghks8654 commented on CodeStarterCamp_Week2/main.swift
> +          }
넵 감사합니다! 자료참고해볼게요ㅎㅎ