Week2 [STEP 2] 무리
yagom-academy/swift-starter-week2 pull request #337
Opened 2022-10-25 06:07 UTC by parkmuri

@wongbingg 
STEP 2 PR합니당 💪😄!!
피드백 주시는게 저에게 꼭 필요한 내용이어서 항상 감탄해요😌 감사합니다!
---
## 고민했던 점
### while문이 돌지 않아요!
- 순서도에 입력한 대로 코드를 구현해보고 있는데, while문이 작동하지 않는 현상이 나타났습니다 ...
- **웡빙의 코멘트가 떠올라 while문이 언제 동작하는지 생각해보게되었어요!☺️**
- while문은 뒤의 조건식에 일치하면 작동하기때문에, 제가 처음 생각했던 조건인 set.count == 6은 맞지않는 조건이었습니다!
~set.count가 6이 되어야만 작동을한다니...~
- 조건문을 바꾸어 진행하니 해결되었습니다!

---

## 해결이 되지 않은 점
### Array와 Set의 비교
- 홈페이지에는 다음과 같이 나와있었습니다.
```swift
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
```
- 배열에 제가 지정한 값을 넣었을때, 당첨기로 만든 Set와 비교가 될까? 하는 고민이 있었어요!
- 배열로 만들어 Set.intersection하니 비교가 불가능할것같다는 생각과는 다르게 정상적으로 작동하더라구요...!
- 그래도 이해는 가지 않아 배열 대신 Set에 저장하여 진행하게되었습니다.
- 컬렉션타입이 다른데 어째서 비교가 가능한걸까요?

2022-10-25 10:49 UTC, wongbingg commented
# week2 [step2] 양식

안녕하세요 무리님 step2 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Step1의 순서도를 바탕으로 `로또 당첨 번호`를 생성하는 함수인지
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교했는지 
- [ ] 출력 값이 요구사항과 일치하는지


### ✅ 고민했던 점에 대하여

while문의 포인트를 알게 되셨군요 ! 👏 

while 문은 조건적으로 돌게 됩니다~! 그 기준은 while 뒤에 붙는 Bool 타입의 값 또는 식이겠죠~?


### ✅ 해결이 되지 않은 점에 대하여

- 로또 번호는 순서가 중요하죠 ! 현재 내가찍은 번호인 `myLottoNumbers` 가 작성된 코드상에서 나타나는 순서와, 출력되었을 때 `내가 찍은 번호는 [  ] 입니다` 에서 나오는 순서가 달라진 것 같아요~! 왜그럴까요!?

    힌트 :
    >[Apple Docs - Set](https://developer.apple.com/documentation/swift/set)
    Set 타입에 대한 설명이 나와있는 Apple Docs 문서에요~! 여기서 Overview 의 첫 문단을 봐볼까요!? 여유가 되신다면 쭉 읽어보시는 것도 추천드려요~!

- 컬렉션 타입이 Array 와 Set으로 다른데 비교가 가능한 intersection 함수에 대해 한번 알아볼까요 ? 해당 함수를 option + 클릭하면 Docs 내용을 볼 수 있습니다! 
<img src="https://i.imgur.com/ewoRlK5.png" width="400">


### 🛠 수정 요청사항

- 순서도에서 while문의 조건 부분이 아직 수정되지 않은 것 같습니다!
- `[`,`]` 기호를 포함하지 않은 상태로 출력값을 수정 해주세요!🙏

2022-10-26 04:29 UTC, parkmuri commented
@wongbingg 
피드백 요청 받은 것 수정해보았습니다!

## 고민했던 점
### 형변환?
 - joined 함수를 사용하여 컬렉션타입을 String으로 출력하고 싶었습니다.
 - 제가 가진 컬렉션 타입은 String이 아닌 Int값이어서, 컬렉션 타입 자체를 형변환 할 필요가 있었어요!
 - 간단한 String(변수) 방법으로는 컬렉션타입 전체 형변환이 어려워 고차함수 map을 찾게되었습니다.
 - map으로 Int값을 가지는 Set를 String값으로 반환하고, 그 Set를 joined(seperator: ", ")를 이용하여 문자열로 출력했습니다!
 
### Set.intersection 의 사용
 - 추천해주신대로 option+함수 클릭해서 살펴보니, 'A sequence of elements. other must be finite'라고 나오는것을 확인했습니다.
 - Set는 물론 Array또한 sequence of elements이기때문에 비교가 가능했구나! 하고 이해했어요😄
  
---

2022-10-26 05:08 UTC, wongbingg requested changes

2022-10-26 05:08 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +let intToStr = intersectionSorted.map {(value : Int) -> String in return String(value)}
고차함수로 인해 클로저 구문이 생겼군요 ~! 
- 여기서 사용되는 value 값이 무엇인지 설명해주실 수 있을까요 ?
- 지금 사용한 클로져 기법은 기본 클로져 일까요? 후행 클로저 일까요 ?
- 컨벤션 
``` swift
let intToStr = intersectionSorted.map { (value: Int) -> String in
    return String(value)
}
```

이런 식으로 in 뒤에 줄바꿈이 들어간답니다!

2022-10-26 05:21 UTC, parkmuri commented on CodeStarterCamp_Week2/main.swift
> +}
주석제거 잊지않겠습니다😭

2022-10-26 05:41 UTC, parkmuri commented on CodeStarterCamp_Week2/main.swift
> +let intToStr = intersectionSorted.map {(value : Int) -> String in return String(value)}
- 여기서 사용되는 value 값이 무엇인지 설명해주실 수 있을까요 ?
   - value는 intersectionSorted Set의 값들이라고 생각합니다! 
   - intersectionSorted Set의 값들이 매핑되어 int에서 String값으로 반환되는것이라고 이해했습니다.
- 지금 사용한 클로져 기법은 기본 클로져 일까요? 후행 클로저 일까요 ?
   - 개념이 확실치않아 검색해보니 후행클로저라고 생각합니다.
   - 인자값으로 들어가있지않고 사용되고있기때문입니다!
   - 일반적인 클로저는 인자의 형태로 들어가 Inline closure라고합니다!

2022-10-26 07:23 UTC, parkmuri commented
@wongbingg 
아직 제대로 배우지않은 개념인 map보다는 배운 내용으로 할 수 있는 반복문을 이용하여 수정해보았어요!
🥲구글링을 통해 자체 하드모드를 한 것 같네요!

## 고민했던 점
### 배열안에 들어있는 값을 어떻게 String으로 변환할수있을까?
- 배열안에 들어있는 값들을 출력해 String값으로 저장하면 된다는 생각을 못하고 '배열 자체'를 '형변환'해야한다는 생각에 더 어렵게 접근한것같아요😭 
- 처음 접하는 정보가 중요하다는 생각을 하게되었고, 그만큼 검색하는법도 중요하다는 생각이 들었습니다🥲

--- 

## 조언을 얻고싶은 부분
### 위처럼 뭔가 다른 방향으로 흘러가고있을때 자각을 하지 못한다면 시간낭비가 되는느낌인데😭 이것도 겪어야할 실수들 중 하나라고 생각해야할까요?
### (구글링 등)해결방법을 찾았다고 생각했을때, 시야가 좁아지지 않는법에 대해 조언을 얻고싶습니다;-;

2022-10-26 12:54 UTC, wongbingg commented
#### 고민했던 점

여러가지 방법이 있을 것 같아요, 이전에 map을 사용하신 방법도 좋고, 현재 바뀐 코드도 좋습니다 ㅎㅎ
map 과 같이 많이 접해보지 못했던 고차함수의 경우 뒤에 프로젝트 에서 다루게 될거에요!
구글링 같은 경우, 해당 개념에 대한 문서 먼저 찾아보시는 것을 추천드려요~! 
[Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html)
위 문서에 대부분의 개념이 다 들어가 있답니다 ㅎㅎ 

#### 조언을 얻고싶은 부분
모르는 부분에 대해 한시간 정도 찾아보았는데 해결책이 나오지 않는다면, 저에게 또는 다른 학습도우미 분들이나, 크루 분들께 질문을 해주셔도 좋습니다 ~! 해당 질문에 대한 정답을 말씀드리는 것은 아닐테지만, 조금 더 효율적으로 해당 개념에 대해 찾아볼 수 있는 방법을 알려주실 거에요! 저에게도 질문 마구마구 주세요 💪

#### 머지

이번 프로젝트도 수정사항이 잘 반영이 되었네요! 머지 시키도록 할게요 👏
다음스텝도 화이팅입니다 💪

2022-10-26 12:54 UTC, merged