Week2 [STEP 2] Rowan
yagom-academy/swift-starter-week2 pull request #341
Opened 2022-10-25 10:32 UTC by Kyeongjun2

@wongbingg 
안녕하세요 웡빙! 
Step2 PR 보내드립니다. Step2 에서는 새롭게 배웠던 Set 컬렉션 타입을 직접 사용할 수 있어서 좋았던 것 같습니다.
다행히 큰 문제 없이 코드 작성할 수 있어서 너무너무 기분이 좋네요~!! 😄

## 고민했던 점
### 생성된 로또 번호와 내가 고른 로또 번호가 intersection 연산이 되는걸까?
- Set 콜렉션 타입의 편리한 점은 집합 연산이 가능하다는 것인데요, 미션을 수행하면서 myLottoNumbers는 상수를 선언할 때 이 녀석이 Set 타입이 맞나? 하는 의문이 들었습니다. Set 컬렉션타입을 선언하려면 오직 ```Set<Int> = [...]``` 밖에 없다고 생각했거든요!
```swift
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
``` 
### 순서도 내용의 중요성
- 제가 만들었던 순서도를 참고해서 함수를 만들어 갔습니다만... while 구문의 조건 작성할 때 조금 막혔답니다.
  "순서도에는 Set Collection 멤버 수가 5보다 커질 때까지"라고 써놨기 때문입니다!
### switch를 써볼까...?
- switch 구문도 공부했기 때문에 한 번 써먹어보고 싶었는데요! 사용하지 않기로 했습니다. 🥲
   if-else 구문과 다르게 switch 구문은 비교값을 설정해서 각 케이스를 만들어야 했는데, 숫자 6개를 채우기 위해선 같은 작업을 하는 케이스를 
   5회 더 작성해야 했기 때문입니다. 
---
## 조언을 얻고 싶은 부분
### 다음 스텝 진행 시
- Step3에서는 로또 번호를 생성할 때마다 Dictionary 컬렉션에 데이터를 저장해야 합니다. 이럴 때는 새로운 함수 안에 로또번호를 생성하는 함수를 호출하려고 하는데 가능할까요?!
### 집합연산
- 고민했던 점에 먼저 말씀드렸던 부분인데요, 
```swift
let intersection: Set<Int> = lottoNumbers.intersection(myNumbers)
```  

```🛠error build: Cannot convert value of type 'Set<Int>' to specified type '[Int]' ```  

위 집합연산에서 intersection의 타입을 [Int]로 했더니 오류가 발생했습니다!  

```swift
let intersection: [Int] = myNumbers.intersection(lottoNumbers)
```
```🛠error build: Value of type '[Int]' has no member 'intersection' ```  

이렇게 바꿨더니..이번엔 이런 오류가 나왔어요.
그래서 현재 상태로 마무리 하게 되었습니다.
요 부분에 대해서 설명 조금 부탁드릴게요🙏

2022-10-25 23:50 UTC, wongbingg commented
안녕하세요 로웬님 step2 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Step1의 순서도를 바탕으로 `로또 당첨 번호`를 생성하는 함수인지
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교했는지 
- [ ] 출력 값이 요구사항과 일치하는지

### ✅ 고민했던 점에 대하여

#### - 생성된 로또 번호와 내가 고른 로또 번호가 intersection 연산이 되는걸까?

현재 선언한 상수 `myLottoNumbers` 의 타입은 무엇일까요 ?
`intersection()` 함수는 어떤 함수일까요 ? 

#### - 순서도 내용의 중요성
약간의 오류가 있었군요 ~! 하지만 전체적인 순서도가 잘 짜여져 있었기 때문에 코드화 하는데에 어려움이 없었을 것 같아요
#### - switch를 써볼까...?
아마 나중에 프로젝트에서는 switch구문을 다루게 될 거에요~! 

### ✅ 조언을 얻고 싶은 부분에 대하여 

#### - 다음 스텝 진행 시

충분히 가능해 보입니다~!

#### - 집합연산

`intersection()` 함수를 호출하는 타입이 어떤 타입인지 알아보면 좋을 것 같은데요 , 이럴 땐 함수를 option + 클릭을 해서 정보를 확인해보면 좋을 것 같아요! 이 함수의 반환타입이 무엇인지 확인해볼까요?

Swift는 TypeSafe 언어입니다. 사용자가 작성한 코드를 컴파일할 때 타입검사를 하는데, 이때 오류가 생긴 것 같아요 ! 이 키워드에 대해서도 알면 좋을 것 같아요~! `type safe`

### 🛠 수정 요청사항

- `[`,`]` 기호를 포함하지 않은 상태로 출력값을 수정 해주세요!🙏

2022-10-25 23:55 UTC, wongbingg requested changes

2022-10-25 23:55 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +}
- 함수 네이밍이 매우 좋습니다~!
- `Type Inference` 특성을 이용하여 12번줄의 코드를 줄여볼까요 ?

2022-10-25 23:55 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +}
- 현재 로또 번호와 내가뽑은 번호와 비교가 잘 되고있을까요? 
- 로또는 번호만 일치한다고 맞은게 아니죠~? 번호와 순서가 일치해야 됩니다! 
- Set 타입의 특성이 무엇일까요 ?

2022-10-26 04:35 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +}
1. ```let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]``` 은 Array 타입 상수였네요!

2. intersection() 함수
 - 비교할 sequence와 다른 setB를 비교하여 공통된 멤버만 포함하는 새로운 set를 반환하는 함수
 - return값이 set type이기 때문에 ```let intersection``` 상수 선언 시, set type으로 설정할 필요가 있었습니다.

3. 함수의 summery를 Xcode에서 확인할 수 있었네요!! 너무 편리해서 꼭 기억해두도록 하겠습니다~~
 - option + mouse click

4. ```Type safe``` 학습자료에서도 몇 번 본 기억이 납니다~~ swift는 데이터 타입에 엄격한 언어라고 하셨죠!!
 - 컴파일 오류가 났던 이유는 set type을 반환하는 함수인 intersection을 사용하면서 상수를 array 타입으로 선언했기 때문이네요😅

2022-10-26 04:38 UTC, Kyeongjun2 commented
1. ```let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]``` 은 Array 타입 상수였네요!

2. intersection() 함수
> - 비교할 sequence와 다른 setB를 비교하여 공통된 멤버만 포함하는 새로운 set를 반환하는 함수
> - return값이 set type이기 때문에 ```let intersection``` 상수 선언 시, set type으로 설정할 필요가 있었습니다.

3. 함수의 summery를 Xcode에서 확인할 수 있었네요!! 너무 편리해서 꼭 기억해두도록 하겠습니다~~
> - option + mouse click

4. ```Type safe``` 학습자료에서도 몇 번 본 기억이 납니다~~ swift는 데이터 타입에 엄격한 언어라고 하셨죠!!
> - 컴파일 오류가 났던 이유는 set type을 반환하는 함수인 intersection을 사용하면서 상수를 array 타입으로 선언했기 때문이네요😅

2022-10-26 04:39 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +}
Set 타입은 순서가 없이 멤버가 오직 하나로 유일한 콜렉션 타입입니다!

그래서 intersection 함수를 사용해도 자리에 상관 없이 겹치는 번호를 뽑아낼 수 있었습니다.

2022-10-26 04:40 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +}
```swift
var lottoNumbersSet = Set<Int>()
```
이렇게 수정해보겠습니다~~

2022-10-26 06:03 UTC, wongbingg commented
수정 요청사항이 잘 반영 되었네요~ ! 잘 해주셨습니다👏👏

그 외 다른 코멘트에 대한 학습도 잘 되신 것 같아요 👍
머지 해드리겠습니다 ~! 다음 스텝도 화이팅입니다💪

2022-10-26 06:03 UTC, merged