Week 2 [Step 3] 500beckwon
yagom-academy/swift-starter-week2 pull request #344
Opened 2022-10-26 10:31 UTC by 500beckwon

@llingo 

Step 3: 로또 당첨 번호를 회차별로 저장하고, 확인하자! 를 완성하였습니다!
사족으로 과제에 지시사항이 없던 코드 몇 줄을 수줍게 추가하였습니다.

## 고민했던 점
 ### 고차함수에 대하여
 - 고차라는 단어가 뭔가 있어보이고 웅장한 기능을 제공하는 것 같아서 겁이 났고 아직 이해가 완벽하게 된건 아니지만 흉내내는 식으로 한번 사용해보았습니다. 대표적으로 Step 2의 피드백 받은 부분인 checkSameLottoNumber()에서 filter를 사용하였습니다
 -  Step 3 에서는 로또 번호가 담긴  [Int] 배열의 대괄호를 없애고 출력하기 위해 [String]으로 바꾸는데 map을 사용했습니다.  같은 배열인데 joined(seperator: String)가 사용이 안돼서 많이 당혹스러웠는데 반복문을 쓰면서 Int 값을 "\(Int)"로 바꾸는 중에 데자뷰를 느껴 구글링과 코드를 계속 쓰다보니 map을 사용하여 간편하게 바꾸는데 성공하였습니다!

 ---

 ## 해결이 되지 않은 점
 ### 문제의 제약
 - 로또 번호를 연속으로 만들지 말라는 제약이 없어서 반복문을 통해 지정한 회차까지 로또 번호를 만들어 저장하게 만들었습니다

 ---

 ## 조언을 얻고 싶은 부분
 ### 사족으로 작성한 코드
 - DictIonary는 Set과 마찬가지로 순서가 일정치 않다고 읽었습니다. 다만 회차별로 조회라는 조건이 있어서 순서에 신경을 쓰진 않았는데 맞게 진행한 걸까요?
 - 5회까지 만들라는 지시가 있었지만 예시로 5회인지 무조건 5회인지 확실하지 않아서 매개변수와 지정값을 넣어서 함수를 제작했습니다. 또한 키가 없는 경우를 생각하여 사족으로 else 문에 print()문을 넣어서 예외처리를 하였습니다. 수행하면서 이런 식으로 사족을 붙여도 괜찮을까요?

2022-10-27 06:07 UTC, llingo requested changes
@500beckwon 님! 벌써 2주차의 마지막 STEP이네요 🎉

STEP 3의 미션을 잘 수행해주셨습니다!
- [x] Dictionary의 저장, 추출
- [x] Optional 값의 안전한 추출
- [x] Step 2 에서 사용했던 함수(로또 당첨 번호 생성 함수)를 재사용
- [x] Swift API Guideline을 바탕으로 네이밍, 컨벤션

사용하지 않는 코드에 대해서는 주석처리보다 제거하는 것이 좋습니다! 또한, `Dictionary<String, [Int]>` 보단 `[String: [Int]]`가 더 좋아보입니다! 

이번 주차에서 고차함수 filter, map을 사용하셔서 잘 구현해주셨습니다! 혹시 사용하시는 데 어려움은 없었나요? 😄

---

**Q1. DictIonary는 Set과 마찬가지로 순서가 일정치 않다고 읽었습니다. 다만 회차별로 조회라는 조건이 있어서 순서에 신경을 쓰진 않았는데 맞게 진행한 걸까요?**
A. 회차별 조회라서 잘 구현하셨습니다!

**Q2. 5회까지 만들라는 지시가 있었지만 예시로 5회인지 무조건 5회인지 확실하지 않아서 매개변수와 지정값을 넣어서 함수를 제작했습니다. 또한 키가 없는 경우를 생각하여 사족으로 else 문에 print()문을 넣어서 예외처리를 하였습니다. 수행하면서 이런 식으로 사족을 붙여도 괜찮을까요?**
A. Dictionary에 해당 키-값이 없는 예외적인 상황에 대해 예외처리를 잘해주셨습니다!

코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

2022-10-27 06:07 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +func saveLottoNumbers(maxRound: Int = 5) {
default 값을 사용하셨군요 좋습니다 👍

2022-10-27 14:18 UTC, llingo approved these changes
@500beckwon 님!

2주차 미션도 수고하셨습니다! 다음 주차도 화이팅입니다 :) 🎉

**Q1. $0 <- 이 표현은 일종의 축약어 같은데 지칭하는 단어가 따로 있을까요?**
A. 이 부분은 클로저 축약과 관련된 부분인데 추후에 클로저가 익숙해지셨을 때 **클로저 축약**을 찾아보시고 사용하는 것이 좋아보입니다!

2022-10-27 14:18 UTC, merged

2022-11-16 12:28 UTC, ElonPark commented
$0는 shorthand argument라고 불러요