Week2 [Step2] 송중
yagom-academy/swift-starter-week2 pull request #346
Opened 2022-10-27 06:13 UTC by kimseongj

@llingo 
링고! Step2입니다! 무난하게 작성한거 같긴한데 뭔가 복잡한 느낌이군요..🧐

## 고민했던 점 
### for문이 너무 많이 들어간 느낌이예요! 
PR을 보내기 전에 다른 분들은 어떻게 하셨나 봤었는데 intersection이라는 연산을 사용하는거 같더라구요 ㅠ intersection 대신 for문으로 작성했는데, 다음부터는 코드를 더 간결하게 작성할 수 있는 방법이 무엇이 있는지 찾아봐야겠어요!!

2022-10-27 14:35 UTC, llingo requested changes
안녕하세요 @kimseongj 님!

STEP 1에서 작성해주신 순서도에 맞게 잘 구현해주셨습니다 🎉
- [x] Step 1의 순서도를 코드화하기
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교하기

**Q1. for문이 너무 많이 들어간 느낌이예요!**
A. [joined(separator:)](https://developer.apple.com/documentation/swift/array/joined(separator:)-7uber)를 활용하면 해당 코드를 줄일 수 있을 것 같아요!

코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +let myLottoNumbers: [Int] = [1,2,3,4,5,6]
[1,2,3,4,5,6] 보단 [1, 2, 3, 4, 5, 6] 이 더 좋을 것 같아요!

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +func makeLottoSet()  {
소괄호 뒤에 빈칸이 있는 것 같습니다!

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +func checkLottoNumbers () {
소괄호 앞에 빈칸이 있는 것 같습니다!

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +        }
이 부분 때문에 for문을 많이 쓴 것 같다고 하신 것 같은데 `joined(separator:)`를 활용할 수 있을 것 같아요!

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +        }
또는 저 부분을 함수로 따로 구분할 수 있을 것 같습니다

2022-10-27 14:35 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +    print("당첨번호는 \(lottoSet)입니다.")
당첨번호 출력은 요구사항에 없지만 확인을 위해 따로 출력해주신건가요?

2022-10-28 02:22 UTC, kimseongj commented
변경사항
- joined(separator: ) 을 통해 더 손쉽고 간결한 코드를 완성했습니다. 
- 함수 표기를 수정했습니다.

당첨번호 출력은 요구사항에 없지만 확인용으로 작성했습니다. 
저 부분은 요구사항에 없는 것이니 삭제하는게 맞을까요?

2022-10-28 12:41 UTC, llingo approved these changes
@kimseongj 님!

이번 스탭 수고하셨습니다!
당첨번호 출력 부분은 요구사항에는 없지만 이번 스탭에서 문제가 되는 사안은 아니기 때문에 Merge 하겠습니다! 추가적으로 `joined(separator:)` 사용하셨던 부분을 조금 더 간단하게 줄일 수 있을 것 같아요! 코멘트 확인하시고 다음 스탭에 반영해주시면 좋을 것 같아요 :)

이번 스탭 수고하셨습니다 🙇🏻

2022-10-28 12:41 UTC, llingo commented on CodeStarterCamp_Week2/Step2.swift
> +        print(" 입니다")
```swift
let joinedCorrectNumber = correctNumber.joined(separator: ", ")
print("축하합니다! 겹치는 번호는 \(joinedCorrectNumber) 입니다")
```

이렇게 사용하면 더 줄일 수 있을 것 같아요!

2022-10-28 12:42 UTC, merged

2022-10-28 13:58 UTC, kimseongj commented on CodeStarterCamp_Week2/Step2.swift
> +        print(" 입니다")
W😯W! 왜 이생각을 못했을까요! 감사합니다^^