WEEK2 [STEP 3] Rowan
yagom-academy/swift-starter-week2 pull request #347
Opened 2022-10-27 06:55 UTC by Kyeongjun2

@wongbingg 
안녕하세요 웡빙 👋
지난 STEP 2에서 많이 고민해보고 피드백 반영한 덕에 이번 스텝도 수월하게 결과 얻어낼 수 있었습니다.
정말 보람차고 기분이 좋네요~! 👍
이번 주 미션도 항상 도와주셔서 감사합니다😁

# 고민했던 점
## "특정회차"의 로또 번호를 구하기 편하게..
- Dictionary의 멤버를 추출하려면 옵셔널 바인딩이 불가피했습니다! 맨 처음 코드를 작성할 때, if-let 구문에서 Key에 회차를 직접 기입했는데 이렇게 되면 다음 회차의 번호를 구할 때 if let 구문 안쪽을 손봐야하는 부분이 마음에 들지 않았습니다.
- ```var wantedLottoRound```를 따로 선언하여 편하게 회차를 변경할 수 있도록 해결했습니다.
## lottoRound 변수를 어디에 선언해야 할지
- 처음에는 ```var lottoRound = 0```을 ```saveLottoDataToDict``` 내부에 선언했습니다. 하지만 반복문을 사용해 로또 번호를 5회 생성 시, 매회 함수 내부에서 lottoRound가 0으로 초기화되기 때문에 함수 외부에 따로 선언했습니다.
## Naming
- 영어 공부가 좀 더 필요한 것 같습니다.. 단번에 떠오르는 단어가 없어 몇 번씩 변수, 함수의 이름을 수정했어요. 😂

# 조언을 얻고 싶은 부분
## Naming
- ```wantedLottoRound``` 변수의 더 알아보기 좋은 이름이 생각나신다면 말씀 부탁드립니다!! (처음엔 findRound, findNumbersOfRound 등 여러가지 많이 써봤습니다 😅)
## 너무 복붙을 했나..?
- 지난 회차에 그대로 가져다 쓸 수 있는 내용이 많아서 꽤나 빠르게 미션을 마무리한 느낌이 적지 않습니다ㅎㅎㅎ... 혹시 추가적으로 공부해야될 내용이나 수정하면 더 좋아질 부분이 보이신다면 코멘트 마구마구 부탁드립니다~ 🔥

2022-10-27 12:26 UTC, wongbingg commented
안녕하세요 로웬님 step3 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 딕셔너리 내부타입이 적합한지
- [x] 옵셔널 값의 안전한 추출이 이뤄졌는지

### [아쉬운점]

- 이전 스텝의 출력문이 함께 나와서 결과값에 가독성이 떨어지는 것 같아요!
- 반복되는 코드가 보입니다. 메서드로 묶어주면 적절한 파라미터에 따라 다른 값을 출력하도록 만들 수 있을 것 같아요!
- 원하는 회차를 입력하면 해당 회차의 당첨번호를 출력하는 함수를 만들어볼까요? 

### ✅ 고민했던 점에 대하여
- 코드를 보고 말씀 드릴게요~!


### ✅ 조언을 얻고 싶은 부분에 대하여 
- 현재의 네이밍도 좋습니다 👍

2022-10-27 12:36 UTC, wongbingg requested changes

2022-10-27 12:36 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +}
하나의 함수로 묶어서 해결할 수 있을 것 같아요~! 🧐
이 부분 한번 고민 해볼까요 ?

2022-10-27 12:36 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +}
이 코드라인이 `wantedLottoRound `만 바뀌면서 3회가 반복되었는데요,
반복되는 코드를 함수로 묶어줄 수 있을 것 같아요 ! 
또한 세부 코드들도 내용에 따라 함수로 분리하여 사용할 수 있을 것 같아요
이부분 한번 고민해볼까요~?

2022-10-27 12:36 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +}
중괄호 컨벤션이 맞지 않는 것 같습니다 이럴 땐, `command + A` 로 전체를 선택한 후 `control + i` 를 하면 정돈이 된답니다

2022-10-27 12:36 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +var lottoRound = 0
전역변수로 선언을 해주셨네요~ 
지역변수와 전역변수의 차이를 아시면 좋을 것 같은데요, 해당 변수는 특정한 곳에서만 사용되고 있나요? 아니면 전체적인 부분에서 사용이 되고 있나요 ? 특정 함수에서만 사용이 되고 있다면, 그 함수 내부에서 선언을 해주어도 되겠죠 ?

2022-10-28 02:39 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +}
함수로 묶으면서 위에 선언했던 전역변수 ```var lottoRound```를 함수의 매개변수로 바꿔줬습니다!
이에 따라 매개변수가 for-in 구문의 시행 횟수 정보를 입력받을 수 있게 되었습니다.
훨씬 깔끔해 보이네요 👏

2022-10-28 02:39 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +}
1. ```findLottoData```함수로 묶어서 원하는 회차의 정보를 출력하도록 수정했습니다!
피드백 시간에 배운 wildcard를 이용해서 함수 호출 시 간편하게 원하는 회차를 argument로 입력할 수 있도록 해봤습니다.

2. 중괄호 컨벤션 너무 편해졌어요!! 감사합니다 👍

2022-10-28 02:39 UTC, Kyeongjun2 commented on CodeStarterCamp_Week2/main.swift
> +var lottoRound = 0
그렇네요!! 전역변수로 선언해도 특정한 부분에서만 사용되고 있었습니다.

```saveLottoData```함수와 for-in 구문을 합치면서 전역변수를 삭제하고 매개변수로 설정해줬답니다~~
불필요한 변수의 선언이 줄어들어 훨씬 깔끔한 느낌이 듭니다!!

2022-10-28 02:40 UTC, Kyeongjun2 commented
코멘트 감사합니다 웡빙!

함수로 묶어 표현했더니 코드가 정말 보기 편해졌어요!!
이번에도 큰 도움이 되었습니당~~ 감사해요😁

2022-10-28 04:58 UTC, wongbingg commented
모든 요구사항이 충족 되었네요 ~! 고생하셨습니다 👍👍
불필요한 전역변수의 선언도 줄고 한결 깔끔해진 코드가 보이네요
머지해드릴게요 ~! 다음주 프로젝트도 화이팅입니다 👏💪

2022-10-28 04:59 UTC, merged