week2 [step1] owen
yagom-academy/swift-starter-week2 pull request #348
Opened 2022-10-27 08:14 UTC by Duckduck1596

- 고민했던 점
터미널에서 갑자기 레포가 두개라면서 오류가 나고....포크를 제대로 안했는지 삽질하고 했습니다! 
아직 순서도는 어색하네요!

@llingo

2022-10-27 14:41 UTC, llingo requested changes
@Duckduck1596 님!
새로운 주차의 STEP 1 PR 잘 보았습니다 🎉

STEP 1은 코드를 작성하지 않고 요구사항만을 보고 순서도로 작성해보는 미션이었는데요. 요구사항에 맞게 잘 작성해주셨습니다. 처음부터 코드로 작성하는 것보다 순서도를 작성하고 참고하여 코드를 구현하면 해당 기능이 어떻게 동작할 지 쉽게 파악할 수 있고 다른 길로 빠지는 것을 방지할 수 있습니다!

순서도에 Yes/No로 분기하는 곳이 있었는데요 "오름차순 정렬로 값을 반환한다" 보다는 "set의 랜덤 숫자의 갯수가 6개인가?"라는 문장에서 Yes/No로 분기하는 것이 좋을 것 같아요!

코멘트 확인하시고 순서도 수정 부탁드립니다 :)

2022-10-28 01:33 UTC, llingo requested changes
@Duckduck1596 님!

순서도가 잘 수정되었네요! 그런데 STEP 2에서 진행해야할 코드가 STEP 1에 같이 커밋된 것 같은데 확인 부탁드립니다 🤭

2022-10-28 03:26 UTC, Duckduck1596 commented
@llingo 번거롭게 해드려서 죄송합니다.🥲

2022-10-28 12:33 UTC, llingo approved these changes
@Duckduck1596 님!

이번 스탭 수고하셨습니다! 다음 STEP2 도 화이팅입니다 🎉

2022-10-28 12:33 UTC, merged