Week2 [STEP 2] 졔
yagom-academy/swift-starter-week2 pull request #353
Opened 2022-10-28 16:20 UTC by yijiye

@wongbingg 
늘 많은 도움 주셔서 감사합니다 👍 

# 어려웠던 점 

### 1. 랜덤한 6개의 숫자 저장하기, Array 와 Set
질문했던 내용이기도 한데 처음에 1부터 45까지의 랜덤한 숫자를 생성하라는 문구에서
```swift
let numberArray: Array<Int> = Array<Int>(1...45)
```
이렇게 접근을 했고 랜덤한 숫자를 불러오는 구문인 Int.random(in:) 구문을 사용할 수 없었습니다.
왜냐하면 in 뒤에는 특정 숫자가 들어와야 했기때문에 숫자를 또 지정해주면 Array 타입과 중복된다고 생각했어요
그래서 .randomElement() 구문을 이용하고자 했습니다!

**그런데**
<img width="692" alt="image" src="https://user-images.githubusercontent.com/114971172/198673143-231b42ee-b258-4384-8128-197a038ca03d.png">
randomElement() optional type 이라서 완전한 Int가 아니여서 발생하는 문제로 보여졌습니다.

👉  **randomElement [https://developer.apple.com/documentation/dispatch/dispatchdata/2994429-randomelement/](url)**
👉  **optional [https://slee2540.tistory.com/14](url)**
👉  **optional [https://developer.apple.com/documentation/swift/optional/](url)**

그래서 처음부터 돌아와서 Int.random(in:) 을 이용할 수 있도록 변경했습니다.
 

### 2. Set 구문 insert
로또번호 생성하는 함수를 만들때 단순히 6개의 랜덤한 숫자만 출력되는데에 초점을 맞춰서 진행했습니다.
그러다보니 랜덤한 숫자랑 내가 뽑은 숫자를 어떻게 비교해야할지 엄청 고민했어요...

```swift
func makeLottoNumber() {
for _ in 1...6 {
print()
}
```

이런식으로 처음에 접근을 하다보니 함수에 Set 컬렉션을 어떻게 적용시켜야 하는지 전혀 감이 안잡혀서 구글링해서 
함수를 Set 컬렉션으로 출력하는 것을 찾았습니다 😮‍💨 
func 함수이름() -> **Set<Int> (결과가 되는 타입) ** 이 부분을 놓치고 있었습니다
계속해서 생략하는 함수만 하다보니 타입 이름을 정할 생각은 아예 못했었던것같아요..아무래도 코드를 처음 접해봐서 용어나 문법(?) 작성법등등 익숙하지 않아서 더 어렵게 느껴지는 것 같습니다. 😢 

---

## 새롭게 알게 된 내용

### 📝  randomElement() 를 이용하려면
이번 과제를 하면서 오류를 찾아보다보니 optional 이란 것을 알게 되었습니다.
optional 을 강제로 풀어주려면 ! 를 쓰면 된다는 사실도 알게 되었습니다.
그래서 randomElement()! 를 써서 해보고 커밋하겠습니다 ✋

---

## 도움이 필요한 점
코드를 짤때 기본적인 틀  =, . , : , <> , () 등등 익숙해지는 법은 계속 많이 해보는거겠죠?
지금은 공부하면서 교육자료를 계속 참고하면서 하고 있는데 어떤식으로 공부하는게 도움이 될까요?
웡빙만의 좋은 팁이 있으신가요?!

2022-10-29 00:49 UTC, wongbingg commented
안녕하세요 졔 님 step2 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Step1의 순서도를 바탕으로 `로또 당첨 번호`를 생성하는 함수인지
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교했는지 
- [ ] 출력 값이 요구사항과 일치하는지

### ✅ 어려웠던 점에 대하여
#### 1. 랜덤한 6개의 숫자 저장하기, Array와 Set
 - `randomElement()` 메서드 문서에 보시면 반환타입이 옵셔널이죠 ? 해당 옵셔널을 `무엇` 을 통해서 정상적으로 사용할 수 있을까요? 이 `무엇` 의 방법에는 여러가지가 있습니다. 그중 `Force Unwrapping` 방법을 사용하셨는데요, 이 방법은 선호되지 않는 방법 입니다. 왜일까요 ? 또 안전하게 `무엇` 을 하는 방법에는 어떤 것들이 있을까요? 

### ✅ 새롭게 알게 된 내용에 대하여
#### randomElement() 를 이용하려면
- 위에서 말씀드렸다 싶이 optional 처리의 다른 방법도 찾아보시면 좋을 것 같아요!

### ✅ 도움이 필요한 점에 대하여 
- 현재 프로젝트에 필요한 내용들은 충분히 캠핑사이트에 제공 되어있다고 생각해요~! week 별로, 또 step단위로 참고할 개념들에 대한 정리가 잘 되어있는데요, 이 자료들을 다 보시기에도 벅찰 것 같아요~! 연습 코드를 플레이그라운드에서 많이 짜보면서 복습 해보시는 것도 좋을 것 같아요 ☺️


### 🛠 수정 요청사항

- `[`,`]` 기호를 포함하지 않은 상태로 출력값을 수정 해주세요!🙏

2022-10-29 00:59 UTC, wongbingg requested changes

2022-10-29 00:59 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +var lottoNumber: Set<Int> = Set<Int>()
lottoNumber 가 전역변수로 선언이 되어있는데요 , 이 변수가 전역적으로 사용되고 있을까요? 
아니면 특정 함수 내에서만 사용되고 있을까요? 한번 고민해보시면 좋을 것 같아요 🧐

2022-10-29 00:59 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +var luckyNumber: Set<Int> = Set<Int>()
`Type Inference` 에 대해 알아보시면 좋을 것 같아요 , 알아본 후 코드를 더 간편하게 선언할 수 있을 것 같습니다🧐

2022-10-29 00:59 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +    }
54번, 60번, 61번 줄 코드가 들여쓰기 컨벤션이 맞지 않는데요, 
이럴 땐 해당부분을 드래그하여 `Ctrl + i` 단축키를 통해 정돈을 시켜줄 수 있습니다.
모든 코드에 적용하고 싶다면 `command + A` 를 통해 선택해준 후 정돈하면 되겠죠?

2022-10-29 00:59 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +    }
들여쓰기 컨벤션이 맞지 않습니다 수정해볼까요? 🛠

2022-10-29 00:59 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +        let intersection: Set<Int> = winningNumbers.intersection(myLottoNumbers)
intersection 은 어떤함수 인가요? 또 어느 타입에서 사용할 수 있고 반환타입이 무엇일까요?

2022-10-29 06:54 UTC, yijiye commented on CodeStarterCamp_Week2/main.swift
> +var lottoNumber: Set<Int> = Set<Int>()
아 로또 번호 생성하는 함수에서만 사용되는 변수이므로 안으로 포함시켰습니다!
```swift
func makeLottoNumbers() -> Set<Int> {
    var lottoNumber: Set<Int> = Set<Int>()
    while lottoNumber.count < 7 {
        let randomNumber = Int.random(in: 1...45)
        lottoNumber.insert(randomNumber)
    }
    return lottoNumber
}
```

2022-10-29 06:56 UTC, yijiye commented on CodeStarterCamp_Week2/main.swift
> +var luckyNumber: Set<Int> = Set<Int>()
처음이라 용어들이 익숙하지 않아서 풀로 적었는데 타입 추론을 적용시켜 보는 것도 익숙해지도록 많이 해보겠습니다 💪

2022-10-29 07:17 UTC, yijiye commented
## 수정사항 
### [] 없이 숫자만 출력하기

set 컬렉션 타입으로 지정해놓고 intersection 을 추출 하는 식으로 코드를 짰고 그래서 어떻게 [] 없이 숫자만 출력하는지 도무지 모르겠어서 다른캠퍼분들의 TIL 을 읽어보았고 joined(separator: )를 알게되었습니다.
접근하는 방법은 결국 숫자 하나씩을 string 으로 바꾸어 추출하는 방법이였고 그걸 보고서 웡빙의 힌트를 다시보니 무슨말인지 조금 더 이해하기 쉬웠어요! 그래서 Array 를 String 으로 변환하는 방법을 구글에서 찾아서 적용시켰습니다.
그런데 사실 구체적으로 어떤식으로 변환되고 왜 그렇게 되는건지에 대한 이해는 충분하지 못한것같습니다 😢 
주말동안 아래 키워드를 공부해 볼 생각입니다!
 - .map {String($0)}
 -  joined(separator:)

### optional 처리방법

step2 다음 교육자료에 바로 optional 이더라구요!
그래서 공부해본 결과
야곰이 ** 절대절대 ! 우리 캠프 코드에서는 사용하지 말라고** 하시더라구요 😂
그만큼 안전하지 못한 추출법이라는 것을 알게되었습니다.

대신에 optional binding 방식으로 사용해보면 좋을 것 같습니다.
- optional binding 이란, 상자안에 값이 있는지 없는지 물어보는 것처럼 값이 있다면 추출되고 값이 없다면 추출되지 않음!
- if let 구문을 사용해서 추출 가능!

2022-10-30 12:41 UTC, yijiye commented
# 추가 수정사항
```swift
func makeLottoNumbers() -> Set<Int> {
    var lottoNumber: Set<Int> = Set<Int>()
    while lottoNumber.count < 6 {
        let randomNumber = Int.random(in: 1...45)
        lottoNumber.insert(randomNumber)
    }
    return lottoNumber
}
// while lottoNumber.count < 6 부분 수정!
```
step3 미션을 진행하면서 코드를 잘못 짰다는 걸 알게되었습니다.
6개의 숫자를 출력해야하는데 7개의 숫자가 출력되었어요.
코드를 다시한번 천천히 살펴보니 제가 짠 코드의 조건은 lottoNumber.count가 7개 미만 일때 랜덤한 숫자가 추가된다 라는 조건이였고
이미 숫자가 6개가 됐음에도 7개 보다 작으니 숫자가 하나 더 추가가 되어 7개가 나타난다는 사실을 알게되었습니다.
그래서 위의 코드를 수정하였습니다!

2022-10-31 00:54 UTC, wongbingg requested changes

2022-10-31 00:54 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +    let lottoNumbers = Array( winningNumbers.intersection(myLottoNumbers))
`Array(` 뒤에 불필요한 공백이 들어가 있는 것 같아요🧐

2022-10-31 00:54 UTC, wongbingg commented on CodeStarterCamp_Week2/main.swift
> +    let stringOverlapNumbers = lottoNumbers.map {String($0)}
보통 중괄호 안에서도 공백으로 띄워서 `lottoNumbers.map { String($0) }` 이렇게 작성하는 컨벤션을 사용합니다🧐
고차함수 축약형을 사용하셨네요 ~! 그렇다면 $0 는 무엇을 의미할까요?

2022-10-31 00:57 UTC, wongbingg commented
수정 요청사항이 잘 반영되었네요. 불필요한 전역변수의 선언도 줄고 깔끔해진 것 같습니다 👏
추가적으로 컨벤션에 대한 사항은 다음 스텝에 적용해보시면 좋을 것 같아요. 고차함수에 대한 질문에 대한 답은 
답글에 남겨주시면 되겠습니다🙏 이번스텝 머지해드릴게요 고생하셨습니다 👍

2022-10-31 00:58 UTC, merged

2022-10-31 14:15 UTC, yijiye commented on CodeStarterCamp_Week2/main.swift
> +    let stringOverlapNumbers = lottoNumbers.map {String($0)}
함수를 축약할때 클로저 표현식으로 이용해서 하는데 이때 사용되는 첫번째 인자로 알고있습니다.
이 구문에서 저는 array 를 string 으로 변환하고자 map을 이용했고 이때 축약하면서 String($0)을 사용했습니다!