week2 [Step2] Owen
yagom-academy/swift-starter-week2 pull request #354
Opened 2022-10-30 08:07 UTC by Duckduck1596

@llingo  
드디어 이주차 두번째 PR을 보내내요 좀 뒤쳐지는 거 같아 더 열심히 해야겠다고 다집합니다! 😳

## 고민했던 점
- 랜덤 숫자를 어떻게 만들어야하지? 고민했지만 모르겠어서 구글링했습니다.
- myLottoNumbers나 lottoNumbes 변수로 지정할 때 변수? 상수? 무엇으로 지정할 지 고민하였습니다.
- 조건문의 경우 repeat-while 문을 사용해 보았는데 while을 사용해도 상관없어 보였습니다.

2022-10-31 04:35 UTC, llingo requested changes
안녕하세요 @Duckduck1596 님!

STEP 1에서 작성해주신 순서도에 맞게 잘 구현해주셨습니다 🎉
- [x] Step 1의 순서도를 코드화하기
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교하기

코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

2022-10-31 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +    lottoNumbes.insert(randomInt)
중괄호 내에서는 줄바꿈을 해주는 것이 좋아보입니다 :)

```swift
repeat {
    let randomInt = Int.random(in: 1...45)
    lottoNumbes.insert(randomInt)
} while lottoNumbes.count < 6
```

2022-10-31 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(overlapNumbers) 입니다!")
구현된 코드를 출력해보면 아래와 같이 `[21, 8]`로 출력이 되는데 `21, 8`의 형태로 출력하려면 어떻게 해야할까요? 🤔

![스크린샷 2022-10-31 오후 1 30 24](https://user-images.githubusercontent.com/94151993/198931661-c406415b-d412-431f-a8eb-8cfa3c68ac4b.png)

2022-11-01 03:21 UTC, Duckduck1596 commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(overlapNumbers) 입니다!")
@llingo 

1. 줄바꿈 완료.

2. 대괄호 없애기 출력되는 번호를 번호만 추출해서 출력합니다. 매우 어지러운 시간이였지만 극복했습니다. 뿌듯해요 ㅎㅎ

2022-11-01 04:56 UTC, llingo approved these changes
@Duckduck1596 님!

이번 스탭 수고하셨습니다 :)
다음 스탭도 화이팅입니다 🎉

---

코멘트 남겨드린 내용 확인하셔서 다음 스탭 진행에서 반영 부탁드립니다 👍

2022-11-01 04:56 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +    }
중괄호 정리가 필요한 것 같아요 😄

2022-11-01 04:56 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +            }
이 부분을 함수로 분리할 수 있을 것 같아요!

2022-11-01 04:56 UTC, merged

2022-11-01 06:09 UTC, Duckduck1596 commented on CodeStarterCamp_Week2/main.swift
> +    }
중괄호 정리면 일자로 쭉 이쁘게 놓으라는 말씀이신가요??

2022-11-01 06:09 UTC, Duckduck1596 commented on CodeStarterCamp_Week2/main.swift
> +            }
밖에서 함수로 분리해서  안에서는 함수로 실행만 하는게 더 깔금해서 그렇게 하는건가요??🙂

2022-11-01 07:03 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +            }
저 부분이 [1, 2, 3]을 1, 2, 3으로 출력하는 기능을 수행하는 부분이라서 따로 분리가 가능하다고 생각했습니다!

```swift
func joined함수() -> String {
  ...
}
```