Week2 [Step3] 졔
yagom-academy/swift-starter-week2 pull request #362
Opened 2022-10-31 14:44 UTC by yijiye

@wongbingg 
이번 미션을 수행하는데 가장 큰 어려움은 문제를 이해하는데 있었던 것 같습니다.
개념을 이해하고 그걸 응용시키는게 너무 어렵네요 😢 

# 어려웠던 점
### 1. Dictionary 이해
dictionary 에 저장한다는 개념을 이해하기 어려웠던 것 같아요.
처음부터 감을 못잡아서 다른 캠퍼분들을 많이 참고했는데 dictionary 를 만들고 출력(?)하는게 없었습니다.
저는 5번 생성해야 한다고 해서 1회차 : 번호, 2회차: 번호 ..... 5회차: 번호 이렇게 값이 출력이 된 후에 거기서 원하는 회차를 찾는 그런식으로 문제를 이해했는데  dictionary  변수를 만들어서 옵셔널 바인딩으로 원하는 회차를 출력하도록 하는게 과제의 핵심이였다는 걸 뒤늦게 알게되었습니다. 이 문제는 dictionary와 optional 개념을 아직 잘 모른다는 뜻인거 같습니다 😢 

# 해결하지 못한 점 & 도움이 필요한 부분 

### 1. 새로운 로또 당첨 번호를 생성하면, 직전회차에 1을 더해 금번 회차를 만들어내는 함수
회차를 key, 생성번호를 value로 잡고 dictionary 변수를 만들었고
1회차 : 1, 2, 3, 4, 5, 6 을 표현하는 건 만들었는데 회차에 1을 더해 금번 회차를 만들어서 새로운 번호를 생성 하는 건 하지 못한것 같습니다.
직전회차와 금번회차를 각각 다른 매개변수로 잡고 해야할까요?

2022-11-01 00:30 UTC, wongbingg commented
안녕하세요 졔 님 step3 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [ ] 딕셔너리 내부타입이 적합한지
- [x] 옵셔널 값의 안전한 추출이 이뤄졌는지

### [아쉬운점]

- 1회차, 2회차, 3회차... 모든 회차의 로또 당첨 번호가 같은 값이 나오네요! 정상적으로 로또번호 생성이 이루어지지 않은 것 같아요 😭
- 딕셔너리의 타입에 Any 를 사용하셨네요, Any 타입은 무엇일까요?

### ✅ 어려웠던 점에 대하여
### 1. Dictionary 이해
과제의 의도를 파악하기 어려웠을 수 있겠네요 ! 
아무래도 처음 접하는 Dictionary 타입 때문일 것 같은데요, 저도 처음에 많이 어려웠답니다😭 


### ✅ 해결하지 못한 점, 도움이 필요한 부분
### 1. 새로운 로또 당첨 번호를 생성하면, 직전회차에 1을 더해 금번 회차를 만들어내는 함수

출력값이 "1, 2, 3, 4, 5, 6" 이라고 해서 딕셔너리에 직접 그렇게 넣지는 않아도 됩니다~! 딕셔너리에 value 값은 [Int] 타입으로 넣고, 키값으로 꺼내올 때, "1, 2, 3, 4, 5, 6" 형태로 변환을 시켜 print 해주어도 될 것 같아요. 

각 회차 별 로또번호를 생성하는 것은 반복문을 활용하면 해결할 수 있을 것 같아요!

2022-11-01 00:38 UTC, wongbingg requested changes

2022-11-01 00:38 UTC, wongbingg commented on Step3/main.swift
> +
이 상수값이 모든 회차의 value 값으로 들어가고 있는데요, 결론은 makeLottoNumbers() 가 한번만 실행되었습니다
저희의 목적은 매 회차별 새로운 로또번호를 생성하는 것이니 어디서 생성해주어야 할지 고민해볼까요?

2022-11-01 00:38 UTC, wongbingg commented on Step3/main.swift
> +
Any 타입은 무엇일까요 ? 여기서 사용하신 이유가 궁금합니다 🧐

2022-11-01 00:38 UTC, wongbingg commented on Step3/main.swift
> +    }
딕셔너리의 key 값은 "1회차" 부터 "5회차" 까지 잘 들어가겠군요! 문자열 보간법을 잘 이용해주셨네요👍
각 회차별 value 값은 현재 어떻게 들어가고 있을까요?

2022-11-01 00:38 UTC, wongbingg commented on Step3/main.swift
> +}
if let 구문을 통해 옵셔널 바인딩을 해주셨군요 👍
하지만 옵셔널 해제된 값 `lottoList` 값이 사용되지 않고있네요 ! 그렇다면 옵셔널 해제를 해준 의미가 있을까요~?🧐

2022-11-01 04:34 UTC, yijiye commented
웡빙의 도움을 받아 문제를 해결해보았습니다!
어떤 부분이 문제였고 어떤식으로 접근했는지 그래서 어떻게 해결했는지 등을 자세하게 기록해봤어요


## 원하는 회차의 로또 당첨 번호를 추출하는 법

### 문제점 1
- 회차는 바뀌지만 로또 당첨 번호는 같은 번호로 계속 출력이 됨.
- 상수로 지정한 부분이 문제였음
```swift
let makeNewLottoNumbers = makeLottoNumbers().map{ String($0) }.joined(separator: ", ")
```
### 위와 같이 지정한 이유는 ?
  - step2에서 만든 로또번호 생성 함수는 [ ] 로 포함하여 출력이 되었기 때문에 처음에 [ ] 없이 출력되는 값을 상수로 표현하면 코드를 입력하는데 단순해 질 것이라고 생각해서 하였음.
  -  **그러나** [] 없이 출력은 되었지만 오히려 한가지 값만 출력되도록 상수로 입력된 문제가 생김 
 
### 👉 해결 방법
- 도움 주신 내용대로 dictionary 값의 value 를 로또번호 생성하는 함수 자체를 입력하였음.
```swift
var lottoDictionary: Dictionary<String, Set<Int>> = [String: Set<Int>]()

func makeLottoByRounds(round: Int) {
    for round in 1...round {
        lottoDictionary["\(round)회차"] = makeLottoNumbers() //로또 번호 출력하는 함수
    }
}
```
- [] 없이 출력하고자 하는 표현은 원하는 회차를 출력하는 함수에서 print 에 적용하였음.

---

### 문제점 2
- 해제된 optional 값인 'lottoList' 는 어디에 사용되었는지? 왜 필요한지? 

### lottoList 를 사용했던 이유
- lottoDictionary 값이 저장된 list 임을 명시해주려고 if let 구문에 입력하였음.
- 근데 따로 지정해준 상수/변수가 없어 무의미 하다고 생각함.

### 👉  해결 방법
- 구글로 검색해보니 Xcode가 제안하는 방법으로 수정하는 것을 알게 됨 
[https://stackoverflow.com/questions/39060215/warning-value-was-defined-but-never-used-consider-replacing-with-a-boolean-tes](url)
- if 구문에서 lottoDictionary 값이 nil 이 아니라면 print 하도록 수정하였음.
```swift
func findLottoRound(roundYouWant: String) {
    if lottoDictionary[roundYouWant] != nil {
        print("\(roundYouWant)의 로또 당첨 번호는 ", terminator: "\(makeLottoNumbers().map {String($0)}.joined(separator: ", ")) 입니다.")
    } else {
        print ("원하는 회차가 없습니다.")
    }
}
```

2022-11-01 04:41 UTC, yijiye commented on Step3/main.swift
> +
Any 는 어떤 타입도 올 수 있다는 의미라 생각하여 any로 지정했습니다.
그런데 결국 value 값으로 불러올 로또번호생성 함수는 Set<Int> 타입이므로 Any => Set<Int> 로 바꿨습니다.

2022-11-01 06:19 UTC, wongbingg commented
## ✅ 원하는 회차의 로또 당첨 번호를 추출하는 법에 대하여

### 문제점 1

잘 해결 해주셨군요 ! 

---

### 문제점 2

현재 방법으로 print 를 해주게 되면, 기존 딕셔너리의 n회차에 해당하는 value 값이 아닌, 새로 만들어진 로또번호가 출력이 되는데요, 이는 문자열 보간법에서 makeLottoNumbers() 를 실행시켜 새로운 로또번호를 만들기 때문인 것 같아요. 딕셔너리에 저장되어 있는 값을 뽑아오려면 어떻게 해야할까요? 

딕셔너리를 만드는 makeLottoByRounds() 실행 후 , lottoDictionary를 한번 출력해보시면 딕셔너리를 확인할 수 있습니다.
현재 회차에 해당하는 로또번호들이 맞는지 확인해보시면 좋을 것 같아요! 

딕셔너리의 사용 방법은 캠핑사이트 week2 의 `01.컬렉션타입` 에 설명이 나와있는데, 보고 이해가 안가신다면 질문 주세요 !

2022-11-02 11:30 UTC, yijiye commented
@wongbingg 
1대1 과외(?) 를 받고 나니 이해가 너무 잘되었어요 감사해요 웡빙 👍 

## Set<Int> 를 Array로 변환 
```swift
func makeLottoNumbers() -> Set<Int> {
    var lottoNumber: Set<Int> = Set<Int>()
    while lottoNumber.count < 6 {
        let randomNumber = Int.random(in: 1...45)
        lottoNumber.insert(randomNumber)
    }
    return lottoNumber
}

// Mark: 로또 번호를 저장하는 dictionary 타입의 함수

func makeLottoByRounds() -> Dictionary<String, [Int]> {
    var lottoDictionary: Dictionary<String, [Int]> = [String: [Int]]()
    for round in 1...5 {
        let makeLottoNumbersArray = Array(makeLottoNumbers()) // 이부분으로 넣어주었습니다!
        let round = "\(round)회차"
        lottoDictionary[round] = makeLottoNumbersArray
    }
    return lottoDictionary
}

```
makeLottoNumbers() 함수는 Set<Int> 타입이었기 때문에 미션에 맞는 출력값이 아니였어요
그래서 set[숫자] 으로 반환되지 않고 [숫자] 로 반환되도록 Array 타입으로 변경하였습니다!
처음엔 전역 상수로 표시해 주었더니 한 번호가 1회-5회까지 반복되는 문제가 있었고
이 변환 되는 부분이 5번 반복이 되어야 하므로 for roun in 1...5 구문 밑으로 넣어주었습니다.
그랬더니 잘 해결 되었어요 😃 
 
## [] 없이 출력

Array 구문으로 바꿔서 앞에 붙는 set 은 제거 했는데 [] 는 제거되지 않아서
원하는 회차를 출력하는 함수 print 구문에 step2 를 진행하면서 배운 고차함수를 적용시켜서 [] 없이 출력하도록 하였습니다!

2022-11-02 13:40 UTC, wongbingg commented on Step3/main.swift
> +    print(lottoDictionary)
현재는 불필요 하겠죠? 다음스텝 부터는 테스트코드도 제거해서 보내주세요 🙏

2022-11-02 13:41 UTC, wongbingg commented on Step3/main.swift
> +// Mark: 로또 번호를 저장하는 dictionary 타입의 함수
마크주석은 `// MARK:` 또는 `// MARK: - ` 이렇게 대문자로 작성해야 발동된답니다

2022-11-02 13:43 UTC, wongbingg commented
수정이 모두 완료되었네요! 고생하셨습니다 👍
추가로 작성해둔 코멘트는 참고만 해주시면 될 것 같아요 ~!
이번 스텝 머지 시키겠습니다 ! 다음 프로젝트도 열심히 해봅시다 💪💪

2022-11-02 13:43 UTC, merged