Week2 [STEP3] owen
yagom-academy/swift-starter-week2 pull request #387
Opened 2022-11-09 03:43 UTC by Duckduck1596

@llingo 
어머니 카페에 코로나 확진자가 나와서  퇴근 후 카페 출근한다고 공부를 잘 못했네여ㅠㅠ 남은 시간 열심히 하겠습니다!!

## 고민했던 점 
1. 어떻게 딕셔너리에 당첨 번호는 저장할 것인가?
2. 어떻게 옵셔널 값을 추출할 때  대괄호를 없앨 건인가?

2022-11-09 04:35 UTC, llingo requested changes
안녕하세요 @Duckduck1596 님! 
2주차의 마지막 STEP이네요 🎉

STEP 3의 미션을 잘 수행해주셨습니다!
- [x] Dictionary의 저장, 추출
- [ ] 요구사항에 맞는 Dictionary 타입
- [x] Optional 값의 안전한 추출
- [ ] 함수를 기능 단위로 분리
- [ ] Swift API Guideline을 바탕으로 네이밍, 컨벤션

코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

2022-11-09 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +} while lottoNumbers.count < 6
매 회차마다 로또 번호가 달라야할 것 같아요! 로또 번호 생성하는 부분을 함수로 분리해볼까요?

2022-11-09 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +func deleteBracket(numbers: Set<Int>) {
함수명은 `Bracket을 제거하라`는 의미로 보이지만 내부 함수의 기능은 로또 번호를 출력하는 것 같아요! 이 부분은 어떻게 수정할 수 있을까요?

2022-11-09 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +func checkOverlapNumbers() {
`overlap을 검사한다`는 함수명을 가지고 있지만 이를 확인하는 기능은 위쪽에 구현하셨던
```swift
let overlapNumbers: Set<Int> = lottoNumbers.intersection(myLottoNumbers)
```
인 것 같습니다! 어떻게 개선할 수 있을까요?

2022-11-09 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +var savedLottoNumbers = [String: Set<Int>]()
> "1회차": [1, 2, 3, 4, 5, 6] 와 같은 Key와 Value를 가집니다. 

요구사항에 맞게 매 회차 로또 번호 배열을 저장할 수 있도록 `[String: [Int]]` 타입이 더 좋을 것 같아요!

2022-11-09 04:35 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +}
현재는 생성된 로또번호가 매 회차 같을 것 같아요! 위에서 코멘트 드렸던 부분을 참고하셔서 수정해볼까요! 👀

2022-11-11 02:33 UTC, Duckduck1596 commented
@llingo  리뷰 반영하여 수정완료 하였습니다!

2022-11-11 05:09 UTC, llingo approved these changes
@Duckduck1596 님!

2주차 미션동안 수고하셨습니다 :)
남겨드린 코멘트 확인하시고 다음 주차도 화이팅입니다 🎉

2022-11-11 05:09 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +func makeLottoNumbers() -> Array<Int>{
`Array<Int>`는 `[Int]`로 표현할 수 있습니다!

2022-11-11 05:09 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +            print("아쉽지만 겹치는 번호가 없습니다.")
사용하지 않는 코드는 주석처리보단 제거하는 것이 좋을 것 같아요 :)

2022-11-11 05:10 UTC, merged