Week2 [step2] mang2
yagom-academy/swift-starter-week2 pull request #390
Opened 2022-11-09 20:42 UTC by mang-2

@llingo 
step2를 드디어 보내게 되었습니다.
진행하면서 고민했던 점, 궁금했던 점들 질문드리고 싶습니다.

 ## 고민했던 점
 - 반복문과 조건문들을 많이 사용해 보려고 시도해 보았습니다.

 ---

 ## 해결이 되지 않은 점
 - 배열을 출력할 때 대괄호를 제외하고 출력할 수 있는 방식이 있다면 어떻게 할 수 있는지 궁금합니다.

 ---

 ## 조언을 얻고 싶은 부분

2022-11-10 03:30 UTC, llingo requested changes
안녕하세요 @mang-2 님!

STEP 1에서 작성해주신 순서도에 맞게 잘 구현해주셨습니다 🎉
- [x] Step 1의 순서도를 코드화하기
- [x] 로또 당첨 번호와 내가 찍은 번호를 비교하기

각 기능별로 함수로 분리해주셔서 재사용성이 증가하고 가독성이 좋아보입니다! 👍 
코멘트 남겨주신 부분에 대한 수정하신 후 디스코드 DM으로 남겨주시면 빠르게 확인 후 Merge 해드리겠습니다!

2022-11-10 03:30 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +    }
`for _ in 1...6`은 어떤 역할을 하나요? 
내부에 while문을 통해 구현하신 부분이 lottoNumbers의 갯수가 6인 것을 확인하고 있는 것 같아요!

2022-11-10 03:31 UTC, llingo requested changes

2022-11-10 03:31 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(equalNumber) 입니다!")
대괄호가 포함된 형태로 출력될 것 같아요!

2022-11-11 21:59 UTC, mang-2 commented on CodeStarterCamp_Week2/main.swift
> +    }
for 문으로 실행하였을 시 6번 반복이 되는데 이때 반복되는 수일 때도 횟수에 포함에 되어 6개의 수보다 적을 때가 있었습니다. 그래서 while 문을 활용하여 lottoNumbers 배열 요소를 이용해 반복을 시도해 보았습니다.
지금 생각해 보니 while 문만 이용하더라고 6개의 수를 다 만들어 낼 수 있었네요..!
아니면 if 문에서 반복되는 수일 때 반복 횟수를 -1 하는 방향도 있었네요.
while 문만 활용한 코드로 수정하겠습니다.

2022-11-13 04:03 UTC, llingo requested changes
@mang-2 님!

코멘트 드린 내용을 잘 반영해주셨습니다!
코드를 확인하다가 STEP 3 내용이 포함되어 있는 것 같아요 확인부탁드립니다 :)

2022-11-13 04:03 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +        }
`control + i`를 통해 한번에 코드를 정리할 수 있습니다 :)

2022-11-13 04:03 UTC, llingo commented on CodeStarterCamp_Week2/main.swift
> +    let equalString = equalNumberString.joined(separator: ", ")
`joined(separator:)`를 사용해주셨군요! 👍

2022-11-13 04:03 UTC, llingo commented on CodeStarterCamp_Week2/step3.swift
> +repeatCreateLotto()
이 부분은 STEP3의 내용인 것 같아요! 확인 부탁드립니다 :)

2022-11-13 18:28 UTC, mang-2 commented on CodeStarterCamp_Week2/step3.swift
> +repeatCreateLotto()
step2 코드 수정 후 코멘트 기다리면서 작성한 step3입니다. 
 pr 수정하면서 step3파일도 같이 commit되면서 올라간 것 같습니다.

2022-11-13 19:10 UTC, mang-2 commented on CodeStarterCamp_Week2/main.swift
> +        }
한번에 코드를 정리할 수 있다는 건 어떤 것을 의미하나요?
if 부분에 control을 이용하는 건가요? 아니면 위 코드 전체를 control+1로 대체하는 건가요??

2022-11-14 05:40 UTC, llingo commented on CodeStarterCamp_Week2/step3.swift
> +repeatCreateLotto()
그렇군요! STEP 3 관련 파일을 따로 저장한 후에 삭제하시고 커밋 주시면 바로 Merge 진행하겠습니다! 😄

2022-11-14 10:08 UTC, llingo approved these changes
@mang-2 님!

이번 스탭 수고하셨습니다! 다음 스탭도 화이팅입니다 🎉

2022-11-14 10:08 UTC, merged