Wee2 [STEP2] game
yagom-academy/swift-starter-week2 pull request #424
Opened 2023-03-01 07:03 UTC by increw

@jsa0224 
솜, 어제 정말 감사했습니다. 덕분에 해결해서 정말 좋았습니다.

### 고민했던 점
- 막상 코드를 완성했지만.... 이렇게 해도 되나 싶다는 생각이 듭니다...
- 많은 경우의 수 때문에 당첨이 언제 될지는 모르겠지만, 당첨됐을 떄 제대로 출력이 될지 의문이 듭니다...
- myLottoNumbers 를 배열의 형태로 해주려고 하였으나 randomNumbers가  Set의 형태이기에 if에서 오류가 발생하여 Set 형태로 해주었습니다.

### 해결되지 않은 점
- 딱히 없었던 것 같습니다.

### 조언을 받고 싶은 점
- 고민했던 점 마지막 부분과 같습니다. if 구절에 쓰려고 할 때 둘다 같은 타입이어야 하던데, 만약의 경우에 하나가 다른 타입이면 그 타입을 같은 타입으로 어떠한 방식으로 변환할 수 있나요?

2023-03-01 12:49 UTC, jsa0224 requested changes
안녕하세요, 개미(@increw)님~🐜
그래도 문제가 금방 해결되어서 너무 다행이었습니다! 

Step 2 코드에 대한 리뷰는 아래 코멘트로 남겨두었어요~

---

## 조언을 얻고자 하신 부분

> 고민했던 점 마지막 부분과 같습니다. if 구절에 쓰려고 할 때 둘다 같은 타입이어야 하던데, 만약의 경우에 하나가 다른 타입이면 그 타입을 같은 타입으로 어떠한 방식으로 변환할 수 있나요?
> 

‘형변환’ 이라는 키워드로 검색하시면 많은 예제들을 찾으실 수 있으실 거예요!
덤으로 형변환을 공부하시면 자연스럽게 옵셔널이라는 개념도 공부하시게 되실 텐데요.
제가 알기론 이번 주차에 옵셔널 개념 또한 공부하는 걸로 알아서 같이 공부하시면 좋을 거 같아요😊

Set와 Array 타입의 비교는 배열의 요소들을 비교하면 되실 겁니다!
for문을 사용하는 방법도 있고, 고차함수를 활용할 수도 있지만 우선 for문으로 해보시는 걸 추천드려요!

2023-03-01 12:49 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func creatRandomNumbers() -> Set<Int> {
'create' 부분에 오타가 존재합니다!

2023-03-01 12:49 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    }
`myLottoNumbers`와 `createRandomNumbers`의 배열 요소가 완전히 똑같아야 아래의 `print()문`이 나오는 거 같아요~

![스크린샷 2023-03-01 오후 9 38 45](https://user-images.githubusercontent.com/94514250/222142151-8e7d797c-6b3a-4fc8-87b3-e1a89bc65864.png)

제가 따로 `createRandomNumbers`의 배열 요소를 `print`해보고 비교한 결과, '4'라는 같은 숫자가 나와도 `else문`을 거치는 것을 확인할 수 있습니다!

배열의 요소를 서로 비교하고 겹치는 숫자를 출력해주는 코드가 필요해보입니다!

2023-03-01 14:39 UTC, increw commented on CodeStarterCamp_Week2/main.swift
> +func creatRandomNumbers() -> Set<Int> {
네, 수정할게요

2023-03-01 14:42 UTC, increw commented on CodeStarterCamp_Week2/main.swift
> +    }
@jsa0224  솜, 말씀하신대로 그럴거 같아요.

그래서 Set의 집합 연산 중 차집합으로 해봤는데 괜찮을까요?

2023-03-01 16:19 UTC, GaeMeee commented
@jsa0224 
솜, 늦은 시간에도 불구하고 답변해주셔서 정말 감사해요. 말씀하신거 수정하였습니다.

2023-03-02 06:38 UTC, jsa0224 commented
수고하셨습니다, 개미님(@increw)!
Step 2는 여기서 마무리해도 될 거 같아요!
다음 스탭도 화이팅입니다!

2023-03-02 06:38 UTC, merged