Week2 [STEP2] redmango1446
yagom-academy/swift-starter-week2 pull request #425
Opened 2023-03-01 14:31 UTC by redmango1446

@jsa0224 
반가워요 솜! 잠깐 일정이 생겨서 드문드문 저녁에 몰아서하려니 고역이네요 ㅠ

#고민했던 점
내가 입력한 번호와 로또 번호가 어떻게하면 일치하는지 알수있을까를 고민했어요
처음엔 입력한 번호 하나하나를 로또번호 컬렉션에 contains를 활용하여 찾아봐야하나 생각해봤는데 Set 컬렉션엔 이미 intersection라는 함수?가 존재하더라구요! A와 B의 교집합을 찾아주는 기능인데 문젠 Set 컬렉션끼리만 사용이 가능해보이더라구요. 제가 매개변수로 주는 내가 입력한 번호는 Array 타입인데말이죠. 그런데 검색해보니 형변환이라는게 있더라구요. 그래서 해봤더니 짜잔! 해결되었습니다!

그외엔 역시 네이밍...쉽지않아요

2023-03-02 06:35 UTC, jsa0224 requested changes
안녕하세요, 레드망고님(@**redmango1446**)~🥭
Step 2 구현해주신 부분 잘 보았습니다! 
전체적으로 잘 구현해주셔서, 프로그램 실행했을 때 나는 오류는 없었어요!

시간이 없으셔서 빠듯하게 구현하신 거 같은데, 코드 상으로는 전혀 안 느껴져서 놀랐습니다!
그만큼 레드망고님이 코딩에 익숙해져가고 있으신 거 같습니다👍

이번에도 네이밍 위주로 코멘트를 남겼습니다!
아래에서 확인해주시면 될 거 같아요!

---

## 고민 하신 부분

> 내가 입력한 번호와 로또 번호가 어떻게하면 일치하는지 알수있을까를 고민했어요
처음엔 입력한 번호 하나하나를 로또번호 컬렉션에 contains를 활용하여 찾아봐야하나 생각해봤는데 Set 컬렉션엔 이미 intersection라는 함수?가 존재하더라구요! A와 B의 교집합을 찾아주는 기능인데 문젠 Set 컬렉션끼리만 사용이 가능해보이더라구요. 제가 매개변수로 주는 내가 입력한 번호는 Array 타입인데말이죠. 그런데 검색해보니 형변환이라는게 있더라구요. 그래서 해봤더니 짜잔! 해결되었습니다!
> 

맞습니다! Array는 배열의 느낌이 강하고, Set는 집합의 느낌이 강해요!
그래서 Set는 같은 숫자가 들어가는 것을 허용하지 않죠!
Set 자체가 집합이다보니, 교집합(intersection) 메서드가 Set 끼리만 가능합니다!

형변환도 찾아보셨군요👏
스스로 찾아보시고 문제 해결하는 부분도 너무 중요한데, 레드망고님은 잘 해내고 있으세요!

## 조언을 얻고 싶으신 부분

> 네이밍...쉽지않아요
> 

맞아요, 네이밍… 참 어렵죠🥲
PR 보내시기 전에 함수에 대한 네이밍을 한국어로 해석해서 한 번 생각해보시면 더 도움이 되지 않을까요?

함수를 만들기 시작했을 때는 이런 기능을 계획하고 보통 네이밍을 정하잖아요?
그런데 거기서 뭔가 오류가 나서 이렇게 저렇게 바꾸다보면 처음 계획했던 기능과는 다른 기능으로 수정되었을 확률이 높아질 거 같아요!
그러다 보면 원래 지었던 네이밍과 기능이 동떨어져 보이기도 하고요🥺

그래서 PR 보내시기 전에 이게 좋은 네이밍인지 충분히 고민해보시고, 보내시는 것도 방법이에요!
(모호하다 싶으시면 저에게 디엠으로 질문 주셔도 돼요!)

2023-03-02 06:35 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(my number : [Int]) -> (matchingResult : Set<Int>, lottoNumber : Set<Int>) {
- check는 뭔가 확인한다? 라는 의미가 강한 거 같아요.
대조한다, 비교한다와 같은 의미의 네이밍이 적절해보입니다! 

- 튜플을 사용해주셨네요! 튜플은 어떤 개념이었나요?

2023-03-02 06:35 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +        matchingNumbers = [0]
여기에는 왜 0을 배열에 넣어주셨나요?

2023-03-02 06:35 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func writeLottoNumbersResult(my number : [Int]) {
write는 '적는다'라는 의미가 강해서 결과를 '보여준다'와 같은 네이밍이 적절해보여요!

2023-03-02 06:35 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +        print("이번주의 당첨번호는 \(outputNumbers.lottoNumber.sorted())입니다")
해당 print문이 아래에서 똑같이 2번 사용되고 있는데, 한 번만 사용할 수 있는 방법이 있을까요?

2023-03-02 14:44 UTC, redmango1446 commented on CodeStarterCamp_Week2/main.swift
> +        matchingNumbers = [0]
matchingNumbers 변수에 멤버가 아예 없으면 로또번호와 일치하는 번호가 없다는 뜻으로도 해석될까봐 1~45사이의 값이 아닌 0을 넣어 반환하게했어요! 출력은 showLottoNumbersResult 함수에서만 되게 하고싶었거든요

2023-03-02 14:47 UTC, redmango1447 commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(my number : [Int]) -> (matchingResult : Set<Int>, lottoNumber : Set<Int>) {
타입의 이름이 따로 지정되어 있지 않은, 개발자 맘대로 만드는 타입
지정된 데이터의 묶음으로 표현할 수 있음....이라고 하네요! 자세한 사용법은 더 찾아봐야겠어요!

2023-03-03 01:43 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(my number : [Int]) -> (matchingResult : Set<Int>, lottoNumber : Set<Int>) {
[The Swift Programming Language - The Basics](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics#Tuples)에 튜플 개념이 상세히 설명되어 있네요! 참고하셨으면 좋겠어요!

2023-03-03 04:58 UTC, jsa0224 commented
레드망고님(@redmango1446) Step 2도 수고 많으셨습니다!
Step 3에서 뵈어요~!

2023-03-03 04:58 UTC, merged