Week2 [STEP 2] yyss99
yagom-academy/swift-starter-week2 pull request #434
Opened 2023-03-02 07:31 UTC by yy-ss99

@jsa0224
😫 점점 과제들이 어려워지네요

 ## 고민했던 점
 ### 함수를 만드는 기준이 뭔가요???
 - 처음에는 같은 번호를 확인하는 함수(compareSameNumbers)와 같은 번호를 출력하는 함수(printSameNumbers)를 합쳐 한 함수로 만들었습니다. 그러다가 서로 다른 기능을 하는거 같아서 나눴는데
 1.  혹시 함수를 만드는 기준이 뭔가요? 기능별로 나누는 건가요? 
 2. 지금 같은 경우는 짧아서 그냥 넣는게 더 나았을까요?🧐
 ---
  
 ### 어떤게 더 나은 코드 일까요??? 
 - compareSameNumbers함수를 처음엔 단순히 for문 비교로 만들었는데 아무래도 더 좋은 방법이 있을 것 같아서 고민하다가 set을 쓰면 좋을거 같아서 set으로도 만들어봤습니다. 
  1. set을 사용한 코드가 더 나은 코드일까요? 제 판단에는 둘다 변수는 하나씩 새로 만들지만 set을 사용하면 for문은 안돌려도 되어서 더 낫다고 생각하는데 솜의 의견은 어떤가요?

 ---

그 외에 어떤 부분을 생각해보면 좋을지 말해주세요!

2023-03-02 14:00 UTC, jsa0224 requested changes
안녕하세요 와이님(@yy-ss99)~😊
슬슬 과제들이 점점 어려워지기 시작하죠…!
그래도 와이님은 너무 잘 해내주시고 계십니다!

Step 3 고지가 멀지 않았네요! 화이팅입니다!

## 조언을 얻고자 하신 부분

> ### 함수를 만드는 기준이 뭔가요???
> - 처음에는 같은 번호를 확인하는 함수(compareSameNumbers)와 같은 번호를 출력하는 함수(printSameNumbers)를 합쳐 한 함수로 만들었습니다. 그러다가 서로 다른 기능을 하는거 같아서 나눴는데
> 1. 혹시 함수를 만드는 기준이 뭔가요? 기능별로 나누는 건가요?
> 2. 지금 같은 경우는 짧아서 그냥 넣는게 더 나았을까요?🧐

함수는 길이에 상관 없이 기능별로 나누는 게 좋다고 생각이 들어요.
지금은 로또를 구현하는 프로그램 뿐이지만, 확장성을 고려해서 다른 숫자게임을 같은 프로그램 내에서 구현해야 한다면 기능을 분리했던 함수들을 재사용할 수도 있습니다!

확장성? 재사용? 아직은 와닿지 않는 개념들이실지도 모르겠습니다.
하지만 개발자의 역량 중 하나가 확장성과 재사용성을 고려하는 것도 있기 때문에, 앞으로 iOS 공부를 하실 때 옆에 따라다닐 키워드들이 될 거예요!

> ### 어떤게 더 나은 코드 일까요???
> - compareSameNumbers함수를 처음엔 단순히 for문 비교로 만들었는데 아무래도 더 좋은 방법이 있을 것 같아서 고민하다가 set을 쓰면 좋을거 같아서 set으로도 만들어봤습니다.
> 1. set을 사용한 코드가 더 나은 코드일까요? 제 판단에는 둘다 변수는 하나씩 새로 만들지만 set을 사용하면 for문은 안돌려도 되어서 더 낫다고 생각하는데 솜의 의견은 어떤가요?

저도 교집합으로 같은 수를 비교하는 함수가 더 좋다는 생각이 들었어요!
현재 다른 함수는 for문을 2중으로 사용하고 계시더라고요. 
이러면 자연스럽게 그 함수는 속도가 느려질 거라고 생각이 들어요.

물론 제가 아래에 2중 for문을 안 쓰는 방법을 코멘트로 남겼지만, 그것을 고려해도 2번째 함수가 간결성이 더 좋아보여요!

---

그 외에 부분은 아래 코멘트에 남겼습니다!

2023-03-02 14:00 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    }
2중 `for문`을 써주셨는데, `contains` 라는 메서드를 사용해보면 `for문`의 양이 줄어들 거 같네요!

2023-03-02 14:00 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +}
저라면 2번 함수가 더 간결해보이고 효율적으로 보입니다!

2023-03-02 14:00 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +}
함수 안의 코드 컨벤션이 대체적으로 개행이 없다보니 가독성이 안 좋은 거 같아요!
```suggestion
func printSameNumbers(lottoNumbers: Set<Int>, myLottoNumbers: Array<Int>) {
    let sameNumbers = compareSameNumbers(lottoNumbers: lottoNumbers, myLottoNumbers: myLottoNumbers)
    
    if sameNumbers.count > 0 {
        var StringSameNumbers = [String]()
        
        for num in sameNumbers {
            StringSameNumbers.append(String(num))
        }
        
        StringSameNumbers.sort()
        print("축하합니다! 겹치는 번호는 \(StringSameNumbers.joined(separator: ", ")) 입니다!")
    } else {
        print("아쉽지만 겹치는 번호가 없습니다.")
    }
}
```
제 코드 컨벤션 스타일이긴 하지만, 가독성을 위해서 위의 함수들도 적절한 개행을 해주셨으면 합니다!

2023-03-03 08:44 UTC, yy-ss99 commented on CodeStarterCamp_Week2/main.swift
> +}
@jsa0224
아예 같은 요소를 확인하는 함수가 있었군요!🥲 contains를 사용해서 for문 한번만 사용하도록 수정해 보고 개행도 넣었습니다.

2023-03-05 06:23 UTC, jsa0224 commented
안녕하세요, 와이님(@yy-ss99)!
현재 수정하신 부분을 확인해보니, 확실히 코드가 간결해지는 것이 느껴집니다!

## 2차 피드백 사항 
- 로또 번호와 자신의 번호를 비교하는 함수가 아직 2개로 구현되어 있으셔서, 하나로 선택해서 구현해주셨으면 합니다!
- return문의 경우도 개행하신 걸로 컨벤션을 맞추는 게 좋아보여요! (컨벤션이 안 맞는 부분이 있습니다.)

2023-03-07 09:35 UTC, yy-ss99 commented
> 

컨벤션 규칙을 설명해주실수 있나요? 저는 함수 안에 변수는 바로 붙여쓰고 그 밖에 for문, while 문도 붙여쓰고 return도 띄어쓴다고 이해해 했는데 맞을까요?? 
수정하는 김에 줄일수 있는 변수도 줄여봤습니다!!

2023-03-07 14:47 UTC, jsa0224 commented
수고하셨습니다, 와이님(@yy-ss99)!
다음 스탭 진행하시면 됩니다!

2023-03-07 14:47 UTC, merged