Week2 [STEP2] Whales
yagom-academy/swift-starter-week2 pull request #440
Opened 2023-03-02 16:26 UTC by WhalesJin

## 내사랑 내멘토님 Som님 @jsa0224 

Step2 로또!!
### 계획
1. 1-45 랜덤숫자 가질 집합 만들기
2. 내가 찍은 번호 집합 만들기
3. 두 집합의 교집합 intersection 프린트하기
4. if문으로 낙첨알리기

​
### 수행 과정
1. 첫 번째 할 일 랜덤숫자 생성 함수 찾기!! 1부터 들어갈거라 저번에 배운 데이터 타입 UInt로 찾아봤습니당
   검색하기 보다는 rand라고 쓰고 아래 나오는 애들을 둘러봤어요
   point! 45 이하라는 상한선이 있어야 한다!
<img width="387" alt="스크린샷 2023-03-02 오후 7 08 52" src="https://user-images.githubusercontent.com/124643545/222484981-8a024901-42f0-4649-b326-3fdc46926c3b.png">
찾았다고 좋아했는데
UInt32는 UInt가 아니라서 안된다길래 Set 타입을 UInt32로 변경!
했는데 떡하니 나오는 [0] 왜죠...? 양순데 왜죠...?
급하게 검색해보니 UInt는 사실 양의 정수가 아니라 부호가 없는 0부터더라고요....

게다가 일단 for문 먼저 돌려볼까싶어서 돌렸더니 
'아니 나는 6개 돌렸는데 왜 5개 나와요...?'
'뭐지 7로 바꿨더니 7개 나오길래 다시 6으로 바꿨더니 6이네..?'
'뭐 잠깐 오류였나보당 아니네 5개 6개 왔다갔다하네'

​자 그러면 문제점 2가지
- 0 제외하기
- 개수 6개 고정시키기 -> 번뜩하고 깨달은 원인!! 집합이라서 + 랜덤이라서!!
랜덤이기에 겹치는 게 나올 수 있는데 집합이라 한 번만 보여줘서 개수가 부족한 것처럼 보인것!

​#### 해결과정
자, 그러면 어떻게 해볼까
일단 바로 넣지말고 넣기 전에 검사하자.
- 랜덤으로 뽑았을 때 0 이면 버리고 0 아니면 넣기
- 집합 안에 있으면 버리고 아니면 넣기

1. if 로 시도 
<img width="821" alt="if로 시도-실패" src="https://user-images.githubusercontent.com/124643545/222486970-041f0e0d-6b66-4e62-b986-7a2c4ade2af0.png">

​2. switch로 시도
<img width="514" alt="switch로 시도-실패" src="https://user-images.githubusercontent.com/124643545/222487110-5e6b6e4e-c993-44e2-bbcf-2dd0a5dd2d57.png">

얘도 안되겠다
반복 횟수가 아니라
원소 개수로 기준을 잡아야겠는데

그러면 while 문으로 가보자
3. while 문으로 시도
<img width="798" alt="스크린샷 2023-03-02 오후 11 05 49" src="https://user-images.githubusercontent.com/124643545/222487341-9f530ee3-7d8e-4fd4-acb4-91b11393cfa0.png">

저거 자꾸 알림 떠서 let으로 변경
아니 근데 let은 상수라 변하지 않는데 왜 let이어도 되는거지?
반복이 도는 동안 계속 새로 만들어줘서 그런건가요?? Som님??

### 다시 수행
2. myLottoNumbers 생성
3. 교집합! 아니 근데 왜 집합 넣는 순서에 따라 오류가 생겼다 없었다 하지? 둘 다 UInt32인데??
<img width="819" alt="내꺼부터 하면 안된다 왜지?" src="https://user-images.githubusercontent.com/124643545/222488589-9c8b5d67-dd82-472c-bd19-64b08c74677d.png">
<img width="570" alt="당첨부터하면 되고" src="https://user-images.githubusercontent.com/124643545/222488627-da7fa3d7-9144-4aa6-bea0-816e78356f99.png">
4. if 문까지 성공!!

## 질문하고 싶은 부분
1. while문 안에서 반복할 때 element라는 랜덤 숫자는 반복마다 바뀔거라 var로 선언을 했는데 바뀌지 않는다고 상수선언인 let으로 하라는 안내창이 계속 뜹니다. 바뀌기 때문에 여러 원소가 들어가는 것 같은데 왜 let일까요?
2. 교집합을 만드는데 순서에 따라 성공하기도 실패하기도 해요. 왜 그러는 걸까요?
3. 미리 여쭤봤던 원소만 빼내는 법을 아직 못 찾았어요ㅠㅠ 검색에 실패했답니다ㅠㅠ 참고할 수 있는 게 있을까요?

2023-03-03 02:38 UTC, jsa0224 requested changes
안녕하세요, 웨일님(@WhalesJin)~🐳
Step 2 프로젝트도 아주 알차게 수행해주셨네요!
저도 웨일님 애정합니다…💕

---

## 조언을 얻고자 하신 부분

> while문 안에서 반복할 때 element라는 랜덤 숫자는 반복마다 바뀔거라 var로 선언을 했는데 바뀌지 않는다고 상수선언인 let으로 하라는 안내창이 계속 뜹니다. 바뀌기 때문에 여러 원소가 들어가는 것 같은데 왜 let일까요?
> 

while문이 반복될 때마다 element 값이 바뀌는 로직으로 보여요! 
그러니 while문 안에서는 값이 바뀌지 않는 상수로 봐도 될 거 같습니다.
’랜덤한 값’이라는 개념 때문에 이 부분이 혼동되시는 거 같아요!

랜덤한 값이라도 while문이 한 번 반복되는 동안은 그 값이 계속 유지가 되겠죠? 그래야 Set에 들어갈 수 있으니까요! (Set도 자기 멋대로 변경되는 값이면 받아주지 않을 거 같아요…ㅎㅎ)

만약 while문 안에서 element의 값을 변경하는 코드가 생기면, 그때는 변수인 var로 설정해야겠죠?

설명이 잘 되었을지는 모르겠네요…! 

> 교집합을 만드는데 순서에 따라 성공하기도 실패하기도 해요. 왜 그러는 걸까요?

![https://user-images.githubusercontent.com/124643545/222488589-9c8b5d67-dd82-472c-bd19-64b08c74677d.png](https://user-images.githubusercontent.com/124643545/222488589-9c8b5d67-dd82-472c-bd19-64b08c74677d.png)

이 부분 말씀하시는 거죠? 사진 첨부 해주시니 이해가 명확하게 되네요!

myLottoNumbers는 Array 타입, lottoWinNumbers는 Set 타입이죠!
둘은 컬렉션 타입이라는 공통점이 있지만, Int, String처럼 완전 다른 타입이라고 보시면 돼요!

Array는 배열, Set는 집합이라는 개념으로 보시면 이해가 쉬우실텐데, intersection은 두 집합의 교집합을 반환하는 메서드라 Set의 메서드입니다!

그래서 lottoWinNumbers로 대입했을 때, 오류가 사라지는 거죠!

(여기서 제가 궁금한 건 매개변수에 Set 타입이 들어가야 되는 걸로 알고 있는데, Array도 실행이 되네요…?)

![스크린샷 2023-03-03 오전 11 35 53](https://user-images.githubusercontent.com/94514250/222617265-9d69f32e-dbd5-40d2-81ad-6fb62e021c30.png)

[intersection(_:)](https://developer.apple.com/documentation/swift/set/intersection(_:)-1zh8f)의 설명 중 일부인데요. 코드 형태를 보면 Set가 들어가야 하는 걸로 보여서... 이 부분을 저도 더 공부한 후에 공유해드릴게요! 
ㅇ0ㅇ! 오늘 저도 모르는 부분 많이 알아가네요!

> 미리 여쭤봤던 원소만 빼내는 법을 아직 못 찾았어요ㅠㅠ 검색에 실패했답니다ㅠㅠ 참고할 수 있는 게 있을까요?
> 

제가 ‘형변환’이라는 키워드는 드렸죠!
그러면 여기서 Set에서 궁극적으로 어떤 타입으로 형변환이 되어야 ‘[]’ 없이 print가 될까요?
잘 모르시겠으면 다시 디엠 주세요!

## 조언 드리고 싶은 부분

### 사라진 함수,,,

이번 프로젝트에 함수로 구현하지 않으셨더라고요!
함수로 구현해보셨으면 좋겠습니다! 

---

자세한 피드백은 아래 코멘트로 남길게요!

2023-03-03 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    let element = arc4random_uniform(45)
오, 저는 `UInt`라는 타입을 안 써봐서 처음 보는 코드네요👍
지금 이 코드로 0~45 사이의 랜덤값이 나와서 0을 제외하는 조건문을 아래 코드로 작성해주신 거 같아요!
`for문`이 시퀀스를 지정해서 그만큼 반복되는 것처럼, 랜덤한 값을 지정한 시퀀스 내에 뽑아주는 함수도 존재합니다!
[random(in:)](https://developer.apple.com/documentation/swift/int/random(in:)-9mjpw) 요 메서드 공부해서 한 번 적용해보시면 아래의 조건문이 필요 없어 보여요!

2023-03-03 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +        if lottoWinNumbers.contains(element) == false {
마찬가지로, `Set`가 집합의 개념이라 같은 수가 원래 들어오지 못함으로 이 조건문도 없어도 될 거 같아요!

2023-03-03 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +if intersection.isEmpty {
`isEmpty` 프로퍼티를 사용해보셨군요👍
`isEmpty`에 대해 설명해주실 수 있나요?

2023-03-03 05:56 UTC, WhalesJin commented on CodeStarterCamp_Week2/main.swift
> +        if lottoWinNumbers.contains(element) == false {
사실 이 부분은 같은 원소인데도 넣는 작업을 해서 원소개수가 줄어드는 문제점 때문에 넣었었는데
생각해보니 그건 for문 일 때 반복횟수를 6으로 넣어서 문제가 된거고 지금은 while로 원소 개수를 6개로 지정해놓은 거니까 문제가 없겠네요!!!! 감사합니다!!!!!

2023-03-03 05:57 UTC, WhalesJin commented on CodeStarterCamp_Week2/main.swift
> +if intersection.isEmpty {
isEmpty란 그 집합이 비어있는지를 묻는 프로퍼티에요! 대답은 비어있다면 true, 원소가 존재한다면 false인 Bool타입으로 나오기 때문에 if의 조건문으로 쓸 수 있습니다!

2023-03-03 05:58 UTC, WhalesJin commented on CodeStarterCamp_Week2/main.swift
> +    let element = arc4random_uniform(45)
이걸로 한번 함수형태로 만들어보겠습니다!!

2023-03-05 10:27 UTC, jsa0224 commented
수고하셨습니다!
다음 스탭도 화이팅입니다!

2023-03-05 10:27 UTC, merged