Week2 [STEP3] gaemee
yagom-academy/swift-starter-week2 pull request #444
Opened 2023-03-03 08:10 UTC by increw

@jsa0224 
솜, 우선은 완성은 시켰습니다... 하지만 문제가 분명히 있을테니 확인하시고 코멘트 부탁드려요.

### 고민했던 점
- randomNumbers 변수를 다른 함수에서 또 호출을 하고 싶었는데 솜의 말씀대로 전역 함수가 있더라구요.. 아직 사용하기에 어렵기에 그냥 함수안에 넣어서 실행했습니다.
- Step2 에서는 randomNumbers를 Set 형태로 하였지만 작업하면서 딕셔너리(회차와 번호)를 출력시에 '값(번호)'에서 Set이 그대로 출력되어 Array로 바꿨더니 해결되었습니다.

### 해결되지 않은 점
- 해결되지 않아서 화면 공유로 조언을 얻고자 하였지만, 여러 시도를 하여 실행이 되기는 했습니다. 단지 맞는지는 잘 모르겠네요...

### 조언을 받고 싶은 점
- 고민했던 점에서 딕셔너리를 출력시에 값 부분에서 Set이 그대로 출력되더라구요. 혹시 Set부분은 나오지 않고 값만 출력할 수 있는 방법이 있을까요?
- 혹시 밖에서 변수를 선언하고 함수에서 변수를 호출 후 값을 넣은 다음에 다시 밖에 있는 변수에 저장하고 싶은데 어떠한 방법이 있나요?

2023-03-05 07:09 UTC, jsa0224 requested changes
안녕하세요, 개미(@increw)님~🐜
제가 다른 업무 중이었어서 그때 도움을 못 드려서 너무 죄송스러웠어요🥺
그래도 스스로 해결해보셨다니 다행입니다!

---

## 조언을 얻고자 하신 부분

> 고민했던 점에서 딕셔너리를 출력시에 값 부분에서 Set이 그대로 출력되더라구요. 혹시 Set부분은 나오지 않고 값만 출력할 수 있는 방법이 있을까요?

이 부분은 아래 코멘트에서 확인하실 수 있습니다!

> 혹시 밖에서 변수를 선언하고 함수에서 변수를 호출 후 값을 넣은 다음에 다시 밖에 있는 변수에 저장하고 싶은데 어떠한 방법이 있나요?

제가 이 부분에 대해 전역변수가 해결방법이 될 수 있다고 잠깐 말씀드렸는데요.
예시를 들어볼까요?

![스크린샷 2023-03-05 오후 3 53 30](https://user-images.githubusercontent.com/94514250/222946781-64c2de03-3a2c-4aa9-a509-0915cc510f07.png)

전역변수를 함수를 통해서 값을 변화시켜보려고 시도를 했는데, print를 통해 출력해보았을 때, 빈 배열 그대로입니다.
바로 ‘함수 호출’을 하지 않아서 값이 변화가 없겠죠?

![스크린샷 2023-03-05 오후 3 55 47](https://user-images.githubusercontent.com/94514250/222946820-e03e5e3e-5b90-4ab9-bf72-21494bd8d361.png)

위 사진과 달라진 부분이 느껴지시나요?
전역변수를 함수를 통해 값의 변화를 주는 코드를 작성하고, 함수 호출을 통해 값의 변화를 주었습니다.
그리고 개미님 코드와의 차이는 반환값이 없다는 것이죠!
우선 지역변수와 전역변수에 대한 구현에 대해 고민해보셔야 할 거 같아요.
저라면 로또번호 배열과 로또번호 배열과 회차가 담긴 딕셔너리를 전역변수로 둘 거 같아요.
다른 함수들에서 쓰임이 많기 때문이죠!

![스크린샷 2023-03-05 오후 4 05 10](https://user-images.githubusercontent.com/94514250/222946847-0a86bbd2-d810-4ee8-9437-6a4bef1f36b0.png)

lottoNumbers라고 전역변수로 설정했을 경우로 제가 잠시 개미님의 코드를 리팩토링해봤는데요!
한 번 보시고 어떤 차이점이 있는지, 어떤 코드가 더 효율적인지 고민해보시는 시간을 가지셨으면 좋겠습니다!

2023-03-05 07:09 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func addRandomNubers() -> Array<Int>{
number 오타가 존재합니다!

2023-03-05 07:09 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    print(lottoList)   // 회차번호끼리 값이 같은지에 대한 확인용
이러한 테스트 코드 같은 경우는 확인 후 PR 보내실 때는 삭제해주세요!

2023-03-05 07:09 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func wantLottoTurn(count: Int, wantTurn: Int, randomNubers: [Int]) {
함수 네이밍이 어색해보이네요!
- want는 원하다 라는 뜻인데, 함수가 원하는 기능을 한다...? 이렇게 해석하니 조금 이상해지죠!
- `wantTurn`이라는 매개변수 네이밍도 적절해보이지 않아요! 
'원하는 회차'라는 네이밍을 지으시기 위해 위 같이 나온 거 같습니다.
매개변수명은 명사형이 적절해보여 이 부분도 다시 고민해보셨으면 좋겠습니다!

2023-03-05 07:09 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +           print("\(wantTurn)회차의 로또 당첨 번호는", randomNubers)
배열 형태로 그대로 출력되더라고요!
프로젝트에서 명시된 대로 String 타입으로 형변환이 필요해보여요!

2023-03-06 01:49 UTC, increw commented
@jsa0224 
답변 주셔서 감사합니다. 확실히 솜이 말씀해주신 전역 변수를 사용하는 것이 더 효율적으로 보입니다.
커밋으로 수정이 필요하다고 말씀하신 부분들은 수정하였고, Array를 .map 매소드를 통해 String으로 변환 시켰으며 joined(separator", ") 를 넣어 번호들을 구분시켰습니다. 혹시 문제점이 더 있다면 커밋 주시면 감사하겠습니다.

2023-03-06 12:22 UTC, jsa0224 commented
수고하셨습니다, 개미님(@increw)!
다음 프로젝트 진행하시면 됩니다!
벌써 3주차네요... 화이팅입니다!

2023-03-06 12:22 UTC, merged