Week2 [STEP3] redmango1446
yagom-academy/swift-starter-week2 pull request #450
Opened 2023-03-04 13:32 UTC by redmango1446

@jsa0224 

#고민했던 점
로또번호를 기록해서 조회 할 수있게끔 만드는거에 더해서 입력한 번호와도 일치하는지 확인시켜주고 싶었어요! 근데 기존의 함수로 진행하려하니 계속 뭔가 꼬이는 느낌이더라구요 그래서 그냥 약간 갈아엎기로 했습니다!

옵셔널 값을 추출하는게 확실히 힘들더라구요 사용한게 옵셔널 체이닝인지 아직 잘 모르겠지만 일단 코드가 돌아가게끔은 했...습니다

네이밍...원래 솜한테 물어보려구 했는데 시간이 늦어서...일단 PR 보냅니다 ㅎㅎ

2023-03-05 08:03 UTC, jsa0224 requested changes
안녕하세요, 레드망고님(@**redmango1446**)~🥭
Step 3도 구현해주신 부분 잘 보았습니다! 
고민하신 부분이 네이밍과 옵셔널 부분인 거 같아 아래 코멘트로 자세하게 남겼습니다! 

그리고 해당 회차별 로또 번호와 자신의 번호를 비교하는 기능도 추가로 구현해주셨군요!
멋지십니다👍

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
>      var number : Set<Int> = Set<Int>()
Set 타입인데 number이라는 변수가 적절할까요?

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func comparisonLotto(my number : [Int], lottoNumber : Set<Int>) -> Set<Int> {
comparison이 비교라는 단어(명사)라 함수명에는 적절하지 않은 거 같습니다!

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func writeLotto(number : Set<Int>) -> Dictionary<String, Set<Int>> {
이부분에 대한 네이밍...! 상당히 고민하셨을 거 같아요.
적는다는 행위보다는 기록하는 행위의 기능을 하고 있네요!
적절한 네이밍으로 수정해보시길 바랍니다!

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +func inquiryLotto(my number : [Int], roundNumber : UInt) {
이 부분도 함수 네이밍 시작이 명사네요!

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    var lottoRecord : Dictionary<String, Set<Int>>? = Dictionary<String, Set<Int>>()
`lottoRecord`를 옵셔널 타입으로 설정하신 이유가 궁금합니다!

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +    if let inquiryResult = lottoRecord?[round]{
if let 👍
이 경우는 옵셔널 바인딩이 적절합니다! 
[옵셔널 바인딩](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics#Optional-Binding)과 [옵셔널 체이닝](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/optionalchaining)의 개념이 혼동되시면 링크 클릭해서 공부해보시는 걸 추천드립니다!

2023-03-05 08:03 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +            print("축하합니다! 검색하신 회차의 로또번호와 겹치는 번호는 \(matchingResult.sorted())입니다!")
이 부분이 배열 형태 그대로 나오더라고요!
프로젝트 예시처럼 String형태로 나오도록 수정해보시면 좋겠습니다!

2023-03-08 12:10 UTC, redmango1446 commented on CodeStarterCamp_Week2/main.swift
> +    var lottoRecord : Dictionary<String, Set<Int>>? = Dictionary<String, Set<Int>>()
앗...사실 저도 잘 모르겠어요 흠흠.... 필요없어 보여서 수정했습니다!

2023-03-09 05:36 UTC, jsa0224 commented
수고하셨습니다, 레드망고님!(@redmango1446)
다음 프로젝트 진행하시면 됩니다!
화이팅이에요!

2023-03-09 05:36 UTC, merged