Week2 [STEP 3] appledayz
yagom-academy/swift-starter-week2 pull request #464
Opened 2023-03-07 09:24 UTC by Appledayz

@jsa0224 som~
STEP3 PR 보냅니다~🧑‍💻
남들이랑 비교하면 안되지만, 재능있는 사람들을 자꾸 보다보니 기분이 참 가라앉네요. 프로그래밍 뿐만 아니라. 나는 잘하는게 없는 것 같고...
그냥 최근 기분 적어봤어요.ㅎㅎ. (여긴 일기장이 아니라고..)

# 👨‍🔬 Step 3: 로또 당첨 번호를 회차별로 저장하고, 확인하자!

네이밍은 항상 어렵군요. 항상 영어로 써야해서 더!

# 1. 고민한 점 및 조언을 바라는 점

조회한 회차가 없는 경우, guard문법을 써보려고 했어요. 그러면  `guard !numbers.isEmpty else` 가 되는데 `'값이 비어있지 않지 않은 경우'` 가 되어버리는거 같아요. 가독성이 if 문이 더 나은거 같아서 guard는 쓰지 않았습니다. **som** 생각은 어떤가요?

2023-03-07 13:53 UTC, jsa0224 requested changes
안녕하세요, 애플데이즈님(@Appledayz)~🍎
Step 3도 잘 구현하셨네요! 

세상에는 재능 있는 사람들이 참 많죠!
저도 코드 스타터 들을 당시에는 저보다 잘하는 분들이 너무 많아서 스스로 자책하는 시간이 많았던 걸로 기억해요.

그래도 코딩이 너무 하고 싶고, 더 배우고 싶다는 생각으로 끝까지 버티니까 과거의 저보다 더 많이 성장했네요!
애플데이즈님도 분명 2주 전의 자신보다 성장해있으실 거예요!
코드 컨벤션과 네이밍도 좋아지셨고, 피드백 수가 줄고 계신 거 느껴지시나요!

남과 비교하는 건 좋은 습관은 아닌 거 같아요! 과거의 자신과만 비교합시다!! 
이런 고민 있으심 언제든 디엠으로 털어놓으세요! 공유해주셔서 감사합니다😊

---

## 조언을 얻고신 싶은 부분

> 조회한 회차가 없는 경우, guard문법을 써보려고 했어요. 그러면 `guard !numbers.isEmpty else`가 되는데 `'값이 비어있지 않지 않은 경우'`가 되어버리는거 같아요. 가독성이 if 문이 더 나은거 같아서 guard는 쓰지 않았습니다. **som** 생각은 어떤가요?
> 

조회할 회차를 round 파라미터에 받으려고 하신 거 같아요!

```swift
if let numbers = lottoNumbersHistory["\(round)회차"] {
        return numbers
}
```

그러면 round 파라미터가 옵셔널 타입으로 설정하셔야 할 거 같은데, 로또가 담긴 set가 왜 옵셔널 타입으로 설정하시려고 했는지 잘 이해가 안 되네요!

이 부분은 텍스트로 말씀드리기가 애매해서 시간되실 때 디코에서 이야기해봐도 좋을 거 같네요!

`if let문`과 `guard문`에 대한 비교는 검색해보셔도 많이 나올 거 같은데요!
한 번 공부해보시고 TIL로 쓰셔도 좋은 키워드가 될 거 같네요😊👍

2023-03-07 13:53 UTC, jsa0224 commented on CodeStarterCamp_Week2/main.swift
> +print(lottoNumbersHistory)
테스트 코드는 삭제해주세요!

2023-03-07 13:53 UTC, jsa0224 commented on CodeStarterCamp_Week2/step3.swift
> +var lottoNumbersHistory = Dictionary<String, Set<Int>>()
History는 역사라는 의미가 강해서 회차별 로또 번호를 담고 있는 딕셔너리 네이밍으로는 적절한 거 같지는 않습니다.

2023-03-07 13:53 UTC, jsa0224 commented on CodeStarterCamp_Week2/step3.swift
> +}
이 부분이군요!
- 애플데이즈님이 의도에 따르면 회차 번호가 옵셔널 타입으로 되어야 하는데, 옵셔널 타입이 존재하지 않네요!
옵셔널이 아닌 파라미터를 옵셔널 바인딩 하고 계시군요...🧐
- 위의 설명드린 내용을 참고로 `if let문`과 `guard문` 중에 어떤 게 적절할지 스스로 판단해보세요!

2023-03-07 13:53 UTC, jsa0224 commented on CodeStarterCamp_Week2/step3.swift
> +        "\(round)회차의 로또 당첨 번호는 \(numbers.description.trimmingCharacters(in: ["[", "]"])) 입니다."
오! 이런 방법으로 구현하신 분 처음 보네요!
신박한 방법이네요👍

2023-03-08 01:44 UTC, Appledayz commented on CodeStarterCamp_Week2/main.swift
> +print(lottoNumbersHistory)
넵

2023-03-08 01:48 UTC, Appledayz commented on CodeStarterCamp_Week2/step3.swift
> +var lottoNumbersHistory = Dictionary<String, Set<Int>>()
넵 기록이란 의미의 record로 바꾸겠습니다.

2023-03-08 01:57 UTC, Appledayz commented on CodeStarterCamp_Week2/step3.swift
> +}
넵 시간되실 때 디코에서 봬요~

2023-03-10 13:31 UTC, jsa0224 commented
수고하셨습니다, 애플데이즈님(@Appledayz)!
다음 프로젝트 진행하시면 됩니다, 화이팅이에요!

2023-03-10 13:31 UTC, merged