Week2 [STEP 3] tag
yagom-academy/swift-starter-week2 pull request #475
Opened 2023-03-09 07:44 UTC by Haesus

@JoSH0318 
Week2의 마지막 Step3입니다!

<h2>고민했던 점</h2>

- 회차별로 저장되는 value의 값을 String형태로 저장을 할지 Set<Int>형태로 저장을 할지 고민했습니다. Set<Int>의 형식으로 저장할 때 코드가 줄어 드는 것 같아 value의 값을 Set<Int>의 형태로 받아 저장하였습니다.
- 회차를 확인할 때 사용되는 `times`변수를 전역함수로 설정했었는데 전역함수를 최대한 줄여보고자 함수 내부에 조건문으로 추가하였습니다.

<h2>조언을 얻고 싶은 부분</h2>

1. 네이밍...어제 이야기를 듣고도 아직 복잡한 것이 있는 것 같습니다. `findLottoTimes`에서 argument label을 `at`으로 주었는데 바람직한 네이밍인지 알고 싶습니다.

2023-03-09 18:25 UTC, JoSH0318 reviewed
@Haesus

전체적으로 네이밍에 신경 더 써주셨으면 좋겠습니다. 🥹
저도 아직 네이밍이 어렵습니다 😀
개발자의 영원한 과제라는 생각이 들어요.
정말 이해가 어렵다면 꼭 DM 주세요! 

---

### 질문 답변

> Q: 네이밍...어제 이야기를 듣고도 아직 복잡한 것이 있는 것 같습니다. findLottoTimes에서 argument label을 at으로 주었는데 바람직한 네이밍인지 알고 싶습니다.

A: 일단 함수명과 parameter name이 명확하지 않아서 argument label을 판단할 수가 없습니다 🥹
이 함수를 예시로 들면
만약 `func checkLottoNumbers(by round: Int)`라고 네이밍했다고 가정해볼게요.
`로또 번호들을 검증하다. round에 따라`라고 해석됩니다.
호출부는 checkLottoNumbers(by: 1) 이런식으로 쓸수 있겠네요.

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +    return saveLottoTimes(lottoNumbers: lottoNumbers)
1. return 값을 없앤 특별한 이유가 있을까요?
2. return 값이 없는데 `return`은 삭제하지 않으셨네요.
3. 이러한 로직이면 요구조건을 만족하기 위해선 `selectLottoNumbers`을 5번 호출해야하는 문제가 있습니다.
기존의 리턴값을 활용해서 원하는 회차만큼 만들어내도록 바꾸면 좋을 것 같네요.

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +var lottoTimes: Dictionary<String, Set<Int>> = [:]
1. 전역변수의 위치는 어떠한 기준인가요?
2. `lottoTimes`는 무슨 뜻인가요? 
로또 타임즈? 로또 시대? 로또 재곱? 로또 경기? 어떠한 뜻도 명확하지 않습니다 🥹

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +        lottoTimes[time] = lottoNumbers
1.  네이밍을 수정해야할 것 같습니다.
2. 이 로직은 count를 올려가며 회차에 대한 랜덤 로또 번호를 넣어주고 있습니다. 
비슷한 역할을 하는 다른 방법은 없을까요?
> hint: for문

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +func saveLottoTimes(lottoNumbers: Set<Int>) {
이곳도 lottoTimes라는 단어가 어색합니다. 🥹

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +func findLottoTimes(at findLottoTime: Int) {
1. `LottoTimes` 👀
2. 만약 `lottoTimes`라는 상수가 있다면 우리는 sequence일 것이다 예상할 수 있습니다. 
또한, `lottoTime`이라는 상수는 자연스럽게 `lottoTimes`의 sequence 하나의 element라고 예상하게 됩니다. 
`lottoTimes`가 [Int]타입이라고 하면 `lottoTime`는 Int 타입이라 예상되는 거죠.

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +    if let lottoTime: Set<Int> = lottoTimes["\(findLottoTime)회차"] {
해당 회차 번호를 뜻해야 할 것 같습니다. 네이밍에 조금 더 신경써야 할 것 같아요.🥹

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +        for lottoNumberCount in 0...lottoTime.count - 1 {
`lottoTime`은 해당 회차의 로또 번호들을 뜻합니다.
그것의 element가 `lottoNumberCount`가 맞을까요?

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +            let a = lottoTime.sorted()[lottoNumberCount]
1. `a`라는 네이밍은 수정해야겠네요.
2. `sorted`는 고차함수 입니다. for loop를 돌 때마다 이 고차함수가 불리겠네요.
for문 밖에서 lottoTime를 sorted()한 상수에 접근하여 사용하는게 좋을 것 같습니다.

2023-03-09 18:25 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +selectLottoNumbers()
5번 반복 호출하는 건 피하는게 좋아보입니다.

2023-03-10 12:46 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +    return saveLottoTimes(lottoNumbers: lottoNumbers)
1. 기존 return 값은 Step2에서 `checkLottoNumbers`에서 사용하기 위해 반환했습니다. 그러나 이번 Step3에서는 `saveLottoTimes`에 값을 저장할 것이기 때문에 필요 없다고 판단했습니다.
2. `return` 삭제했습니다.
3. 5회 실행하라고 적혀있어 5번 호출하는 방향으로 이해를 했습니다. 함수에 Int값을 받아 실행 회수를 추가해보았습니다.

2023-03-10 12:46 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +var lottoTimes: Dictionary<String, Set<Int>> = [:]
1. 전역변수는 코드 시작부분에 들어가는게 코드 가독성이 좋다고 생각합니다. Step2 작성 이후 코드를 작성하다 보니 그대로 아래쪽에 쓴 것 같습니다. 수정했습니다.
2. `lottoTimes`는 로또 회차로 생각하고 작성했습니다. Dictionary의 형태가 회차별로 회차와 회차별 당첨 번호가 들어가 있기 때문에 적절하다고 판단했습니다. 아니면 다른 변수로 `lottoRounds`도 비슷한 의미일 것 같습니다.

2023-03-10 12:46 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +        lottoTimes[time] = lottoNumbers
1. 위 피드백에 의견 드렸습니다.
2. for문을 사용해서 `selectLottoNumbers`에서 Int값을 받아 지정된 회차만큼 반복되도록 해보았습니다.

2023-03-10 12:46 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +        for lottoNumberCount in 0...lottoTime.count - 1 {
1. `lottoNumber`로 수정해보았습니다. 제가 궁금한 것은 for문 안에서 `lottoNumberCount`의 역할은 `lottoTime`의 index를 하나씩 가져와서 출력해주는 역할인데 이런 의미에서 count를 사용했는데 차라리 index를 사용하는 것이 더 좋을까요?

2023-03-10 12:46 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +            let a = lottoTime.sorted()[lottoNumberCount]
1. `sortedLotto`로 수정했습니다.
2. 고차함수가 for문 밖에서 사용되야하는 이유가 있을까요? 검색해보니 오버헤드가 발생할 가능성이 있다는데 그외 다른 이유가 있을까요?

2023-03-10 13:02 UTC, Haesus commented
@JoSH0318 
피드백 주신대로 수정해보았습니다. 
정말 네이밍이 어려운 것 같습니다.

마지막 피드백에서 함수를 여러번 호출하는 것은 피하는게 좋다고 하셨는데 동일한 함수를 여러번 호출하는 것을 피하는 이유가 있을까요?

2023-03-10 14:24 UTC, JoSH0318 requested changes
@Haesus 

네이밍 아직 많이 어려우시죠 🥹
라이브로 말씀드리면 더욱더 와닿는 설명이 가능할 것 같습니다.
Dm 주시면 감사하겠습니다 👍

코멘트 남겼습니다.

---

### 질문 답변

> Q: 반복 호출에 대해서 피하는 이유

A: 이유는 비효율적입니다. 또한, 가독성에 영향을 줍니다.
10번의 로또를 생성해야하는 조건이 있다고 가정해볼게요.
그렇다면 10번을 호출해야겠네요.
그런데 한눈에 10번 호출됐다고 파악하기 어렵죠. 만약 100번이면 어떨까요?
호출이 100번 됐는지 하나하나 세어야겠죠?
또한, 반복되는 코드(호출부)를 100줄을 써넣어야겠네요.🥹

2023-03-10 14:24 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +func findTimesNumbers(by Time: Int) {
1. `Times`라는 단어를 선택할 이유가 있을까요?
만약 `findLottoNumbers(by round: Int)`라고 함수명을 정했다고 가정해볼게요.
해석했을때, `로또 번호들은 찾는다, round에 따라.`정도로 해석할 수 있겠네요.
하지만 지금의 함수명은 "times 번호들을 찾는다, Time에 따라"가 됩니다.

2. parameter name이 대문자로 시작해요.

3. time은 시간, 횟수를 뜻하는 단어인 것 같아요. 때문에 round과 같은 단어가 네이밍이 더 어울려 보입니다.

2023-03-11 08:40 UTC, Haesus commented on CodeStarterCamp_Week2/main.swift
> +func findTimesNumbers(by Time: Int) {
1. `회차의 값(번호)를 찾는다, Int값의`라는 의미로 작성을 해보았습니다. API Design Guidelines에서는 
**Prefer method and function names that make use sites form grammatical English phrases.
```**
x.insert(y, at: z)          “x, insert y at z”
x.subViews(havingColor: y)  “x's subviews having color y”
x.capitalizingNouns()       “x, capitalizing nouns” 
```
처럼 Parameter name이 없을 경우 함수 해석에 제외하고 해석을 해서 제가 만든 코드도 Parameter name을 제외하고 Argument label과 함수만 읽었을 때 해석이 되도록 작성을 해보았습니다. 혹시 제가 잘못 이해를 하고 있는 것인지 궁금합니다.
3. 대문자 수정했습니다.
4. 네 이해했습니다.

2023-03-12 05:08 UTC, Haesus commented
@JoSH0318 
피드백 주신 방법으로 수정해보았습니다.

2023-03-13 04:22 UTC, JoSH0318 commented on CodeStarterCamp_Week2/main.swift
> +func findTimesNumbers(by Time: Int) {
접근하신 방법자체는 너무 좋습니다. 다만 time 이라는 단어가 혼동의 여지가 있습니다.

`findTimesNumbers`를 직독직해 해보시면 더욱더 와닿을거라 생각해요. 
흔히 times가 몇 번째, 또는 몇회를 뜻하기 위해선 `숫자 + times`를 사용한다고 생각해요.
때문에 findTimes라고 하면 뜻이 애매합니다. 숙어로 find time은 짬을내다, 틈을내다 이런식으로 사용되니까요.
또한 times + number는 number의 배수를 뜻합니다.

현재 사용된 단어로 우리가 원하는 몇 회차를 표현하기 위해선 findNumberOfTimes 정도인데 
이것 또한 반복된 횟수 자체를 뜻하기 때문에 정확히 해당 회차와는 뜻이 조금 다르다고 생각합니다.

2023-03-13 06:19 UTC, Haesus commented
@JoSH0318
DM으로 이야기하신 방법으로 수정해보았습니다.

2023-03-13 06:41 UTC, JoSH0318 commented
@Haesus 

고생하셨습니다 ㅎㅎ merge 하도록 하겠습니다.
week3 도 화이팅 입니다 !

2023-03-13 06:41 UTC, merged