Week2 [STEP 2] Im-loki
yagom-academy/swift-starter-week2 pull request #485
Opened 2023-03-15 09:44 UTC by lm-loki

@wonbi92 
step2를 진행하는데 ..많이 어렵네요 ㅎㅎ
순서도 구조는 다시 뜯어고쳐서 만든 함수에 맞췄습니다

 ## 고민했던 점
 ### 주제
 - 이번 과제에서는 컬렉션 set타입의 집합연산 중 하나인 교집합,if -else 그리고 기존의 for-in 구문을 버리고 while 구문을 사용하였습니다
 - 더불어 랜덤 숫자 생성에는 random Int에 대해 조사해서 인용했습니다
 - 제 로또번호와 당첨번호를 비교하기 위해 교집합을 사용했습니다
 - if else는 당첨시 출력 구문과 미당첨시 출력구문을 다르게 하려고 했습니다
 - for in 구문을 버린 이유는 while이 숫자가 6개될때까지 뽑는다라는 맥락상으로 더 적절해서 인용했습니다

 ---

 ## 해결이 되지 않은 점
 ### 주제
 - 지난번에 질문드렸듯이 let intersection: [Int] = myLottoNumbers.intersection(collectLotto)
 - 이문장에서 [Int]값이 포함되어있지 않다는 에러가 떳습니다.
 - 그래서 컬렉션간에 변환이 되는지에 대해 검색했으나 음 mutating이라는 구문을 알게 되었지만 값을 변경할뿐 컬렉션을 변경하는건 아니었습니다
 -"""
func removeDuplication(in array: [Int]) -> [Int]{
    let set = Set(array)
    let duplicationRemovedArray = Array(set)
    return duplicationRemovedArray
}
""" 혹시 이방식이 맞을까요?
 ---

 ## 조언을 얻고 싶은 부분
 ### 주제
 - 아직은 모르거나 오류나는 부분에 있어서 검색하는 능력이 떨어지는 거 같습니다
 - 일단은 지금 공부 방식은 주차 강의를 정독하고 swift language guide를 참조하고 있는데 아직은 많이 부족한거 같네요
 - 혹시 다른 방식으로도 더 많은 정보를 알수있을까요?
 -
 ```

2023-03-16 06:38 UTC, wonbi92 requested changes
@lm-loki 
안녕하세요 로키님!
스탭2 고생하셨습니다.

순서도 수정해주신 부분 봤는데, 만든 함수에 맞추지 마시고 순서도 자체가 함수의 로직을 설명하도록 해주세요. 
함수에 맞추다보니 이전에 작성해주신것보다 오히려 더 로직파악이 어려워진거 같아요 🥲
코드와 순서도를 같이 봐야만 이해되는 것이 아니라, 순서도만 보고도 이해가 가도록해야 합니다.
조금 더 수정해주세요!

> 해결되지 않은 점에 대해

- 코맨트로도 말씀드렸지만, 힌트를 조금 더 드리자면 만들어주신 함수도 하나의 방법이 될 수 있겠네요
- 다만, `intersection`메서드는 Set타입의 메서드라는 것을 생각해보시면 도움이 되실거에요.
- 지금 로또 당첨 번호를 만들어서 반환해주는 함수의 반환값은 Set타입이죠?

> 아직은 모르거나 오류나는 부분에 있어서 검색하는 능력이 떨어지는 거 같습니다
일단은 지금 공부 방식은 주차 강의를 정독하고 swift language guide를 참조하고 있는데 아직은 많이 부족한거 같네요
혹시 다른 방식으로도 더 많은 정보를 알수있을까요?

- 모르는 것을 알기 위해 찾아가는 과정이 쉽지 않죠. 저도 많이 고민하고 찾아보곤 합니다.
- 사실, 말씀해주신 방법이 결국 가장 빠르고 정확한 방법입니다. 공식문서보다 공신력있고 정확한 문서는 없습니다. 공식문서가 가장 중요하죠! 그리고 조금 읽기 힘들긴하지만 스위프트의 공식문서는 꽤나 잘 설명해주고 있답니다! 😁
- 그게 아니라면, 결국 무한 구글링일거 같아요. 관련 키워드를 구글링을 통해 검색 또 검색하는 것이죠!
- 에러 메시지를 해석해서 관련 키워드를 얻거나, 에러 메시지 자체를 검색해보는것도 도움될 때도 있답니다.


로직에 오류가 있기 때문에, 요 오류를 먼저 해결해주셔야 할거 같아요!
그리고, 다음 PR부터는 동작하는 코드로 PR을 보내주세요! 
동작하는 코드를 보내주셔야 제가 정확한 리뷰가 가능합니다!
수정이 완료되면 디엠주세요~
화이팅입니다! 💪

2023-03-16 06:38 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +func collectLotto() -> Set<Int> {
`collectLotto`라는 네이밍이 살짝 어색한거 같아요.
"로또 모으기" 정도로 해석할 수 있을거 같은데 어떤 의미인지는 알겠지만 약간 넘겨짚게 만드는 거 같군요🤔
이 함수는 로또당첨 번호를 만들어서 반환하는 로직이죠?
로직을 잘 설명할 수 있는 함수명으로 한번 수정해볼까요?

2023-03-16 06:38 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +    var numberSet: Set<Int> = Set<Int>()
`numberSet`이란 네이밍 역시 조금 의미가 정확하지 않은거 같아요.
"번호 집합" 정도로 해석할 수 있을거 같은데, 어떤 번호들의 집합인지 모르겠네요 🤔

일반적으로, 스위프트에서는 타입명을 변수명에 넣는 것을 피하는 편입니다. 변수나 함수의 의미를 명확하게 파악할 수 없어서 문맥파악이 힘들기 때문이지요. 타입 자체가 명확한 속성을 설명할 경우 사용할 수 있긴 하지만, 지금은 알맞은 경우는 아닌거 같아요.

이 변수는 로또 당첨번호를 담고있는 변수죠!
이 변수의 속성을 잘 설명할 수 있는 변수명으로 수정해볼까요?

2023-03-16 06:38 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +func checkNumbers(myLottoNumbers: [Int]) {
`checkNumbers`도 명확하지 않은거 같아요.
"번호 체크하기" 정도로 파악되는데, 어떤 번호를 의미하는것이고, 체크라는 동작 자체가 어떤 행동인지 명확하지 않네요.

이 함수는 내 로또번호와 당첨번호를 비교해서 그 결과를 출력해주는 함수네요!
이 함수명 역시 로직을 설명하는 네이밍으로 바꿔봅시다!

2023-03-16 06:38 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +    let intersection: [Int] = myLottoNumbers.intersection(collectLotto)
음.. 일단 PR메시지로 말씀해주신대로 이부분은 현재 제대로 동작하는 코드가 아니네요.
디엠으로 말씀 드렸듯, `intersection`이라는 메서드는 Set타입의 메서드죠? 근데 `myLottoNumbers`는 배열이네요? 🤔
또, `collectLotto`는 무엇인가요? `intersection`메서드의 매개변수 값으로 `collectLotto`를 넣어주신 이유는 무엇인가요?

`intersection`메서드의 매개변수는 어떤 타입인가요?

2023-03-16 06:38 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +        print("축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!")
현재 랜덤한 로또 번호를 뽑았는데, 겹치는 번호는 무조건 `1, 2, 3, 4, 5, 6`인가요?
그리고 겹치는 번호가 1개만 있거나 3개만 있거나 하는 경우는 어떻게 되나요?

`intersection`이라는 상수에는 어떤 값이 담길까요?

2023-03-17 03:10 UTC, lm-loki commented on CodeStarterCamp_Week2/lotto.swift
> +        print("축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!")
갯수가 아닌 내번호가 다른번호여도 나올수있게끔 변경해봤습니다!
intersection상수에는 겹치는 번호가 나올거라 생각해요

2023-03-17 03:11 UTC, lm-loki commented on CodeStarterCamp_Week2/lotto.swift
> +    let intersection: [Int] = myLottoNumbers.intersection(collectLotto)
Set타입으로 변경하여 교집합으로 구할수있게끔 시도했습니다

2023-03-17 03:11 UTC, lm-loki commented on CodeStarterCamp_Week2/lotto.swift
> +func collectLotto() -> Set<Int> {
당첨하다 뜻을 가진 win으로 바꿔보았습니다

2023-03-17 05:40 UTC, wonbi92 requested changes
@lm-loki 
안녕하세요 로키님! 
잘 수정해주셨습니다만, 아직 수정해야할 부분들이 많네요.
코맨트 확인해보시고 다시 수정해주세요!

2023-03-17 05:40 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +    var winningNumberSet: Set<Int> = Set<Int>()
훨씬 좋은 네이밍이군요!
한가지만 추가적으로 말씀드리면, 특별한 몇몇 경우를 제외하고 스위프트에서는 타입명 자체를 변수명에 넣지 않습니다.
```suggestion
    var winningNumbers: Set<Int> = Set<Int>()
```
요정도로 표현하는게 좋겠네요

2023-03-17 05:40 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +    let intersection: Set<Int> = myLottoNumbers.intersection(winLottoNumbers)
`intersection`이라는 변수명은 무엇을 의미하나요?
이 상수는 내 로또번호와 당첨번호를 비교한 결과물이죠?
이를 조금 더 잘 설명해주는 네이밍으로 바꿔볼까요?

2023-03-17 05:40 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +        }
필요 이상의 들여쓰기가 되고 있네요 👀

2023-03-17 05:40 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +        if intersection == intersection {
요 조건문은 무엇을 의미하나요?
제 생각에는 항상 true일거 같은데요..? 🤔

2023-03-17 05:40 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +            print("축하합니다! 겹치는 번호는", intersection, "입니다!")
요렇게 하면 출력될 때 대괄호가 포함된 문자열이 출력될거 같네요 👀
미션의 요구사항대로 대괄호 없이 숫자만 출력되게 해볼까요?

2023-03-20 06:34 UTC, wonbi92 approved these changes
@lm-loki 
안녕하세요 로키님!
잘 구현해주셨습니다. 고생하셨습니다.

아직 전반적으로 네이밍이 조금 어색합니다. 
코맨트 드린 부분 참고하셔서 다음 스탭 진행하시면서 수정해보세요!
고생하셨습니다. 다음 스탭 진행해주세요~

2023-03-20 06:34 UTC, wonbi92 commented on CodeStarterCamp_Week2/lotto.swift
> +        for row in arraySameNumbers {
for문 내의 변수명의 경우, 배열의 각 항목을 나타내는 네이밍을 사용하시는 것이 좋습니다.
```suggestion
        for number in arraySameNumbers {
```

2023-03-20 06:34 UTC, wonbi92 commented on CodeStarterCamp_Week2/main.swift
> +checkWinMyNumbers(winLottoNumbers: winLottoNumbers())
네이밍이 어색합니다. 
win, lotto, numbers 와 같은 단어들이 자주 반복되서 어떤 동작을 하는지 명확하지 않습니다.
호출부에 작성될 때 하나의 문장처럼 읽히게 코드를 작성해주는 것이 좋습니다!

2023-03-20 10:24 UTC, merged