Week2 [STEP 1] Manito
yagom-academy/swift-starter-week2 pull request #531
Opened 2023-07-21 03:18 UTC by ParkSY0919

@Rhode-park  로데님 2추자 Step1 PR 드려요!

## 고민하였던 점:
- 조건이 아래와 같이 명시되어있는데, 코드를 자세히 명시하여 적는 것이 맞는지 고민하였던 것 같습니다
> 코드를 작성하지 않고, 해당 함수의 순서도만을 작성합니다.
> 순서도를 그대로 코드로 옮겼을 때, 원하는 동작이 이루어 질 수 있을 정도로 상세히 작성해봅시다.

## 해결되지 않은 점: 없었습니다!
## 조언을 얻고자 하는 부분: '겹치지 않아야 한다.' 는 조건은 Set로 표현하기 수월하나, Array 타입 역시 표현할 수 있는 것으로 알고있는데 이런 문제들을 마주하면 다양한 방법으로 풀어 보는 것을 추천하시나요??

2023-07-22 00:24 UTC, Rhode-park requested changes
Manito님 열심히 순서도를 그려주셨지만, 순서도의 형식에 맞지 않는 부분들이 다소 있는 것 같습니다.
Flow Chart 또한 나 자신만을 위한 것이 아닌 다른 사람도 보고 쉽게 이해할 수 있어야 합니다.
순서도를 검색해보면, 많은 페이지들에서 각각의 순서도 기호가 무엇을 의미하는지 설명해주고 있습니다.
그 순서도 기호에 따라서 순서도를 작성해볼까요?

순서도 기호에 따라 순서도를 작성하시면 다시 리뷰드리겠습니다.

2023-07-22 11:07 UTC, ParkSY0919 commented
@Rhode-park 
수정하였습니다! 추후 순서도를 작성할 때에는 각 기호의 의미와 맞게 만들겠습니다!

2023-07-24 09:31 UTC, Rhode-park commented
Manito님 순서도를 기호의 의미에 맞게 수정해주셨네요!

순서도만 보아도 코드를 작성할 수 있을 정도로 상세하게 설계할 수 있다는 점은 좋지만, 코드가 아닌 실제 문장을 바탕으로 작성할 수 있도록 순서도를 작성하는게 좋을 것 같습니다.
문법 영향 없이 논리적인 흐름을 만들어내기 위해서입니다.

그 밖에는 무리 없이 잘 만들어진 순서도라는 생각이 듭니다!
실제 문장으로 순서도를 작성해주시면 머지해드리겠습니다!

2023-07-25 07:12 UTC, ParkSY0919 commented
@Rhode-park 수정하였습니다!

2023-07-25 11:07 UTC, Rhode-park commented
머지해드리겠습니다. 다음 Step에서 뵈어요!

2023-07-25 11:07 UTC, merged