week2 [STEP3] doylehong
yagom-academy/swift-starter-week2 pull request #54
Opened 2021-12-23 08:33 UTC by doylehong

@Neph3779 
saveLotto() 함수를 새로 만들어서 makeLottoNumbersSet()함수로 로또 번호가 만들어지면 회차를 키로 로또번호 Array를 value로 dictionary에 집어넣게 코드를 만들었습니다.

전역변수로 lottoDictionary를 만들고 함수들의 parameter로 넣어서 새로 값을 집어넣었는데, 
error: cannot assign through subscript: 'dict' is a 'let' constant  라는 에러가 나와서 inout 을 붙여서 사용했습니다. inout의 기능은 정확히 모르겠습니다.

2021-12-23 12:09 UTC, Neph3779 requested changes
안녕하세요 doylehong님!
step3 진행하시느라 고생 많으셨습니다
제가 남겨드린 피드백을 통해 조금 더 개선해보면 더 좋을 것 같아요!
언제든 모르는 것이 있으시면 dm 주세요~!

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +// STEP 3
PR을 보내는 코드에는 불필요한 주석은 지워주는게 좋습니다!
이전 스텝의 기록은 Git에 잘 보관되어 있으니 걱정하지 마시고 지워주셔도 됩니다!
만약 Git이 익숙하지 않아 이런 보관방법을 택하신거라면 다른 것을 잠시 미뤄두고 Git 공부를 해보시는걸 추천드려요!

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +var lottoDictionary: Dictionary<String, Array<Int>> = Dictionary<String, Array<Int>>()
Dictionary를 선언하는 방법이 여러가지가 있는데 한번 알아볼까요?🧐
지금처럼은 잘 선언하지 않습니다! 
`참고 링크`
https://www.swift.org/documentation/api-design-guidelines/
https://github.com/StyleShare/swift-style-guide

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +    saveLotto(lottoNumbersArray: lottoNumbersArray, lottoDictionary: &lottoDictionary)
& 기호의 의미를 알고 계신가요?
inout에 대한 학습이 이루어지지 않은 상태로 inout을 사용하는 것은 조금 곤란할 것 같아요 😅
언제 내가 알지 못하는 곳에서 에러를 발생시킬지 모르므로.. 
모르는 부분은 최대한 학습을 진행해주신 뒤에 사용해주시는게 좋습니다!

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +    saveLotto(lottoNumbersArray: lottoNumbersArray, lottoDictionary: &lottoDictionary)
제가 바로 알려드릴 수도 있지만.. 
이번 캠프의 목적은 단순히 코딩을 할 줄 알게 된다라기 보다는
앞으로도 수많은 "모르는 것들"을 마주했을때 이를 잘 해결해나갈 수 있는 문제해결능력을 기르는 것이 핵심적인 요소입니다.
애플은 꾸준히 새로운 것들을 만들어 프로그래머들에게 제공할 것이고
우리는 이걸 잘 학습해서 사용할 수 있어야겠죠! 💪
만약 공부를 하다 어려운 점이 있으시면 언제든 dm을 남겨주세요!

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +print("2회차의 로또 당첨 번호는 \(lottoNumbers2[0]) ", terminator: "")
\(lottoNumbers2[0])
이렇게 선언하게 되면 만약 배열에 원소가 없다면 어떻게 될까요?

2021-12-23 12:09 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +var lottoNumbers2: Array<Int> = lottoDictionary["2회차"]!
네이밍이 조금 부적절해보여요..
위에 드린 컨벤션 가이드 링크를 보고 조금 더 개선해볼까요?

2021-12-23 13:13 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +// STEP 3
넵 Git에 익숙하지 않아서 몰랐습니다ㅠ, Git에 대해 더 공부해보겠습니다.

2021-12-23 13:14 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +var lottoDictionary: Dictionary<String, Array<Int>> = Dictionary<String, Array<Int>>()
네 문서 참고해서 수정했습니다.

2021-12-23 13:17 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +    saveLotto(lottoNumbersArray: lottoNumbersArray, lottoDictionary: &lottoDictionary)
swift에서는 파라미터가 기본적으로 상수라 함수내부에서 파라미터의 값을 변경해주기위해 inout을 사용합니다.
inout을 이용하면 파라미터의 값을 복사하는 대신 주소값을 이용하여 변수 내부값을 변경해 주는 기능입니다.
&기호는 변수의 주소값을 나타내는 기능입니다. 이렇게 학습해보았습니다!

2021-12-23 13:19 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +print("2회차의 로또 당첨 번호는 \(lottoNumbers2[0]) ", terminator: "")
암시적 추출 옵셔널 ! 대신 일반적인 옵셔널 ?을 사용하였고 
옵셔널 바인딩을 이용해보았습니다.

2021-12-23 14:54 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +    saveLotto(lottoNumbersArray: lottoNumbersArray, lottoDictionary: &lottoDictionary)
inout은 말그대로 변수의 주소에 접근하는 것이에요
swift는 argument의 값을 변경하는 것을 허용하지 않습니다
왜 그런걸까요? 또 parameter와 argument의 차이는 무엇일까요?

2021-12-24 23:37 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +    saveLotto(lottoNumbersArray: lottoNumbersArray, lottoDictionary: &lottoDictionary)
argument의 값이 함수내부에서 실수로 변하는 것을 방지하는 것 같습니다. argument의 값이 함수내부에서 변경되면 의도하지 않게 변수들의 값이 바뀔수 있습니다.
argument(인수)는 함수로 전달되는 값, parameter(매개변수)sms 함수에서 사용되는 전달된 값을 받는 변수 입니다.

2021-12-26 21:06 UTC, Neph3779 requested changes
안녕하세요 doylehong님!
반영해주신 피드백에 다시 한 번 피드백을 달아드렸습니다
Week3의 PR을 보내주신 것으로 확인되는데 이전 PR이 종료되기 전까지 다음 PR을 보내주시면 안돼요 🥲

단순히 빠르게 미션들을 해나가는건 전혀 중요한게 아닙니다. 지금은 프로그래머로서의 기초를 닦는 단계이고 현업에서 가장 중요한 네이밍, 기본적인 swift의 문법들을 학습하는 단계에요!
너무 조바심 갖지 마시고 기초부터 차근차근 다져나가시면 좋겠습니다~!
이번 스텝에서 아직 해결해야 할 것들이 남아있는 것 같아 이번 스텝은 다시 한번 수정 요청을 드릴게요!
다시 한 번 말씀드리지만 한 스텝에서 오래 머물러있는게 절대 안좋은 것이 아닙니다
어떤 것을 배우고 다음 스텝으로 가야하는지 꼭 생각해주시면 감사하겠습니다! 😁

2021-12-26 21:06 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
>      } while lottoNumbersSet.count < 6
while문과 repeat while문의 차이는 무엇인가요?
여기서는 왜 repeat while문을 선택하셨나요?

2021-12-26 21:06 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
>  }
lotto가 로또 번호들을 담은 배열의 네이밍으로 적절할까요?
lotto 배열이 nil이 아니라는 것이 곧 lotto배열안의 0번째 원소에 접근할 수 있다는 의미일까요? 🧐

2021-12-28 14:35 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
>      } while lottoNumbersSet.count < 6
repeat while문을 쓰면 맨 처음에는 조건을 보지 않고 while문 안의 동작을 실행하고 while문은 처음부터 조건을 확인하고 while문 안의 동작을 실행하는 차이가 있습니다.
근데 제가 .. repeat while문을 선택한 특별한 이유는 없습니다

2021-12-28 14:38 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
>  }
inout 대신에 변수를 맨위에 선언하고 함수의 인자로 전달하지 않고 접근해 보았습니다!

2021-12-28 14:43 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
>  }
lotto 배열이 nil이 아니라는 것은 배열안에 어떤 값이 있다는 뜻이라고 생각합니다. 근데 이때 배열의 0번째 원소가 nil일 경우가 있으니까 . 이 말이 lotto배열안의 0번째 원소에 접근할 수 있다는 의미는 아닌 것 같습니다.  예를 들어 [nil, 1, 2, 3, 4, 5]
근데 제가 neph님 말을 잘 이해한건지 모르겠습니다.ㅠ

2021-12-28 16:19 UTC, Neph3779 commented
> lotto 배열이 nil이 아니라는 것은 배열안에 어떤 값이 있다는 뜻이라고 생각합니다. 근데 이때 배열의 0번째 원소가 nil일 경우가 있으니까 . 이 말이 lotto배열안의 0번째 원소에 접근할 수 있다는 의미는 아닌 것 같습니다. 예를 들어 [nil, 1, 2, 3, 4, 5]
근데 제가 neph님 말을 잘 이해한건지 모르겠습니다.ㅠ

배열 자체가 optional type인 것과
배열이 optional type들을 담고 있는 것은 완전히 다른 이야기겠죠?

doylehong님께서는 배열 자체를 optional로 만들어주신 것이니
원소는 반드시 Int 타입입니다!
하지만! 배열에 원소가 0개인데 [0]와 같이 인덱스로 접근한다면 어떤 일이 생길까요?
그리고 0번째 인덱스가 아닌 1번째 인덱스를 사용하는 이유가 있을까요? 이 분야에서는 대부분 0번째 인덱스부터 활용하는 것이 보통이랍니다

2021-12-28 16:31 UTC, Neph3779 requested changes
안녕하세요 doylehong님!
추가적으로 피드백을 남겨드렸습니다~
그동안 많이 바쁘셨어서 조금 급하게 작업을 해주신 것 같아요 🥲
조금만 더 힘내서 스텝을 마무리 지어볼 수 있도록 해봅시다!

2021-12-28 16:31 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
>      } while lottoNumbersSet.count < 6
repeat while문은 보통 doylehong님이 적어주신 것처럼
한 번은 확정적으로 실행하고 그 뒤에 반복해서 조건을 확인하고 싶을때 사용합니다!
코드는 프로그래머의 가장 훌륭한 의사소통 수단이에요! 이 코드는 왜 이렇게 적혀있을까를 남들이 고민했을때
유의미한 결과가 나오도록 해주세요!

2021-12-28 16:31 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
>  }
다시 한 번 미션의 요구사항을 확인해볼까요? 🥲

![image](https://user-images.githubusercontent.com/67148595/147586045-ace4726c-8242-494a-968a-8cbb751f5c69.png)

2021-12-28 16:31 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +}
이 부분은 무슨 작업을 하신건지 잘 이해가 가지 않는데 설명해주실 수 있으신가요?

2021-12-29 06:29 UTC, doylehong commented on CodeStarterCamp_Week2/main.swift
> +}
step2에서 썻던 코드를 안 바꾸고 for 구문안에 넣어서 사용했습니다. 새롭게 주어진 수만큼 로또 당첨 번호를 만드는 함수를 만들었습니다.

2022-01-27 10:16 UTC, closed without merging