Week2 [STEP 2] Manito
yagom-academy/swift-starter-week2 pull request #542
Opened 2023-07-27 01:44 UTC by ParkSY0919

@Rhode-park  로데님 2추자 Step2 PR 드려요!

## 고민하였던 점:
## 해결되지 않은 점: 
- Step2 코드 리뷰 이전 이미 끝난 것으로 착각하고 Step3를 main으로 옮긴 이후 push 하여서, git reflog 등을 진행하였으나 아직 완벽하게 하지 못하여 main 만 수정하여 올려두었습니다..
## 조언을 얻고자 하는 부분:

2023-07-28 10:05 UTC, Rhode-park requested changes
Manito님 PR 잘 받았습니다!
수고하셨습니다!
자세한 내용은 코멘트 확인 부탁드립니다!

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +}
PR에는 STEP2에 대한 내용만 넣고, 학습내용에 대한 부분은 빼주시길 바랍니다.

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {
[Collection Types - Array Type Shorthand Syntax](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/#Array-Type-Shorthand-Syntax)를 확인해봅시다.
다음과 같은 내용이 있네요:

> Although the two forms are functionally identical, the shorthand form is preferred and is used throughout this guide when referring to the type of an array.

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +    for i in winnerNumbers {
swift에서는 for문에서 `i`만 쓰는 경우는 좀처럼 보이지 않습니다.
[API Design Guidelines - Use Terminology Well](https://www.swift.org/documentation/api-design-guidelines/#use-terminology-well)에 다음과 같은 내용도 나와있네요:

> Avoid abbreviations. Abbreviations, especially non-standard ones, are effectively terms-of-art, because understanding depends on correctly translating them into their non-abbreviated forms.
> > The intended meaning for any abbreviation you use should be easily found by a web search.

어떻게 바꿔보면 좋을까요?

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +            count += 1
`count`를 증가시키는 목적이 무엇일까요?
`step2Solution`을 보면 `count`를 전혀 사용하고 있지 않습니다.
다음과 같이 작성해도 결과물은 같게 나오고 있습니다:

```swift
func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {

//    var count = 0
    var correct = [Int]()

    for i in winnerNumbers {
        if myLottoNumbers.contains(i) {
//            count += 1
            correct.append(i)
        }
    }
    return correct
}
```
그렇다면, `count`가 하는 기능이 무엇인가요?

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +    let winnerNumbers = Array(makeLottoNumbers())
`Set<Int>`를 `Array`로 바꿔주고 있습니다. 멋집니다!
그렇게 바꿔주신 이유를 알 수 있을까요?(단순 질문입니다)

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +    if correctNumbers.count == 0 {
`isEmpty`에 대해서 알고 있으실까요?
`isEmpty`를 사용해보면 코드를 색다르게 변화시켜볼 수도 있을 것 같습니다!(단순 제안입니다)

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +        for i in correctNumbers {
마찬가지입니다. `i`사용 지양해주세요.

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +            }
배열에서 대괄호(`[]`)를 벗기기 위한 적절한 방법을 잘 사용해주고 계십니다. 멋집니다!

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +                print(i, terminator: ",")
그런데, 결과물이 조금 다른 것 같습니다.

```swift
축하합니다! 겹치는 번호는 4, 3 입니다!
```
라는 결과물을 만들어 내야하는데, 다음과 같은 결과물이 나오고 있네요:

```swift
축하합니다! 겹치는 번호는 4,3 입니다!
```

뭔가 띄어쓰기가 조금 다르죠?
요구사항대로 코드를 짜볼까요?

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +func step2Solution() {
네이밍이 아쉽습니다.
`step2Solution`보다는 해당 함수가 가지고 있는 기능을 설명하는 이름이면 더 좋을 것 같습니다.

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +        print("")
```swift
축하합니다! 겹치는 번호는 6,5,3 입니다!
```
와 같은 경우에서 개행을 해주기 위한 코드를 넣어주셨습니다. 멋집니다!
그런데, `terminator`안에 개행 내용을 넣거나, 해당 코드가 다음의 코드 아래에 위치하면 더 읽기 좋을 것 같습니다(개인적인 의견입니다):
```swift
print(i, terminator: " 입니다!")
```

2023-07-28 10:05 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {
함수의 네이밍이 함수의 기능을 적절하게 설명하지 않는 것처럼 보입니다. 내 번호와 로또 당첨번호를 비교하는 혹은 당첨번호에 몇개가 부합하는지 체크하는 함수일 것이라고 생각이 드는데요.
그러한 기능을 좀 더 반영하는 네이밍을 지어볼까요?

2023-07-29 01:34 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +            count += 1
각 배열의 자리를 비교한다고 착각하여 넣었다가 추후 아닌걸 알고 지웠을 때에 미처 지우지 못하였나봐요!
주의하겠습니다!

2023-07-29 01:36 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +    let winnerNumbers = Array(makeLottoNumbers())
lottoMachine 함수의 매개변수 타입이 [Int] 이기도 하며, contains과 append를 사용하기 위하여 바꾸었습니다.

2023-07-29 01:37 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +    if correctNumbers.count == 0 {
알고있습니다! 
적용시킨 코드로 commit하겠습니다!

2023-07-29 01:37 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +        for i in correctNumbers {
넵 주의하겠습니다!

2023-07-29 01:38 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +                print(i, terminator: ",")
넵 수정하여 올리겠습니다!

2023-07-29 01:40 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +func step2Solution() {
주의하겠습니다!

2023-07-29 01:43 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +        print("")
수정하였습니다!
terminator 안에 개행 내용을 넣으라는 말씀이 \n 을 넣는 것이 맞을까요?

2023-07-29 01:44 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {
수정하였습니다! 앞으로 주의하겠습니다!

2023-07-29 01:44 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +    for i in winnerNumbers {
주의하겠습니다!

2023-07-29 01:45 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {
[Int]와 같은 표현으로 축약형태로 표현해야한다는 말씀이신가요?

2023-07-29 01:46 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/Step2.swift
> +}
주의하겠습니다!

혹, 괜찮으시다면 위의 내용이 맞았는지 이야기해주실 수 있나요?

2023-07-29 01:49 UTC, ParkSY0919 commented
@Rhode-park 수정하였습니다!

2023-07-31 08:22 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +}
지금의 상황에서는 적절한 방법으로 3을 출력하고 있다고 생각합니다!

2023-07-31 08:22 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +func lottoMachine(winnerNumbers: Array<Int>) -> Array<Int> {
네. 그게 더 선호된다는 말씀을 드리고자 한 것입니다.

2023-07-31 08:26 UTC, Rhode-park commented on CodeStarterCamp_Week2/Step2.swift
> +        print("")
네 그렇습니다.

2023-07-31 08:36 UTC, Rhode-park commented
리뷰를 많이 반영해주셨습니다. 멋집니다!
몇가지 짚고 넘어가겠습니다.

1️⃣ else문
```swift
if correctNumbers.isEmpty {
    print("아쉽지만 겹치는 번호가 없습니다.")
}
else {
    print("축하합니다! 겹치는 번호는 ",terminator: "")
    for num in correctNumbers {
        if num != correctNumbers[correctNumbers.count-1] {
            print(num, terminator: ", ")
        }
        else {
            print(num, terminator: " 입니다!\n")
        }
    }
}
````
else문을 개행 후 적는 것보다는 다음과 같이 if문의 다음에 적는 것이 바람직해보입니다:
```swift
if correctNumbers.isEmpty {
    print("아쉽지만 겹치는 번호가 없습니다.")
} else {
    print("축하합니다! 겹치는 번호는 ",terminator: "")
    for num in correctNumbers {
        if num != correctNumbers[correctNumbers.count-1] {
            print(num, terminator: ", ")
        } else {
            print(num, terminator: " 입니다!\n")
        }
    }
}
````

2️⃣ 함수명
함수명은 대체로 동사로 시작됩니다.
혹은 어떤 결과물을 만들어내는게 명확할 경우에는 그 결과물(명사)만 작성합니다.
그런점에서 `correctNumberReturner()`보다 좋은 네이밍이 있을 것 같습니다.
더불어 함수가 일치하는 숫자를 반환해주기보다는 일치한 숫자에 따라 문구를 출력하고 있기때문에, `Return`이라는 단어의 사용보다 좋은 표현이 있을 것 같습니다.

수고하셨습니다. 
머지해드리겠습니다.
다음 STEP에서 뵙겠습니다.

2023-07-31 08:36 UTC, merged