Week2 [STEP 3] knumber2
yagom-academy/swift-starter-week2 pull request #543
Opened 2023-07-27 02:30 UTC by cognd98

@Rhode-park 

### 고민했던 점

- 강제 추출이 아닌 if let 구문을 사용하여 값을 안전하게 추출하고자 하였습니다.

2023-07-28 10:13 UTC, Rhode-park requested changes
폴더에는 step3 파일이 있지만, Xcode내에는 step3가 존재하지 않습니다. 그래서 build가 되지 않습니다. 혹시 `Delete - Remove Reference`를 하셨을까요? 해당 파일을 다시 Xcode내로 돌려놓으시면 다시 리뷰드리겠습니다.
돌려놓는 방법은 두 가지가 있을 것 같습니다:
 - 폴더에서 step3.swift파일 xcode로 끌어다놓기
 - 폴더에서 step3.swift파일 삭제 후 xcode내에서 새로 작성하기

화이팅입니다!

2023-07-28 15:12 UTC, cognd98 commented
파일 수정하였습니다.

2023-07-31 17:23 UTC, Rhode-park requested changes
knumber2님 PR 잘 받았습니다! 수고하셨습니다!
전반적으로 코드를 잘 짜주셨으나, 회차와 상관 없이 로또 번호들이 구성되는 것 같습니다.
반복문에 대해서 조금 더 학습해보셨으면 좋겠습니다.
또한, 지역변수와 전역변수에 대해서도 조금 더 학습해보셨으면 좋겠습니다.

2023-07-31 17:23 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +}
while문을 사용해서 6개의 숫자가 들어있는 로또 넘버를 만들어주고 계시는군요! 멋집니다!

2023-07-31 17:23 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    makeLottoNumbers()
`makeLottoNumbers`는 `lottoNumbers`를 구성해주는 함수입니다. 그런데, 이 함수는 총 몇 번 불릴까요? 즉, 몇 번 `lottoNumbers`가 구성될까요?

2023-07-31 17:23 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +        resultNumbers["\(resultNumbers.keys.count + 1)회차"] = lottoNumbers
이렇게 했을 때 `resultNumbers`는 어떻게 되어있을까요? 출력해보셨을까요? 저는 이런 형태가 될 것이라고 생각합니다:

```text
["2회차": Set([45, 10, 42, 35, 27, 13]), "4회차": Set([45, 10, 42, 35, 27, 13]), "1회차": Set([45, 10, 42, 35, 27, 13]), "5회차": Set([45, 10, 42, 35, 27, 13]), "3회차": Set([45, 10, 42, 35, 27, 13])]
```

2023-07-31 17:23 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    let winningNumbers = lottoNumbers.map { String($0) }.joined(separator: ", ")
`lottoNumbers`가 `round`의 영향을 받지 않고 있는 것 같습니다.

2023-07-31 17:23 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    if let checkNumbers = resultNumbers["\(round)회차"] {
`checkNumbers`는 무엇을 위한 상수인가요? `checkNumbers`가 쓰이는 곳이 없습니다.

2023-08-01 03:31 UTC, cognd98 commented on CodeStarterCamp_Week2/main.swift
> +    makeLottoNumbers()
한번만 호출될 것 같습니다. 수정하겠습니다!

2023-08-01 08:51 UTC, Rhode-park commented
많은 것들을 반영해주셨습니다. 멋집니다!
머지해드리기 전에 몇 가지를 말씀드리고자 합니다.

1️⃣ `storeLottoNumbers()`에서 분기처리가 불필요한 것 같습니다.
다음과 같은 방식으로 분기처리 없이도 작성할 수 있을 것 같습니다:
```swift
func storeLottoNumbers() {
    for _ in 0..<5 {
        let time = "\(resultNumbers.keys.count + 1)회차"
        resultNumbers[time] = makeLottoNumbers()
    }
}
```

2️⃣ `resultNumbers`를 출력해보라고 말씀드린 것은 딕셔너리가 제대로 만들어졌는지를 확인하기 위해서였습니다.
프로젝트 내에 `resultNumbers`를 출력하는 코드를 넣으실 필요는 없습니다!
단지, 딕셔너리가 회차별로 서로 다른 로또 번호가 들어가지 않고, 같은 번호가 반복해서 들어가기 때문에 확인을 해보라는 말씀을 드린 것입니다.

수고 많으셨습니다. 머지해드리겠습니다!

2023-08-01 08:51 UTC, merged