Week2 [STEP 3] Manito
yagom-academy/swift-starter-week2 pull request #548
Opened 2023-07-31 16:52 UTC by ParkSY0919

@Rhode-park  로데님 2추자 Step3 PR 드려요! 너무 늦은 시간에 올려 죄송합니다!

## 고민하였던 점: 없습니다!
## 해결되지 않은 점: 없습니다!
## 조언을 얻고자 하는 부분:  없습니다!

2023-08-01 08:33 UTC, Rhode-park requested changes
마니또님 PR잘 받았습니다.
딕셔너리에 회차별로 다른 로또 번호들이 들어가있습니다. 멋집니다!
딕셔너리의 value를 잘 언래핑해주고도 계십니다. 멋집니다!
기능분리와 네이밍에 조금 더 신경 쓰고, 결과물만 요구사항만 일치시키면 좋을 것 같습니다.
이번 STEP도 힘내봅시다!

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +func lottoDicWithSeparator() {
단순히 대괄호만 없애는 기능을 하고 있는 함수가 맞나요? 하나의 함수에는 하나의 기능만이 있어야합니다. 지금은 로또 숫자들을 만들어서 할당해주고, 그 결과물을 가지고 대괄호를 없애기도 하고, 대괄호를 없앤 결과물을 딕셔너리에 key-value형태로 넣어주는 기능까지 하고 있는 것 같습니다. 

또한, 여러가지 기능을 가지고 있기 때문에 함수명이 그 기능들을 다 설명해주지 못하고 있다고 생각합니다.

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    let lottoWithJoined = lottoWithMap.joined(separator: ",")
두 번에 걸쳐서 두 개의 상수를 만드는 방법 외에도, 한 번의 과정으로 하나의 상수를 만드는 방법도 있을 것 같습니다!

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    lottoDic[countOfLotto] = lottoWithJoined
이렇게 하게 되면, 어떤 key와 value를 가지게 될까요?
요구사항에는 다음과 같이 나와있습니다:
> - 회차와 Lotto번호들을 저장하는 Dictionary 타입의 변수를 생성합니다.
>     - `"1회차": [1, 2, 3, 4, 5, 6]` 와 같은 `Key`와 `Value`를 가집니다.

제가 보기엔, 이 방법대로면 다음과 같은 딕셔너리가 생성될 것 같습니다:
> [3: "41,17,33,26,13,5", 5: "41,21,27,14,19,42", 2: "24,17,36,40,19,30", 1: "2,45,25,27,4,9", 4: "14,36,37,20,4,6"]

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +}
for문을 잘 사용하고 계십니다. 멋집니다!
만약에 와일드카드(`_`)를 사용하지 않고 다음과 같이 반복문을 작성하고자 한다면, 어떻게 함수를 구성할 수 있을까요?(단순 질문입니다)

```swift
for time in 1...5 {
    //여기에 어떤 함수가 들어가야할까요?
}
```
혹은 이렇게 한다면, 어떻게 함수를 구성할 수 있을까요?
```swift
for time in 0..<5 {
    //여기에 어떤 함수가 들어가야할까요?
}
```

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +}
기능분리가 잘 되어있습니다. 멋집니다!

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
>      }
딕셔너리의 value값을 잘 언래핑해주고 있습니다. 멋집니다!

2023-08-01 08:33 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +printOutWinningNumbers(4)
결과물은 다음과 같이 나옵니다:
```text
4회차의 로또 당첨 번호는 14,36,37,20,4,6 입니다.
````

다음과 같이 번호들 사이에 띄어쓰기 한 칸씩이 필요할 것 같습니다:
```text
2회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다.
```

2023-08-02 04:39 UTC, ParkSY0919 reviewed
수정하였습니다!
단순질문파트는 금방 수정하여 올리겠습니다!

2023-08-02 04:39 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/main.swift
> +func lottoDicWithSeparator() {
'하나의 함수에는 하나의 기능' 명심하겠습니다!

2023-08-02 04:39 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/main.swift
> +    let lottoWithJoined = lottoWithMap.joined(separator: ",")
수정하겠습니다! 알려주셔서 감사합니다!

2023-08-02 04:39 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/main.swift
> +printOutWinningNumbers(4)
수정하였습니다!

2023-08-02 04:39 UTC, ParkSY0919 commented on CodeStarterCamp_Week2/main.swift
> +    lottoDic[countOfLotto] = lottoWithJoined
key 값의 타입을 String으로 수정하여 푸시하겠습니다!

2023-08-02 04:51 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    lottoDic[countOfLotto] = lottoWithJoined
value를 String으로 잡아주셨는데, value가 String이 맞을까요? 요구사항을 보면 콜렉션 타입이 들어가야할 것 같습니다.

2023-08-03 06:55 UTC, Rhode-park commented
Manito님 수고하셨습니다!

다만, 딕셔너리에 value를 넣어줄 때, [Int]형태로 넣어줬으면 어떨까 싶습니다.
```text
["1회차": Set([31, 7, 26, 42, 45, 30]), "2회차": Set([44, 40, 11, 28, 24, 45]), "4회차": Set([20, 38, 45, 21, 24, 1]), "3회차": Set([45, 9, 19, 33, 23, 25]), "5회차": Set([3, 23, 1, 15, 9, 28])]
````
출력해보면 이렇게 나오는데, 
```text
"1회차": [1, 2, 3, 4, 5, 6]
````
이 결과물과는 조금 다른 것 같습니다.
확인 해보셨을까요 혹시?

그래도 정말 정말 수고하셨습니다. 머지해드리겠습니다!

2023-08-03 06:56 UTC, merged