Week2 [STEP 3] 아담
yagom-academy/swift-starter-week2 pull request #552
Opened 2023-08-03 16:13 UTC by yawoong2

@Tediousday93 
안녕하세요 로웬!
드디어 Week2의 마지막 스텝입니다! 🙌

 ## 고민했던 점
 ### 이름짓기
 - 언제나 그렇지만, 이름짓기는 정말 많은 고민이 필요하네요.🧐

 ### 로또 당첨번호 생성과, 특정 회차 당첨번호 조회를 분리
 - 로또 당첨번호 생성 조회를 하나의 함수에 작성할 지, 분리하는게 좋을지 고민하다가 분리하여 작성하였습니다.

 ---

 ## 해결이 되지 않은 점

 ---

 ## 조언을 얻고 싶은 부분
 ### Optional
 - Optional 처리된 값을 Unwrapping 할 때, 시기적절하게 사용하는 법을 알고 싶습니다.
 ```

2023-08-04 00:13 UTC, Tediousday93 requested changes
안녕하세요 아담님 step3 고생하셨습니다! 👏

스텝 요구조건이 완벽히 지켜지지 않아 조금 아쉬웠습니다🥲
아래 코드에서도 코멘트를 확인해주시고, 수정이 완료되시면 디스코드로 머지 의사를 알려주세요 ☺️

### [수행한 점]
* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기
---
- [x] 딕셔너리 내부타입 적절하게 설정하기
- [x] 옵셔널 값을 안전하게 추출하기
- [x] Step2 에서 사용한 함수 재사용하기

</br>

### ✅ 고민했던 점
* 네이밍을 많이 고민하신게 느껴지네요. 저도 항상 고민되는 부분이기도 하고 또, 영어가 참 어렵다고 생각이 듭니다..🫠
* swift naming 관련된 글을 검색해 읽어보시는 것도 좋습니다!
* 언제나 하나의 함수는 하나의 기능만을 담당하는 것이 좋습니다. 분리 많이 많이 해주세요~! 👍

</br>

### ✅ 조언을 얻고 싶은 부분
Swift의 핵심 기능인 옵셔널은 사용 방법이 아주 다양합니다. 
하지만 공통적으로 옵셔널 타입의 값을 사용할 때 unwrapping을 해야 옵셔널 내부의 값을 사용할 수 있습니다. 옵셔널 타입은 값이 없을 수도 있다는 것을 내포하고 있기 때문에 `Optional`이라는 박스를 열어서 안을 확인해봐야 하는 과정이 필요한 것이죠! 
따라서 안전하게 언래핑하는 옵셔널 바인딩을 통해 값을 추출하여 사용합니다.

* 언래핑 시기에 관해서..
물론 언래핑을 하지 않고 활용하기도 합니다만, 지금처럼 옵셔널 내부의 값을 직접 사용해야하는 경우에는 꼭 언래핑해서 사용해야 합니다!
(print 함수에 옵셔널타입 값을 전달해보면 `Optional(value)`의 형태로 출력이 된답니다.)
정해진 언래핑 시기는 따로 없는 것 같네요 😅

</br>

### 다음 미션 참고사항
* **주석**
현재 코드에서 자주 주석을 사용하신게 보입니다.
주석은 코드 사이사이에 사용하지 않습니다. 이미 네이밍, 컨벤션을 통해 주석 없이도 충분히 이해 가능한 코드를 작성해주고 계세요!
다음 미션부터는 주석을 사용하지 않도록 해봅시다 💪
(혹시 step 주석을 남기고 싶은 경우, MARK 주석을 활용해볼 수는 있습니다.)

2023-08-04 00:13 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +}
딕셔너리에 회차별 로또번호를 저장하는 함수를 잘 만들어주셨네요 👍
하지만 요구조건과 조금 다른 것 같습니다. 🤔

1. 로또 당첨 번호 생성 함수를 `호출할 때마다 저장`을 하도록 바꾸려면 어떻게 해야할까요?
2. 현재 회차별로 다른 로또번호를 갖고 있지 않습니다. `LottoNumbersStore`에 한 번만 번호를 생성하고 같은 번호를 5회 딕셔너리에 저장하고 있네요. 💭

저장하는 기능만을 하는 함수로 정의하고 기존의 함수를 호출했을 때 생성된 번호가 저장될 수 있도록 수정해봅시다!

2023-08-04 00:13 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +func readLottoNumbers(when round: Int, from wholeTimesLottoNumbers: [String: [Int]]) {
호출할 때 when 뒤에 바로 정수가 들어가면 어떤 파라미터인지 알 수 없을 것 같아요.
이 경우에는 전달인자 레이블을 없애도 괜찮아 보입니다.
```suggestion
func readLottoNumbers(from wholeTimesLottoNumbers: [String: [Int]], round: Int) {
```

2023-08-04 00:13 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +    if let selectedLottoNumbers = wholeTimesLottoNumbers["\(round)회차"] {
Dictionary의 value를 옵셔널바인딩을 통해 안전하게 추출해주셨네요 👍
네이밍에 신경쓰신게 느껴집니다 👏

2023-08-04 00:13 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +let fiveTimesLottoNumbers: [String:[Int]] = makeFiveTimesLotto()
요구조건은 Dictionary type `변수`를 생성하는 것인데 현재는 상수로 생성해주셨네요!
위의 코멘트대로 함수를 수정하면 자연스럽게 변수로 바꾸게 되실 겁니다 👀

참고로 Dictionary와 같은 collection type은 상수로 생성하면 key-value 쌍(또는 element)을 추가/삭제 할 수 없습니다 💭

2023-08-04 00:13 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +    let LottoNumberStore: [Int] = Array(makeLottoNumber())
회차 조회를 할 때는 로또번호가 오름차순 정렬되어있는 편이 보기 편하지 않을까요?!
Set의 숫자들을 정렬하는 메서드를 찾아보시고 어떻게 적용했는지 코멘트 달아주세요 🙏

2023-08-06 13:36 UTC, yawoong2 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +}
문제를 다시 읽고 요구조건을 잘못 이해하고 있었다는 점을 확인하여 다시 작성했습니다!

2023-08-06 13:57 UTC, yawoong2 commented on CodeStarterCamp_Week2/LottoWinningChecker.swift
> +    let LottoNumberStore: [Int] = Array(makeLottoNumber())
Swift 공식문서를 읽어보니. Set에 저장된 값을 정렬하는 메서드는 sorted()가 있었습니다.
다만, sorted()를 사용하려면 집합연산 메서드를 사용한 뒤 정렬 가능합니다.
당첨번호가 저장된 Set과 빈 Set을 선언하여 oddDigits.union(evenDigits).sorted()로 정렬이 가능합니다.

하지만 저는 당첨번호의 컬렉션 타입을 배열로 바꿔서 값을 정렬하는 방향으로 코드를 수정하였습니다!

2023-08-07 07:51 UTC, Tediousday93 commented
벌써 주석까지 다 제거해주셨군요!
가독성이 좋아진 것 같습니다 👍

요구사항이 모두 잘 반영되어 있네요 👏👏👏
고생하셨습니다.

다음 스텝도 화이팅입니다!

2023-08-07 07:51 UTC, merged

2023-08-07 08:10 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoGenerator.swift
> +    sortedLottoNumbers = Array(lottoNumbers).sorted()
Set 타입의 인스턴스 메서드 `sorted()`는 반환 타입이 Array이기 때문에
별도로 변수를 만들어주지 않고 바로 반환해주셔도 괜찮습니다!
```suggestion
    return lottoNumbers.sorted()
```

2023-08-07 08:10 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoGenerator.swift
> +}
잘 바꿔주셨네요 ! 👍

다만 함수 네이밍과 상수 선언이 중복되는 감이 있어서 아래 처럼 바꿔보셔도 좋을 것 같습니다☺️
```suggestion
func save(lottoNumbers: [Int]) {
    let roundNumber = lottoNumbersDictionary.count + 1
    lottoNumbersDictionary.updateValue(lottoNumbers, forKey: "\(roundNumber)회차")
}
```

2023-08-07 08:10 UTC, Tediousday93 commented on CodeStarterCamp_Week2/LottoGenerator.swift
> +func makeLottoNumbers() -> [Int] {
이제 반환값을 활용하지 않으니 -> [Int]는 없어져도 괜찮겠네요 👀