Week2 [STEP 2] QL
yagom-academy/swift-starter-week2 pull request #562
Opened 2023-08-24 09:31 UTC by slowkuma

@Tediousday93
Round 2 의 Step 2 진행 결과 입니다.

## 고민했던 점
### `myLottoNumbers` 를 변수(var) 로 하는 기준으로 알고리즘 구현
- 교집합 함수를 실행하고 반환 값을 다시 대입 하는것으로 변수에대한 동작을 구현 하였습니다.

---

## 해결이 되지 않은 점
- 없습니다.

---

## 조언을 얻고 싶은 부분
- 없습니다.

2023-08-24 14:35 UTC, Tediousday93 requested changes
안녕하세요 QL님 step2 고생하셨습니다 ☺️
빠르게 보내주셨네요 👍
너무 잘해주셔서 중요한 코멘트는 적습니다 .. 😅

### 수행 내용
* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기
---
- [x] Step1의 순서도를 바탕으로 `로또 당첨 번호`를 생성하는 함수 생성하기
- [x] 내가 찍은 번호를 변수에 할당하기
- [x] 찍은 번호와 로또 당첨 번호의 겹치는 숫자 확인하는 함수 생성하기
- [x] 출력 값이 요구사항과 일치하는지

</br>

### ✅ 고민했던 점

**겹치는 숫자 확인하는 함수**
* Set의 집합연산을 활용하여 겹치는 숫자를 정확히 구해주셨습니다 👍
* 고차함수를 이미 활용하실 줄 아시는군요! 나중에 학습 내용으로 한 번 더 만나게 되실겁니다. ☺️
* 배열을 출력할때 괄호를 잘 제거해주셨습니다 👍

2023-08-24 14:35 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +}
`round2Step2Main` 함수에 기능이 여러가지가 있는 것 같네요!
이전 스텝처럼 기능별로 분리해주시면 좋을 것 같습니다 ☺️

2023-08-24 14:35 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +        .map( String.init )
오 처음보는 문법이네요!
이니셜라이저 파라미터에 전달되는 것이 명시되어있지 않은데도 암시적으로 전달이 되나보네요..?
설명 부탁드려도 될까요?

저는 고차함수 사용할 때 후행 클로저를 활용하는 편입니다.
```swift
.map { String($0) }
```

2023-08-24 14:35 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +    } while result.count < 6
repeat - while 반복문을 활용해주셨군요 👍

2023-08-24 14:35 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +fileprivate func getLottoNumbers() -> [Int] {
이 함수도 배열을 가져오는 것이 아니라 새로 만들어주기 때문에 `make`로 하면 어떨까요?!

2023-08-24 15:24 UTC, slowkuma commented on CodeStarterCamp_Week2/Round2Step2.swift
> +        .map( String.init )
Swift 타입추론에 따른 agrument 전달입니다.

이 구문의 경우 후행 클로저 가 아니라
map() 에 agrument 로 closure 를 전달 한것이 되고
map 은 `(Self.Element) -> T` 를 받음으로서
String 의 `init<T>(_ value: T) where T : LosslessStringConvertible` 
를 전달하면 같은 type 의 closure 가 됨으로 추론 되어 바로 동작 하게 되는 것 입니다.

![closure](https://github.com/yagom-academy/swift-starter-week2/assets/7185156/eb48141f-f490-4164-a85d-5968176c45bb)

이는 예시와 같이 형식이 맞으면 축약 하여도 동작하며
map, reduce 등등 뿐만 아니라 closure 를 전달 받는
모든곳에서 적용 가능 한것으로 알고 있습니다.

Swift 의 강력한 타입 추론 덕분 이지요.

2023-08-25 04:22 UTC, slowkuma commented on CodeStarterCamp_Week2/Round2Step2.swift
> +}
검증부분과 교집합구하는 부분을 분리 하였습니다.

2023-08-25 04:23 UTC, slowkuma commented on CodeStarterCamp_Week2/Round2Step2.swift
> +fileprivate func getLottoNumbers() -> [Int] {
변경 하였습니다.

2023-08-25 04:25 UTC, slowkuma commented
@Tediousday93
지적 해 주신 내용을 적용하였으니 확인 부탁 드립니다.

2023-08-25 06:42 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +        .map( String.init )
정확히 알고 계시는군요!! 👍
평소에 사용하지 않다보니 후행클로저로 빼지 않아도 클로저만 전달할 수 있다는 점을 놓치고 있던 것 같네요. 
설명 감사합니다 ☺️

2023-08-25 06:44 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Round2Step2.swift
> +fileprivate func getLottoNumbers() -> [Int] {
QL님 만의 이유가 있다면 사용하셔도 무방하답니다~!
저는 평소에 get을 다른 객체나 콜렉션에서 가져오는 인터페이스에 사용한다고 생각하고 있었기 때문에 말씀드린 것이었어요!
지금처럼 이유를 말씀해주시면 무조건 제 의견을 따라가지 않으셔도 좋습니다.ㅎㅎ

2023-08-25 06:49 UTC, Tediousday93 commented
QL님 코드를 보면서 저도 배워가는 것이 많네요!
이번에도 친절하고 자세한 설명 감사드립니다 ☺️
주석도 함수의 summary 제공하는 방법으로 사용해보셨네요!! 멋있습니다 👍

예외 처리에 관한 내용은 추후 학습 자료에서 보실 수 있기 때문에 따로 피드백 드리지 않겠습니다~~

고생많으셨습니다! 다음 스텝도 화이팅입니다 💪

2023-08-25 06:51 UTC, merged