Week2 [STEP 3] Say
yagom-academy/swift-starter-week2 pull request #578
Opened 2023-08-29 10:31 UTC by SAY-Hong

@Tediousday93

안녕하세요 로웬!
Step3 PR입니다😆

## ✍️코드 작성
* allLottoNumberStorage -> 지난 회차의 로또 번호 정보를 저장하는 딕셔너리   

* save(thisWeekLottoNumbers: Set<Int>) -> 이번 주의 로또번호를 저장하는 함수

* findWhatLottoNumbers(week: String) -> 회차 수를 매개변수로 받고 해당 회차의 로또 번호 정보를 출력하는 함수.  
=> if let을 이용해서 원하는 회차(키)에 맞는 allLottoNumberStorage value 옵셔널 값을 안전하게 추출하는 코드를 작성했습니다.
    
## ✍️코드 작성 시 고민한 부분  
1. save함수의 위치  
    step2에서 작성한 로또 당첨 번호 생성하는 함수를 호출할 때마다 딕셔너리에 저장하라고 그러길래 일단 step2에서 작성한 generateRandomNumbers() 안에서 save 함수를 호출했습니다.

2023-08-29 19:01 UTC, Tediousday93 requested changes
안녕하세요 세이님 step3 고생하셨습니다! ☺️

이번 스텝도 잘 해주셨네요!! 👍👍
좋은 고민을 해주셨습니다 💭

---

### 수행 내용
* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [x] 딕셔너리 내부타입 적절하게 설정하기
- [x] 옵셔널 값을 안전하게 추출하기
- [x] Step2 에서 사용한 함수 재사용하기

</br>

### ✅ 고민했던 점
* `allLottoNumberStorage` -> 잘 지어주셨습니다. 👍 </br> all은 없어도 괜찮지 않을까요?! 
* `save` 함수, `count` 전역 변수 사용 -> 코드 코멘트에서 확인해주세요~!
* 옵셔널 바인딩 👏👏👏

**`save` 함수의 위치**
음~~ 전역변수로 count가 있고, save 함수의 호출이 step2의 재사용 함수 내부에 작성이 되었네요. 이 부분 같이 개선해볼까요?

질문은 언제든 환영입니다 😄

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step2.swift
> +
여기 줄바꿈이 한 번 더 되어있네요? 👀
줄바꿈도 중요한 컨벤션 요소이니 잘 맞춰주세요~~

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step2.swift
> +    save(thisWeekLottoNumbers: thisWeekLottoNumbers)
이 코드가 추가됨으로 인해 재사용할 함수에 변경이 생겼습니다!
기존 코드를 변경하지 않는 방향을 지향하시면 좋답니다 👍

카멜케이스 놓친 부분을 고쳐주셨군요 🫠👍

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +var allLottoNumberStorage: Dictionary<String , Set<Int>> = [String : Set<Int>]()
Dictionary 타입을 잘 설정해주셨네요! 👍

다만, [애플 공식문서](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/#Dictionary-Type-Shorthand-Syntax)에 따르면 Dictionary의 타입을 나타낼 때 축약형 표현을 선호한다고 합니다.

좀 더 간략하고 보기 쉽기 때문인 것 같네요 🤔
short form을 활용하면 아래와 같이 간단히 표현할 수 있습니다.
Dictionary 타입을 표현할 때 보통 colon의 뒤에만 공백을 한 칸 줍니다.

```suggestion
var lottoNumberStorage: [String: Set<Int>] = [:]
```

---

추가로, step2 에서는 숫자의 순서가 상관이 없었지만
일련의 숫자를 저장할 땐 보통 `정렬`을 하죠!

* Dictionary의 value 타입을 순서가 있는 콜렉션 타입으로 변경해주세요!
* Set의 인스턴스 메서드 중에서 내부 항목들을 정렬(`sort`)하는 메서드를 찾아봅시다. 💪

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +}
`generateLottoNumbers` 내부를 변경하지 않으려면 어떻게 할까요?

생성하는 기능은 이미 step2에서 구현했고, step3에서 저장하는 기능인 `save(thisWeekLottoNumbers:)`를 잘 만들어주셨죠!
그렇다면 두 기능을 모두 사용하는 함수를 새로 만들 수 있지 않을까요? 💭
5회 생성하는 반복문까지 포함하면 main 파일도 간단해지겠네요~!

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +func findWhatLottoNumbers(week: String) {
naming에서 개선할 점이 보입니다.

* find -> 좋습니다.👍 Dictionary에서 값을 가져오기 때문에 get을 사용하셔도 좋습니다!
* What -> 사용하신 이유가 따로 있을까요?? 없어도 충분히 이해가 될 것 같아요!
* parameter -> forWeek: Int 타입으로 받은 뒤, 함수 내부에서 String으로 변환해주면 훨씬 깔끔하고 안정적일 것 같네요 👀
* 함수 위에 주석 삭제해주세요~

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +        print(week + "의 로또 당첨 번호는 \(numberString) 입니다. ")
이런이런~ 옵셔널 바인딩은 잘 해주셨는데 아래에서 강제추출을 사용하셨네요!
옵셔널 강제추출(!)은 사용을 지양하셔야 합니다. week에 잘못된 값이 들어온다면 앱이 종료되고 말거에요...
(지금은 if 에서 nil인 경우를 걸러주고 있어서 터지진 않습니다 😅)
옵셔널 바인딩으로 만들어진 상수를 통해 안전하게 추출된 값을 사용해주세요 ☺️

```suggestion
    if let lottoNumbers = allLottoNumberStorage[week] {
        let numberString = lottoNumbers.map({ String($0) }).joined(separator: ", ")
        print(week + "의 로또 당첨 번호는 \(numberString) 입니다. ")
```

2023-08-29 19:01 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +    }
예외 처리 Good 👍

2023-08-30 07:14 UTC, SAY-Hong commented
@Tediousday93 수정 완료했습니다🙂

2023-08-30 12:32 UTC, Tediousday93 requested changes
요구사항을 잘 반영해주셨네요~!
어느정도 고민하셨던 점이 해결되셨을까요?

코멘트 드린 간단한 부분 추가로 수정해주시면 머지 하도록 하겠습니다~~
고생 많으셨습니다.

2023-08-30 12:32 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +var lottoNumberStorage: [String : Array<Int>] = [:]
Array의 경우도 축약형으로 해주시면 좋겠네요~~
```suggestion
var lottoNumbersStorage: [String: [Int]] = [:]
```

2023-08-30 12:32 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +    lottoNumberStorage["\(count)회차"] = sortedThisWeekLottoNumbers
👍👍👍

2023-08-30 12:32 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +func findLottoNumbers(weekNumber: Int) {
파라미터에 전치사를 붙여주고 싶은 마음이 들긴 하네요. 💦
지금도 나쁘지 않습니다!

말씀드렸던 for를 사용하면 호출할 때 자연스럽게 읽힐 것 같습니다.
```suggestion
func findLottoNumbers(forWeek: Int) { // ... }

findLottoNumbers(forWeek: 3)
```

2023-08-30 12:32 UTC, Tediousday93 commented on CodeStarterCamp_Week2/Week2Step3.swift
> +    for _ in 1...count{
중괄호 앞 공백 하나 추가해주셔야 합니다~

2023-08-30 12:44 UTC, SAY-Hong commented
@Tediousday93 수정 완료했습니다!!

2023-08-30 12:56 UTC, merged