Week2 [STEP 2] 알드
yagom-academy/swift-starter-week2 pull request #584
Opened 2023-08-30 14:33 UTC by aldalddl

@Rhode-park 
안녕하세요, 로데!
오늘도 잘 부탁드립니다😌

 ## 고민했던 점 
 - STEP1에 이어서 로또번호를 담을 공간은 set타입으로 선언했는데, 
 이번 STEP2에 추가된 `myLottoNumbers`는 어떤 타입으로 선언할지 고민해보았고,
 겹치는 숫자를 확인하는 부분에서 set의 `intersection` 메소드를 사용하면 편할 것 같아 set으로 선언하고 연산하였습니다.
 - 겹치는 숫자`sortedSameNumbers`를 출력할 때, 평소처럼 `\(sortedSameNumbers)`로 출력하면 중괄호`[]`가 함께 출력되므로, 
 어떻게 없애고 출력할지 고민해보았습니다.
 고차함수`map`을 사용해 `sortedSameNumbers`의 각 멤버들을 `Int`에서 `String`으로 변환한 후, 
 `joined`를 사용해 ", "로 결합하여서 원하는 형태인 "1, 2, 3"을 출력하도록 했습니다.
 ---

 ## 해결이 되지 않은 점
없습니다
</br>

 ---

 ## 조언을 얻고 싶은 부분
없습니다
</br>

2023-08-31 01:12 UTC, Rhode-park requested changes
## ✅ 고민했던 점
> * STEP1에 이어서 로또번호를 담을 공간은 set타입으로 선언했는데, 이번 STEP2에 추가된 myLottoNumbers는 어떤 타입으로 선언할지 고민해보았고, 겹치는 숫자를 확인하는 부분에서 set의 intersection 메소드를 사용하면 편할 것 같아 set으로 선언하고 연산하였습니다.
> * 겹치는 숫자sortedSameNumbers를 출력할 때, 평소처럼 \(sortedSameNumbers)로 출력하면 중괄호[]가 함께 출력되므로,
> 어떻게 없애고 출력할지 고민해보았습니다.
> 고차함수map을 사용해 sortedSameNumbers의 각 멤버들을 Int에서 String으로 변환한 후, joined를 사용해 ", "로 결합하여서 원하는 형태인 "1, 2, 3"을 출력하도록 했습니다.
 
Set에는 `intersection`메서드가 사용되는군요. 멋집니다!
그렇다면, 해당 타입이 Array일 경우 어떤 메서드를 사용하면 좋을까요?
공부해보시고 답변 부탁드립니다.

또한, map에 대해서도 코멘트 남겼으니 확인 부탁드립니다.

## ✅ 해결이 되지 않은 점
> 없습니다.

## ✅ 조언을 얻고 싶은 부분
> 없습니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ 요구사항에 맞춰 프로젝트 작성하기
다음과 같은 요구사항들이 있었습니다:
> - 우리가 찍은 6개의 번호를 다음과 같은 형태의 상수로 저장해봅시다.
>     - let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
> - Step1의 순서도를 바탕으로 `로또 당첨 번호`를 생성하는 함수를 생성합니다.
> - 내가 `찍은 번호` 배열을 `myLottoNumbers` 변수에 할당합니다.
> - `찍은 번호`와 `로또 당첨 번호` 의 겹치는 숫자를 확인하는 함수를 생성합니다.

`myLottoNumbers`도 잘 만들어주셨고, 이에 맞춰서 두 개의 함수를 만들어주셨네요. 멋집니다!

### 2️⃣ 해당 브랜치에 PR보내기
본인의 해당 브랜치가 아닌 main브랜치에 PR을 보내주셨습니다. 멋집니다!

### 3️⃣ 카르마 스타일 참고하여 commit보내기
카르마 스타일에 따라서 commit message를 남겨주고 계십니다. 멋집니다!

---

코드를 멋지게 잘 짜주셔서 코멘트 할 부분이 많지 않았네요. 멋집니다!
여러가지 반영해보시고, 질문한 부분 답변 주신 후 DM 주시면 merge해드리겠습니다.

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    var lottoNumbers: Set<Int> = Set<Int>()
`myLottoNumbers`에서는 다음과 같이 타입 어노테이션이 되어있습니다:
```swift
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
```

그런데, `sortedSameNumbers`에서는 타입 추론이 사용되고 있네요.
타입 어노테이션을 사용하실지, 타입 추론을 사용하실지 자신만의 기준을 정하면 좋을 것 같습니다.
또한, 타입 어노테이션과 타입 추론은 각각 어느 상황에서 쓰이는지, 장단점이 무엇인지 등을 공부해보시고 제게 알려주시면 좋겠습니다.

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    let sameNumbers: Set<Int> = lottoNumbers.intersection(Set(myLottoNumbers))
`intersection`이라는 메서드를 사용해주셨습니다. 멋집니다!
`intersection`은 어떤 메서드이며 왜 사용해주신 것일까요?

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +    let sortedSameNumbers = sameNumbers.sorted()
`sorted()`를 통해서 일치하는 번호를 정렬해주셨습니다. 멋집니다!
그렇다면, `sorted()`와 `sort()`의 차이는 무엇일까요?
공부해보시고 답변 부탁드립니다!

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sortedSameNumbers.map{ String($0) }.joined(separator: ", ")) 입니다!")
중괄호를 없애기 위하여 `map`과 `joined`메서드를 사용해주셨습니다. 멋집니다!
고차함수 map과 비슷한 아이들로는 flatMap, compactMap이 있습니다.
map, flatMap, compactMap이 어떤 기능을 하는지, 각각의 차이가 무엇인지 등에 대해서 설명해주실 수 있나요?

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sortedSameNumbers.map{ String($0) }.joined(separator: ", ")) 입니다!")
**(참고)**`map`을 축약형태로 쓰지 않는다면, 어떻게 쓸 수 있을까요?
다음과 같은 형태로 쓸 수 있을 것 같습니다:
```swift
let sortedSameNumbersString: [String] = sortedSameNumbers.map { (무엇이들어갈까요?) in
    (무엇이들어갈까요?)
}
```

2023-08-31 01:12 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sortedSameNumbers.map{ String($0) }.joined(separator: ", ")) 입니다!")
`joined`는 어떤 메서드인가요?
무엇을 어떻게 처리하여 어떤 것을 반환하는 메서드인가요?
공부해보시고 저에게 설명 부탁드립니다.

2023-08-31 04:54 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +    let sortedSameNumbers = sameNumbers.sorted()
`sorted()`는 원본의 복제본을 반환해주는 것입니다. 복제본인 정렬된 배열을 다른 변수나 상수에 할당하여 사용합니다.
새 배열을 생성하는 것이기 때문에 메모리 사용량이 더 큽니다.

`sort()`는 원본을 바꾸는 것입니다. 원본 변수에 `.sort()`를 해주어 원본 값을 정렬합니다.
원본의 순서가 중요한 경우에는 사용을 주의해야 합니다.

2023-08-31 05:16 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +    let sameNumbers: Set<Int> = lottoNumbers.intersection(Set(myLottoNumbers))
`intersection`은 두 set이 공통으로 갖고 있는 값을 반환해주는 메서드입니다.
집합 연산에서 교집합 연산에 해당합니다.

저는 `내가 찍은 번호`와 `로또 당첨 번호`의 겹치는 숫자를 확인하는 부분에서
`내가 찍은 번호`set과 `로또 당첨 번호`set의 교집합을 알기 위해 사용했습니다!

2023-08-31 06:08 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +    var lottoNumbers: Set<Int> = Set<Int>()
그렇군요. 잘 알고 기준을 정해 사용하겠습니다!

타입 어노테이션은 타입을 직접 정해주는 것입니다. `: [Int]`
타입을 미리 알려준 것이니 초기값을 통해 타입을 추론하는 과정(타입 추론)이 필요 없고, 
내가 원하는 타입으로 정확히 정해둘 수 있으며, 타입 추론에 드는 시간을 줄여주는 장점이 있지만
직접 명시해주어야 하는 번거로움을 단점으로 들 수 있습니다.

선언을 먼저하고 나중에 값이 할당되는 변수, 서버를 통해 추후에 값을 받아오는 변수 등 초기값을 정해둘 수 없는 경우에 사용할 수 있습니다.

타입 추론은 선언과 동시에 값을 초기화 해주는 것입니다. `= [1, 2, 3, 4, 5, 6]`
그러면 컴파일러가 초기값을 보고 타입을 알아서 추론하므로 
타입 어노테이션을 따로 해주지 않아도 돼서 간단하다는 장점이 있지만
Character를 String으로 추론하거나 Float을 Double로 정하는 등 의도와 다른 타입으로 추론될 수 있고
추론하는 데에 시간이 조금 더 걸릴 수 있다는 단점이 있습니다.

초기값이 명확히 있고, 초기값의 타입도 확실이 유추되는 경우에 사용할 수 있습니다.

2023-08-31 06:40 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sortedSameNumbers.map{ String($0) }.joined(separator: ", ")) 입니다!")
`map`은 배열의 각 요소마다의 값을 변경해 다른 값으로 반환해주는 기본 매핑 기능을 합니다.

`flatMap`은 배열이 2차원일 경우, 2차원 배열 그대로 반환하는 `map`과 `compactMap`과 달리 1차원 배열로 반환해줍니다. 
현재는 deprecated되어 compactMap을 사용합니다. 

`compactMap`은 배열이 옵셔널 타입일 경우, 옵셔널 배열 그대로 nil도 함께 반환되는 `map`과 달리 nil은 제외하고(non-nil) 바인딩되어 옵셔널이 아닌 배열로 반환해줍니다.

2023-08-31 08:07 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(sortedSameNumbers.map{ String($0) }.joined(separator: ", ")) 입니다!")
`joined`는 배열의 각 요소들을 하나로 묶어주는 메서드입니다. 
배열에서, 안에 들어있는 배열 형태의 요소들을 연결하고, 연결된 하나의 배열을 반환합니다.

2차원 배열에 사용하면 각 배열들을 연결하여 1차원 배열로 반환하고,
String 배열에 사용하면 각 String들을 연결하여 하나의 String으로 반환합니다. (String도 Character의 배열이므로)

즉 배열을 한차원 낮춰주는 `flatten` 기능을 합니다. (`flatMap`과 비슷한 것 같아 공식문서를 읽어보니 동일한 기능을 한다고 써있는 것을 발견했습니다)

2023-09-01 03:07 UTC, Rhode-park commented
수고하셨습니다! merge해드리겠습니다!

2023-09-01 03:08 UTC, merged