Week2 [STEP 3] 알드
yagom-academy/swift-starter-week2 pull request #592
Opened 2023-09-04 01:11 UTC by aldalddl

@Rhode-park 
안녕하세요, 로데!
이번 Step도 어떻게 코드를 짜면 좋을지 고민하는 과정이 흥미로웠습니다.
오늘도 잘 부탁드립니다😌

 ## 고민했던 점 
 #### `createLottoNumbers` 함수
 - 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장한다고 했으므로
 로또 당첨 번호 생성 함수인 `createLottoNumbers` 내에서, 회차와 로또 번호를 저장하는 함수인 `storeLottoNumbers`를 호출해주었습니다.
 - 또한 저장만 하면 되므로 기존처럼 로또 번호를 반환할 필요가 없을 것 같아 `lottoNumbers` 리턴을 삭제했습니다.

#### 결과 출력
- dictionary의 value 값인 로또 당첨 번호가 옵셔널이므로
옵셔널 바인딩 `if let`으로 추출하여 출력했습니다.
 ---

 ## 해결이 되지 않은 점
없습니다
</br>

 ---

 ## 조언을 얻고 싶은 부분
없습니다
</br>

2023-09-04 16:42 UTC, Rhode-park requested changes
## ✅ 고민했던 점
> **createLottoNumbers 함수**
> * 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장한다고 했으므로
> * 로또 당첨 번호 생성 함수인 createLottoNumbers 내에서, 회차와 로또 번호를 저장하는 함수인 storeLottoNumbers를 호출해주었습니다.
> 또한 저장만 하면 되므로 기존처럼 로또 번호를 반환할 필요가 없을 것 같아 lottoNumbers 리턴을 삭제했습니다.
> 
> **결과 출력**
> * dictionary의 value 값인 로또 당첨 번호가 옵셔널이므로
> 옵셔널 바인딩 if let으로 추출하여 출력했습니다.

로또 번호를 반환하는 대신에 `storeLottoNumbers()`의 매개변수로 넣어주고 계시는군요. 멋집니다!

`if let`으로 추출하여 출력하고 계시네요. 멋집니다!
`if let`과 비슷한 문법으로는 `guard let`이 있습니다.
둘의 차이는 무엇일까요?

## ✅ 해결이 되지 않은 점
> 없습니다.

## ✅ 조언을 얻고 싶은 부분
> 없습니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ 요구사항에 맞춰 프로젝트 작성하기
요구사항에 맞게 딕셔너리에 적절한 Key에 따른 적절한 Value를 넣어주고 계십니다. 멋집니다!
각각의 회차별 로또 번호도 다 다릅니다. 멋집니다!
옵셔널을 안전하게 추출한 점 역시 멋집니다!

### 2️⃣ 해당 브랜치에 PR보내기
본인의 해당 브랜치가 아닌 main브랜치에 PR을 보내주셨습니다. 멋집니다!

### 😄
나날이 코드가 발전해가네요.
정말 많이 성장하셨음이 느껴집니다. 항상 화이팅입니다.

리뷰 반영해주시고 DM주시면 merge해드리겠습니다.

2023-09-04 16:42 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +var storedLottoNumbers = [String: [Int]]()
`[String: [Int]]()`를 사용하여 정해진 타입의 빈 딕셔너리를 만들어주고 계십니다. 멋집니다!

2023-09-04 16:42 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
>      var lottoNumbers: Set<Int> = Set<Int>()
다른 곳과 컨벤션을 맞추기 위해서라면 타입 어노테이션이 아닌 타입 추론이 사용되어야할 것 같습니다.

2023-09-04 16:42 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
>  }
로또 숫자들을 저장하는 함수를 잘 만들어주셨습니다. 멋집니다!

2023-09-04 16:42 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +createLottoNumbers()
만약에 로또 숫자들이 100회차까지 생기게 되면 어떻게 될까요?
그 때마다 100번 해당 함수를 호출하실 생각이실까요?
이 기능을 담당해주는 함수를 만들어보시는게 좋을 것 같습니다.

2023-09-04 16:42 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +}
특정 기능을 하고 있는 부분이네요.
함수로 만들어서 호출하는 과정을 거쳐볼까요?
몇회차 번호를 출력할지에 대한 매개변수를 가지면 좋을 것 같습니다.

2023-09-05 06:25 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
>      var lottoNumbers: Set<Int> = Set<Int>()
앗 그렇네요. 
항상 컨벤션을 생각하며 코드를 짜고, 컨벤션이 안 맞춰진 곳이 있는지도 잘 확인해야겠습니다. 감사합니다!

2023-09-05 06:28 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +createLottoNumbers()
그렇군요! 😲
`repeatCreatingLottoNumbers`함수를 만들었습니다.

2023-09-05 06:31 UTC, aldalddl commented on CodeStarterCamp_Week2/main.swift
> +}
특정 기능을 하고 있으니 함수로 만드는 게 좋겠군요😲
`printLottoRoundNumbers`함수를 만들고, `searchingLottoRound`라는 매개변수를 만들었습니다.

2023-09-05 07:27 UTC, aldalddl commented
#### 옵셔널 바인딩
- **공통점**
 nil이 아닐 때 -> 추출된 값을 상수에 저장하고, true를 반환합니다. 
 nil일 때 -> false를 반환합니다.
- `if let` 
    - `else` 문은 생략이 가능합니다.
    - 추출된 상수는 `if let`구문 안에서만 사용 가능합니다.
- `guard let`
    - `else` 문을 꼭 작성해주어야 합니다. 
    그리고 `else`문 내에는 return, break, throw, continue 등이 들어갑니다.
    - 추출된 상수는 `guard let`구문 밖에서도 사용 가능합니다.
    - `guard let`은 자신이 위치해있는 함수, 반복문, 또는 조건문을 나가는 경우에 사용되기 때문에 
    `else` 문에 종료하는 내용을 작성해놓습니다.

2023-09-05 10:28 UTC, Rhode-park commented
수고하셨습니다! merge해드리겠습니다! 다음 step에서 뵙겠습니다!

2023-09-05 10:28 UTC, merged