Round 2 [STEP 1] 아지
yagom-academy/swift-starter-week2 pull request #613
Opened 2023-10-06 01:27 UTC by ungchun

@Rhode-park 

## 고민했던 점
서로 겹치지 않아야 한다는 점에서 어떤 로직으로 처리를 할까 생각을 하다 중복을 허용하지 않는 컬렉션인 Set을 사용했습니다.

2023-10-10 06:18 UTC, Rhode-park requested changes
## ✅ 고민했던 점
> 서로 겹치지 않아야 한다는 점에서 어떤 로직으로 처리를 할까 생각을 하다 중복을 허용하지 않는 컬렉션인 Set을 사용했습니다.

컬렉션 타입에는 어떠한 것들이 있으며, 각각의 특징 및 장단점은 어떻게 되나요?
공부해보시고 답변 부탁드립니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ 요구사항에 맞춰 프로젝트 작성하기
요구사항에 맞춰 코드 작성 없이 순서도만을 첨부해주셨습니다. 멋집니다!

### 2️⃣ 해당 브랜치에 PR보내기
main브랜치가 아닌 본인의 해당 브랜치에 PR을 보내주셨습니다. 멋집니다!

### 3️⃣ 카르마 스타일 참고하여 commit보내기(참고)
[카르마 스타일](http://karma-runner.github.io/6.3/dev/git-commit-msg.html)에 대해서 들어보셨나요?
`:(콜론)`앞에 타입을 작성하고 뒤에 commit하는 내용에 대해서 작성하는 형식입니다.
이 때, 타입은 영어 소문자이며, 뒤의 내용은 한글로 작성하셔도 됩니다.
가능한 타입의 종류는 다음과 같습니다:
> * feat = 주로 사용자에게 새로운 기능이 추가되는 경우
> * fix = 사용자가 사용하는 부분에서 bug가 수정되는 경우
> * docs = 문서에 변경 사항이 있는 경우
> * style = 세미콜론을 까먹어서 추가하는 것 같이 형식적인 부분을 다루는 경우 (코드의 변화가 생산적인 것이 아닌 경우)
> * refactor = production code를 수정하는 경우 (변수의 네이밍을 수정하는 경우)
> * test = 테스트 코드를 수정하거나, 추가하는 경우 (코드의 변화가 생산적인 것이 아닌 경우)
> * chore = 별로 중요하지 않은 일을 수정하는 경우 (코드의 변화가 생산적인 것이 아닌 경우)

이를 활용하여 commit message를 다음과 같이 작성할 수 있습니다.
```text
feat: drawPeperoStick 함수 구현
```
다음 step부터는 자신의 프로젝트에서 commit을 하려는 부분이 어떤 종류인지 고민해보고, 자신만의 기준을 세워서 commit message를 작성해볼까요?

### 4️⃣ 순서도
Set에 6개의 원소들이 들어가있을 때, `Set의 크기가 6보다 크다`라는 조건문을 만나면, 어느쪽으로 향하게 될까요?

2023-10-10 06:50 UTC, ungchun commented
컬렉션 타입에는 Array, Dictionary, Set이 있습니다. 각 특징으로는

Array
Array는 멤버가 순서(인덱스)를 가진 리스트 형태의 컬렉션 타입입니다.

Dictionary
Dictionary는 키와 값의 쌍으로 이루어진 컬렉션 타입입니다.

Set
Set는 순서가 없고, 멤버가 유일한 것을 보장하는 컬렉션 타입입니다.

-------
Set에 6개의 원소들이 들어가 있는 상태에서 Set의 크기가 6보다 크다라는 조건문을 만나면 Yes 쪽으로 이동, Set을 반환합니다.

2023-10-11 13:44 UTC, Rhode-park commented
6보다 크다라는 것은 n>6이라는 것을 의미하는데, 그러면 No쪽으로 이동하지 않을까요?

2023-10-11 13:58 UTC, ungchun commented
아 그러네요.. 크거나 같을 때를 생각하고 있었는데, 그게 아니었네요.. 차라리 "Set의 크기가 6인가?"가 더 맞을 거 같기도 합니다.

2023-10-11 14:24 UTC, merged