Round 2 [STEP 2] 아지
yagom-academy/swift-starter-week2 pull request #617
Opened 2023-10-12 08:17 UTC by ungchun

@Rhode-park 

## 고민했던 점
번호를 출력할 때 ", "를 출력해야하고 마지막에는 출력하면 안되는 부분을 고민하다 
string 값에 number, 를 계속 추가하고 마지막에 공백과 , 부분을 삭제하는 코드를 추가했습니다.

2023-10-14 07:14 UTC, Rhode-park requested changes
## ✅ 고민했던 점
> 번호를 출력할 때 ", "를 출력해야하고 마지막에는 출력하면 안되는 부분을 고민하다 string 값에 number, 를 계속 추가하고 마지막에 공백과 , 부분을 삭제하는 코드를 추가했습니다.

코멘트를 남겼으니 확인 부탁드립니다.

## ✅ 해결이 되지 않은 점
> 없습니다.

## ✅ 조언을 얻고 싶은 부분
> 없습니다.

2023-10-14 07:14 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
`myLottoNumbers`에서는 다음과 같이 타입 어노테이션이 되어있습니다:
```swift
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
```

그런데, `correctNumbers`에서는 타입 추론이 사용되고 있네요.
타입 어노테이션을 사용하실지, 타입 추론을 사용하실지 자신만의 기준을 정하면 좋을 것 같습니다.
또한, 타입 어노테이션과 타입 추론은 각각 어느 상황에서 쓰이는지, 장단점이 무엇인지 등을 공부해보시고 제게 알려주시면 좋겠습니다.

2023-10-14 07:14 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	var correctNumbers = Array<Int>()
[CollectionTypes - Array - Shorthand Syntax](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/#Array-Type-Shorthand-Syntax)를 확인해보시면, 다음과 같은 문구가 있습니다.
```text
the shorthand form is preferred
```
이에 맞춰 컨벤션을 변화해볼까요?

2023-10-14 07:14 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +		if(lottoNumbers.contains(number)) {
```suggestion
		if lottoNumbers.contains(number) {
```
위와 같이 쓰는 것이 적절한 컨벤션일 것 같습니다.

2023-10-14 07:14 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	if(correctNumbers.isEmpty) {
```suggestion
	if correctNumbers.isEmpty {
```
위와 같이 쓰는 것이 적절한 컨벤션일 것 같습니다.

2023-10-14 07:14 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +		print("축하합니다! 겹치는 번호는 \(lottoString) 입니다!")
removeLast()를 사용해주셨군요. 멋집니다!
그렇지만, `print(, terminator: )`와 분기처리를 사용해서도 구현할 수 있을 것 같습니다.
그렇게 하려면 어떻게 구현해야할까요?

2023-10-15 05:58 UTC, ungchun commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
타입 추론은 초기값을 지정해줘야 하고, 타입 어노테이션은 자료형을 지정해줘야 합니다.
타입 추론을 사용시 발생할 수 있는 문제점은 원하는 타입이 추론이 안될 수 있고, 초기값이 없을 경우 사용할 수 없습니다. 이 문제점이 발생한다면 타입 어노테이션을 사용해야 합니다.

2023-10-15 06:05 UTC, ungchun commented on CodeStarterCamp_Week2/main.swift
> +		print("축하합니다! 겹치는 번호는 \(lottoString) 입니다!")
if correctNumbers 마지막 index가 아니면 {
        print("\(number)", terminator: ", ")
} else {
        print("\(number)", terminator: "")
}

correctNumbers안에 있는 number들을 하나씩 출력하는데 마지막 number가 아니면 print("\(number)", terminator: ", ")를 마지막 number면 print("\(number)", terminator: "")로 출력하면 될 거 같습니다. terminator 사용을 많이 안하다 보니 생각을 잘 못했네요.

2023-10-16 14:40 UTC, merged