Round2 [STEP 3] 뉴프로
yagom-academy/swift-starter-week2 pull request #618
Opened 2023-10-13 06:44 UTC by joonHyoung

@Tediousday93 

 ## 고민했던 점
 - 중복되는 부분은 최대한 함수로 작성하여 재사용 하려 하였습니다.

2023-10-14 01:28 UTC, Tediousday93 requested changes
안녕하세요 뉴프로님 step3 고생하셨습니다! ☺️
이번 스텝도 정말 잘 해주셨네요!! 👍👍

---

### 수행 내용
* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [x] 딕셔너리 내부타입 적절하게 설정하기
- [x] 옵셔널 값을 안전하게 추출하기
- [x] Step2 에서 사용한 함수 재사용하기

</br>

### ✅ 고민했던 점
* 세세하게 함수를 잘 분리해주셨습니다 👍
* 옵셔널 바인딩 👏👏👏

</br>

수정 완료되시면 DM 부탁드립니다 🙏

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +        returnMessage = "축하합니다! 겹치는 번호는 " + makePrintIntersectionNumbers(intersectionNumbers: intersectionNumbers) + " 입니다!"
지난 스텝 리팩토링 👍👍

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +
개행이 한 줄 더 있네요 👀

main 파일에는 상수/변수 선언, 함수 호출 코드만 남겨놓고
함수를 정의하는 코드는 별도의 파일로 관리해도 좋을 것 같습니다. 😊

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +func printWinningNumbersForRound(round: Int) {
함수이름과 파라미터에 중복된 정보가 있네요!
Swift API Design Guidelines 내용에 따라,
파라미터의 이름을 `_`를 이용해서 가려주거나 forRound를 파라미터 이름으로 하는 방법이 좋을 것 같습니다 🤔

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +}
이번 스텝은 회차 당첨번호를 조회하고 있기 때문에
출력되는 숫자들을 오름차순으로 정렬해주는게 보기 좋을 것 같습니다 😊
저장할 때 정렬해서 저장해볼까요?!

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +}
함수를 세세하게 분리해주셨군요 👍

2023-10-14 01:28 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +    if let winnigNumbers = listWinnigLottoNumbers[roundString] {
옵셔널 바인딩을 통해 값을 안전하게 추출해주셨네요 👍👍👍

2023-10-25 02:43 UTC, joonHyoung commented on CodeStarterCamp_Week2/main.swift
> +func printWinningNumbersForRound(round: Int) {
수정하였습니다.

2023-10-25 02:43 UTC, joonHyoung commented on CodeStarterCamp_Week2/main.swift
> +}
네 수정하였습니다.

2023-10-25 05:41 UTC, Tediousday93 approved these changes
요구사항이 잘 반영되었네요 ☺️
고생하셨습니다.

2023-10-25 05:41 UTC, Tediousday93 commented on CodeStarterCamp_Week2/main.swift
> +    return returnNumbers.map { String($0) }.joined(separator: ", ")
출력할때마다 정렬을 해주시는 방향으로 수정하셨군요! 👍

처음에 번호를 저장할 때 정렬해서 저장하는 방법도 좋다고 생각합니다. 😊
그렇게 된다면 딕셔너리의 value 타입을 조금 수정해야겠지만요 💭
```swift
var listWinnigLottoNumbers: [String: [Int]] = [:]
```

2023-10-25 05:43 UTC, merged