Week2 [STEP 3] 김마루
yagom-academy/swift-starter-week2 pull request #621
Opened 2023-10-15 07:29 UTC by marukim365

안녕하세요, 두두!(@FirstDo  )
김마루 입니다.

Week2 STEP 3 - 로또 당첨 번호를 회차별로 저장하고, 확인하자!
완료하여 PR 보냅니다!

🤔 어려웠던 점
----------
1. 요구 사항에 아래와 같은 내용이 있었습니다.
```
Step 2의 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장하고자 합니다. 
이와 같은 동작을 구현하기 위한 별도의 함수를 만들어봅시다.
새로운 로또 당첨 번호를 생성하면, 직전 회차에 1을 더해 금번 회차를 만들어냅니다.
```
저는 이 부분을 `for` 반복문을 사용하여 구현했는데, 요구 사항이 충족될지...의문입니다.
오랜 고민을 해봤지만 반복문 사용 밖에는 보이지 않았습니다.

이상입니다.

PR 확인 부탁 드립니다!
감사합니다 :)

2023-10-15 23:33 UTC, FirstDo requested changes
마루님 Week2의 마지막 스텝 고생하셨습니다!

## 🔥 STEP의 핵심경험

- [x] Dictionary의 저장, 추출
- [x] Optional Unwrapping 

전체적으로 너무 잘해주셔서 크게 드릴 말씀이 없습니다!
이전 스탭을 깔끔하게 해놨기 때문에, STEP3는 더 쉽게 넘어갈 수 있던것 같습니다

## 📋 질문에 대한 답변

> 요구 사항에 아래와 같은 내용이 있었습니다.
`
Step 2의 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장하고자 합니다. 
이와 같은 동작을 구현하기 위한 별도의 함수를 만들어봅시다.
새로운 로또 당첨 번호를 생성하면, 직전 회차에 1을 더해 금번 회차를 만들어냅니다.
`

> 저는 이 부분을 for 반복문을 사용하여 구현했는데, 요구 사항이 충족될지...의문입니다.
오랜 고민을 해봤지만 반복문 사용 밖에는 보이지 않았습니다.

너무 잘 구현해주신것 같습니다!
요구사항도 충족하고, 로직도 깔끔합니다

## 😆 좋았던점

- 코드를 요구사항에 맞게 깔끔히 작성해 주신점

## 🙏 부탁드리고 싶은점

- x

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/checkLotto_STEP2.swift
아마 새로운 스탭을 진행하고, 파일을 분리했는데 매서드 명이 겹쳐서 이런식으로 주석처리를 하셨겠죠?
굳이 이전코드를 다 주석처리 할 필요없이, 안쓰는 파일은 xcode 오른쪽의 target membership을 체크 해제 해준다면 오류없이 컴파일 가능합니다!

<img width="262" alt="스크린샷 2023-10-16 오전 8 15 07" src="https://github.com/yagom-academy/swift-starter-Round2/assets/69573768/dd8e2e6b-5943-4c3c-96de-65a443dc34de">

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
아래와 같이 쓰면 Xcode가 line과 bold로 좀 더 해당 주석을 강조해 줍니다
구분이 필요할때는 이런식으로 쓰는것도 좋아요 

<img width="778" alt="스크린샷 2023-10-16 오전 8 17 38" src="https://github.com/yagom-academy/swift-starter-Round2/assets/69573768/c1ff9816-2924-4412-823f-6375ec2e6acb">


```swift
// MARK: - Week2 [STEP2] - 내 번호와 맞추어보기!

// MARK: - Week2 [STEP3] - 로또 당첨 번호를 회차별로 저장하고, 확인하자!
```

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/saveLotto_STEP3.swift
> +    var savedLotto: [String: [Int]] = [:]
컨벤션에서 단수/복수를 맞추는것도 신경쓰시면 좋습니다
`savedLotto` -> `savedLottos`

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/saveLotto_STEP3.swift
> +}
guard 문을 사용하여 optional 값을 언래핑 하신점이 좋았습니다.

아시겠지만 guard 말고도 몇가지 방법이 있으니, 알아두심 나중에 도움이 될 것 같습니다 ㅎㅎ
- Optional Binding (if let)
- Optional Binding (guard let)
- Nil coalescing
- Forced unwrapping

처음부터 선언을 !로 하는 방법도 있습니다
- Implicitly Unwrapped Optionals

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/saveLotto_STEP3.swift
> +    guard let nonOptionalNumbers = savedLotto["\(userCount)회차"] else {
nonOptionalNumbers는 변수의 뜻보다는 그냥 타입을 나타내는 느낌이고, 
좀 더 해당 변수가 갖는 뜻에 맞게 네이밍을 해보면 어떨까요?

2023-10-15 23:33 UTC, FirstDo commented on CodeStarterCamp_Week2/saveLotto_STEP3.swift
> +    var savedLotto: [String: [Int]] = [:]
마루님 컨벤션상 굳이 타입 명시를 할 필요가 없겠네요

```swift
var savedLotto = [String: [Int]]()
```

2023-10-16 02:57 UTC, marukim365 commented on CodeStarterCamp_Week2/checkLotto_STEP2.swift
이런 방법이!!
감사합니다 :)

2023-10-16 02:59 UTC, marukim365 commented on CodeStarterCamp_Week2/main.swift
이런 방법이!! 2
감사합니다 :)

2023-10-16 02:59 UTC, marukim365 commented on CodeStarterCamp_Week2/saveLotto_STEP3.swift
> +    var savedLotto: [String: [Int]] = [:]
넵! 신경 쓰겠습니다.

2023-10-16 04:01 UTC, FirstDo approved these changes

2023-10-16 04:01 UTC, merged