Round 2 [STEP 3] 아지
yagom-academy/swift-starter-week2 pull request #625
Opened 2023-10-17 16:39 UTC by ungchun

@Rhode-park 

## 고민했던 점
고차함수를 쓰면 내부적으로 어떻게 돌아가는지 궁금해졌습니다. 
예를 들어 map으로 String array를 int array로 바꾼다거나 joined 같은 고차함수를 사용하면 고차함수를 사용하지 않았을 때와의 메모리, 시간복잡도 등 여러가지 측면에서 어떤 차이가 날까 궁금해졌습니다.

2023-10-19 07:57 UTC, Rhode-park requested changes
## ✅ 고민했던 점
> 고차함수를 쓰면 내부적으로 어떻게 돌아가는지 궁금해졌습니다.
예를 들어 map으로 String array를 int array로 바꾼다거나 joined 같은 고차함수를 사용하면 고차함수를 사용하지 않았을 때와의 메모리, 시간복잡도 등 여러가지 측면에서 어떤 차이가 날까 궁금해졌습니다.

고차함수에 대해서 더 공부해보면 좋을 것 같습니다.
시간복잡도와 메모리에 대해서 한 번 더 찾아보시겠어요?
찾아보시고 각 고차함수별로 시간복잡도가 어떻게 되는지 설명 부탁드립니다.

## ✅ 해결이 되지 않은 점
> 없습니다.

## ✅ 조언을 얻고 싶은 부분
> 없습니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ 요구사항에 맞춰 프로젝트 작성하기
요구사항에 맞게 딕셔너리에 적절한 Key에 따른 적절한 Value를 넣어주고 계십니다. 멋집니다!
각각의 회차별 로또 번호도 다 다릅니다. 멋집니다!
옵셔널을 안전하게 추출한 점 역시 멋집니다!

### 2️⃣ 해당 브랜치에 PR보내기
본인의 해당 브랜치가 아닌 main브랜치에 PR을 보내주셨습니다. 멋집니다!

### 😄
나날이 코드가 발전해가네요.
정말 많이 성장하셨음이 느껴집니다. 항상 화이팅입니다.

리뷰 반영해주시고 DM주시면 merge해드리겠습니다.

2023-10-19 07:57 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	var savedLotto = [String: [Int]]()
`[String: [Int]]()`를 사용하여 정해진 타입의 빈 딕셔너리를 만들어주고 계십니다. 멋집니다!

2023-10-19 07:57 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	let saveLottos = saveLottoNumbers(totalCount: totalCount)
`saveLottos`라는 네이밍은 동사로 시작하고 있네요.
상수나 변수명은 명사형이 좋습니다.
참고로 말씀드리자면, 다른 메서드라면 내부에서 같은 네이밍을 사용해도 될 것 같습니다.

2023-10-19 07:57 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	let getCountLotto = saveLottos["\(userCount)회차"]
마찬가지로 `getCountLotto`역시 동사로 시작하고 있네요.

2023-10-19 07:57 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	guard let getCountLotto else { return print("\(userCount)회차는 아직 진행되지 않았습니다.") }
딕셔너리의 value는 옵셔널인가보군요!
guard문을 이용하여 잘 바인딩 해주셨습니다!
다만, 이렇게 쓰는 것이 더 자연스러울 것 같습니다.

```suggestion
        guard let getCountLotto else {
            print("\(userCount)회차는 아직 진행되지 않았습니다.")
            return
    }
```

2023-10-19 07:57 UTC, Rhode-park commented on CodeStarterCamp_Week2/main.swift
> +	let removeBraces = getCountLotto.map {String($0)}.joined(separator:", ")
`removeBraces`라는 내용보다는 해당하는 회차 로또 번호의 String이라는 것을 표현하면 좋을 것 같습니다.

2023-10-20 06:39 UTC, ungchun commented on CodeStarterCamp_Week2/main.swift
> +	guard let getCountLotto else { return print("\(userCount)회차는 아직 진행되지 않았습니다.") }
아 그러네요.. return이 뒤로 가야하네요!

2023-10-20 06:41 UTC, ungchun commented
map, filter, reduce 전부 O(n)의 시간복잡도를 가지네요!

추가로  https://jeong9216.tistory.com/403

해당 사이트를 보니 제가 평소에 궁금했던 내용들이 풀리더군요!
무조건 적인 고차함수는 오히려 더 안좋을 수도 있다는 걸 알게 됐습니다 :)

2023-10-23 07:58 UTC, merged