Week2 [STEP 2] lucie
yagom-academy/swift-starter-week2 pull request #627
Opened 2023-10-18 06:08 UTC by lucidly-lucie

@FirstDo 안녕하세요! 2주차 두번째 과제 제출합니다.

## 고민했던 점
- 내가 찍은 로또번호와 랜덤으로 생성된 로또 번호의 비교를 위해 intersection을 이용했습니다. Array와 Set은 컬렉션 타입이 다른데, intersection이 될까 고민하였는데 문제 없이 동작하는 것 같습니다.
- 처음에 matchedNumber 함수를 이용해서 겹치는 번호를 출력하니 [1, 3] 식으로 나와 예제와는 다른 것을 볼 수 있었습니다. 1, 3 식으로 출력하려면 Int가 아닌 String으로 출력해야 하는 것을 확인 한 후 검색해보니 for문을 이용하는 방법과 고차함수 map을 이용하는 방법 두가지 예제를 찾을 수 있었습니다.
- swift에서 제공하는 고차 함수를 이용하면 더 깔끔한 방식으로 구현할 수 있을 것 같아 map을 사용하여 openNmbers 함수를 생성하였습니다.

## 해결이 되지 않은 부분
- 고차함수 map 이용 시,
~~~
let openNumbers = matchedNumbers.map { String($0) }
~~~
이 부분만으로도 string으로 변환이 되었다고 생각하는데, 여기까지 작성하면 ["2", "6"] 입니다 식으로 표시가 되게 됩니다.
~~~
.joined(separator: ", ")
~~~
위의 , 표시까지 써주었을때 원하는 결과를 얻을 수 있었는데요, 이미 문자형인데 []대괄호가 왜 표시되는 것인지 궁금합니다. 
string으로 변환이 되었다는 것을 생각하면 그냥 26 입니다 이렇게 출력이 되지 않는걸까요?

## 조언을 얻고 싶은 부분
- 특별히 없습니다.

## 실행 결과
- 로또 당첨 시
~~~
축하합니다! 겹치는 번호는 4, 6 입니다!
~~~
- 로또 낙첨 시
~~~
아쉽지만 겹치는 번호가 없습니다.
~~~

2023-10-18 23:42 UTC, FirstDo requested changes
안녕하세요 lucie님! 
이번스탭 고생많으셨습니다!
로직을 깔끔하게 짜주시고 순서도가 명확해서 코드 보기가 편했어요

## 질문에 대한 답변

고차함수 map 이용 시,
let openNumbers = matchedNumbers.map { String($0) }
이 부분만으로도 string으로 변환이 되었다고 생각하는데, 여기까지 작성하면 ["2", "6"] 입니다 식으로 표시가 되게 됩니다.

.joined(separator: ", ")
위의 , 표시까지 써주었을때 원하는 결과를 얻을 수 있었는데요, 이미 문자형인데 []대괄호가 왜 표시되는 것인지 궁금합니다.
string으로 변환이 되었다는 것을 생각하면 그냥 26 입니다 이렇게 출력이 되지 않는걸까요?

---

우선 map 이라는 함수는 Array, Dictionary, Set 같은 CollectionType에 적용가능합니다

map은 컨테이너(쉽게 말하면 배열)이 가지고 있는 각각에 값에 대해 
클로져 ( map {   이부분  }  ) 로 전달받은 연산을 수행하여, 
결과를 새로운 컨테이너로 반환하는 것입니다

조금 더 자세히 써보면
matchedNumbers = [1, 2, 3, 4, 5, 6] 이라 할때
`matchedNumbers.map { String($0) }`의 의미는
($0은 element 하나 하나를 의미합니다)

각각의 원소에 String 연산을 적용한 후, 새로운 컨테이너로 반환하라는 말입니다
결과로는 `[String(1), String(2), String(3), String(4), String(5), String(5)]` 이 반환되겠죠?

그러니까 결과는 애초에 [String] 타입이었던 거죠
[String] 타입에 .joined 를 써서 얻은 결과가 String 타입인 거고요

option키를 누른 후, 변수를 눌러보면 실제 타입을 확인할 수 있습니다
<img width="840" alt="스크린샷 2023-10-19 오전 8 36 47" src="https://github.com/yagom-academy/swift-starter-Round2/assets/69573768/e915bd06-4584-49e7-abae-7d12b6125b2a">



더 자세한 내용은 밑의 링크 참석하시면 좋을것 같습니다
[Swift Map](https://developer.apple.com/documentation/swift/array/map(_:)-87c4d)

고차함수는 정말 많이 쓰는 개념이다보니
Map 말고도 다른 고차함수들 (filter, compactMap, flatMap, reduce)도 찾아보시면 좋을것 같네요!

2023-10-18 23:42 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +}
개행이 조금 이상한거 같아요..!

스타일은 다 다르겠지만, 보통 아래처럼 쓰는 편입니다

```swift
if condition {
// ...
} else {
// ...
}
```

```swift
if condition 
{
// ...
}
else 
{
// ...
}
```

2023-10-18 23:42 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +var lottoGameResult: Set<Int> = Set<Int>()
아래와 같은 초기화도 가능합니다

```swift
var lottoGameResult: Set<Int> = []
var lottoGameResult = Set<Int>()
```

2023-10-18 23:42 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +if matchedNumbers.count >= 1 {
`matchedNumbers.count >= 1` 보다는 `matchedNumbers.isEmpty` 가 좀 더 직관적일것 같습니다

2023-10-18 23:42 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
현재는 함수가 하나도 없고 로직이 모두 전역 범위에 쓰여있습니다.
전역변수 사용을 지양하고

함수로 나눠서 작성해주세요!
해야할 일을 적어본다음, 기능별로 나눠주시면 될것 같습니다

ex)
- 랜덤한 로또번호 6개를 만드는 함수
- 비교해서 결과를 출력하는 함수
등등..

2023-10-19 05:56 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
제가 개념을 명확하게 파악하지 못해 컬렉션을 만들면서 함수를 만든거라고 생각하고 있었네요.
- 로또 번호를 추천하는 함수
- 로또 번호를 맞추는 함수
- 내 로또번호를 받아서 결과를 실행하는 함수
위와 같이 함수를 분리해서 작성했습니다!

2023-10-19 05:57 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +if matchedNumbers.count >= 1 {
https://github.com/yagom-academy/swift-starter-Round2/commit/10b928840b21c65df6816c5b57d7a0a9b9d4a0ab
결과가 공백으로 나와서 당황했네요 ㅎㅎㅎ machedNumber.isEmpty일때 겹치는 번호 없음 출력으로 순서를 변경할까 하다가, ! 사용으로 풀이하였습니다.

2023-10-19 05:57 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +}
https://github.com/yagom-academy/swift-starter-Round2/commit/10b928840b21c65df6816c5b57d7a0a9b9d4a0ab
해당 내용 수정하였습니다.

2023-10-19 05:58 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +var lottoGameResult: Set<Int> = Set<Int>()
https://github.com/yagom-academy/swift-starter-Round2/commit/a6917f3e5fb104a8c907dc33c4e6e2c70b76ee50
var lottoNumbers: Set<Int> = [] 로 수정해보았습니다.

2023-10-19 07:00 UTC, FirstDo approved these changes
고생하셨어요!
코맨트는 한번 읽어보시고 다음스텝에서 적용 가능한 부분은 적용해보도록 합시다

2023-10-19 07:00 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +}
함수 분리 잘해주셨습니다
전체적으로 개행이나 들여쓰기가 안맞는 부분이 있습니다
일일히 신경써서 고쳐도 되고

command + a 로 코드를 전체선택한다음
control + i 로 한번에 고칠수도 있습니다

2023-10-19 07:00 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    if !matchedNumbers.isEmpty
! 는 가독성을 해친다고 생각하는 사람들도 있습니다
다만 컨벤션일 뿐이니 그냥 그런 의견도 있구나 라고 생각해주심 좋을거 같습니다
저는 아래와 같이 쓰는 걸 선호합니다

```swift
if matchedNumbers.isEmpty {
// 찾는 번호 없음
} else {
// 축하합니다
}
``

or

```swift
if matchedNumbers.isEmpty == false {
// 축하합니다
} else {
// 찾는 번호 없음
}
``

2023-10-19 07:00 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    let openNumbers = matchedNumbers.map { String($0) }.joined(separator: ", ")
`matchedNumbers` 라는 이름은 명확합니다
다만 `openNumbers`라는 네이밍이 조금 애매한거 같아요

2023-10-19 07:00 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    }
playLotto 매서드를 만든것 너무 좋습니다!

다만 matchedLotto 함수는 이름을보면, 로또를 비교만 해야합니다
지금은 matchedLotto 함수 내에서 LottoNumbers를 만들고 있죠?
그것보다는

matchedLotto 함수는 로또 넘버 두개를 받아서 비교하는 쪽으로 매서드를 짜시는게 이름과 더 맞는것 같습니다

2023-10-19 07:00 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
빼빼로는 draw가 맞지만
로또 넘버를 만드는건

generate or make 가 조금 더 적절할것 같네요!

2023-10-19 07:00 UTC, merged