Week2 [STEP 2] Cleon
yagom-academy/swift-starter-week2 pull request #631
Opened 2023-10-20 09:21 UTC by Orderlee

@minsson

## 고민했던 점
첫 순서도를 작성한것을 보고 Set 타입에 대해서 생각하고 공부했습니다.
처음에는 숫자 하나를 생성했을 때 마다 Set 타입 을 생성하는 방식으로 순서도를 생각했습니다.
하나의 Set 타입을 만들면 그 안에 값을 하나씩 쌓으면 되는 것이기 때문에 순서도 변경 및 코드 작성때도 반영했습니다.

---

## 해결이 되지 않은 점
-

---

## 조언을 얻고 싶은 부분
-

 ```<br/>

2023-10-20 14:59 UTC, minsson requested changes
Cleon님, 안녕하세요! 

STEP 1에서 아직 머지되지 않은 상태로 STEP 2의 코드가 커밋되고, 저도 그걸 놓치고 머지하다보니 이 PR에는 `main.swift`에 처음 STEP 2 코드를 구현했던 커밋은 포함되지 않고, 그 다음 커밋만 포함되었어요. 따라서 코드리뷰에서 기존 파일이 어떻게 수정되었는지만 볼 수 있어 원래와 같이 한 줄 한 줄 개별 코멘트를 달기는 어려워요.

따라서 이번 STEP 2에서만 PR 종합 코멘트에서 코드리뷰를 진행해보겠습니다. 


## 코드리뷰
```swift
func generateLottoNumbers() -> [Int] {
    var lottoNumbers: Set<Int> = Set<Int>() // 1️⃣
    while lottoNumbers.count < 6 {
        let randomNumber = Int.random(in: 1...45)
        lottoNumbers.insert(randomNumber)
    }
    let sortedLottoNumbers = lottoNumbers.sorted()
    return sortedLottoNumbers
}
```

아주 깔끔하네요. 네이밍도, 코드의 컨벤션도 전반적으로 좋습니다! 👏👏👏
다만 이건 취향의 문제일 수 있는데, 1️⃣ 부분에서 `Set<Int>`라는 타입을 명시했으니 이니셜라이즈할 때 `Set<Int>()`라고 하지 않고 `[]`라고 작성해도 좋겠다는 생각이 들어요. 이유는 Cleon님이 지금까지 코드를 작성하실 때 그런 컨벤션을 써오셨기 때문이에요.

```swift
let myLottoNumbers: [Int] = [1, 4, 27, 21, 40, 3]
```

좋습니다 👏👏👏

```swift
func lookMatchingNumbers() {
    let lottoResult = generateLottoNumbers()
    print("로또 당첨 번호: \(lottoResult)")
    let matchingNumbers = Set(myLottoNumbers).intersection(lottoResult)
    if Set(myLottoNumbers) != Set(lottoResult) {
        print("아쉽지만 겹치는 번호가 없습니다.") 1️⃣
    } else if  Set(myLottoNumbers) == Set(lottoResult) {
        print("축하합니다! 겹치는 번호는 \(matchingNumbers.sorted()) 입니다!") 2️⃣
    }
        // 👀 여기 개행은 불필요해 보이네요.
}
```

이 함수는 언뜻보면 무척 깔끔하게 작성된 코드 같지만, 큰 논리적 오류가 있네요! 웬만큼 실행해서는 1️⃣의 print문이 호출되지 않을 거예요. 말 그대로 로또에 당첨될 확률로 실행될 수 있는 상황 같네요 😅 어떻게 하면 이 문제를 해결할 수 있을까요?

2️⃣가 실행된다고 해도 결과물은 `축하합니다! 겹치는 번호는 [15, 40] 입니다!`처럼 나올텐데요, 요구사항에는 `축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!` 라고 나와있어요. 어떻게 하면 정확히 같은 포멧으로 print되게 만들 수 있을까요? 

```swift
lookMatchingNumbers()
```
이렇게 나눠서 보니 네이밍이 조금 모호하게 느껴지는 측면이 있네요. 매칭넘버를 보라...는 게 정확히 무슨 의미인지 이해하기 어려울 수 있을 것 같아요. 좀 더 명확하고 구체적인 단어를 쓰면 어떨까요?


## 추가 피드백
순서도와 코드의 내용이 일치하지 않아요. 코드를 수정하고, 순서도도 코드에 맞게 수정해주세요 ☺️

2023-10-21 02:45 UTC, Orderlee commented
- 이 함수는 언뜻보면 무척 깔끔하게 작성된 코드 같지만, 큰 논리적 오류가 있네요! 웬만큼 실행해서는 1️⃣의 print문이 호출되지 않을 거예요. 말 그대로 로또에 당첨될 확률로 실행될 수 있는 상황 같네요 😅 어떻게 하면 이 문제를 해결할 수 있을까요?
                -> 이 부분은 랜덤으로 생성되는 부분을 6으로 줄여서 출력 결과물을 알 수 있게 수정했습니다.

- lookMatchingNumbers() 함수 이름을  findMatchingNumbers로 수정했습니다.


- 겹치는 번호에 대한 출력도 수정했습니다.

- 순서도를 조금 수정했습니다.

2023-10-23 04:18 UTC, minsson requested changes
Cleon님, 수정하시느라 고생하셨습니다. 👏
다만 구현에 버그가 있어 다시 코멘트를 남겼으니 참고해서 수정 부탁드려요.
화이팅입니다! 🔥

2023-10-23 04:18 UTC, minsson commented on CodeStarterCamp_Week2/main.swift
> +    if myLottoNumbers != lottoResult {
지난 번 코멘트에서 피드백 드렸던 내용을 다시 가져와볼게요.
> 이 함수는 언뜻보면 무척 깔끔하게 작성된 코드 같지만, 큰 논리적 오류가 있네요! 웬만큼 실행해서는 1️⃣의 print문이 호출되지 않을 거예요. 말 그대로 로또에 당첨될 확률로 실행될 수 있는 상황 같네요 😅 어떻게 하면 이 문제를 해결할 수 있을까요?

저번 피드백에서는 일부러 조금 간접적으로 말씀드렸는데, 해당 부분이 수정되지 않아 코드에 직접 피드백을 남깁니다.
이 if문의 `myLottoNumbers != lottoResult`가 `true`가 되기 위해서는 6개의 번호가 모두 일치해야 해요. 6개의 번호가 모두 일치하지 않으면 몇 개가 일치하든 `print("아쉽지만 겹치는 번호가 없습니다.")`가 실행될 거예요. 프로그램의 요구사항과 맞지 않는 부분이에요.

이런 부분은 사실 코드를 작성하고 여러번 실행해봤으면 발견할 수 있었던 부분이라고 생각해요. 아무리 실행해봐도 `"아쉽지만 겹치는 번호가 없습니다."`만 떴을테니까요. 그래서 조금 아쉽습니다. 과제를 빠르게 진행하는 것도 좋지만 올바르게 작동하도록 구현하는 것이 더 중요합니다.

또, 현재 기준으로는 몇 번을 실행하든 실행 결과가 아래와 같을 거예요. 코멘트 이후 `randomNumber`를 구하실 때 `Int.random(in: 1...6)`을 사용하셨으니까요. 
```swift
로또 당첨 번호: [1, 2, 3, 4, 5, 6]
축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!
```

2023-10-23 04:18 UTC, minsson commented on CodeStarterCamp_Week2/main.swift
> +        let randomNumber = Int.random(in: 1...6)
요구사항과 맞지 않는 부분이네요. 
1부터 45까지의 범위로 다시 되돌려주세요. 😅

2023-10-23 04:18 UTC, minsson commented on CodeStarterCamp_Week2/main.swift
> +        let matchingNumbersString = matchingNumbers.sorted().map { String($0) }.joined(separator: ", ")
좋습니다. 👏👏👏
다만 한 줄에 너무 많은 `.`, `()`, `{}`들이 등장하다보니 가독성이 좋지 않아 보여요. 여러 줄로 나눠주시면 더 보기 좋을 것 같아요.

2023-10-23 04:18 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +}
Step 2의 PR이 진행 중인데 Step 3 내용을 커밋하고 푸쉬해주셨네요.
이렇게 되면 Step 3 PR에서 코드리뷰를 할 수 없을 거예요.
수정하면서 Step 3 관련된 코드는 모두 제거해주세요. 나중에 Step 2가 Merge되고 다시 포함시켜주시면 됩니다.

2023-10-23 04:18 UTC, minsson commented on CodeStarterCamp_Week2/main.swift
> +
불필요한 개행은 제거해주세요 👀

2023-10-26 14:59 UTC, merged