Week2 [STEP 3] lucie
yagom-academy/swift-starter-week2 pull request #633
Opened 2023-10-21 06:01 UTC by lucidly-lucie

## 고민했던 점
- 이전 코드에서 drawLottoNumber만 사용하였습니다. 
- lottoDrawHistory 함수를 만들어 draw 카운트가 5가 될 동안 drawLottoNumber를 실행하여 딕셔너리에 저장되게 하였습니다.
- searchHistory 함수를 만들어 생성된 lottoDrawHistory를 검색하고, if let 구문을 이용하여 안전하게 딕셔너리에서 값을 꺼내 올 수 있도록 하였습니다. 

## 해결이 되지 않은 부분
- 과제의 실행 결과가 정상적으로 작동하였다고 생각하였으나, 혹시나 하는 마음에 print(lottoDrawHistory)도 같이 넣어 3회차의 결과가 맞는지 출력해보았습니다.
~~~
["5회차": Set([23, 36, 21, 12, 19, 5]), "1회차": Set([15, 32, 23, 7, 24, 29]), "3회차": Set([44, 19, 42, 4, 7, 17]), "4회차": Set([13, 27, 44, 45, 24, 30]), "2회차": Set([19, 34, 6, 41, 42, 43])]
3회차의 로또 당첨 번호는 13, 28, 37, 39, 34, 36 입니다.
~~~
- 위 결과를 볼때, lottoDrawHistory에서 실행된 결과를 searchHistory에서 가져온다고 생각하였었는데, 각각 새로 생성하는 것을 알 수 있었습니다.
- 상식적으로 생각하면, 한번 생성된 딕셔너리가 있으면 회차별 결과 조회에 쓰던 당첨 조회를 할 때 쓰던 동일한 결과를 보여줄 수 있어야 할 것 같은데요. 제가 작성한 코드가 이 부분을 해결할 수 없는 것 같습니다. 
- 처음 번호를 생성해서 저장할 때 빼고는 let으로 불변을 사용하고 있다고 생각했는데, 왜 이렇게 되는걸까요? 이 부분을 어떻게 해결해야 할 지 잘 모르겠습니다.

## 조언을 얻고 싶은 점
- 함수 네이밍까지는 괜찮은데, 변수 네이밍으로 갈수록 어려워지는 것 같습니다. 특히 stringResultNumbers = resultNumbers.map 같은 케이스 같이, 동일한 기능을 하면서 단순히 String으로 바꿔서 다시 저장하는 것 뿐인데... 이름을 특징 있게 붙이기가 어려운 것 같아요.

## 실행 결과
- 히스토리가 있는 회차 조회 시
~~~
3회차의 로또 당첨 번호는 6, 1, 32, 13, 28, 20 입니다.
~~~
- 히스토리가 없는 회차 조회 시
~~~
7회차의 결과가 없습니다.
~~~

2023-10-21 07:40 UTC, FirstDo requested changes
안녕하세요 luice님!
2주차의 3번째 과제 정말 고생 많으셨습니다!

전체적으로 코드를 잘 작성해 주셨으나 함수를 좀 더 명확히 분리해 주시면 더 좋을것 같습니다

**😅 그리고 PR을 main branch에 보내셨습니다..! 수정부탁드려요**

## 해결이 되지 않은 부분

![스크린샷 2023-10-21 오후 4 28 23](https://github.com/yagom-academy/swift-starter-Round2/assets/69573768/ecaa064c-2528-4bc9-906e-b229e69061d9)

우선 로직은 문제가 없고 잘 짜신것 맞습니다.
그리고 실행된 결과를 가져오는것도 맞습니다.

만드신 `lottoDrawHistory` 라는 함수는 호출할때마다 
랜덤한 로또번호가 들어가있는 count = 5 인 딕셔너리를 만듭니다.

두번 호출하면 어떻게 될까요?
아래 result1, result2의 결과는 당연히 다를 수 밖에 없습니다.

```swift
let result1 = lottoDrawHistory()
let result2 = lottoDrawHistory()
```

실제로 해당 매서드를 한번만 호출하면 당연히 예상했던 결과를 보입니다

```swift
func searchHistory(회차: String) {
    let lottoResult = lottoDrawHistory()
    print(lottoResult)
    // ...
}
```

```
["3회차": Set([11, 27, 30, 43, 15, 26]), 
"4회차": Set([23, 18, 32, 28, 1, 26]), 
"5회차": Set([16, 32, 30, 40, 14, 37]), 
"2회차": Set([4, 3, 31, 9, 29, 21]), 
"1회차": Set([27, 45, 10, 36, 37, 31])]

3회차의 로또 당첨 번호는 11, 27, 30, 43, 15, 26 입니다.
```

![스크린샷 2023-10-21 오후 4 28 46](https://github.com/yagom-academy/swift-starter-Round2/assets/69573768/e1b653c7-670a-4c87-a96d-e8d9a3604284)

사실 이거 같은 경우 답은 없고, 원래 `타입`을 변수에 넣는건 지양하는 편이긴 합니다만,
그래도 꼭 넣어야 한다면 영문법상으로는 `resultNumbersString` 이 더 맞는것 같네요..!

아래 문서가 생각보다 되게 잘 나와있습니다!
[Swift API Naming Guide](https://www.swift.org/documentation/api-design-guidelines/#naming)

코드를 계속 짜고, 다른 사람 코드도 많이 보다보면 좀 더 감을 더 잡으실 수 있을것 같습니다!


더 자세한 내용은 코맨트로 달았으니 확인 부탁드려요~

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> + */
지워주세요!
아니면 이전 STEP의 경우 파일을 분리하는것도 좋은 방법입니다

STEP1.swift
STEP2.swift
STEP3.swift
main.swift

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
함수 네이밍에 있어서 로또번호는 그리는 (draw)것은 아닌것 같습니다.

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    return lottoNumbers
랜덤으로 6개의 번호를 만드는 방법은 아래처럼도 가능합니다!
방법은 다양하니 그냥 이런방법도 있구나.. 참고하시면 좋을것 같아요

```swift
let numbers = (1...45).sorted()[0..<6]
```

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +func lottoDrawHistory() -> Dictionary<String, Set<Int>> {
함수이름은 동사로 시작하는게 좋습니다
그리고 draw라는 네이밍은 로또랑은 잘 안맞는것 같아요..!

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +        let saveLottoNumbers = drawLottoNumbers()
반대로 변수 이름은 일반적으로 동사로 시작하지 않습니다
`saveLottoNumbers` 보다 영문법상 `savedLottoNumbers` 가 더 자연스럽습니다

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    }
이런 경우에는 while문보다 for문이 더 적합할것 같습니다
코드를 한번 작성해보시면 왜 그런지 확인하실 수 있을것 같아요!

현재는 drawCount라는 변수를 하나 더 선언해야 하는데 for문으로 바꾸면 그럴 필요가 없습니다

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    var NumberHistory: Dictionary<String, Set<Int>> = [:]
첫글자는 소문자로 바꿔주세요~

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +func searchHistory(회차: String) {
한글을 쓰는게 불가능 한것은 아니나, 특별한 이유가 없지 않는 이상 영어로 작성하는게 좋을것 같네요

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +}
현재는 searchHistory 라는 함수에서
- 로또 번호를 만들고
- 특정 회차를 찾은다음 결과를 출력하고 있습니다

함수가 하는 일이 너무 많은것 같아요. 네이밍에 맞는 일을 하는게 중요합니다

2023-10-21 07:40 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    }
아래처럼 쓸수도 있습니다.
정답은 없고 본인만의 기준을 갖는게 중요할 것 같네요

```swift
guard let resultNumbers = lottoResult[회차] else {
  print("\(회차)의 결과가 없습니다.")
  return 
}

let stringResultNumbers = resultNumbers.map { String($0) }.joined(separator: ", ")
print("\(회차)의 로또 당첨 번호는 \(stringResultNumbers) 입니다.")
```

2023-10-21 16:15 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
앗...draw는 추첨의 의미입니다. draw lotto, draw game 등으로 사용하고 있는것으로 알고있습니다.

2023-10-21 16:15 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +    return lottoNumbers
넵 알겠습니다~!

2023-10-21 16:23 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +}
해당 부분의 코멘트가 잘 이해가 되지 않아 문의드립니다.
저는 로또 번호는 drawLottoNumbers에서 생성하고, lottoDrawHistory에서 딕셔너리 형태로 저장하고, 최종적으로 searchHistory에서 이전에 만든 함수를 가져다가 if let 구문으로 반환처리만 하고 있다고 생각해서 작성한 코드인데요, 
혹시 let lottoResult = lottoDrawHistory()처럼 변수로 다시 한번 저장해서 그런 말씀을 하시는 걸까요?
그렇다면 아래와 같이 수정하면 특정 회차를 찾은다음 결과를 출력하는 역할만 하는 것이 되는지 궁금합니다.
~~~
func searchHistory(회차: String) {
    if let numbers = lottoDrawHistory()[회차] {
    {
        let stringResultNumbers = resultNumbers.map { String($0) }.joined(separator: ", ")
        print("\(회차)의 로또 당첨 번호는 \(stringResultNumbers) 입니다.")
    }
    else
    {
        print("\(회차)의 결과가 없습니다.")
    }
}
~~~

2023-10-21 16:37 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +    }
guard let ~ 형식으로도 사용할 수 있군요.
혹시 정답이 있는게 아니지만, 두두께서는 왜 guard let을 쓰는게 더 낫겠다고 판단하신건지 궁금합니다!

2023-10-21 16:56 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
https://github.com/lucidly-lucie/swift-starter-Round2/commit/f3988cc0164923ae4254827e587690e4e9eda37c
해당 커밋으로 수정하였습니다.

2023-10-21 16:57 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
https://github.com/lucidly-lucie/swift-starter-Round2/commit/f3988cc0164923ae4254827e587690e4e9eda37c 으로 수정하였습니다!

2023-10-21 16:58 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +func lottoDrawHistory() -> Dictionary<String, Set<Int>> {
https://github.com/lucidly-lucie/swift-starter-Round2/commit/d30df9050717b509a2b02c439d541f0c668919b3 해당 내용 record 동상를 사용하는 recordLottoNumber로 수정하였습니다

2023-10-21 16:59 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +        let saveLottoNumbers = drawLottoNumbers()
https://github.com/lucidly-lucie/swift-starter-Round2/commit/d30df9050717b509a2b02c439d541f0c668919b3
해당 부분 for in으로 변경되며 삭제되었습니다.

2023-10-21 16:59 UTC, lucidly-lucie commented on CodeStarterCamp_Week2/main.swift
> +    }
https://github.com/lucidly-lucie/swift-starter-Round2/commit/d30df9050717b509a2b02c439d541f0c668919b3
해당 부분 수정되었습니다

2023-10-22 09:18 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +    }
guard, if 의 문제가 아니라, if - else 의 문제입니다

if - else 구문은 무조건 1 depth가 생기지만, 
guard let 구문은 else 문을 제외하면 아래 코드는 별도의 괄호 없이 써 나갈 수 있기 때문입니다

현재는 코드가 간단하지만 더 복잡하게 작성될 수도 있겠죠?

이런코드보단
```swift
if condition1 {
  return 
} else {
 if condition1 {
   return
 } else {
  // do something
 }
}
```

이런 코드가 더 좋습니다
```swift
if condition1 {  return }
if condition2 { return }

// do something

```

`early return` 이라는 패턴이 있습니다. 
https://www.hackingwithswift.com/new-syntax-swift-2-guard

2023-10-22 09:23 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +}
아 우선 무조건 수정하실 필요는 없습니다
그리고 제 의견일 뿐인걸 감안하시고 읽어봐주심 좋을것 같네요!

저장여부는 상관이 없는것 같습니다
`searchHistory` 함수에서 `lottoDrawHistory` 함수를 호출하는거 자체가 어색합니다.
특정회차 검색 함수에서 로또 히스토리를 생성하는것 자체가 어색하다고 느꼈습니다.
만드는 함수는 만드는것만하고, 검색하는 함수는 검색만 하는게 좋습니다.

아래처럼 분리하는걸 의도하긴 했습니다 ㅎㅎ

```swift
func start() {
  let history = lottoDrawHistory()  // 히스토리를 만든다
  search(history: [String: Set<Int>], 회차: Int)   // 히스토리에서, 특정 회차를 검색한다
}
```

2023-10-22 09:24 UTC, FirstDo commented on CodeStarterCamp_Week2/main.swift
> +func drawLottoNumbers() -> Set<Int>{
그리다 라는 뜻만 있는줄 알았네요!!

2023-10-22 09:26 UTC, FirstDo approved these changes

2023-10-22 09:29 UTC, merged