Week2 [Step3] Cleon
yagom-academy/swift-starter-week2 pull request #639
Opened 2023-10-27 01:51 UTC by Orderlee

@minsson 

step3 입니다.

2023-10-27 15:44 UTC, minsson requested changes
Step 2 Week 3 수행하시느라 고생하셨어요!
이번 스텝은 워낙 간단하고, 코드도 잘 작성해주셔서 간단하게 피드백해보았습니다! ☺️

2023-10-27 15:44 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +    let previousRound = lottoResults.keys.count + 1
👏👏👏

2023-10-27 15:44 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +        let randomNumber = Int.random(in: 1...6)
```suggestion
        let randomNumber = Int.random(in: 1...45)
```

2023-10-27 15:44 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +    let lottoResultString = lottoResult.sorted().map { String($0) }.joined(separator: ", ")
개행의 기준이 무엇인가요?

2023-10-27 15:44 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +var lottoResults: [String: Set<Int>] = [:]
Value의 타입이 Set<Int>인 이유는 무엇인가요? [Int] 타입을 넣어도 될 것 같은데, 각 경우에는 어떤 차이가 있을까요?

2023-10-30 08:40 UTC, Orderlee commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +var lottoResults: [String: Set<Int>] = [:]
set은 중복을 걸러내기 때문에 로또 번호 생성 규칙에 적합하여 사용 했습니다. int를 사용했을 경우에는 중복된 숫자가 나올 수 있기 때문에 로또 규칙에 적합하지 않아 적합하지 않습니다.

2023-10-30 09:04 UTC, Orderlee commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +    let lottoResultString = lottoResult.sorted().map { String($0) }.joined(separator: ", ")
기준없이 let 상수 선언 후 
개행을 해버렸습니다. 
불필요한 개행에 대해서 말씀하셨었는데 다시 해버렸습니다. 주의하겠습니다.

2023-10-30 11:12 UTC, minsson commented on CodeStarterCamp_Week2/step3/step3/main.swift
> +    let lottoResultString = lottoResult.sorted().map { String($0) }.joined(separator: ", ")
넵..! 그리고 제가 코멘트를 남겼던 것 같은데 안 남아 있네요..! 😅 그래서 다시 한번 작성합니다.
`let lottoResultString = lottoResult.sorted().map { String($0) }.joined(separator: ", ")` 같은 코드는 가독성이 떨어집니다. 

아래와 같이 길게 풀어 써보는 연습을 해보는 것이 좋습니다. 코드의 길이가 길어져 불편해보일 수 있지만 변수명과 타입 명시를 통해 어떤 과정을 통해 어떻게 변화하는지 더 읽기 쉬워진다는 장점이 있습니다.
```swift
let sortedLottoResultNumbers: Set<Int> = lottoResult.sorted()
let sortedLottoResult: [String] = sortedLottoResult.map { String($0) }
let formattedLottoResult: String = sortedLottoResult.joined(seperator: ", ")
```

또, 아래와 같은 컨벤션으로 쓰는 방법도 있습니다. Cleon님, 그리고 Cleon님과 협업할 동료들이 아래 같은 코드를 쉽게 읽을 수 있다면, 굳이 첫번째 방법처럼 길게 쓰지 않아도 될 수 있습니다. 
```swift
let formattedLottoResult: String = lottoResult
    .sorted()
    .map { String($0) }
    .joined(separator: ", ")
```
코드에 정답은 없기에 선택은 Cleon님의 몫입니다 ☺️

2023-10-30 11:13 UTC, minsson commented
Cleon님, 지난 5주 동안 고생하셨습니다. ☺️
캠프에서의 시간이 Cleon님에게 도움이 되었기를 바랍니다.
앞으로도 화이팅입니다! 🔥

2023-10-30 11:14 UTC, merged