Round2[Step1] - kunhee
yagom-academy/swift-starter-week2 pull request #676
Opened 2024-01-02 04:17 UTC by Revolutionary-kunhee

첫번째 커밋에 순서도를 간단하게 만들어 보았습니다! 
(두번째 코드는 학습 중 발생한 낙서 코드를 제거하였습니다. )

2024-01-02 06:11 UTC, jaemuYeo commented
학습도우미 태그가 되어있지 않네요~

2024-01-02 06:21 UTC, Revolutionary-kunhee commented
앗 감사합니다! 수정했습니다!

2024-01-02 12:37 UTC, havilog requested changes
스탭1 수고하셨어요!

2024-01-02 12:37 UTC, havilog commented on lotto_순서도.jpeg
안녕하세요 건희님!
아래 순서도를 작성해주셨는데요,
해당 순서도는 순서도의 역할 보다는 코드의 역할에 더 가까운거 같아요!
어떤 경우에 어떤 행동을 해야하는지, 조건에 만족하는지 등을 코드 없이 그려보시면 좋을 듯 합니다!

또한 1~45 중 랜덤한 숫자를 뽑는 방식에는 말씀하신 것처럼 하는 방법도 있지만,
중복 제거를 위해서 1...45가 들어가 있는 배열을 셔플 돌린뒤에 출력하는 방법도 있을 듯 하네요 : )

2024-01-03 02:20 UTC, Revolutionary-kunhee commented on lotto_순서도.jpeg
순서도 수정하여 다시 올렸습니다!!

2024-01-03 02:21 UTC, Revolutionary-kunhee commented
Step1 순서도 수정 및 Step2 코드 올렸습니다!

2024-01-09 00:59 UTC, merged