Round2[Step1]
yagom-academy/swift-starter-week2 pull request #686
Opened 2024-01-07 03:34 UTC by jimin387

2024-01-07 03:36 UTC, jimin387 commented
@havilog

2024-01-07 06:12 UTC, havilog reviewed
순서도에는 Set[]이라고 표현하기 보다는, 로또 당첨번호 후보들 정도로 표현하면 어떨까요?
어떠한 Set인지 모호해보여서요 ㅎㅎ

2024-01-08 06:16 UTC, JIMIN-iOSDev commented
@havilog
No exact matches in call to instance method 'joined' 이런 에러가 joined 메소드를 작성한 행에서 뜨는데 해결을 하지 못했습니다.

2024-01-08 13:12 UTC, havilog requested changes
고래님 수고하셨어요 : )

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +        let sameNumbers: String = result.map {String($0)}.joined(seperator: ", ")
> No exact matches in call to instance method 'joined' 이런 에러가 joined 메소드를 작성한 행에서 뜨는데 해결을 하지 못했습니다.

separator에 오타가 있어서 함수 이름을 찾지 못하는거 같습니다.

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +        let sameNumbers: String = result.map {String($0)}.joined(seperator: ", ")
중괄호에는 한 칸씩 띄워주시는게 좋을 거 같습니다!
```suggestion
        let sameNumbers: String = result.map { String($0) }.joined(seperator: ", ")
```

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +        let sameNumbers: String = result.map {String($0)}.joined(seperator: ", ")
```suggestion
    let sameNumbers: String = result.map(String.init).joined(separator: ", ")
```
요렇게 쓰면 더 읽기 쉬울거 같아요!

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +    if result.count == 0 {
```suggestion
    if result..isEmpty {
```
로 써보는건 어떨까요?

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +    }
Int.random을 사용하는것도 좋지만,
let candidates: [Int] = Array(1...45)
로 만들고, 섞은 뒤에 하나씩 뺀다면 중복되지 않은 수가 나오면서 while문을 적게 돌릴 수 있을거 같아요!

요건 틀린건 아니구 취향차이입니다 ㅎㅎ

2024-01-08 13:12 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +func checkLottoNumbers(myNumbers: Set<Int>, matching: Set<Int>) {
matching이라는 단어보다는 당첨 번호를 뜻하는 워딩을 사용해보면 어떨까요?

2024-01-09 05:29 UTC, merged