Round2[Step3] - 고래안고래
yagom-academy/swift-starter-week2 pull request #702
Opened 2024-01-21 00:17 UTC by jimin387

step3 제출합니다.
브랜치를 새로 생성해서 보냈는데 맞게 보낸게 맞을까요?

2024-01-21 00:26 UTC, jimin387 commented
@havilog

2024-01-22 02:59 UTC, havilog requested changes
구현하시느라 고생하셨어요~!

2024-01-22 02:59 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +    roundNumbers["\(Round)회차"] = lottoNumbers
로또 번호를 만드는 함수 / 
만들어진 로또 번호를 라운드에 추가하는 함수(혹은 로직) / 
로또 번호를 만든 뒤 라운드에 추가하는 함수

이렇게 세개를 분리해보는건 어떨까요?

2024-01-22 02:59 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +var roundNumbers: Dictionary<String, Set<Int>> = [String: Set<Int>]()
roundNumbers의 키값을 String으로 하신 이유가 있을까요?
"회차"라는 postfix가 붙어서 들어가야하고, 그렇게 되면 휴먼에러가 발생할 수도 있을거 같아서요!

2024-01-22 02:59 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +var Round: Int = 0
변수 이름의 시작은 소문자로 해주세요~

2024-01-22 02:59 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(lottoNum.map(String.init).joined(separator: ", ")) 입니다.")
딕셔너리에서 값을 못가져 왔을 때 처리도 해보시면 어떨까요?

2024-01-22 02:59 UTC, havilog commented on CodeStarterCamp_Week2/main.swift
> +var roundNumbers: Dictionary<String, Set<Int>> = [String: Set<Int>]()
```suggestion
var roundNumbers: [String: Set<Int>] = .init()
```
요즘 컨벤션은 Dictionary를 명시하지 않는 걸로 알고 있어요 ㅎㅎ

2024-02-05 01:24 UTC, closed without merging