[Round 2/Step 1] - Crois
yagom-academy/swift-starter-week2 pull request #759
Opened 2024-07-08 09:32 UTC by Crois0509

@yagom 
안녕하세요 Crois 입니다.
week2 첫 번째 미션을 제출합니다.

## 고민했던 점
### 순서도에 담을 내용
- 지난 수업에서 들은 내용들을 토대로 순서도 내에 어떤 내용을 담아야 순서도만 보고도 즉시 코드를 작성할 수 있게 만들 수 있을지 고민했습니다.
- 머릿속으로 코드를 구상하며 어떤 코드를 입력하면 로또번호랜덤생성기 코드를 무사히 작성할 수 있을지 고민했습니다.
- 구상한 코드를 메모하며 어떤 순서도를 그릴지 구상했습니다.

## 해결이 되지 않은 점
### 무엇이 옳은 순서도인가?
- 배운 내용을 토대로 순서도를 작성하고는 있지만, 제가 작성하는 순서도가 과연 옳은 내용일까 모르겠습니다.
- 어떤 변수 혹은 함수를 넣고, 어떤 도형을 사용하여 작성하면 좋을지 아직 명확히 구상을 할 수가 없습니다.

## 조언을 얻고 싶은 부분
### 랜덤한 숫자를 호출하기
- 이번 과제에서 로또번호를 생성하기 위한 조건 중 하나로 "1~45의 랜덤한 숫자"라는 조건이 있었습니다.
- 인터넷을 찾아보니 랜덤한 숫자를 호출하는 코드의 종류가 여럿 있는 것을 확인했지만, 배운 내용 안에서 해결할 수 있지 않을까 싶어 고민해 보았습니다.
- 결론적으로 for-in 반복문으로 1~45의 숫자를 Set<Int> 컬렉션 타입에 insert 하면 Set 컬렉션의 특성인 내부 멤버가 순서대로 배치되지 않는 점을 활용하기로 했습니다.
- 6개의 숫자만 남기는 것은 while 반복문으로 Set.count 가 6 보다 크다면 Set.removeFirst 를 반복하게끔 하였습니다.
- 이 방법만이 정답이 아니라고 생각합니다. 때문에 혹시 다른 접근 방법이 있다면 조언을 얻고 싶습니다.

2024-07-09 06:10 UTC, jaemuYeo requested changes
안녕하세요 crois님!! Round2 입성을 축하합니다 🎉
순서도 작성하는 것이 쉬운일이 아니죠?? 
하지만 논리적 사고를 키우기위해, 코드의 흐름을 한눈에 파악하기 위해, 훗날 내 코드의 동작을 기록으로 남기기위해 등등
여러 방면에서 플로우차트 작성은 매우 중요합니다! 특히 처음 프로그래밍을 접하는 시기에서는요~
저도 알고리즘 공부하며 종종 노트를 펴놓고 손으로 써가며 그릴때가 있어요 :)

먼저 말씀드리고 싶은 것은 흐름도에 변수와 자세한 설명은 생략해도 된다고 생각합니다!
최대한 간결하고, 누가봐도 이해할 수 있을정도로 한눈에 파악하기 쉽게 작성하는 것이 베스트인 것 같아요.

## 도형 관련
도형은 잘 선택해주신 것 같아요!
동작을 수행하는 함수와 조건이 필요한 부분과 시작과 끝 모두 완벽합니다 👍

## 흐름도를 그리기 전
흐름도를 그리기 전에 사람의 언어로 의사코드를 먼저 작성해보면 좋을 것 같아요.
시작 -> 1 to 45의 숫자를 랜덤으로 생성 -> 컬렉션에 저장 -> 컬렉션에 여섯개의 숫자가 저장되었나? -> Yes or No

이렇게 작성하게 된다면 위의 의사코드를 그대로 도형안에 집어넣으면 된답니다!
한번 Try 해보세요 💪

아참 그리고 태그를 야곰으로 해주셨는데 다음 PR 및 코멘트에는 저를 태그해주세요!

2024-07-09 09:01 UTC, Crois0509 commented
@jaemuYeo 
태그를 하는 과정에서 실수가 있었네요 죄송합니다.
말씀하신 대로 순서도에 함수나 변수명 등을 제외하고
좀 더 단순화 시켜보았습니다.

2024-07-09 09:03 UTC, Crois0509 reviewed
남겨주신 코멘트를 확인하고
순서도를 조금 더 간결하고 알아보기 쉽게 수정하였습니다.

2024-07-10 02:30 UTC, jaemuYeo reviewed
전보다 훨씬 가독성이 좋아지고 로직도 스텝2의 의도와 가까워진 것 같습니다 👍
다만 조금 수정이 필요할 것 같아 그 부분에 대해 남겨드리며
merge 진행하겠습니다!

```swift
// Hint
시작
1에서 45 사이의 숫자를 랜덤하게 생성
Set 컬렉션 에 저장
(여기서 1~45 사이 숫자인지 판단하고 있는데 실제 구현할때 코드로 작성되지 않으니 생략)
Set 컬렉션에 여섯개의 숫자가 담겨잇는가?
No라면 처음부터 Yes라면
Set컬렉션의 여섯개 숫자 반환
종료
```
개선할 부분 수정 후 이어서 코드 작성하시면 되겠습니다 💪
어렵다면 코드를 작성하며 플로우차트를 수정하는 방법도 좋습니다!

2024-07-10 02:31 UTC, merged