[Round 2/Step 2] - Crois_R01
yagom-academy/swift-starter-week2 pull request #761
Opened 2024-07-11 07:24 UTC by Crois0509

@jaemuYeo 
안녕하세요. 코멘트 해주신 내용을 보고
플로우 차트 및 코드 수정하였습니다.
또, 말씀하신대로 브랜치를 분리하여 git push 해보았는데 이렇게 하는게 맞을까요?
코드에 대해서도 main 과 step 을 분리해 두었는데 이렇게 하면 되는지 확인 부탁드립니다.

## 코멘트에 대한 답변
### 왜 Set의 첫번째 요소를 제거하려고 했나요?
- Step 2를 pull-request 했을 때 적은 내용입니다만, 랜덤한 숫자를 생성하는 코드를 사용하지 않고, Round2의 Step2 내용에 도달하기까지 배운 내용만을 활용하여 랜덤한 숫자를 생성할 수 있도록 하고싶었습니다.
- 이때, Set 컬렉션이 내부에 멤버들을 입력된 순서와 무관하게 순서를 배치하는 것을 이용하기로 했습니다.
- 때문에 먼저 Set 컬렉션에 1~45의 숫자를 입력하고, 내부 멤버가 6개가 남도록 만들어야 했기에 6개가 될 때까지 첫번째 멤버를 제거하도록 코드를 작성했습니다. 이는 멤버 수가 6개만 되면 되기에 마지막 멤버를 제거해도 되고, 어느 멤버를 제거하든 내부 멤버가 6명이 남기만 하면 되는 코드입니다.
- 이렇게 하면 Set 컬렉션 내의 멤버는 무분별하게 정렬되어 있는 상태에서 앞에서부터 39개의 멤버가 제거되고, 이로 인해 남은 6개의 멤버가 로또 번호가 되도록 하는 것을 유도했습니다.

### 현재 겹치지 않을 경우의 결과만 나오고 있습니다. 왜 이런 결과가 나올까요?
- 이는 myLottoNumber 변수에 [1, 2, 3, 4, 5, 6] 이라는 임의의 숫자를 넣어두었기 때문입니다.
- 우연히라도 Set 컬렉션 내의 숫자가 [1, 2, 3, 4, 5, 6]로 남게 되지 않는 이상 겹치지 않는 결과만이 나올 것입니다.
- 혹시나 오류가 있는지 확인하기 위해 myLottoNumber 변수를 winningNumberOfLotto 의 값과 같게 하였을 경우 결과 값으로 print("축하합니다! 겹치는 번호는 \(myLottoNumbers) 입니다!")가 출력되는 것을 확인할 수 있었습니다.
- 또, 이번에 코드를 수정하며 randomNumberGeneratorOfLotto 의 함수에 매개변수로 myLottoNumber 를 입력하도록 수정하였습니다.

2024-07-12 06:39 UTC, jaemuYeo requested changes
브랜치 분리는 잘 되었습니다 👍
crois님의 원격저장소에도 최종 결과물을 main브랜치에 merge하는 시도도 해보면 좋을 것 같아요!
다만 PR이 이전에 보냈던 것과 별개로 새롭게 다시 보내진 것 같아요~

## 코드
아직까지 스텝2의 구현 의도와 다르게 로직이 작동하고 있는 것 같습니다!
랜덤한 숫자와 나의 숫자 여섯개가 모두 동일해야 겹치는 문구를 프린트하는 것이 아니라
매칭된 숫자가 하나만 있더라도 겹치는 문구를 프린트 해주어야해요.

여섯개의 숫자 중 단 하나라도 없을 경우만 `아쉽지만 겹치는 번호가 없습니다`라는 문구를
프린트해주세요!

Hint. 
- Step1의 코드를 사용할 것(랜덤하게 숫자 생성하는 함수)
- 함수의 반환 타입 활용하기

숙제
- 겹치는 번호가 나오는 프린트 문구 캡처하여 다음 코멘트에 이미지로 남겨주기

아직 구현이 완전히 이루어지지 않았기에 스텝2의 예시 결과와 동일하게
결과물이 나온 이 후 코드를 살펴보겠습니다!

2024-07-12 07:15 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님.
코멘트 해주신 내용을 토대로 코드를 수정했습니다.
제가 지문을 잘못 이해하고 있었네요. 저는 모든 숫자가 동일해야만 출력하는 조건이라고 생각하고 있었습니다.
코드를 수정하여 겹치는 숫자가 있을 경우 해당 숫자를 출력하도록 변경하였습니다.
겹치는 숫자가 있을 때의 출력 결과를 사진으로 첨부합니다.

git 에 대해 아직 헷갈려서 더 공부가 필요할 것 같아요.
branch 분리를 하고 origin도 새로운 브랜치로 옮겨버리는 바람에 새로운 PR로 보내진 것 같습니다.
이전 PR은 삭제하는게 좋을까요?
또, Merge 는 병합이라고 알고 있는데,
예를 들어 제가 Step1 브랜치를 만들고 작업을 완료한 후
Step1 브랜치에 add 및 commit 을 하고 main에 merge 하는 순서일까요?
merge를 실행하는 타이밍이 어려워 질문을 남깁니다.

![스크린샷 2024-07-12 오후 4 05 18](https://github.com/user-attachments/assets/5ef3f7ba-2879-4997-9ac6-565edce231f5)

2024-07-12 07:18 UTC, jaemuYeo commented
클로즈하기 전 이전 코멘트를 참고할 수 있으니 일단 그대로 두겠습니다!

첨부해 주신 이미지 확인했습니다 :)
프로젝트의 실행 예시와 다른 부분을 확인하여 구현 후 다시 한번 검토하겠습니다!

2024-07-15 13:30 UTC, Crois0509 commented
@jaemuYeo 
잼킹님 말씀하신 대로 Step 2의 의도에 맞도록,
출력결과가 올바르게 나오도록 코드를 수정했습니다!

## 조언을 구하고 싶은 점
### 배열에서 값을 꺼내기
이번 미션을 수행하면서 배열에서 값을 꺼내는게 가장 힘들었습니다...
처음에는 for-in 반복문으로 아래와 같이 구현했으나 출력 결과가 원하는 대로 나오지 않았습니다.
```swift
if winningLottoNumber != 0 {      // winningNumber = 로또 당첨 번호와 겹치는 번호
      print("축하합니다! 겹치는 로또 번호는", terminator: "")
      for number in winningLottoNumber {
            print("\(number), ", terminator: "")
      }
      print("입니다!") // 출력결과 = "축하합니다! 겹치는 로또 번호는 1, 2, 3, 4, 5, 6, 입니다!" -> 마지막 숫자 뒤에도 ","가 남는 문제
```
이후 알려주신 separator 를 이용해보기 위해 찾아보고 적용해 보았으나
제 코드가 문제인지, 제 방식이 문제인지 원하는 출력 결과를 얻을 수 없었습니다.

인터넷 서치를 통해 map 을 사용하면 더욱 쉽고 간결하게 원하는 출력값을 얻을 수 있었지만,
map 의 코드의 작동 방식이 이해가 되지 않아 다른 방법을 이용하기로 했습니다.
```swift
let winningMesage = winningNumber
let printWinningMesage: String = winningMesage.map { Strint($0) }.joined(separator: ", ")
// 출력 결과 = 축하합니다! 겹치는 로또 번호는 1, 2, 3, 4, 5, 6 입니다! -> map 의 원리를 이해 못한 채 사용
```

결국 저는 출력할 문구를 String 타입의 새로운 변수에 넣고,
String.removeLast() 기능을 이용하여 ","를 없애는 방법을 선택했습니다.

separator 의 정확한 사용법과 map 의 작동원리에 대해 조금 더 자세히 알고 싶습니다.

2024-07-16 13:51 UTC, jaemuYeo reviewed
출력 예시와 동일하게 시도해보셨군요! 고생많으셨습니다 👏

map에 대한 원리를 이해하지 못하여 사용하셨다고 하였는데
사실 코드에 정답은 없기때문에 결과만 같다면 뭐가 맞고 틀리다고 할 수 없습니다!
충분히 잘 하셨고, 이해하지 못한 코드의 사용을 포기하고 
이유 있는 코드로 작성하신 부분에 대해 너무 박수를 드리고 싶습니다 👍

걱정하지않으셔도 됩니다!! 곧 고차함수에 대해서 알아갈 시간이 있으니 그때 함께
이해하는 시간 가져보면 좋을 것 같아요 :)

그 외 코드에 대해서 간단히 코멘트 남겨두겠습니다!

2024-07-16 13:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func randomNumberGeneratorOfLottoNumber() {
함수 네이밍의 처음에는 동사가 오는 것이 좋습니다!
[API guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming)의 함수 네이밍 부분을 확인하여
새롭게 네이밍을 해보면 좋을 것 같습니다.

그 전에!! 해당 함수가 하는 일이 너무 많은 것 같아요🤔
함수를 분리한다면 조금 더 명확하게 함수의 역할에 맞게 네이밍을 할 수 있을 것 같은데요.
어떻게 기능을 분리해보면 좋을까요?

+ 현재 번호 생성을 하나만 하는 것이아니라 여러개를 하는데 Number와 Numbers 중 어떤 표현이 맞을까요?

2024-07-16 13:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    randomNumberOfLottoNumber.removeAll()
randomNumberOfLottoNumber와 winningNumber의 요소를 지우지 않아도
매번 다른 번호가 생성되고 거기에 따라 winningNumber넘버도 바뀌는데
removeAll 메서드를 사용한 이유가 궁금합니다!

2024-07-16 13:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    randomNumberOfLottoNumber = Set(1...45)
Int.random(in:) 을 활용해보면 좋을 것 같습니다!

2024-07-16 13:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    while randomNumberOfLottoNumber.count > 6 {
해당 while문에서 count가 < 6 일때까지 내부에서 insert 해주어도 좋을 것 같아요 :)

2024-07-16 14:05 UTC, Crois0509 commented on CodeStarterCamp_Week2/step2.swift
> +    randomNumberOfLottoNumber.removeAll()
이 부분은 제가 코드를 수정하던 중
함수를 2회 호출했더니 이전과 같은 결과값이 출력되어서
호출할 때마다 초기화 되도록 removeAll 메서드를 사용해 보았습니다!

다른 문제점은 수정해서 다시 push 해보도록 하겠습니다!

2024-07-16 14:44 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님!
남겨주신 피드백 코멘트 모두 확인 후 코드를 수정하여 재요청 드립니다!
코드는 다음과 같이 수정했습니다.
##
- 먼저, 함수가 너무 많은 일을 하는 것 같다고 하셔서 
  1. 랜덤 번호를 생성하는 함수
  2. 로또번호추첨기 함수
  3. 로또 당첨,낙첨 결과를 출력하는 함수
- 이렇게 3가지의 함수로 분리해 보았습니다.
- 다음으로는 함수의 네이밍을 의도에 맞도록 조금 더 적절하게 수정해 보았습니다. 영어 실력이 모자라니 번역기를 쓰더라도 자연스러운 네이밍을 짓기가 어렵네요...ㅠㅠ
- 또, removeFirst 메서드가 아닌 Int.random(_ in:) 메서드를 사용하여 랜덤번호를 생성하도록 수정하였습니다.
- 위의 내용들로 코드를 변경한 후 전체적으로 출력 결과가 미션의 의도와 알맞게 나오도록 조정했습니다.
##
추가로, 질문이 있습니다.
이번에 배열 벗기기를 진행하며 여러 방법을 시도하면서
배열을 벗기는 방식이 옵셔널을 벗기는 방식과 유사하다고 느꼈는데,
이는 옳은 생각일까요?
배열의 값을 꺼내는 것과 옵셔널의 값을 꺼낼 때 같은 방식을 써도 항상 문제가 없을지 궁금합니다.

2024-07-17 06:15 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    randomNumberOfLottoNumber.removeAll()
그런 이유가 있었군요~
다음 스텝을 위한 코드라고 생각이 되어서 의문이 들었습니다 ㅎㅎ 
의도 이해했습니다!

2024-07-17 07:03 UTC, jaemuYeo reviewed
함수 분리와 개선까지 고생많으셨습니다!
남겨둔 코멘트 확인 후 문제없으면 merge 진행하겠습니다 :)
PR은 항상 신중하게 보낼 수 있도록 해야해요.
꼭 많은 테스트와 실행 예시 등을 확인 후 결과가 동일 한 경우에 요청해주셔요! 🙏

### 질문 . 배열의 값을 꺼내는 것과 옵셔널의 값을 꺼낼 때 같은 방식을 써도 항상 문제가 없는가?
여기서 말하는 방식이 옵셔널 바인딩을 말씀하시는 건지 어떤 방식인지 파악하지 못했습니다!
예시 코드를 함께 포함해주시면 조금 더 정확한 답변을 드릴 수 있을 것 같아요!
일단 사용하신 메서드의 [firstIndex](https://developer.apple.com/documentation/swift/array/firstindex(of:))같은 경우를 보면 반환타입이 옵셔널 이기에 동일한 방법으로 사용가능하며 다른 컬렉션들도 때에 따라 동일한 방법으로 진행 될 수 있을 것 같습니다.

가장 큰 이유는 값을 꺼내는 시도를 하는데 배열에 값이 없다면 심각한 에러를 발생시킬 수 있기때문이죠.

2024-07-17 07:06 UTC, jaemuYeo reviewed
함수 분리와 개선까지 고생많으셨습니다!
남겨둔 코멘트 확인 후 문제없으면 merge 진행하겠습니다 :)
PR은 항상 신중하게 보낼 수 있도록 해야해요.
꼭 많은 테스트와 실행 예시 등을 확인 후 결과가 동일 한 경우에 요청해주셔요! 🙏

### 질문 . 배열의 값을 꺼내는 것과 옵셔널의 값을 꺼낼 때 같은 방식을 써도 항상 문제가 없는가?
여기서 말하는 방식이 옵셔널 바인딩을 말씀하시는 건지 어떤 방식인지 파악하지 못했습니다!
예시 코드를 함께 포함해주시면 조금 더 정확한 답변을 드릴 수 있을 것 같아요!
일단 사용하신 메서드의 [firstIndex](https://developer.apple.com/documentation/swift/array/firstindex(of:))같은 경우를 보면 반환타입이 옵셔널 이기에 동일한 방법으로 사용가능하며 다른 컬렉션들도 때에 따라 동일한 방법으로 진행 될 수 있을 것 같습니다.

가장 큰 이유는 값을 꺼내는 시도를 하는데 배열에 값이 없다면 심각한 에러를 발생시킬 수 있기때문이죠.

2024-07-17 07:06 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func generatorOfRandomNumbers() {
generator의 경우 명사로 많이 사용되는데요.
함수의 네이밍은 동사로 시작할 수 있게 generate로 해주면 적절할 것 같습니다 :)
of와 같은 전치사또한 파라미터를 사용할 경우 인자 레이블에 작성하는 편이며 
간단하게 generateRandomNumbers와 같이 해주어도 좋아요!
네이밍 쉽지 않죠? ㅎㅎㅎ 저도 제일 어려워요 😆 천천히 적응해나가면 될 거예요! 💪

2024-07-17 07:06 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func lottoNumberLotteryMachine() {
해당 함수의 네미밍 또한 동사로 시작해보면 좋을 것 같아요~
모든 함수가 전부 동사로 시작하지는 않지만 대부분의 겨우 가이드라인에서는 동사로 시작하는 것을 권장하고 있습니다.
그렇지 않은 경우는 언제일까요?

2024-07-17 07:06 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    LottoNumber.removeAll()
removeAll을 해주는 것도 별도로 기능을 분리해볼 수 있을 것 같아요~

2024-07-17 15:45 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요. 남겨주신 코멘트 확인하여 코드 최종 수정하였습니다.
아직도 git 을 사용하는게 어색하여 PR을 보낼 때도 실수를 하곤 하네요...
좀 더 공부하고 연습해서 실수를 줄일 수 있도록 해보겠습니다.
##
질문에 관해 답변을 남겨 주셨는데, 제가 생각한 것은 옵셔널 바인딩과의 비교였습니다.
옵셔널의 값을 추출하는 방법이 여러가지인데 제가 옵셔널 바인딩 외에는 아직 활용하지 못하여
당연히 옵셔널 바인딩을 한다고 생각하고 질문을 남겨 설명이 부족했던 것 같아요.

firstIndex 는 옵셔널 함수였군요!
지난번 피드백 강의에서도 한번 설명 해주셨던 기억이 있네요.
Array[0]과 Array.firstIndex 의 차이를 설명해 주셨던 것과 비슷하게 이해하면 될까요?
배열의 값을 출력할 때 [ arr1, arr2, ...] 의 형태가 아닌 arr1, arr2, ... 의 형태로 출력하는 다른 방법이 있다면
또 알고 싶습니다.
##
피드백을 받기 전까지는 스스로 코드를 꽤나 잘 구현했다고 생각하는 때가 있는데
앞으로는 조금 자중을 하고 실수를 줄일 수 있도록 더 자세히 들여다보고
검토하는 습관을 들여야겠다고 생각했습니다...
또, 영어공부를 병행하면 코딩을 하는데 도움이 될 것 같다고 생각했어요.
코드를 구현하는 것만큼이나 네이밍이 어렵네요...

2024-07-18 02:02 UTC, jaemuYeo reviewed
너무너무 잘 하고 계세요!!
기죽지말고, 재밌게 코딩하셨으면 좋겠어요 ㅎㅎ 💪

하다보니 스텝2가 너무 길어졌는데 스텝3에 기능을 추가하면서
리팩토링 해보는 시간도 가져보면 좋을 것 같습니다!!

배열의 값을 꺼내오는 방법은 대표적으로 separateor를 많이 쓰곤합니다!
[이 블로그](https://ios-development.tistory.com/377)를 찹고해봐도 좋을 것 같아요~

고생 많으셨고 다음 스텝에서 만나요!!

2024-07-18 02:02 UTC, merged