[Round 2/Step 3] - Crois
yagom-academy/swift-starter-week2 pull request #764
Opened 2024-07-18 08:29 UTC by Crois0509

@jaemuYeo 
안녕하세요 잼킹님!
드디어 Step2를 정복하여(?) Step3를 제출합니다.
Dictionary 컬렉션을 사용하며 많은 시행착오를 겪었네요...
Array 나 Set 컬렉션과는 달리 Key 와 Value를 각각 지정해줘야만 하다보니
많은 고민을 했던 것 같아요

## 고민했던 점
### Dictionary 의 Key 와 Value 에 무슨 타입을 담을지
- 처음에는 Key 타입에 Int, Value 에 [Int] 타입을 지정하려고 했습니다.
- 다만, 미션의 예시에 "1회차" : [1, 2, 3, 4, 5, 6] 과 같은 Key와 Value 타입을 가진다고 하여 Key를 String 타입, Value를 [Int] 타입으로 지정하였습니다.
- 코딩을 진행하다가 Step2 때와 마찬가지로 Dictionary에서 Value 를 호출할 때 배열을 벗겨야 하는 상황이 발생했습니다.
- 처음에는 Step2 에서 진행한 것과 같은 방법으로 진행하려다가 지난 번 알려주신 separator를 활용하고자 했습니다.
- 이를 위해서는 Dictionary 의 Value 타입을 [String]으로 변경할 필요가 있었습니다.
- 결론적으로는 아래와 같은 코드를 통해 문자열 배열 벗기기로 Dictionary의 Value 타입을 배열 없이 호출할 수 있었습니다.
```swift
func findingLottoNumber(for round: Int) {
    if round > 0 {
        if let finder = winningNumbersRecord["\(round)회차"] {
            print("\(round)회차의 로또 당첨 번호는 \(finder.joined(separator: ", ")) 입니다.")
            // 출력결과 예시 = "n회차의 로또 당첨 번호는 1, 2, 3, 4, 5, 6 입니다."
        }
    }
}
```

## 해결이 되지 않은 점&조언을 얻고 싶은 부분
### 함수를 사용한 횟수를 얻는 방법?
- 이번 미션에서 "새로운 로또 당첨 번호 생성 함수를 호출할 때마다"라는 것이 조건이었습니다.
- 때문에 저는 혹시 함수를 사용할 때마다 이를 Count 할 수 있는 방법이 있을까 찾아보았습니다.
- 결과적으로는 끝내 찾아내지 못하고, 비슷한 내용의 글은 이해하기가 어려웠습니다. (재귀함수는 아니겠죠??)
- 어쩔 수 없이 저는 currentRound 라는 별도의 Int 타입의 변수를 생성하여 함수의 마지막에 값을 +1 하여 회차를 구하도록 하였습니다.
- 혹시 함수를 사용할 때마다 그것을 알 수 있거나 호출된 횟수를 구하는 다른 방법이 있다면 알고 싶습니다.

2024-07-19 06:34 UTC, jaemuYeo requested changes
스텝3도 빠르게 보내주셨군요!!
라인별 코멘트와 해결되지 않은 부분에 대해 전달 드리겠습니다.

### 해결 되지 않은 점
현재 함수를 호출할때마다 Round의 값들이 매번 변경이 되어 `저장`이 되지 않고있군요.
랜덤으로 6개의 숫자를 생성하는 함수가 호출되면 특정 round에
회차와 숫자가 저장이 되고, 계속 호출되면 히스토리는 그대로 남아있고 round를 통해
검색이 가능해야합니다. 함수의 반환타입을 활용해보세요!

🚨 함수들이 너무 각자 본인들의 기능에만 충실하고있습니다.
반환 타입을 통해 반환 값을 전달해 주는 시도도 한 번 해보세요!
익숙해지면 전역 변수 없이 함수들로만 코드를 구현해볼 수 있을 거예요.
```swift
// ex
func someFunc() -> Dictionary<String, [Int]> {
   // 기능
   return
}
```

2024-07-19 06:34 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step3.swift
> +var winningNumbersRecord: Dictionary<String, [String]> = [:]
딕셔너리는 회차와 회차별 로또 `번호`를 저장하고 있는데
String보다는 Int가 더 적절하지 않을까요?

2024-07-19 06:34 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step3.swift
> +func findingLottoNumber(for round: Int) {
꼭 ing를 붙여하지만 동사가 되는 것이 아닌 find 자체로도 동사가 될 수 있어요!
`findLottoNumber`
보통 찾다, 검색하다 등의 네이밍을 지을때 find와 search 등을 많이 쓰는 편입니다.
인자 레이블에 for도 좋지만 조금 더 직접적인 of도 괜찮아 보이네요 :)

2024-07-19 06:34 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step3.swift
> +            print("\(round)회차의 로또 당첨 번호는 \(finder.joined(separator: ", ")) 입니다.")
당첨 번호의 숫자들을 오름차순으로 정렬해보면 어떨까요?
어느 구현부에 정렬해 주어야할까요?

2024-07-20 13:45 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님
지난번 코멘트로 남겨주신 피드백 참조하여
코드를 수정해 보았습니다!

## 수정한 내용
- 개인DM을 통해 실행결과는 문제가 없다고 확인을 받은 후 미션의 의도대로 코딩을 하는 방향으로 수정을 진행했습니다.
- 먼저 currentRound 변수를 함수 내에서 호출하여 1개의 함수에서만 사용하도록 수정하였습니다.
- 다음으로 Dictionary를 함수의 return 값으로 호출할 수 있게끔 코드를 수정하였고, 이를 활용하여 n회차의 로또 당첨 번호를 출력하게끔 코드를 수정하였습니다.
- Dictionary 의 Key와 Value 를 String, [Int] 로 변경하였습니다.
- 함수의 네이밍도 코멘트를 보고 조금 수정하였습니다.
- 마지막으로 출력 된 n회차의 로또 번호를 오름차순으로 출력되도록 코드를 수정하였습니다.


## 함수의 return 에 대해
- 함수의 return 값을 사용하는 것이 아직 어색하고 어렵습니다.
- 특히 Dictionary 컬렉션은 어떻게 활용하면 좋을지 고민했습니다.
- 결국에 .values 를 활용하여 문제를 해결했습니다만, Dictionary<String, [Int]> 값을 반환하는 함수를 호출 할 때
'Result of call to 'saveLottoNumbers()' is unused' 라는 경고 메세지가 계속 표시가 됩니다.
- 크게 신경쓸 필요 없어보이긴 하지만... 이럴 경우 어떻게 하면 좋을지 조언 부탁드립니다.

2024-07-22 07:51 UTC, jaemuYeo requested changes
Result of call to 'saveLottoNumbers()' is unused의 경우 
호출한 함수가 사용되지 않고있기에 불필요한 코드가 됩니다.

경고가 뜨는 곳 바로 위에 `@discardableResult`를 붙여 경로를 지울 수는 있으나
호출이 사용되지 않는다면 호출을 하지 않는 방법도 좋을 것 같아요 :)

현재 결과값이 다르게 나오는 이슈가 있어서 수정 후 merge 진행하도록 하겠습니다!

2024-07-22 07:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +findLottoNumber(of: 2)
<img width="451" alt="스크린샷 2024-07-22 오후 4 49 14" src="https://github.com/user-attachments/assets/8732ecef-7f64-4eda-abcf-8fd3e1939b00">

프린트에 찍히는 2회차의 로또 번호와
2회차 조회 번호와 다르게 출력되고있습니다!

2024-07-22 07:51 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step3.swift
> +func saveLottoNumbers() -> Dictionary<String, [Int]> {
Dictionaary의 타입이 <Int, [Int]>일 수 없을까요?
키에 들어오는 회차 또한 1, 2, 3, 4, 5 라운드...  등의 정수값으로 표현할 수 있을 것 같아서요!

2024-07-22 14:41 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님.
남겨주신 코멘트대로 코드를 수정해 보았습니다.
##
1. Dictionary 컬렉션의 Key 타입을 Int로 수정했습니다.
2. findLottoNumber 함수 사용시 n회차 로또 번호와 번호가 동일하지 않은 현상을 수정했습니다.
3. 그 외에도 의도한 대로 결과를 출력하기 위해 조금씩 수정하였습니다.
##
### 아쉬운 점
- 지난번 피드백으로, 함수의 반환값을 Dictionary 로 해보는 것을 추천받아 그렇게 진행해 보았으나 n회차의 로또번호 찾기에서 여러 시도를 해보아도 원하는 결과가 출력되지 않는 탓에 반환값을 지우고 전역변수로 선언하여 문제를 해결했습니다.
- 대신, 낙첨과 당첨의 결과를 출력하는 함수의 반환값을 String 타입으로 하여 return을 활용하는 방법을 연습했습니다.
- 원래라면 saveLottoNumbers 함수에 반환값을 Dictionary<Int, [Int]> 로 하여 문제를 해결하고 싶었는데 방법이 쉽지 않아 포기했습니다...
- 마지막에 도전했다가 포기한 코드는 아래와 같은데 무슨 문제가 있었던 것인지 조언을 구하고 싶습니다.
```swift
func saveLottoNumbers() -> Dictionary<Int, [Int]> {
    currentRound += 1

    var winningNumbersRecord: Dictionary<Int, [Int]> = [:]
    
    var currentLottoNumber: [Int] = []
    if currentRound > 0 {
        for record in lottoNumbers.sorted() {
            currentLottoNumber.append(record)
        }
        winningNumbersRecord[currentRound] = currentLottoNumber
    }
return winningNumbersRecord
}
// 금번 회차의 로또 번호를 저장하는 함수

func findLottoNumber(of round: Int) {
var finding: Dictionary<Int, [Int]> = [:]
finding = saveLottoNumbers()

    if round > 0 {
        var lottoNumber: String = String()
        if let finder = finding[round] {
            for findRecord in finder {
                lottoNumber.insert(contentsOf: "\(findRecord), ", at: lottoNumber.endIndex)
            }
            lottoNumber.removeLast()
            lottoNumber.removeLast()
            print("\(round)회차의 로또 당첨 번호는 \(lottoNumber) 입니다.")
        }
    }
}
// 함수 실행결과 아무런 값도 호출되지 않음
```

2024-07-23 07:20 UTC, jaemuYeo reviewed
내용 수정 중.. 

Round2 고생많으셨습니다!!
merge 진행하고자 하는데 아쉬우면 한 번 더 진행해보아도 좋을 것 같아요 :)
DM이나 코멘트로 진행여부를 말씀해주시면 merge 진행 여부를 판단하겠습니다!

```
func saveLottoNumbers() -> Dictionary<Int, [Int]> {
    currentRound += 1

    var winningNumbersRecord: Dictionary<Int, [Int]> = [:]
    
    var currentLottoNumber: [Int] = []
    if currentRound > 0 {
        for record in lottoNumbers.sorted() {
            currentLottoNumber.append(record)
        }
        winningNumbersRecord[currentRound] = currentLottoNumber
    }
return winningNumbersRecord
}
// 금번 회차의 로또 번호를 저장하는 함수

func findLottoNumber(of round: Int) {
var finding: Dictionary<Int, [Int]> = [:]
finding = saveLottoNumbers()

    if round > 0 {
        var lottoNumber: String = String()
        if let finder = finding[round] {
            for findRecord in finder {
                lottoNumber.insert(contentsOf: "\(findRecord), ", at: lottoNumber.endIndex)
            }
            lottoNumber.removeLast()
            lottoNumber.removeLast()
            print("\(round)회차의 로또 당첨 번호는 \(lottoNumber) 입니다.")
        }
    }
}
// 함수 실행결과 아무런 값도 호출되지 않음

2024-07-23 14:07 UTC, Crois0509 commented
@jaemuYeo
안녕하세요 잼킹님
남겨주신 코멘트 확인하여 수정을 진행해보려 했지만,
아직 map에 대한 이해가 부족한 것과
적어주신 코드가 제가 적은 코드와 연동이 좋지 않은 점 때문에
난항을 겪었습니다...
currentRound 변수의 경우, 함수의 내부에 위치 시킬 경우
로또번호를 생성할 때마다 1 이라는 Int 값만 생성하게 되어
원하는 회차의 로또번호를 호출하는 목적성을 위해서는 부적합하여 기존의 방식이 좋아보입니다.

조건, 반복문의 경우 for문과 while문 중 어느게 좋을지 여쭤보셨는데
지금과 같은 상황에서는 for문이 적합하다고 생각합니다.
이유로는, 제가 의도한 상황은 currentRound가 0이 아닐 때(로또 회차는 1회차부터 시작하기에)
lottoNumbers 배열의 모든 값을 for문 내의 record에 옮기고, 이를 다시 currentLottoNumber 배열에 넣는 것이 목적이었기 때문에
while문을 사용하면 의도한 바와 다른 코드가 작성될 것 같습니다.

다른 피드백(guard문 사용 등)에 대해서는 앞으로의 코드 작성에 있어
생각의 사고를 넓힐 수 있는 긍정적인 피드백이었다고 생각하여
활용할 수 있는 방안을 모색하고 있습니다.

여러모로 부족해 보일 수 있지만,
이번 미션은 지난 코드의 상태로 마무리 하여 merge를 부탁드리고 싶습니다.
앞으로도 잘 부탁드립니다.

2024-07-24 02:01 UTC, jaemuYeo commented
@Crois0509 
좋습니다!! 저는 지금도 충분히 훌륭한 코드라고 생각합니다 :)
너무 자책하실 필요 없을 것 같아요~ 
다음 프로젝트에서 적용해볼 수도 있는 거고, 앞으로도 많은 고민을 코드에 녹여보아야하니까요 ㅎㅎ

Round2도 고생많으셨습니다!

2024-07-24 02:02 UTC, merged