[Round2] step2 - Riu
yagom-academy/swift-starter-week2 pull request #765
Opened 2024-07-19 15:24 UTC by woolnd

안녕하세요 잼킹님 리우입니다!  @jaemuYeo 
“Round2 두번째 스텝 "내 번호와 맞추어보기!” \
기능구현 설명과 함께 PR드립니다!

## 순서도
<img width="297" alt="image" src="https://github.com/user-attachments/assets/2f39afc1-9132-4a38-9cbb-2c12a2f8a6d9">

## 기능구현
### buyLotto 함수
- 나의 로또 번호를 입력하며 로또번호를 생성하자마자 변수에 저장
- 나의 로또 번호와 로또번호를 체크하는 checkLotto()함수 실행
```swift
func buyLotto() {
    let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
    let lottoNumbers: [Int] = generateLotto()
    checkLotto(myLotto: myLottoNumbers, lotto: lottoNumbers)
}
```

### generateLotto 함수
- 로또번호를 전달하기 위해 임시로 변수 지정
- 로또번호는 6개 임으로 while문으로 6개인지 체크
- Int.random으로 1~45까지 숫자 출력후 number에 저장
- number가 lottoNumber에 있는지 파악후 겹칠 경우 반복문 재실행 없을 경우 번호 추가
- 6개 추가완료 시 전달
```swift
func generateLotto() -> [Int] {
    var lottoNumber: [Int] = []
    
    while lottoNumber.count < 6 {
        let number = Int.random(in: 1...45)
        
        if !lottoNumber.contains(number) {
            lottoNumber.append(number)
        }
    }
    return lottoNumber
}

```
### checkLotto 함수
- 나의 로또를 forEach를 통해서 입력되어있는 값 하나하나 생성된 로또와 비교
- 비교 후 result에 저장후 비지않은경우는 겹치는 번호가 있기에 result를 문자열로 변경후 출력양식 정의
- 비었을 경우 겹치는 번호가 없기에 "아쉽지만 겹치는 번호가 없습니다." 출력
```swift
func checkLotto(myLotto: [Int], lotto: [Int]) {
    var result: [Int] = []
    myLotto.forEach { number in
        if lotto.contains(number) {
            result.append(number)
        }
    }
    
    if !result.isEmpty {
        let resultString = result.map { String($0) }.joined(separator: ", ")
        print("축하합니다! 겹치는 번호는 \(resultString) 입니다!")
    } else {
        print("아쉽지만 겹치는 번호가 없습니다.")
    }
}

```

2024-07-22 08:21 UTC, jaemuYeo requested changes
스텝2도 완벽하게 수행해주셨군요!! 🙌
몇 가지 코멘트 남겨두었습니다~
확인 후 문제없으면 merge 진행하겠습니다 :)

2024-07-22 08:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func generateLotto() -> [Int] {
배열을 반환하는 타입이니 복수형의 네이밍을 해주면 좋을 것 같아요.
generateLottoNumbers와 같이요 :)
좋은 시도였습니다!

2024-07-22 08:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        if !lottoNumber.contains(number) {
contains를 사용하여 중복값을 방지하였군요!
Set을 사용하면 중복값이 들어올 수 없게되는데 그럼에도 불구하고 Set이 아닌 Array를 사용하신 이유가 있나요~?

2024-07-22 08:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    var result: [Int] = []
빈 배열임에도 result라는 변수를 통해 가독성에 신경쓰신 부분 너무 좋습니다 👍

2024-07-22 08:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        let resultString = result.map { String($0) }.joined(separator: ", ")
실행 예시와 동일하게 출력하게 수행하셨군요 👏

2024-07-22 08:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func buyLotto() {
buyLotto라는 네이밍은 myLottoNumbers만 가질 수 있을 것 같은 네이밍인 것 같아요 🤔

2024-07-22 08:42 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +func generateLotto() -> [Int] {
아하 넵!!! 감사합니다

2024-07-22 08:43 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +        if !lottoNumber.contains(number) {
로또 뽑힌 순서를 유지할려고 그대로하였습니다!! set은 출력할때마다 다른 순서로 출려되다보니 같은 순서로 출력될수있게 array로 하였습니다!

2024-07-22 08:43 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +    var result: [Int] = []
감사합니다!

2024-07-22 08:43 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +        let resultString = result.map { String($0) }.joined(separator: ", ")
감사합니다!

2024-07-22 08:44 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +func buyLotto() {
이해가 잘안되서 그러는데 혹시 추가설명 부탁드려도 괜찮으신가요!!

2024-07-23 06:21 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func buyLotto() {
@woolnd 
앗 넵넵.
기능적으로는 문제는 없는데 로또 구매라는 함수명이 나의 로또 번호만을 생성하거나 가지고 있을 것 같은데
구매하는 순간 내 번호가 생기고 비교해서 결과까지 나오니 애매하다고 생각했습니다!

네이밍을 변경해보거나 함수를 분리해보아도 좋을 것 같아요 :)

2024-07-23 09:56 UTC, woolnd commented on CodeStarterCamp_Week2/step2.swift
> +func buyLotto() {
넵 알겟습니다!!

2024-07-24 08:46 UTC, woolnd commented
안녕하세요 잼킹님 리우입니다!  @jaemuYeo 
“Round2 두번째 스텝 "내 번호와 맞추어보기!” \
수정하여서 다시  PR드립니다!

## 순서도
<img width="297" alt="image" src="https://github.com/user-attachments/assets/2f39afc1-9132-4a38-9cbb-2c12a2f8a6d9">

## 기능구현
### compareLotto 함수
- 나의 로또 번호를 입력하며 로또번호를 생성하자마자 변수에 저장
- 나의 로또 번호와 로또번호를 체크하는 checkLotto()함수 실행
```swift
func compareLotto() {
    let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
    let lottoNumbers: [Int] = generateLottoNumbers()
    checkLotto(myLotto: myLottoNumbers, lotto: lottoNumbers)
}
```

### generateLottoNumbers 함수
- 로또번호를 전달하기 위해 임시로 변수 지정
- 로또번호는 6개 임으로 while문으로 6개인지 체크
- Int.random으로 1~45까지 숫자 출력후 number에 저장
- number가 lottoNumber에 있는지 파악후 겹칠 경우 반복문 재실행 없을 경우 번호 추가
- 6개 추가완료 시 전달
```swift
func generateLottoNumbers() -> [Int] {
    var lottoNumber: [Int] = []
    
    while lottoNumber.count < 6 {
        let number = Int.random(in: 1...45)
        
        if !lottoNumber.contains(number) {
            lottoNumber.append(number)
        }
    }
    return lottoNumber
}

```
### checkLotto 함수
- 나의 로또를 forEach를 통해서 입력되어있는 값 하나하나 생성된 로또와 비교
- 비교 후 result에 저장후 비지않은경우는 겹치는 번호가 있기에 result를 문자열로 변경후 출력양식 정의
- 비었을 경우 겹치는 번호가 없기에 "아쉽지만 겹치는 번호가 없습니다." 출력
```swift
func checkLotto(myLotto: [Int], lotto: [Int]) {
    var result: [Int] = []
    myLotto.forEach { number in
        if lotto.contains(number) {
            result.append(number)
        }
    }
    
    if !result.isEmpty {
        let resultString = result.map { String($0) }.joined(separator: ", ")
        print("축하합니다! 겹치는 번호는 \(resultString) 입니다!")
    } else {
        print("아쉽지만 겹치는 번호가 없습니다.")
    }
}

```

2024-07-25 03:00 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        if !lottoNumber.contains(number) {
좋은 이유군요!! 다만 오름차순으로 정렬을 하게되면 추후 결과값은 동일하게 나올 수 있기에 
나중에 Set도 한 번 활용해보시면 좋을 것 같아요 :)

2024-07-25 03:01 UTC, jaemuYeo reviewed
push 과정이 꼬인 부분을 빠르게 해결하셨나보군요!! ㅎㅎ
고생 많으셨습니다 👍
Step3로 얼른 넘어가시죠!

2024-07-25 03:01 UTC, merged