[Round2] step2 - ollekil
yagom-academy/swift-starter-week2 pull request #766
Opened 2024-07-19 18:43 UTC by ollekil

@jaemuYeo 
[Round2] Step 2: 내 번호와 맞추어보기!  작업했습니다. 
이번 스텝에서는 클로저를 매개변수로 받는 filter 함수를 써봤습니다. 
filter 함수를 씀으로 인해서 나의 로또 번호와 당첨번호를 비교해서 배열로 넣는 함수를 만들었습니다. 
그리고 joined 함수를 이용해 배열을 원하는 문자열로 추가 결합하여 string 으로 형변환 할수 있었습니다.

2024-07-22 08:33 UTC, jaemuYeo requested changes
스텝2도 고생많으셨습니다 :)
벌써 고차함수까지 활용해보셨군요!! 

몇 가지 코멘트 남겨두었으니 확인 후 문제없으면
merge 진행하겠습니다!

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +func generateLottoNumbers() -> [Int] {
배열을 반환하기에 네이밍에 Numbers라는 복수형을 사용하셨군요!  좋습니다~ 👍

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +    var lottoNumbers: Set<Int> = []
중복값을 방지하기위해 Set타입을 선택하신 것이 좋네요!!

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +    while lottoNumbers.count < 6 {
가독성을 위해 변수와 while 문 사이에 개행이 있으면 좋을 것 같아요~

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +// 겹치는 숫자 확인하는 함수
주석은 PR보내는 파일이 아닌 다른 코드에 기록해두면 좋을 것 같아요 :)

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +        return generateLottoNumbers.contains(number)
단일 return문 같은 경우 return을 생략할 수도 있습니다! ㅎㅎ
이건 컨벤션 차이이니 추후에 고민해보시면 좋을 것 같아요~

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +func lottoGamePlay(myLottoNumbers: [Int]) {
함수이니 동사가 앞으로 올 수 있도록 playLottoGame이면 좋을 것 같네요!

2024-07-22 08:33 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +        let overlappingNumbersString = findOverlappingNumbers.map { (number: Int) in
map을 통한 형변환 좋습니다 👍

2024-07-22 23:29 UTC, ollekil commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +        return generateLottoNumbers.contains(number)
return 은 생략 했고,
매개변수 number 를 $0 으로 변경 하였습니다.

2024-07-22 23:30 UTC, ollekil commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +func lottoGamePlay(myLottoNumbers: [Int]) {
lottoGamePlay -> playLottoGame 수정 하였습니다.

2024-07-22 23:33 UTC, ollekil commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +        let overlappingNumbersString = findOverlappingNumbers.map { (number: Int) in
마찬가지로 
findOverlappingNumbers.map { (number: Int) in return String(number)}
-> 
findOverlappingNumbers.map { String(&0)} 으로 수정 하였습니다.

2024-07-22 23:36 UTC, ollekil commented
@jaemuYeo 
[Round2] Step 2: 내 번호와 맞추어보기! 
잼킹님 말씀데로 소스 정리 다시 해봤습니다. 
감사합니다~

2024-07-23 06:23 UTC, jaemuYeo commented on CodeStarterCamp_Week2/Step2/LottoGame.swift
> +        return generateLottoNumbers.contains(number)
@ollekil 
좋습니다 :) 다만 너무 많은 축약은 때때로 가독성을 헤칠 수 있다는 점도 인지해주세요!

2024-07-23 06:26 UTC, jaemuYeo reviewed
스텝2 고생많으셨습니다!!
이번 스텝은 merge 진행하겠습니다 👍

커밋 메시지도 조금 신경써서 기록해주시면 좋을 것 같아요!
큼직큼직하게 커밋하지 않고,
기능별로 나누어 남겨보고, 수정 한 부분에 대해서도 남겨두면 좋겠습니다 :)

2024-07-23 06:26 UTC, merged