[Round2] step3 - Riu
yagom-academy/swift-starter-week2 pull request #769
Opened 2024-07-26 05:48 UTC by woolnd

안녕하세요 잼킹님 리우입니다! @jaemuYeo 
“Round2 마지막 스텝 "로또 당첨 번호를 회차별로 저장하고, 확인하자!” \
기능구현 설명과 함께 PR드립니다!

## 순서도
<img width="205" alt="image" src="https://github.com/user-attachments/assets/ea575f5c-29b3-4676-b273-a09db36b114d">

## 기능구현
### lottoDict 함수
- 검색할 회차 번호를 readLine으로 입력을 받음
- 총 5개의 로또 번호를 위해 while문으로 로또번호 생성 함수 generateLotto() 실행
- 생성 즉시 로또번호 저장 함수 storeLotto()실행
- 입력값이 있을경우 Int화 하여 로또번호 확인 함수 checkLotto() 실행
```swift
func lottoDict() {
    print("로또 번호 생성기")
    print("회차 검색: ", terminator: "")
    let roundInput = readLine()
    var roundNum: Int = 1
    var lottoDict: [String: [Int]] = [:]

    while roundNum <= 5 {
        let lottoNumbers = generateLotto()
        storeLotto(roundNum: roundNum, lotto: lottoNumbers, lottoDict: &lottoDict)
        roundNum += 1
    }

    if let input = roundInput, let inputRound = Int(input) {
        checkLotto(round: inputRound, lottoDict: lottoDict)
    }
}
```
### generateLotto 함수
- Int.random으로 1~45까지 랜덤 숫자 생성
- 로또번호 임시 저장변수에 해당 숫자가 있는지 확인후 없을 경우 추가
```swift
func generateLotto() -> [Int] {
    var lottoNum: [Int] = []
    
    while lottoNum.count < 6 {
        let num = Int.random(in: 1...45)
        
        if !lottoNum.contains(num) {
            lottoNum.append(num)
        }
    }
    return lottoNum
}
```

### storeLotto 함수
- 전달받은 업데이트될 회차 번호 포멧을 적용 후 전달받은 로또번호 저장
```swift
func storeLotto(roundNum: Int, lotto: [Int], lottoDict: inout [String: [Int]]) {
    let roundStr: String = "\(roundNum)회차"
    lottoDict[roundStr] = lotto
}
```
### checkLotto 함수
- 확인할 회차 번호 포멧을 적용 후 딕셔너리에 검색후 lottoNum에 임시 저장
- 회차 정보가 있는 경우 저장된 번호를 string으로 변환후 포맷 적용 및 출력
- 회차 정보가 없는 경우 "해당 회차 정보가 없습니다. 출력
```swift
func checkLotto(round: Int, lottoDict: [String: [Int]]) {
    let roundStr: String = "\(round)회차"
    
    if let lottoNum = lottoDict[roundStr] {
        let lottoStr = lottoNum.map { String($0) }.joined(separator: ", ")
        print("\(round)회차의 로또 당첨 번호는 \(lottoStr) 입니다.")
    } else {
        print("해당 회차 정보가 없습니다.")
    }
}
```

2024-07-26 08:31 UTC, jaemuYeo requested changes
상세한 기능 구현 설명으로 코드를 쉽게 파악할 수 있었습니다 👍
네이밍에서 아쉬운 부분이 남아 코멘트 남겨드렸습니다!
화이팅 💪

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func generateLotto() -> [Int] {
Lotto의 어떤 것을 generate하는건지 명확한 네이밍을 작성하면 좋을 것 같습니다!

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    var lottoNum: [Int] = []
Num이라는 단축된 표현보다 Numbers와 같이 명확하게 네이밍해주세요!
파일내에서 전체적으로 변경하려면 컨트롤+커멘드+E 단축키입니다!

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +        let num = Int.random(in: 1...45)
num이라는 네이밍도 랜덤한 숫자라는 것을 명확하게 네이밍해주세요!

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func storeLotto(roundNum: Int, lotto: [Int], lottoDict: inout [String: [Int]]) {
inout 파라미터를 사용한 이유가 궁금합니다!

해당 함수의 네이밍이 어떤 기능을 하는지 와닿지 않아요 🤔
인자 레이블과 파라미터 네임을 함께 활용해보세요!
Dic -> Dictionary로 확실하게 표현해주세요~

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    let roundStr: String = "\(roundNum)회차"
str은 String으로 확실하게 포현해주세요!

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func checkLotto(round: Int, lottoDict: [String: [Int]]) {
딕셔너리에서 value 또한 Round를 나타내고 Round는 숫자로 표현될 수 있을 것 같아요.
String이 아닌 Int타입으로 해볼 수 있을까요?

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func lottoDict() {
함수인데 동사표현이 되지 않았군요!

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(lottoStr) 입니다.")
출력되는 당첨번호는 오름차순이 될 수 있게 정렬해보셔요 💪

2024-07-26 08:31 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    let roundInput = readLine()
해당 Round에서는 사용자 입력을 받지 않습니다!
매개변수를 통해 회차를 받고 출력될 수 있게 해주세요 🙏

2024-07-26 13:15 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +func generateLotto() -> [Int] {
알겠습니다 이해됬습니다!

2024-07-26 13:15 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +    var lottoNum: [Int] = []
넵! 감사합니다

2024-07-26 13:15 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +        let num = Int.random(in: 1...45)
넵!!!

2024-07-26 13:16 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +    let roundStr: String = "\(roundNum)회차"
넵 알겠습니다

2024-07-26 13:16 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +func lottoDict() {
알겟습니다

2024-07-26 13:17 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(lottoStr) 입니다.")
당첨번호 생성부터 저장하고싶어서 오름차순으로 하지 않았습니다!
실제로 로또번호도 랜덤으로 출력되는대로 입력되는대로 알고있습니다! 혹시 랜덤으로뽑힌 순서대로 해도 괜찮으신가요!

2024-07-26 13:17 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +    let roundInput = readLine()
추가적으로 기능을 구현했던것입니다 수정하겠습니다

2024-07-26 13:31 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +func storeLotto(roundNum: Int, lotto: [Int], lottoDict: inout [String: [Int]]) {
inout을 활용하여 직접 Dictionary를 참조하여 수정하기 위함입니다

2024-07-26 13:31 UTC, woolnd commented on CodeStarterCamp_Week2/step3.swift
> +func checkLotto(round: Int, lottoDict: [String: [Int]]) {
넵 확인했습니다!

2024-07-26 13:54 UTC, woolnd commented
안녕하세요 잼킹님! 리우입니다 @jaemuYeo 
“Round2 마지막 스텝 "로또 당첨 번호를 회차별로 저장하고, 확인하자!” \
수정사항 해결완료하여 업데이트드립니다.

## 수정사항
1. 애매한 함수 및 변수 네이밍을 다시 수정하였습니다.
2. round를 불필요한 string 활용하지않고 Int으로 통일하여 dictionary key값으로 사용하였습니다

## 순서도
<img width="192" alt="image" src="https://github.com/user-attachments/assets/74435a00-703e-41bb-86e3-17e0d3d305dd">

## 기능구현
### lottoOutput 함수
- 총 5개의 로또 번호를 위해 while문으로 로또번호 생성 함수 generateLottoNumbers() 실행
- 생성 즉시 로또번호 저장 함수 storeLottoToDictionary()실행
- 저장된 로또번호를 출력하는 checkLottoNumbers()실행
```swift
func lottoOutput() {
    var roundNumber: Int = 1
    var lottoDict: [Int: [Int]] = [:]

    while roundNumber <= 5 {
        let lottoNumbers = generateLottoNumbers()
        storeLottoToDictionary(round: roundNumber, lottoNumbers: lottoNumbers, lottoDictionary: &lottoDict)
        roundNumber += 1
    }

    for round in 1..<roundNumber {
        checkLottoNumbers(round: round, lottoDictionary: lottoDict)
    }
}
```
### generateLottoNumbers 함수
- Int.random으로 1~45까지 랜덤 숫자 생성
- 로또번호 임시 저장변수에 해당 숫자가 있는지 확인후 없을 경우 추가
```swift
func generateLottoNumbers() -> [Int] {
    var lottoNumbers: [Int] = []
    
    while lottoNumbers.count < 6 {
        let number = Int.random(in: 1...45)
        
        if !lottoNumbers.contains(number) {
            lottoNumbers.append(number)
        }
    }
    return lottoNumbers
}
```

### storeLottoToDictionary 함수
- 전달받은 업데이트될 회차 번호 포멧을 적용 후 전달받은 로또번호 저장
```swift
func storeLottoToDictionary(round: Int, lottoNumbers: [Int], lottoDictionary: inout [Int: [Int]]) {
    lottoDictionary[round] = lottoNumbers
}
```
### checkLottoNumbers 함수
- 확인할 회차 번호 포멧을 적용 후 딕셔너리에 검색후 lottoNumbers에 임시 저장
- 회차 정보가 있는 경우 저장된 번호를 string으로 변환후 포맷 적용 및 출력
- 회차 정보가 없는 경우 "해당 회차 정보가 없습니다. 출력
```swift
func checkLottoNumbers(round: Int, lottoDictionary: [Int: [Int]]) {
    
    if let lottoNumbers = lottoDictionary[round] {
        let lottoStrings = lottoNumbers.map { String($0) }.joined(separator: ", ")
        print("\(round)회차의 로또 당첨 번호는 \(lottoStrings) 입니다.")
    } else {
        print("해당 회차 정보가 없습니다.")
    }
}

```

2024-07-26 14:05 UTC, woolnd commented
<img width="358" alt="image" src="https://github.com/user-attachments/assets/43da3b0c-f9e1-470a-bec7-24d69718bbc6">

README.md 충돌이 일어나서 일어나는 부분 수정하였으나 위와같은 오류가뜹니다.. 혹시 어떤 오류인지 알 수 있을까요..? 구글링해도 잘안나오는것 같습니다..

2024-07-30 06:59 UTC, jaemuYeo reviewed
수정 내용 확인했습니다!!
네이밍이 훨씬 보기 좋아졌어요 👍
네이밍이 길어지더라도 축약된 표현보다는 항상 명확한 네이밍을 짓도록 노력해보아요!!

아쉬운 부분은 Round를 함수 호출시 매개변수로 받아 특정 라운드의 번호를 조회하는 것인데
현재 1~5까지의 라운드를 모두 보여주고 있네요 🤔
수정하기 쉬운 부분이기도 하고, 다음 Round를 제출할 시간도 얼마 안남았으니 이 부분은
추후 리우님의 숙제로 남겨두겠습니다!

남겨주신 충돌에 대한 이슈는 저도 처음 접하네요 ㅠㅠ
좋은 방법은 아니오나 강제푸시를 통해 병합하는 방법도 고민해보셔야 할 것 같습니다.
또는 충돌 이전의 커밋 로그로 돌아가는 방법도 있을 것 같아요.
저도 더 조사해보고 알게되면 공유하겠습니다!

2024-08-01 03:26 UTC, merged