[Round2] Step2 - GOO
yagom-academy/swift-starter-week2 pull request #781
Opened 2024-08-19 16:14 UTC by Goohyun3436

@jaemuYeo
안녕하세요. 잼킹. 늦은 시간에도 merge 요청 확인해주셔서 감사합니다.
덕분에 빠르게 step2 를 진행할 수 있었습니다!! 이번 PR 도 잘 부탁드립니다.

<br />

## 고민했던 점
### enum 또는 switch
- 이번 과제에서는 열거형(Enumeration)과 switch문을 활용해보고 싶었습니다.
- 그래서 저는, 겹치는 번호 컬렉션의 `count` 나 `isEmpty` 메소드와 Enumeration을 조합하여 결과를 print하는 함수 `printLotteryResult`를 구현하고 싶었습니다.
- 하지만 아직은 enumeration이 낯설어서 if-else 문보다 더 깔끔한 코드 구조를 구상하는데에 어려움이 있습니다.
- 겹치는 번호 컬렉션의 길이(0보다 큼/0과 같음)를 열거하여 결과 후처리 및 print를 실행해야할지, 로또 당첨 결과(당첨/실패)를 열거하여 print를 실행해야할 지 감이 잡히지 않습니다.

2024-08-20 06:04 UTC, jaemuYeo requested changes
스텝2도 금방 보내주셨군요!
컨벤션과 네이밍등 흠잡을 곳이 없는 것 같아요 👍
특히 배열 등의 네이밍을 복수형으로 해주신 부분도 너무 좋습니다!!

### Enum
지금 상황의 경우 겹치는 변호가 있거나 없는 경우 두 가지의 경우밖에 없기에
switch-case 보다 if문이 더 적절하다고 생각합니다!
코드에 정답은 없지만 저는 현재 작성하신 코드가 더 적절하다고 생각해요 :)

### 함수 코드 블럭 나열 순서
다른 언어와 비교할 수는 없지만 swift언어로 말씀드리겠습니다!
현재와 같은 프로젝트는 객체(타입)을 사용하지 않은 코드이기에 순서는 본인의 기준에
맞춰 작성하면 문제없을 것 같습니다.
다만 객체지향에서는 메서드 은닉화와 캡슐화(자바의 인터페이스와 같은)에서는
은닉화된 메서드를 하단에 작성하고 외부 객체와 소통하는 메서드를 상단에 올려
작성하는 편입니다!
```swift
class SomeClass {
   func someFunc() {
      someFunc1()
      someFunc2()
      someFunc3()
   }

   private someFunc1() {

   }

   private someFunc2() {

   }

   private someFunc3() {

   }
}
```

### 브랜치
현재 모든 스텝이 하나의 브랜치에서 이루어지고있는데
Goo님의 원격브랜치에서 나누어 작업중이신걸까요~?
스텝마다 브랜치를 나누어 작업 후 대표 브랜치에 merge하여
PR보내주는 방법을 권해드리고자 여쭤보았습니다!! ㅎㅎ

몇 가지 코멘트 확인 후 문제없으면 Merge 진행하겠습니다!

2024-08-20 06:04 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func createLottoNumbers() -> Set<Int> {
중복값을 방지하기위해 Set을 사용하셨군요! 👍

2024-08-20 06:04 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    repeat {
많은 반복문 중 repeat-while문을 사용하신 이유가 궁금해요 🤔

2024-08-20 06:04 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        lottoNumbers.insert(Int.random(in: 1...45))
`Int.random(in: 1...45)`도 변수에 담아 의미를 주면 좋을 것 같아요!

2024-08-20 06:04 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        let numbersJoined: String = sameNumbers.map{ String($0) }.joined(separator: ", ")
배열에서 값을 빼는 방법을 잘 해결하셨군요!! 👏👏

2024-08-20 07:07 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step2.swift
> +func createLottoNumbers() -> Set<Int> {
Set은 참 좋은 데이터 타입인 것 같습니다!! 👍

2024-08-20 07:07 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step2.swift
> +    repeat {
`for-in 반복문`: 범위 순회 -> 랜덤 숫자 6개 중 하나라도 겹치면 안되므로 선택 안 함.
`while 반복문`: 조건을 체크 후 루프문 블럭 내의 코드를 실행 -> **사용해도 문제없음**
`repeat-while 반복문`: 1회 선실행 후 다음부터 조건에 따라 블럭 내의 코드를 실행 -> 로또 번호는 1개 이상일 것이 보장된다고 판단하여 **1회 선실행 하는 것이 이득이라고 판단**, 실행할 코드를 먼저 읽게 되어 **가독성이 좋다고 판단**.

위의 이유로 repeat-while 반복문을 사용하였습니다. 하지만 상황에 따라서 1회 선실행의 특성이 독이 될 수 있을 것 같습니다..!

2024-08-20 07:09 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step2.swift
> +        lottoNumbers.insert(Int.random(in: 1...45))
로또 번호 컬렉션에 랜덤한 숫자를 추가한다는 의미를 주기 위해 `randomNumber` 변수에 담았습니다.
`randomNumber`는 repeat 루프문 블럭 바깥에 먼저 선언하였습니다.
큰 차이는 없겠지만 메모리 공간을 한번만 할당하고 메모리 공간을 재사용하는 것이 좀 더 명확하다고 판단했습니다.

2024-08-20 07:10 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step2.swift
> +        let numbersJoined: String = sameNumbers.map{ String($0) }.joined(separator: ", ")
이전에 사용하던 javascript 코드와 유사한 부분이 있어서 고차함수를 사용해봤습니다..!! 😀
하지만 아직 `$0` 의 의미를 정확하게 이해하지 않고 사용했습니다. 이부분은 좀 더 공부하려고 합니다!!

2024-08-20 07:11 UTC, Goohyun3436 commented
이번 PR도 꼼꼼하게 해주셔서 감사합니다.
이번 PR에서는 상황에 따라 필요한 조건문/반복문의 종류와 특성을 명확하게 얻어갑니다.
그냥 다들 사용하니 썼던 코드에도 이유가 필요하다는 것을 추가로 배운 것 같습니다. 감사합니다!
<br/>

### 함수 코드 블럭 나열 순서
답답했던 부분인데, 명확한 답변 감사합니다!! 속이 뚫린 느낌이에요..
객체지향의 메서드 은닉화, 캡슐화 개념을 공부해보겠습니다!

### 브랜치
항상 merge 후에 다음 스텝 작업을 하다보니 브랜치 하나로 upstream pull, origin push 해왔습니다.
말씀해주신대로 다음 스텝부터는 브랜치를 나누어 작업 후 merge, PR 하는 방식으로 진행하겠습니다!

2024-08-21 07:14 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        let numbersJoined: String = sameNumbers.map{ String($0) }.joined(separator: ", ")
해당 부분에 대해서는 다음주(4주차) 피드백 세션에 준비해보겠습니다!

2024-08-21 07:14 UTC, jaemuYeo reviewed
스텝2도 너무 고생많으셨습니다! 👏
다음 스텝 이어서 진행해주세요 💪

2024-08-21 07:14 UTC, merged