Week2 [Step2] - Elin
yagom-academy/swift-starter-week2 pull request #782
Opened 2024-08-20 12:52 UTC by Elin113

@jaemuYeo 
안녕하세요 잼킹! 5번째 PR을 보냅니다.

# 고민했던 점
branch를 생성하여 중간에 함수를 바꿔보았는데 이후 push할 때 오류가 났었습니다.
`You have divergent branches and need to specify how to reconcile them`
위 오류를 rebase, stash를 이용해서 해결은 했는데 프로젝트 파일 내에 생성해둔 파일이 CodeStarterCamp_Week2 폴더에는 존재하지만 프로젝트 파일 내에서는 보이질 않네요ㅠㅠ
우선 push는 된 듯 하여 PR을 보냅니다... (폴더 내 파일 덕에 코드 자체는 날아가진 않았습니다.)

처음에 `makeWinningNumbers` 함수 생성 시에는 if 문 안에 for을 사용하여 숫자를 저장하고, 중복 값이 입력되거나 숫자가 6개 미만 혹은 초과일 경우에 문구가 출력되도록 하였습니다.

그러나 Step3를 미리 진행하다 보니 기존 방식으로는 구현하기가 어려울 것 같아 실제 로또 방송에서는 숫자가 중복되거나 6개가 아닐 일이 없으니 해당 조건문을 삭제하고 6개의 각각의 숫자만이 저장되는 경우만 생각해 while문으로 변경하였습니다.

`winningLottoNumber` Set에서 당첨 번호를 바꾸었을 때 새로 저장이 되지 않아 고민했었습니다.
Array와 혼동하여 새로운 값을 넣으면 당연히 대체될 줄 알았는데, 아니란 것을 깨닫고 `makeWinningNumber` 함수에 초기화 기능을 추가하였습니다.

2024-08-21 08:43 UTC, jaemuYeo reviewed
혹시 브랜치를 새로 생성 후 push는 생성한 브랜치가아닌 다른 브랜치로(main) psuh하셨나요~?
정확한 상황을 알지못해 이유는 알 수 없지만
항상 git pull과 fetch 등 명령어를 통해 원격과 로컬 저장소 간에 싱크를 잘 맞춰주어야
push 또는 merge의 충돌을 예방할 수 있습니다!! 💪
해당 이유때문인지 저도 Elin님 코드를 클론받아와도 코드가 보이지 않네요 ㅠㅠ

## 코드 리뷰를 시작하기 전에 🤔
현재 스텝2에는 실행 예시가 있을거예요! (출력물)
다만 코드에서는 함수 구현만 되어있을 뿐 함수 호출을 통한 실행이 되고 있지 않네요!
해당 부분을 해결하신 후에 다시 한 번 리뷰하도록 하겠습니다!
꼭!꼭! PR은 결과물이 완성된 이후에 보내주세요 🙏
그 전에 해결되지 않는 부분은 디스코드 DM 또는 질문답변 채널을 통해 해결해주시면 됩니다 😀

## 다음 스텝 진행
저희가 스텝을 나눠둔 이유가 있어요!
예를 들어 현업과 비교하면 스텝2까지 회의가 끝나 개발을 진행했는데
디자인과 기획등이 변경되어 스텝3를 진행하게 됬을 경우
여러가지 코드의 유지보수 사항이 발생할 거예요.
그런 경우를 연습하고자 스텝을 분리해둔 것이기때문에 진행중인 스텝을 할때에는
다음 스텝까지 고려하지 않고, 꼭 진행중인 스텝 Merge 이후에 다음 스텝으로 넘어가주세요~
Merge 또는 코드리뷰를 기다리는 동안은 챕터 또는 공식문서를 통해 예/복습을 진행하시면 됩니다!

2024-08-21 08:43 UTC, jaemuYeo requested changes
실행예시와 동일한 결과물을 완성 후 PR 재요청 부탁해요~!

2024-08-21 12:40 UTC, devBambu commented
@jaemuYeo 안녕하세요 잼킹! 피드백 반영하셔 수정 완료하였습니다.

브랜치는 새로 생성 후 기존 브랜치 (ss_19_Elin branch)로 이동하여 merge를 진행하고 삭제했었습니다.
어디서 충돌이 생겼는지는 모르겠지만 지금은 문제없이 잘 되고 있습니다!

강의 진행을 빠르게 하기 위해 PR을 기다리는 동안 다음 스텝을 진행했었는데, 주의하도록 하겠습니다.

# 수정사항
1. main.swift 파일에서 함수를 호출하여 출력되게 하였습니다.
2. result 상수를 match 함수 내에서 선언하도록 위치를 변경하였습니다.
: main.swift 파일에서 match 함수를 두 번 호출하여 두 결과를 모두 출력하려고 시도했었습니다.
 그러나 호출한 첫 번째와 두 번째 함수의 매개변수가 다른데도 출력되는 결과가 같아 원인을 찾고자 했습니다.
 두 번째 호출한 match 함수의 result 값이 제대로 저장되지 않는 점을 발견하였고, 기존에 따로 result 상수를 호출 -> match 함수 내에서 result 상수를 선언 하는 것으로 변경하였습니다. 
 선언 위치를 변경함으로써 함수를 호출할 때마다 result 값이 변하여 원하는 함수 결과 값을 얻을 수 있었습니다.

# 해결하지 못한 점
 - 함수 결과 출력 시 예제 출력 결과 처럼 Set 타입 숫자들의 대괄호를 없애고 싶은데 방법이 있을까요?

2024-08-22 07:07 UTC, jaemuYeo requested changes
빠르게 수정해주셨군요! 
고생많으셨어요 👍

남겨주신 질문인 배열의 값을 꺼내오는 방법과 더불어
난수를 생성하는 기능이 아직 구현되어있지 않기에 Merge는 해결 후 진행하곘습니다!

[해당 블로그](https://sunny-maneg.tistory.com/entry/swift-Array-%EB%A9%A4%EB%B2%84-%EB%8C%80%EA%B4%84%ED%98%B8%EC%97%86%EC%9D%B4-%ED%95%9C-%EC%A4%84%EB%A1%9C-%EC%B6%9C%EB%A0%A5%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-joind-map) 를 참고해보셔도 좋을 것 같아요.

아직 고차함수(map)에 대한 사용이 어렵다면 블로그의 두 번째 내용인 for문을 통해 해결해보셔도 좋습니다! 고차함수는 4주차 피드백 세션에 다룰 예정이예요 :)

블로그만 참고하지마시고 꼭 공식문서도 함께 찾아보셔요!
궁금한 내용이 있으면 언제든 연락주세요 💪

2024-08-22 07:07 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        winningLottoNumbers.insert(lottery[number])
insert 되어아하는 요소가 1~45 사이의 난수여야하는데 매개변수를 통해 주입받고 있는 것 같아요!
그래서 실행 결과가 동일하게 나오고 있습니다 🤔

2024-08-22 07:07 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    winningLottoNumbers.removeAll()
해당 함수 실행시 winningLottoNumbers의 요소를 매번 지우는 이유가 궁금해요!

2024-08-22 07:07 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +let myLottoNumbers: Set<Int> = [11, 26, 3, 4, 35, 6]
상수 선언 너무 좋네요! 👍
컬렉션 타입이기에 복수형으로 네이밍해주신 부분도 좋습니다 👏👏

2024-08-22 07:07 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func matchLottoNumbers(lottery: [Int]) {
현재 매개변수에 로또 번호를 주입받고 있는데 해당 부분에 유저의 로또번호를 주입받고
내부적으로는 1~45사이의 숫자 여섯개가 자동생성되면 좋을 것 같아요!
`makeWinningNumbers`에 남겨둔 코멘트를 해결하면 해결될 것 같습니다 💪

2024-08-22 13:50 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +        winningLottoNumbers.insert(lottery[number])
.random 메소드 이용하여 랜덤 난수를 입력받도록 수정하였습니다!
```swift
while lottery.count < 6 {
lottery.insert(Int.random(in: 1...45))
}
```

2024-08-22 13:55 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +    winningLottoNumbers.removeAll()
함수를 여러 번 호출 했을 때 첫 번째 호출한 함수의 Set 값이 두 번째, 세 번째 호출했을 때 새로운 값으로 변경되지 않았습니다. 첫 번째 호출 시 저장된 Set 내의 값들이 Array 타입 처럼 자동적으로 대체되지 않는다는 것을 깨달았고, 호출될 때마다 새로운 값이 저장될 수 있도록 함수 실행 시 가장 먼저 Set 값을 초기화시켜 주었습니다.

2024-08-22 14:01 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +func matchLottoNumbers(lottery: [Int]) {
당첨 번호는 random 메소드를 활용해 랜덤 생성하였고, match 함수에서는 나의 로또 번호를 입력받도록 수정하였습니다! 숫자 6개를 입력받았을 때만 실행되도록 조건문도 추가하였습니다.
나의 로또 번호를 함수에서 입력받아 저장될 수 있도록 상수 선언 위치를 match 함수 내로 변경하였습니다. 

```swift
func matchLottoNumbers(myNumbers: Set<Int>) {
let myLottoNumbers: Set<Int> = myNumbers

if myLottoNumbers.count != 6 {
print("1 ~ 45 숫자 중 서로 다른 로또 번호를 6개 입력하세요.")
return
}
```

2024-08-22 14:11 UTC, Elin113 commented
@jaemuYeo 
피드백 반영하여 수정 완료하였습니다!
각 세부사항에 대해서는 코멘트 답글 참고 부탁드립니다. 

1. random 메소드를 이용하여 1~45 사이의 당첨 번호를 생성하는 makeLottery 함수 생성
 - makeWinningNumbers 함수는 삭제되었습니다.
 - random 메소드는 항상 서로 다른 값을 생성하나요? 중복 값을 생성할 가능성도 있나요??

2. matchLottoNumbers 함수에서 매개변수로 나의 로또번호를 입력받을 수 있도록 수정
 - myLottoNumbers 상수 선언 위치를 함수 내로 변경하였습니다.
 - 6개의 서로 다른 로또 번호를 입력하도록 유도하기 위한 조건문을 추가하였습니다.

3. 결과 출력 시 대괄호 없이 숫자를 출력하도록 .joined 메소드 활용
 - 블로그를 참고하여 .map 메소드를 활용해 Int 타입인 result를 String 타입으로 변환하였습니다.
 - String으로 변환시킨 result 값을 joined 메소드를 활용하여 출력하도록 했습니다. separator가 출력 값들을 구분해주는 것은 이해하였는데 정확히 joined가 어떤 걸 하는 메소드인지는 아직 이해하지 못했습니다..
 - 다음주 내용이 map과 같은 고차함수를 다룬다 하셔서 해당 내용 학습 후 다시 공부해보려 합니다!

2024-08-23 06:09 UTC, jaemuYeo reviewed
스텝2 고생많으셨어요 👏
네이밍도 너무 잘해주시고 이전 해결하지 못한 부분도 잘 해결된 것 같아요 👍
남겨둔 코멘트는 다음 스텝을 진행하며 고려해보면 좋겠습니다!
Merge할게요! 다음 스텝에서 만나요 😆

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    lottery.removeAll()
이전 removeAll 메서드 사용이유를 물어본 이유는 해당 부분이 없어도
함수 실행시 매번 새로운 값이 저장이 될거예요!
while문이 끝나는 아래에 print(lottery)로 찍어서 확인해보셔요 😀

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        lottery.insert(Int.random(in: 1...45))
`Int.random(in: 1...45)`도 변수에 담아 의미를 부여해주면 좋답니다 🙌

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    if myLottoNumbers.count != 6 {
예외처리를 너무 잘해주셨군요!! 👍
guard문도 학습 후 활용해보면 좋을 것 같아요~

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +
요런 곳은 꼭 개행하지 않아도 좋아요 :)

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        print("축하합니다! 겹치는 번호는 \(stringResult) 입니다!")
스텝3에서는 작은 숫자부터 큰숫자로 정렬이 될 수있게 해보면 좋을 것 같아요!

2024-08-23 06:09 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    let stringResult = result.map {String($0)}.joined(separator: ", ")
stringResult라는 네이밍이 아래 print문에 사용되고 있는데
사용하는 곳과 의미가 이어질 수 있게 네이밍 해주면 어떠까요~?
stringResult도 나쁘지는 않지만 프로그래밍 적인 네이밍인 것 같다고 생각합니다 ㅎㅎ

2024-08-23 06:09 UTC, merged

2024-08-24 10:01 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +    lottery.removeAll()
while문 아래에 lottery를 출력해보았지만 두 번째 실행 시에도 첫 번째 실행 값이 그대로 출력되었습니다..ㅠㅠ
그래서 removeAll 메서드는 그대로 유지하였습니다..!

2024-08-24 10:02 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +        lottery.insert(Int.random(in: 1...45))
`let randomNumber = Int.random(in: 1...45)`로 상수를 생성해주었습니다!

2024-08-24 10:04 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +    if myLottoNumbers.count != 6 {
```swift
guard myLottoNumbers.count = 6 else {
print("내용")
return
}
``` 
guard문을 적용시켜 보았습니다. 이름대로 원하는 조건 외에는 막아주는 기능이네요! 해당 경우에 딱 맞는 기능 같습니다. 감사합니당!

2024-08-24 10:05 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +    let stringResult = result.map {String($0)}.joined(separator: ", ")
축하 문구 출력 시 사용되는 값이라 celebrateResult로 네이밍을 바꿔보았습니다ㅎㅎ

2024-08-24 10:05 UTC, Elin113 commented on CodeStarterCamp_Week2/step2.swift
> +        print("축하합니다! 겹치는 번호는 \(stringResult) 입니다!")
step3에서는 .sorted()를 추가하여 오름차순 적용하였습니다!