[Week2] Step3 - Elin
yagom-academy/swift-starter-week2 pull request #784
Opened 2024-08-24 09:51 UTC by Elin113

@jaemuYeo 안녕하세요 잼킹! 6번째 PR을 보냅니다.
step2 merge 하시면서 받은 마지막 피드백을 반영하여 step2 파일도 조금 수정하였습니다.

### 고민했던 점
1. step2에 `makeLottery` 함수에서 말씀하신 것처럼 `.removeAll()`을 삭제해보았습니다. 그러나 `lottery`에 새로운 값이 저장되지 않아 그대로 `.removeAll()`은 남겨두었습니다.
2. step3 딕셔너리 값 호출 시 옵셔널 값 추출 방법은 알겠으나 이해는 되지 않아 공식 문서를 참고하였습니다.
 > `if let 상수명 = 값`은 값이 `nil`이 아니라면 상수에 값을 할당하며, 해당 상수는 if문 내에서만 사용 가능하다는 것으로 이해 완료하였습니다.

### 궁금한 점
개행 타이밍을 잘 모르겠습니다.
새로운 내용이 추가될 때마다 하고 있긴 합니다만, 새로운 내용이지만 해당 행이 짧은 경우에는 개행을 안하는 쪽이 가시성이 좋을까요?
```swift
makeLottery()
let result: Set<Int> = lottery.intersection(myLottoNumbers)
let celebrateResult = result.sorted().map{String($0)}.joined(separator: ", ")
/* 위의 경우 makeLottery() 다음에 개행을 하지않는 것이 가시성이 좋을까요?
let 두 행도 개행하지 않고 위 처럼 작성하는 것이 일반적인가요? */
``` 
개행의 경우 작성자의 재량에 따른 것인지 궁금합니다!

2024-08-26 08:47 UTC, jaemuYeo requested changes
Step3 코멘트 남겨두었습니다!
확인 부탁해요 :)

개행의 경우도 컨벤션에 해당하기에 이게 맞다!! 라고 확답드리기는 어렵습니다.
다음의 예로 저는 이정도까지 개행해본 적이 있습니다. (같은 코드입니다!)
```swift
    let result: Set<Int> = lottery.intersection(myLottoNumbers)
    
    let celebrateResult = result.sorted()
        .map {
            String($0)
        }.joined(
            separator: ", "
        )
```
팀마다 코드의 길이 제한을 두거나 매개변수의 개수에 따라 달라지기도 해요.
그래서 띄어쓰기의 경우는 대부분 비슷하지만 개행은 팀마다의 가독성 컨벤션에 영향이
있기때문에 무엇이 맞다고는 할 수 없습니다!

2024-08-26 08:47 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var times = 0
times라는 표현보다 회차를 뜻하는 round는 어떨까요~?

2024-08-26 08:47 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var winningHistory = [String: Set<Int>]()
딕셔너리를 활용하셨군요! 👍
딕셔너리의 키값의 경우 회차를 나타내는데 문자열이 아닌 정수 타입으로 해보면 어떨까요?

2024-08-26 08:47 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    if let history = winningHistory["\(time)회차"] {
옵셔널 바인딩 중 if-let을 사용한 이유가 궁금합니다! 🤔
guard-let과는 어떤 차이가 있었나요?

2024-08-26 11:25 UTC, Elin113 commented on CodeStarterCamp_Week2/step3.swift
> +    if let history = winningHistory["\(time)회차"] {
guard-let이라는 게 있다는 것을 몰랐습니다..ㅎㅎㅎ
if-let과 동일하게 nil값 여부를 판단하고, guard 구문과 동일하게 nil값일 시에는 else 구문 내의 함수를, 값이 존재할 시에는 코드를 실행하는 기능이라는 것을 학습하였습니다!

2024-08-26 11:34 UTC, Elin113 commented
안녕하세요 잼킹! 이번 PR도 피드백 감사합니다. 해당사항 반영하여 아래와 같이 수정하였습니다!
개행에 관련하여는 현재는 혼자 작성하는 코드이므로 제 기준에서 가시성이 좋아보이도록 판단하여 작성해보았습니다.
답변 감사합니다!

1. 변수 이름 변경 : `times` -> `rounds`
 -> 이에 따라 `findHistory` 함수의 매개변수 이름도 `time` -> `round`로 변경하였습니다.

2. `winningHistory` 딕셔너리의 키값 타입 변경
 : 예제 실행 예시에서 "n회차의 당첨번호는 ~~입니다." 로 나와있어 String 타입으로 설정했었습니다.
  출력 시에만 해당 문구가 나오면 되니 굳이 String 타입으로 하지 않아도 되네요. Int 타입으로 변경하였습니다.

3. `func findHistory` 내 if-let 구문 -> guard-let 변경
 : guard-let으로 옵셔널 바인딩을 할 수 있는지 몰랐습니다. 코멘트와 같이 어떻게 동작하는지 학슴하였고, 해당 함수에서는 if-let보다 guard-let이 더욱 적절하다 생각되어 코드를 변경하였습니다. 그 덕분에 회차 정보가 없는 경우를 출력할 수 있었습니다.

2024-08-27 07:28 UTC, jaemuYeo reviewed
Round2 너무 고생많으셨습니다!!
이제 다음 라운드로 넘어가셔도 좋을 것 같아요 👏
몇 가지 남겨둔 코멘트는 컨벤션 관련 내용이니 참고만해주세용~

2024-08-27 07:28 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +        let historyResult = history.sorted().map{String($0)}.joined(separator: ", ")
map 부분에서 중괄호 `{` 사이에 띄어쓰기를 해주면 가독성이 좋습니다!
`{ String($0) }` 특별한 이슈는 아니여서 넘어가겠습니다 :)

2024-08-27 07:28 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    guard let history = winningHistory[round] else { print("해당 회차의 정보를 찾을 수 없습니다.")
guard - let의 컨벤션은 보통
```swift
    guard let history = winningHistory[round] else {
        print("해당 회차의 정보를 찾을 수 없습니다.")
        return
    }
```
이렇게 되어있습니다! guard-let의 가장 큰 이점은 `Early exit(빠른 종료)`라는 것인데요!
if문의 경우 조건이 맞지 않으면 else또는 그 다음 흐름으로 로직이 흘러가는 반면
guard문을 통과하지 못할 경우 예외처리 후 곧바로 함수를 종료한다는 것입니다.

각각의 특징이 있으니 상황에 맞게 적절히 활용하시면 좋을 것 같아요 :)

2024-08-27 07:28 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    }
들여쓰기가 되어있네요!

2024-08-27 07:28 UTC, merged