[Round2] Step3 - GOO
yagom-academy/swift-starter-week2 pull request #785
Opened 2024-08-25 09:51 UTC by Goohyun3436

@jaemuYeo 
안녕하세요. 잼킹. 주말 잘 보내고 계신가요!! 😀
2주차 step3 PR을 보내드립니다. 이번 PR도 잘 부탁드립니다!!

## 고민했던 점
### 함수 분리
- 기능당 하나의 함수를 정의하였습니다.
- 함수 목록
  - 로또 번호를 기록하는 함수
    - 직전 회차에서 금번 회차를 구하는 함수
  - 원하는 회차의 로또 당첨 번호를 출력하는 함수

### 두 개의 함수에서 중복되는 코드를 또 다른 함수로 분리해야하는 가
- 코드에서 step2.swift의 `printLotteryResult`함수와 step3.swift의 `printLottoNumbers` 함수에서 Array 타입을 String 타입으로 join하는 기능이 겹칩니다.
  ```swift
  let numbersJoined: String = sameNumbers.map{ String($0) }.joined(separator: ", ")
  print("\(numbersJoined)")
  ```
- 함수를 따로 분리하는게 좋을까요?
- 따로 분리하게 된다면 공통 기능들을 모아둔 파일의 폴더 구조를 어떻게 구성해야할지 궁금합니다.

2024-08-26 08:37 UTC, jaemuYeo requested changes
스텝3도 고생많으셨습니다! 
코멘트 남겨두었어요 :) 확인 부탁해요 🙏

2024-08-26 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var lottoRoundDict: [String: [Int]] = [:]
Dict이라는 표현보다 명확하게 Dictionay로 해주시면 좋아요!
회차(key)의 경우 회차도 숫자로 표현되기에 Int타입이면 좋을 것 같은데
문자열로 구현한 이유가 궁금해요 :)

2024-08-26 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers: [Int] = lottoRoundDict["\(round)회차"] {
옵셔널 바인딩 중 if-let으로 구현한 이유는 무엇인가요?
else문을 통해 1~5회차 이외의 round를 검색했을때의 예외처리도 해주면 좋을 것 같군요! 💪

2024-08-26 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(numbersJoined) 입니다.")
로또번호가 오름차순으로 정렬 되어있으면 번호 확인이 더 잘 될 것 같아요 :)

2024-08-26 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    for round in lottoRoundDict.keys {
하나의 함수에 하나의 기능만 할 수 있도록 정의하셨다는 코멘트를 확인했어요!
다만 해당 함수는 두 개 이상의 일을 수행중에 있는 것 같습니다!
코드 뎁스도 두 번이 발생했구요 🤔
더 분리해 볼 수 있을까요??

2024-08-26 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    var preRoundNumber: Int = 0
pre는 prefix를 표현한 건가요~?

2024-08-26 12:26 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step3.swift
> +var lottoRoundDict: [String: [Int]] = [:]
step3 문제에 `"1회차": [1, 2, 3, 4, 5, 6] 와 같은 Key와 Value를 가집니다.` 라는 문장이 있습니다!

String 타입을 사용하여 String 구조체의 split 메서드를 사용하도록 유도하신 줄 알았습니다 😅

- 변수 명확성을 위해서, `lottoRoundDict` -> `lottoRoundDictionary` 수정하였습니다.
- 회차(key)의 타입을 Int로 수정하였습니다.

2024-08-26 12:39 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers: [Int] = lottoRoundDict["\(round)회차"] {
- if-let으로 구현한 이유
  여러 예외처리를 관리하기에는 옵셔널 바인딩 중 gaurd let 을 사용하는 것이 유리한 것 같습니다.
  하지만 `lottoRoundDictionary`의 lottoNumbers(value)는 있거나([Int]) 또는 없거나(nil) 두가지의 경우만 있다고 판단하였습니다.
  따라서 두가지의 경우의 수를 간편하게 처리할 수 있는 if-let을 사용하였습니다.

- else 코드 블럭을 추가하여 없는 회차를 검색했을 때의 예외처리를 추가하였습니다.

2024-08-26 13:02 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step3.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(numbersJoined) 입니다.")
- `findSameNumbers` 겹치는 번호를 찾아 반환하는 함수 (Step2)
정렬된 컬렉션을 반환하는 [Array sorted(by:)](https://developer.apple.com/documentation/swift/array/sorted(by:)) 메서드를 사용하여 **겹치는 번호를 오름차순으로 정렬하여 반환**하도록 하였습니다.

- `recordLottoRounds` 로또 번호를 회차별로 저장하는 함수 (Step3)
정렬된 컬렉션을 반환하는 [Array sorted(by:)](https://developer.apple.com/documentation/swift/array/sorted(by:)) 메서드를 사용하여 **로또 번호를 오름차순으로 저장**하도록 하였습니다.

2024-08-26 13:14 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step3.swift
> +    for round in lottoRoundDict.keys {
회차(key)의 타입을 String에서 Int로 수정하면서 해당 함수가 간단해졌습니다!
```swift
func getCurrentRound() -> Int {
    return lottoRoundDictionary.keys.count + 1
}
```

만약 수정 전의 코드에서 더 분리했다면, "n회차" 에서 n을 추출하는 함수와, n을 사용하여 금회차를 구하는 함수로 기능을 분리했을 것 같습니다.
```swift
func getCurrentRound() -> Int {
    var preRoundNumber: Int = 0
    for round in lottoRoundDictionary.keys {
        let roundNumber: Int = gerRoundNumber(dictionaryKey: round)
        
        if preRoundNumber < roundNumber {
            preRoundNumber = roundNumber
        }
    }
    return preRoundNumber + 1
}

func gerRoundNumber(dictionaryKey: String) -> Int {
    if let roundNumber: Int Int(dictionaryKey.split(separator: "회")[0]) {
        return roundNumber
    }
}
```

2024-08-26 13:17 UTC, Goohyun3436 commented on CodeStarterCamp_Week2/step3.swift
> +    var preRoundNumber: Int = 0
회차(key)의 타입을 String에서 Int로 수정하면서 해당 변수를 제거했습니다!
만약 수정 전의 코드에서 해당 변수를 수정했다면, 이전의 의미를 뜻하는 `previousRoundNumber`으로 수정했을 것 같습니다.

2024-08-28 05:26 UTC, jaemuYeo reviewed
코멘트 댓글 후 태그가 되어있지 않아 확인이 조금 늦었네요 ㅠㅠ
코멘트 없이 댓글만 단 경우 꼭 디스코드 DM 또는 코멘트에 태그남겨주셔요 🙏
이번 스텝도 잘 수행해주셔서 Merge 진행하겠습니다!!
다음 Round로 넘어가셔도 좋을 것 같아요 👏

2024-08-28 05:26 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    return lottoRoundDictionary.keys.count + 1
이런 단행 return문일 경우 return 키워드를 생략해도 좋습니다!
다만 모든 코드에서 생략하거나 생략하지 않거나 코드의 통일성을 지키면 좋아요 :)
(그냥 전달드리고싶었던 팁입니다!)

2024-08-28 05:26 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers: [Int] = lottoRoundDictionary[round] {
guard-let의 가장 큰 이점은 `Early exit(빠른 종료)`라는 것 이예요.
if문의 경우 조건이 맞지 않으면 else또는 그 다음 로직이 흐름이 이어지는 반면
guard문을 통과하지 못할 경우 예외처리 후 곧바로 함수를 종료한다는 것입니다.

각각의 특징이 있으니 상황에 맞게 적절히 활용하시면 좋을 것 같아요 ☺️

2024-08-28 05:26 UTC, merged