[Round2] Step3 - hansol
yagom-academy/swift-starter-week2 pull request #787
Opened 2024-08-28 08:53 UTC by enqnsol614

@jaemuYeo
항상 상세히 리뷰해주셔서 감사합니다. 오늘은 Round2에 step3 PR요청 드립니다!

## 고민했던 점
### 로또 번호 생성 및 저장 방식
- 이번 과제에서는 로또 번호를 생성하고 회차별로 `Dictionary`에 저장하는 방식을 시도해보았습니다.
- 보너스 번호도 함께 저장하여 회차별로 관리되도록 신경썼습니다.
- 모든 회차를 출력하는 함수를 만들어서 `Dictionary`에 저장된 데이터를 출력했는데, 순서가 뒤죽박죽 나와 당황했지만, Int값을 구해 정렬하도록 하였습니다.

---

## 해결이 되지 않은 점
### 회차와 보너스 번호의 Optional 처리
- 회차와 보너스 번호를 Optional로 관리하려고 했는데, 초기에는 강제 언래핑(`!`)을 사용하는 방식으로 넣거나 조건문으로 에러가 나지않도록 처리하였는데, 강제 언래핑을 모두 제거하는 과정에서 코드가 다소 복잡해졌다고 느껴졌고, 일부 코드에서 불필요하게 복잡한 조건문이 생긴 것 같았습니다.  이 상황에서, 더 깔끔한 방식으로 Optional 값을 처리할 수 있는 방법이 있는지 궁금합니다.
Optional 처리에 대해서 이해도가 부족한 것같습니다. 
---

## 조언을 얻고 싶은 부분
### 정렬 및 Optional 값의 처리
- `Dictionary`에 저장할때 "회차"라는 단어를 빼고 int값만 저장하면 데이터 관리하기 어려운가요? 정렬할떄나 회차 찾을때 번거로운것 같아서요.
- Optional 값을 처리할 때, `guard let`과 `if let`을 사용하는 방식이 안전하다는 것을 알고 있지만, 코드가 지나치게 복잡해지는 것 같다고 느꼈습니다.  이런 경우, 더 깔끔한 코드 구조를 유지하면서 Optional을 안전하게 처리할 수 있는 방법이 있는지 궁금합니다.

2024-08-29 07:17 UTC, jaemuYeo requested changes
스텝3도 고생많으셨습니다!
몇 가지 코멘트 남겨두었어요 :)

## 딕셔너리 키 값의 `회차`
저도 같은 생각인데요! 회차는 정수로 표현하는 것이 맞기에 Int 타입이 맞다고 생각해요.
"회차"는 출력되는 프린트 함수에 넣어주면 좋을 것 같아요 :)

## 옵셔널 처리
가장 일반적으로 많이 사용되는 것이 옵셔널 바인딩 if-let과 guard-let입니다.
그 외에도 nil병합 연산자, 옵셔널 체이닝도 사용하기도 하지만
저는 guard-let을 가장 많이 사용하는 편이예요.

해당 방식도 잘 사용한다면 충분히 좋은 가독성을 보여줄 수 있습니다!
지금 구현한 코드에서는 모두 if-let으로 바인딩처리를 해주었는데
그 이유도 궁금해요!
if-let과 guard-let의 차이점은 무엇일까요??

2024-08-29 07:17 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
>  var winningNumbers: [Int] = []
해당 변수들에 타입 명시와 초기화를 잘 해주었네요! 👍

2024-08-29 07:17 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +var currentLottoRound: Int? = nil
해당 변수는 왜 옵셔널 타입으로 해주었나요~?

2024-08-29 07:17 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +var lottoRoundInfo: [String: [Int]] = [:]
키값은 회차를 저장하고있는데 회차는 문자열이 아닌 정수로도 저장 가능할 것 같아요 :)

2024-08-29 07:17 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +        Int($0.replacingOccurrences(of: "회차", with: ""))! < Int($1.replacingOccurrences(of: "회차", with: ""))!
이 곳에는 옵셔널이 강제추출 되었군요!

2024-08-29 07:17 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +    let sortedKeys = lottoRoundInfo.keys.sorted(by: {
딕셔너리를 정렬하려고 했던 이유가 궁금해요 🤔

2024-08-29 13:01 UTC, enqnsol614 commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +var currentLottoRound: Int? = nil
사실 정확하게는 잘 모르겠습니다.. 요건에 있어서 사용해봤는데요ㅠㅠ
currentLottoRound 변수가 옵셔널로 선언된 이유는 saveRoundWinningNumbers() 함수에서는 currentLottoRound가 nil인 경우 오류 메시지를 출력하고 저장을 하지 않도록 처리할 수 있고 이에 따라 코드의 안전성을 높이기 위함이라고 이해했습니다..

2024-08-29 13:02 UTC, enqnsol614 commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +var lottoRoundInfo: [String: [Int]] = [:]
정수로 수정했습니다!

2024-08-29 13:04 UTC, enqnsol614 commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +    let sortedKeys = lottoRoundInfo.keys.sorted(by: {
모든 회차의 로또 정보를 출력할 수 있는 printLottoAllRoundInfo() 함수를 만들었는데요,
출력해보니 배열에 넣은 순서대로 출력되지 않고 뒤죽박죽 출력되어 보기 좋지않아 정렬을 시도했습니다.
앞서 var lottoRoundInfo: [String: [Int]] = [:] String을 Int로 변경하여서 이 부분도 수정을 했습니다!

2024-09-02 02:27 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +var currentLottoRound: Int? = nil
사용해보았다는 것에 의의를 두면 좋을 것 같아요 :)
옵셔널 타입으로 선언할 경우 가져다 쓰는 곳에서 항상 옵셔널 바인딩을 경혐했을거예요!
이러한 번거로움이 있기에 가능한 옵셔널을 사용하지 않아도 되는 곳에서는 기본 타입으로 설계하는 것도 좋은 방법입니다!

2024-09-02 02:29 UTC, jaemuYeo reviewed
Round2도 너무 고생많으셨습니다!!
기간이 얼마남지않았으니 후딱 Round3의 타입 설계도 맛보았으면 좋겠어요 💪
남겨둔 코멘트는 참고만해주셔요 :)

2024-09-02 02:29 UTC, jaemuYeo commented on CodeStarterCamp_Week2/LottoNumberGenerator.swift
> +            let sBonusNumber = numbers.last!
해당 함수와 아래 함수에 동일한 부분에서 옵셔널 강제추출이 이루어졌네요!
만약 numbers의 마지막 요소가 없다면 어떻게 될까요?? 앱이 강제로 종료되는 치명적인 에러가 발생할거예요.
물론 내가 코드를 짜며 특정 요소는 무조건 있을 수 밖에 없다! 라고한다면 강제추출을 진행해도 무방하지만
가급적 안전하게 바인딩을 하는 것이 좋답니다 :)

2024-09-02 02:29 UTC, merged