Week2 [STEP 2] - tomchoi95
yagom-academy/swift-starter-week2 pull request #790
Opened 2024-09-26 07:35 UTC by tomchoi95

@jaemuYeo

순서도 수정
- set 변수 생성 육각형 모양으로 변경
- 출력 도형 변경
- 함수 생성 제거 후 로직을 순서도 내부로 적용

로또 추첨 코드 업로드

2024-09-27 07:00 UTC, jaemuYeo requested changes
안녕하세요 tomchoi님!
스텝2도 고생많으셨습니다 👍

아쉽지만 현재 결과물이 실행 예시와 달라 다시 한 번 시도 후 
이어서 리뷰하도록 하겠습니다!
현업에 나가면 기획자와 디자이너가 제시하는 요구사항이 항상 있기때문에
결과물과 같도록 시도하는 것은 필수입니다!💪

<img width="755" alt="스크린샷 2024-09-27 오후 3 58 10" src="https://github.com/user-attachments/assets/1b60fe15-71e1-4703-b36a-02355ebc53f3">

## 수정해야할 부분
- 현재 여섯개의 번호를 생성하는 부분과 그것을 출력하는 것만 구현됨 (완료)
- 내 로또 번호(사용자)와 생성한 랜덤한 숫자 6개를 비교하여 중복되는 번호 추출 필요함
- 번호가 한 개도 맞지않을 경우 `아쉽지만 겹치는 번호가 없습니다.' 출력 필요함

플로우 차트는 완벽합니다 👍

2024-09-27 10:35 UTC, tomchoi95 commented
@jaemuYeo

아차차...순서도만 구현하는걸로 이해하고 헷갈렸습니다.

수정 내용

- 찍은 번호 배열(Set)을 'myLottoNums' 변수에 할당

- 당첨 번호를 갖는 Set 생성 후, 'Set간 교집합이 비어있는가' 를 조건으로 갖는 조건문 생성
- - 참일경우 꽝메세지
- -거짓일 경우 두 집합간 intersection 출력

감사합니다.

2024-09-30 08:39 UTC, jaemuYeo requested changes
수정하시느라 고생많으셨습니다 👏
아직 실행 예시와 다른 부분이 한 군데 있기에 merge는 조금만 더 보류하겠습니다!
또한 그 부분과 더불어 한 가지 더 수정해보면 좋을 부분이 있어 아래 남겨둘게요!

## 파일 분리
현재 모든 코드가 main.swift 파일에 작성되어있습니다.
Step2에 해당하는 코드를 파일을 새로 생성하여 구현 후
동작에 필요한 함수 호출만 main.swift에 호출하도록 분리해보면 좋을 것 같아요!

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +func picLottoNum() -> Int {
pic 이라는 동사가 조금은 모하한 것 같아요!
헝상 네이밍은 의미를 전체적으로 전달해주는 것이 좋습니다 :)

pickLottoNumber 또는 createLottoNumber 등등

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +func showLottoNum() -> Set<Int> {
여기도 네이밍을 조금 더 명확하게 해주세요! 😀
컬렉션 타입을 저장하는 변수나 반환하는 함수의 네이밍에는 복수형 s를 붙이는 편입니다!
showLottoNumbers 와 같이요 👍

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +var myLottoNumbers : Set<Int> = [1,2,3,4,5,6]
앗 여기는 복수형으로 잘 네이밍해주셨군요 👏

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    if nums.intersection(choosenNums).isEmpty {
상수와 if문 사이에 개행을 해주면 가독성이 더 좋을 것 같아요!

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +    else {
else문의 위치는 바로위 중괄호 옆에 띄어쓰기 후 작성해주시는 것이 컨벤션입니다!

2024-09-30 08:39 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +        print("축하합니다! 겹치는 번호는 \(choosenNums.intersection(nums))입니다!")
현재 출력 결과가 배열에 감싸여있습니다!
하지만 프로젝트 실행예시를 보면 배열에서 값들이 벗겨져 출력되는 것을 확인할 수 있는데요!
이번 스텝의 가장 난이도가 있는 부분이라고 할 수 있을 것 같아요 :)
이 부분만 해결해보고 제가 남겨둔 코멘트 확인 후 다음 스텝으로 넘어가면 좋을 것 같습니다 💪

2024-09-30 12:43 UTC, tomchoi95 commented
@jaemuYeo

파일 분리
- lotto.swift파일 생성 후 코드 이동
- main.swift에 함수 호출외에는 모두 삭제

네이밍
- picLottoNumber() -> pickLottoNum()
- showLottoNum() -> showLottoNums()

컨벤션 및 기독성
- 상수와 if문 사이에 개행
- else문의 위치는 바로위 중괄호 옆에 띄어쓰기 후 작성 (적용 한다는 것을 잊었네요 다음부턴 컨벤션 적용 하겠습니다!)

배열 벗기기
- Set<Int>를 Array<String>"으로 변경
- joined(separator:)를 이용하여 Array를 문자열로 변경및 출력

##고민점
배열을 벗기는데 더 심플한 방법이 있을 것 같은데 알고 싶습니다!

감사합니다!

2024-10-01 03:49 UTC, jaemuYeo reviewed
어려운 문제였는데 금방 잘 해결해주셨군요!!
몇 가지 코멘트 남겨두었으니 확인해주세요 ☺️
해당 코멘트에서 수정할 부분이 있다면 다음 스텝을 진행하며 수정해주세요!
스텝2 Merge 진행하겠습니다!

2024-10-01 03:49 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +func pickLottoNum() -> Int {
가급적 Num같은 축약어도 Number로 명확하게 해주세요! :)

2024-10-01 03:49 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +        print("축하합니다! 겹치는 번호는 " + stringLottoNums.sorted().joined(separator: ", ") + "입니다!")
`stringLottoNums.sorted().joined(separator: ", ")` 이 친구를 변수에 담아 문자열 보간법을 사용하면
프린트문 내 문자열이 조금 더 간략해질 것 같아요 !

2024-10-01 03:49 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +        for num in nums.intersection(choosenNums) {
for문의 루프 상수 또한 number와 같이 명확하게 해주면 좋습니다!

2024-10-01 03:49 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +
if문 컨벤션입니다!

```swift
if 조건 {
   // 구현 부
} else {
   // 구현부 
}
```

2024-10-01 03:49 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +        var stringLottoNums : Array<String> = []
지금도 너무 좋지만 else문 안의 기능도 함수로 따로 분리하여 else문 안에 호출하는 방식을 사용했으면
어떨까하는 생각도 해보았어요 😀

2024-10-01 03:49 UTC, merged