[Round2] Step2 - sy
yagom-academy/swift-starter-week2 pull request #791
Opened 2024-09-26 15:13 UTC by jeseoyoung

### Main.swift
- let lottoNumbers = pickLotto()를 통해 랜덤한 6자리의 로또번호를 뽑음.
- compareLotto()를 통해 나의 로또 번호와 랜덤하게 뽑힌 로또 번호를 비교.

### step2.swift
- pickLotto() 및 compareLotto()를 구현.
- matching되는 번호를 for문으로 출력해보려고 했는데, 코드가 너무 길어져서 GPT를 사용했습니다🥲 

### 플로우차트 : 피드백을 일부 반영하여
- 변수 선언과 같은 불필요한 부분 삭제
- 분기를 추가
 **=> Set의 경우 중복 데이터가 들어가진 않지만 확실히 표기하고 싶어서 조건을 추가했는데 불필요했을까요?🧐**

@jaemuYeo Karma style이 매우 유용한 것 같습니다 감사해요!!

2024-09-27 06:54 UTC, jaemuYeo requested changes
스텝2도 금방 완료하셨군요! 👏
수정해주신 플로우차트도 훨씬 간결해지고 이해가 편해졌어요.

몇 가지 코멘트 남겨두었는데 확인 후 재요청 주시면
Merge 진행하겠습니다!

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func pickLotto() -> Set<Int> {
반환타입을 잘 활용해주셨군요! 👍

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        lotto.insert(Int.random(in: 1..<46))
`Int.random(in: 1..<46)` 도 의미가 있는 이름을 붙여 변수에 담아주면 가독성이 올라간답니다!

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    var lotto: Set<Int> = Set<Int>()
lotto보다는 컬렉션 타입에 맞게 복수형으로 네이밍해주면 좋겠어요 ☺️
보통 컬렉션 타입들은 s를 붙어 lottoNumbers 와 같이 표현해준답니다.

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    while lotto.count < 6 {
여러 반복구문중 while문을 선택한 이유가 궁금해요!

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +func compareLotto(from myNumbers: [Int], to winningLotto: Set<Int>) {
인자레이블과 파라미터 네임 잘 적용하셨네요! 👏

2024-09-27 06:54 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        let joinedNumbers = matchingNumbers.map { String($0) }.joined(separator: ", ")
크 👍 배열에서 요소를 꺼내어 프린트하는 것이 쉽지않았을텐데 잘 해결해주셨네요! 좋습니다 🥳

2024-09-27 08:32 UTC, jeseoyoung commented on CodeStarterCamp_Week2/step2.swift
> +    while lotto.count < 6 {
플로우차트를 만들 때, 'Set의 길이가 6보다 작을 때까지'라고 생각해서 무의식적으로 while을 떠올렸던 것 같습니다 ㅎㅎ
더 좋은 반복문 코드가 있을까요?

2024-09-28 09:50 UTC, jeseoyoung commented
리뷰해주신 내용 수정했습니다!
감사합니다🙂

2024-09-30 09:00 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +        var randomNumber: Int = Int.random(in: 1..<46)
let 으로 선언해도 좋아요 :)

2024-09-30 09:00 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    while lotto.count < 6 {
아뇨!! 이유가 궁금했을 뿐입니다 ㅎㅎ 좋아요 👍

2024-09-30 09:01 UTC, jaemuYeo reviewed
수정 확인이 조금 늦었네요 ㅠㅠ 죄송합니다 🙏
이번 스텝 머지 진행하곘습니다! 고생하셨어요 👏

2024-09-30 09:01 UTC, merged