[Round2] step1 - Reimos7
yagom-academy/swift-starter-week2 pull request #792
Opened 2024-09-28 07:55 UTC by Reimos7

@jaemuYeo

step1 로또 순서도 첨부 했습니다!

2024-09-30 09:09 UTC, jaemuYeo reviewed
앗 스텝1의 순서도와 코드도 함께 포함되어 push가 된 것 같아요!
PR이 Merge 되기 전까지 같은 브랜치에 새로운 push가 되면 안돼요 😀
일단은 순서도만 리뷰드리겠습니다!

현재 흐름은 아주 좋습니다!

다만 1~45의 난수를 생성하는 함수는 한번에 여섯개의 숫자를 빡! 생성해주는것이아니라
Set에 여섯개의 숫자가 모두 찰때까지 반복하여 하나씩 생성해주고 있습니다.
그렇기에 여섯개의 숫자가 모두 생성되었는지 `판단`하는 흐름을 추가하면 좋을 것 같아요!

2024-10-11 15:48 UTC, Reimos7 commented
@jaemuYeo
step1은 순서도 새로 수정 했습니다.
step2는 기존에 커밋 내용 그대로 올렸습니다.
step3 커밋 푸시 완료 했습니다.

기한이 얼마 남지 않아 한번에 완료 했습니다..

2024-10-15 08:08 UTC, jaemuYeo requested changes
스텝 2, 3 한 번에 리뷰남겨드렸습니다!
아직 실행 예시와 다른 결과를 보여주고있어 Merge는 
수정 후 진행하곘습니다 💪

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    guard let lottoDic = lottoDictionary[choice] else {return}
return 부분의 컨벤션은 아래와 같습니다!
```swift
// 1
guard let lottoDic = lottoDictionary[choice] else { return }

// 2
guard let lottoDic = lottoDictionary[choice] else {
    return
}
```

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    var lottoDictionary: [Int: [Int]] = [:]
딕셔너리의 key와 value는 각각 무엇을 뜻하나요?
네이밍만 봐서 딕셔너리가 어떤 것을 저장하는지 파악하기 힘든 것 같아요 🤔

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func makeLottoDraw(_ choice: Int)  {
makeLottoDraw라는 함수가 너무 많은 기능을 한 번에 담고있는 것 같네요!
함수는 하나의 기능만을 할 수 있도록 나눠주면 좋답니다 😉

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    var randomLottoArray: [Int] = []
실행 결과 중복되는 값이 들어오기도하네요!
Array가 아닌 Set을 활용해보면 어떨까요??
이 두 컬렉션의 차이는 무엇일까요?

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    print("\(choice)회차의 로또 당첨 번호는 \(lottoDic) 입니다.")
출력결과가 프로젝트의 실행예시와 다릅니다!
예시에서는 배열에 값이 나와서 숫자만 출력되고 있어요 🥲

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +
불필요한 개행 같아요!

2024-10-15 08:08 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step2.swift
> +    var randomLottoArray: [Int] = []
아래의 반복문을 보면 중복된 값도 저장될 것 같네요!

2024-10-17 11:50 UTC, Reimos7 commented on CodeStarterCamp_Week2/step3.swift
> +    guard let lottoDic = lottoDictionary[choice] else {return}
수정했습니다

2024-10-17 11:50 UTC, Reimos7 commented on CodeStarterCamp_Week2/step3.swift
> +    var lottoDictionary: [Int: [Int]] = [:]
lottoDraws로 딕셔너리명을 변경하였습니다
key는 회차를 의미하고 value는 해당 회차의 당첨 번호 배열을 의미 합니다

2024-10-17 11:50 UTC, Reimos7 commented on CodeStarterCamp_Week2/step3.swift
> +func makeLottoDraw(_ choice: Int)  {
해당 함수를 어떤식으로 나누는게 좋을지 잘 모르겠습니다..

2024-10-17 11:51 UTC, Reimos7 commented on CodeStarterCamp_Week2/step3.swift
> +    var randomLottoArray: [Int] = []
lottoDictionary와 randomLottoArray 모두 Set을 활용해서 변경 했습니다! 
Set은 Array와 달리 중복을 허용하지 않습니다.

2024-10-17 11:51 UTC, Reimos7 commented on CodeStarterCamp_Week2/step2.swift
> +
수정했습니다!

2024-10-17 11:51 UTC, Reimos7 commented on CodeStarterCamp_Week2/step2.swift
> +    var randomLottoArray: [Int] = []
set으로 수정 했습니다!

2024-10-17 11:51 UTC, Reimos7 commented on CodeStarterCamp_Week2/step3.swift
> +    print("\(choice)회차의 로또 당첨 번호는 \(lottoDic) 입니다.")
고차함수 map을 사용해서 수정 완료했습니다!

2024-10-17 11:54 UTC, Reimos7 commented
@jaemuYeo
말씀하신 내용 수정 완료 했습니다!

2024-10-18 07:52 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    var lottoDictionary: [Int: [Int]] = [:]
numbersOfRound와 같이 네이밍해도 좋을 것 같아요!

2024-10-18 07:56 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +func makeLottoDraw(_ choice: Int)  {
함수가 현재 어떤 기능들을 하는지 먼저 세분화해보면 좋을 것 같아요.

1. 숫자를 랜덤으로 1~45 중에 생성하여 Set컬렉션에 엿서개를 담고있다.
2. 회차를 다섯번 반복하여 5회차까지의 정보를 담는다.
3. 결과를 출력한다.

이렇게 나누고 기능하나씩 함수로 분리해서 상호작용하면 좋겠네요!

2024-10-18 07:59 UTC, jaemuYeo reviewed
5주간 학습하며 프로젝트 진행하시느라 고생많으셨습니다!
열심히 학습하여 멋진 개발자가 되시길 항상 응원하겠습니다 💪

남은 컨텐츠들도 학습하여 문법 얼른 마스터하길 바래요!!
기능 구현은 충분히 잘 학습하신 것 같습니다.
네이밍과 커밋 메시지 등에 조금 더 신경쓰며 프로젝트를 진행해보면 좋을 것 같아요 😀

고생 많으셨습니다!

2024-10-18 07:59 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var randomLottoArray: Set<Int> = []
Set인데 Array로 네이밍되어있군요!
이렇게 표현하기 보다는 randomLottoNumbers로 해주어도 좋을 것 같아요 :)

2024-10-18 07:59 UTC, merged