[Round2] Step3 - sy
yagom-academy/swift-starter-week2 pull request #793
Opened 2024-09-30 09:59 UTC by jeseoyoung

### Main.swift
- 로또 당첨 번호를 생성 함수 및 딕셔너리에 저장하는 함수를 5회 호출.
- 원하는 회차의 정보를 출력하는 함수 호출.

### Step3.swift
- 새로운 당첨번호를 딕셔너리에 저장하는 saveLotto()
- 원하는 회차의 정보를 호출하는 checkLotto()

<details><summary>출력 결과</summary>
<p>
<img width="329" alt="image" src="https://github.com/user-attachments/assets/2a3e8310-0538-447c-8622-b1fb563df0bf">

</p>
</details> 

@jaemuYeo 감사합니다🙂

2024-10-01 03:58 UTC, jaemuYeo requested changes
스텝3도 금방 완료하셨군요!!
코멘트 남겨두었으니 확인해주세요 💪

2024-10-01 03:58 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var times: Int = 1
times도 좋지만 round와 같이 `회차`를 표현하는 네이밍은 어떤가요~?

2024-10-01 03:58 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var history: Dictionary = [String?: Set<Int>]()
키값이 옵셔널인 이유가 궁금합니다!
또한 회차라고 한다면 문자열이아닌 정수로 표현될 것 같은데 Int로 수정해볼 수 있을까요~?
checkLotto함수에는 매개변수의 round가 Int군요! 코드의 통일성도 가독성을 위해 중요하답니다 :)

2024-10-01 03:58 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers = history["\(round)회차"] {
바인딩 중 if let을 통해 바인딩을 한 이유가 궁금해요!
guard let과의 차이는 무엇일까요?

2024-10-01 06:27 UTC, jeseoyoung commented on CodeStarterCamp_Week2/step3.swift
> +var history: Dictionary = [String?: Set<Int>]()
음... 저희는 1~5회차까지만 답을 생성하니까 6회차부터는 없을 수도 있으니까 회차를 나타내는 키가 옵셔널이라고 생각했습니다
근데 다시 생각해보면 회차의 키는 없으면 로또 번호도 존재할 수 없어서 잘못된 표현인 것 같네요🤔🤔

2024-10-01 06:42 UTC, jeseoyoung commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers = history["\(round)회차"] {
알려주셨던 예시나 The Basic에서도 Optional Binding에는 if let 을 쓰고 있어서, 옵셔널 바인딩은 if let이고 Force Unwrapping은 guard let이구나 하고 생각했습니다🙂
guard let은 값이 없는 경우에 빠르게 프로그램을 끝낼 수 있는 것 같고, if let은 else와 함께 쓰여서 성공과 실패의 경우를 표현할 수 있는 것 같네요

2024-10-01 06:53 UTC, jeseoyoung commented
- 전역변수 times -> round로 이름 변경
- checkLotto()를 if let문에서 guard let문으로 변경(코드가 덜 복잡해보여서 고쳐보았습니다.)

피드백 감사합니다🙂

2024-10-02 06:41 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    if let lottoNumbers = history["\(round)회차"] {
앗 Force Unwrapping은 느낌표를 붙여 강제추출한 경우입니다!
그 외에 가장 큰 특징은 guard let은 guard문을 벗어나지 못할경우 return 즉 빠른 종료(Early Exit)해준다는 장점도 있어요 :)
지금의 경우는 if-else문 이외에 다른 함수 로직이 없기에 적절하지만
만약 그 외에 다른 로직도 있을 경우 계속 흐름이 이어지지만 조건 불충족시 바로 함수를 종료하고싶다면
guard-let도 고려해보면 좋을 것 같습니다!

2024-10-02 06:45 UTC, jaemuYeo reviewed
Round2도 고생많으셨습니다!👏👏
남겨둔 코멘트는 참고용으로만 봐주셔요 :)

다음 라운드에서 만나요! 💪

2024-10-02 06:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +var round: Int = 1
Round는 saveLotto함수에서만 사용되기에 해당 함수 내부에 선언해도 괜찮을 것 같아요 :)

2024-10-02 06:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +    }
이 부분에 개행이 한번 되어있으면 가독성이 더 좋아질 것 같네요!

2024-10-02 06:45 UTC, jaemuYeo commented on CodeStarterCamp_Week2/step3.swift
> +        let numbersInRound = sortedNumbers.map { String($0) }.joined(separator: ", ")
들여쓰기가 잘 못 된것 같아요! ㅎㅎ

2024-10-02 06:45 UTC, merged