R2-S3
yagom-academy/swift-starter-week2 pull request #794
Opened 2024-10-01 04:46 UTC by tomchoi95

@jaemuYeo

감사합니다!

2024-10-02 07:37 UTC, jaemuYeo requested changes
Step3도 금방 마무리하셨군요!
코드 라인별 코멘트 남겨두었습니다 :) 확인 부탁드려요 🙏

2024-10-02 07:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +func findLottoNumbers(_ round : Int) {
인자레이블을 활용해 from을 붙여 라인드에서~ 와 같이 한문장으로 읽히게 해보면 어떨까요!

2024-10-02 07:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/main.swift
> +createLottoNumbers()
중요한 부분은 아니지만 for문으로 다섯번 반복해도 될 것 같아요 ><

2024-10-02 07:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +var lottoRoundAndNumbers = [Int:Array<Int>]()
딕셔너리를 잘 활용하셨군요! value 타입을 Set이 아닌 Array로 준 이유가 있을까요~?
아래 함수들에서는 Set을 활용하는 것 같아서요!

2024-10-02 07:37 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(lottoRoundAndNumbers[round]!.map{ String($0) }.joined(separator: ", ")) 입니다.")
앗 느낌표를 통해 옵셔널이 강제추출 되고 있군요!
바인딩을 통해 옵셔널을 안전하게 추출해보셔요 💪
강제추출을 하게되면 어떤 일이 발생할까요?

2024-10-02 10:42 UTC, tomchoi95 commented
@jaemuYeo

인자레이블 추가
- 코드 기독성을 위해 findLottoNumbers()의 인자레이블 추가(_ -> roundFrom)

반복문 활용 반복작업
- createLottoNumbers() 를 for문 안에 집어넣음 

value 타입을 Set이 아닌 Array로 준 이유
- 사실 큰 이유는 없지만 공통인자를 찾을 때는 set를 써서 수학적인?방법이 낫다고 생각했고 그 이후 찾아진 데이터가 set로 유지되기 보단 array로 있을 때 가공성?이 좋다고 생각했습니다.
- 수정된 코드에서는 set로 작업해보았습니다.

옵셔널
- if let으로 바인딩 후 코드의 안정성을 높혔습니다.
- 강제추출을 하게되면 어떤 일이 발생할까요? -> 옵셔널 안의 값이 nil일 경우 오류가 발생해서 런타임 오류 발생 가능

감사합니다.🙂

2024-10-04 05:40 UTC, jaemuYeo reviewed
Round2도 고생많으셨습니다!
몇 가지 남겨둔 코멘트는 참고용으로 생각해주세요 :)
얼른 Round3로 넘어갑시다! 💪

2024-10-04 05:40 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +func findLottoNumbers(roundFrom round : Int) {
앗 제가 의도한 것은 `findLottoNumbers(from round: Int)`와 같은 형태였습니다 :)

2024-10-04 05:40 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lotto.swift
> +        print("\(round)회차의 로또 당첨 번호는 \(numbers.sorted().map{ String($0) }.joined(separator: ", ")) 입니다.")
`numbers.sorted().map{ String($0) }.joined(separator: ", ")`
해당 부분도 변수 등에 의미를 부여해 네이밍 후 넣어주면 가독성이 더 올라간답니다!
예를들어 당첨 번호는 ~ 입니다이니까 ~에 상황에 따라 문자열 보간법에 들어갈만한 네이밍으로 해주면 좋아요.

```swift
var winningNumbers = numbers.sorted().map{ String($0) }.joined(separator: ", ")

// 이하 생략
print("\(round)회차의 로또 당첨 번호는 \(winningNumbers) 입니다.")
```

2024-10-04 05:40 UTC, merged