Week2 [STEP 2] JM.Y
yagom-academy/swift-starter-week2 pull request #8
Opened 2021-12-15 08:19 UTC by JungmoYu

@Neph3779  안녕하세요!

Week2 / Step2 PR 발행 합니다.

고민한점 및 질문은 아래와 같습니다.

고민한 점

1. 야곰의 리더세션에서 함수는 5줄 이내 / 함수의 들여쓰기는 한 번만 이용하는것을 권장하였습니다.
그에 따라서 최대한 함수를 쪼개어 위의 권장사항을 지키고자 노력해봤습니다.

2. 저는  컬렉션 타입으로 세트를 이용하고싶었는데, Step2의 내용에서 let myLottoNumbers: [Int] = [~~] 이렇게 할당하게끔 되어있길래, 타입 캐스팅을 통해 Array <-> Set 의 변환을 진행했습니다.

질문 점

DM에 보내드리긴 했지만...
제가 각 스텝마다 브랜치를 나누어서 진행 -> 원격저장소의 main 에 push 하고싶습니다. (결론은 로컬 저장소와 다른 원격 저장소의 브랜치)

이 방법이 가능한것인지? 가능하다면 주로 개발자들이 개발할 때는 어떤식으로 진행하는지 궁금합니다!
실제로 개발 시 로컬 저장소에서 지정한 이름 그대로 원격저장소에 같은 이름의 브랜치를 생성하여 push하고 pr -> merge하는 방식을 많이 사용하는지요...

감사합니다.

2021-12-15 10:41 UTC, Neph3779 requested changes
안녕하세요 정모님!
너무 고생많으셨습니다!
조금 개선하면 좋을 부분들이 있는 것 같아요!
궁금하신 내용들은 dm으로 질문주시면 감사하겠습니다! 😁

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +
이 코드는 로또 번호를 
로또 번호에 0번이 있을 수 있나요?
그리고 recommendNumber라는 네이밍이 잘 이해가 가지 않아요 🥲
어떤것을 추천하는건가요?

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +                                          myLottoNumbers: Set(myLottoNumbers)))
함수의 depth를 타고 들어가야 이해할 수 있는 구조네요
이런 경우에는 printMessage의 인자로 들어갈 값들을 따로 상수로 빼서 적어주는 편이 더 좋아요!

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +    }
printArray 함수를 print문의 인자로 주는건 조금 어색해보여요
printArray는 말 그대로 array의 정보를 print해줘야하는 것 아닐까요?

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +
intersection을 사용하셨군요!
새로운 메서드를 잘 사용해주셨어요~! 👍👍

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +
파라미터 (코드 상의 array) 는 이름이 꼭 array여야 할까요?
조금 더 처음 코드를 보는 사람이 이해하기 쉽도록 이름을 붙여주는건 어떨까요?

2021-12-15 10:41 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +    }
sorted 함수의 사용은 너무 잘 해주셨습니다~!

2021-12-15 15:23 UTC, JungmoYu commented on CodeStarterCamp_Week2/step2.swift
> +
안녕하세요, 로또번호...아... 너무 간과했네요!
지난 번 1...n 보다 0..<n 을 더 많이 사용한다는 그..생각에 너무 주어진게 무엇인지 생각하지 못했네요 ㅠㅠ
수정하도록 하겠습니다!

그리고 recommend라는의미는, 로또번호 6개를 추천해준다는 의미였는데...
다른식으로 변경하도록 하겠습니다!

2021-12-15 15:26 UTC, JungmoYu commented on CodeStarterCamp_Week2/main.swift
> +                                          myLottoNumbers: Set(myLottoNumbers)))
numbers: ~~

compareLottoNumbers의 반환 값을 상수로 한번 뽑아주는게 더 좋다는 의미가 맞을까요?

2021-12-15 15:26 UTC, JungmoYu commented on CodeStarterCamp_Week2/step2.swift
> +    }
말씀하신것 처럼, 함수의 의미가 너무 모호하네요.
    if numbers.count == 0 {
        print("아쉽지만 겹치는 번호가 없습니다.")
    } else {
        print(printArray(array: numbers.sorted()))
    }

여기서 if와 else의 구조를 같게 해준다고 print를 써주겠다는게 이렇게 됐네요..
다시 생각해보겠습니다!

2021-12-15 15:27 UTC, JungmoYu commented on CodeStarterCamp_Week2/step2.swift
> +
이렇게 하지 않는다면, 코드의 길이기 훨씬 길어질 것으로 판단하여, 스위프트에서 제공해주는 쉬운 함수를 사용했습니다...!

2021-12-15 15:28 UTC, JungmoYu commented on CodeStarterCamp_Week2/step2.swift
> +
네 알겠습니다! 피드백 감사드립니다!

2021-12-15 15:49 UTC, JungmoYu commented
@Neph3779 안녕하세요!
보내주신 의견을 반영하여 코드 수정을 진행해 보았습니다.
감사합니다!

2021-12-16 11:07 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = extractLottoNumbers()
오오 제가 네이밍이 보기엔 훨씬 좋아진 것 같습니다 ㅎㅎ

2021-12-16 11:10 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
좋아졌습니다!
하지만 printArray라는 네이밍은 너무 광범위해 보이네요
뭔가 어떤 array든지 들어가면 이쁘게 print되어 나올 것 같은 느낌이랄까?..
조금 더 구체적으로 바꿔봅시다!

2021-12-16 11:11 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
>      }
idx라는 줄임말보다는 index 혹은 element 등의 단어를 사용하는 것이 더 좋아보여요
가장 좋은 것은 이 특정 원소가 무엇인지 (로또 번호? 사용자의 번호? 맞춘 번호?)를 가지고 네이밍 하는 것이겠죠 ㅎㅎ
코드를 처음 본 사람도 이 코드가 어떤 코드구나~ 하고 알 수 있도록 짜는 것이 가장 중요한 포인트랍니다!
조금만 더 개선해볼까요?

2021-12-16 11:15 UTC, Neph3779 commented on CodeStarterCamp_Week2/step2.swift
> +    stringForPrint += String(arrayForPrint[arrayForPrint.endIndex - 1])
한눈에 봤을 때 이해하기 조금 어려운 코드인 것 같아요
코드를 코드라 생각하기 보단 누군가에게 줄글로 풀어서 이 코드가 실행되면
어떤 일들이 벌어지는지를 알려줄 수 있도록 해주면 더 좋을 것 같아요!
stringForPrint, arrayForPrint와 같은 이름은 이것들이 어떤 것을 print할 것인지에 대한 정보가 담겨있지 않아서
조금 읽기 어려운 것 같습니다 😅

2021-12-16 11:18 UTC, Neph3779 commented on CodeStarterCamp_Week2/main.swift
> +                                          myLottoNumbers: Set(myLottoNumbers)))
넵 맞습니다!

2021-12-16 18:10 UTC, JungmoYu commented
@Neph3779  안녕하세요 네프님, CR 요구사항의 내용을 최대한 반영하여 변경해보았습니다.

확실히 네이밍을 제 생각보다 더 많이(훨씬 많이) 구체적이고 의미전달이 잘 되도록 해야하는 것 같네요...!
이번에도 생각해볼 만한 부분이 있다면 말씀해주시면 감사하겠습니다.

그리고 다음 번 부터는 좀 더 많이 생각하고 코드를 쓰도록 하겠습니다.
(예를 들어 for문 속의 idx같은 부분...은 조금 생각을 하며 쓰면 리뷰하시기에도 많이 편할것으로 생각되네요.)

감사합니다!

2021-12-17 15:38 UTC, Neph3779 commented
이전보다 네이밍이 많이 개선되었네요!
고생 많으셨습니다 여기서 머지하겠습니다~!

2021-12-17 15:38 UTC, merged