Week2 [STEP2] KayAhn
yagom-academy/swift-starter-week2 pull request #84
Opened 2022-02-15 09:07 UTC by cpp2swift

@1Consumption 
올라프님!

이번 스텝은 내번호와 맞춰보기 였습니다.

제가 찍은 번호와 랜덤으로 생성된 번호가 몇개나 겹치며 그 결과에 따라

겹치는 번호를 포함한 문구를, 또는 "아쉽지만 겹치는 번호가 없습니다"를 출력하는 프로그램을 구현했습니다.

많은 조언 부탁드립니다! 항상 감사합니다!

2022-02-15 15:44 UTC, 1Consumption requested changes
안녕하세요 KayAhn님~~

코드 잘 읽었습니다. 확실히 읽기 좋아졌네요! 👏👏👏 
워낙에 잘하셔서 동작 자체에 대한 코멘트는 별로 없습니다.

그런데 아직 아쉬운점이 두가지 있어서 코멘트 드려요.

1.  아래 두개의 커밋은 이름이 같고, 두번째 `당첨 여부 판단 함수 추가` 커밋은 공백을 제거한 커밋이네요. 항상 커밋하기 전에는 내가 어떤걸 커밋하는지 확인하고 커밋을 하는게 좋습니다.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/37682858/154094726-989f8152-999f-420f-90c3-97e7dbd84a08.png">

2. [함수 호출 구현 및 추가](https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/f24764bb587435934d5444afc093cd1ae39bea0a) 이 커밋의 이름이 모호합니다. 어떤 함수를 호출했는지 명시했으면 좋겠어요.

이외에 피드백은 코멘트로 남겼어요! 확인 부탁드리겠습니다~ 🙇‍♂️

2022-02-15 15:44 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1,2,3,4,5,6]
```suggestion
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
```

`,` 사이에는 간격을 주는게 어떨까요?

2022-02-15 15:44 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +}
반환형이 `Void`인 경우도 반환형을 명시해주셨군요! 일반적으로 반환형이 `Void`인 경우는 생략을 하는데, 적어주신 이유가 궁금합니다!

그리고 이 while문을 잘 읽어보니 Set의 특성을 정확히 파악하고 사용하신 느낌이드네요! 그래도 코드에 대한 의도가 궁금한데, 의도를 코멘트로 남겨주실 수 있을까요?

2022-02-15 15:44 UTC, 1Consumption commented on CodeStarterCamp_Week2/main.swift
> +    var commonNumber: Array<Int> = Array<Int>()
다른 곳에서 array를 선언할 때는 `Array<Type>`이 아닌 `[Type]`으로 했는데, 여기는 다른 이유가 있을까요?

2022-02-16 02:44 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1,2,3,4,5,6]
확실히 간격을 주니 훨씬 보기가 수월 하네요.
안좋은 습관을 빨리 고치도록 하겠습니다!

2022-02-16 02:44 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +var randomNumber : Set<Int> = Set<Int>()
잘못하면 혼동을 불러올수도 있겠다는 생각을 했습니다. 감사합니다!

2022-02-16 02:49 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +}
제가 아직 많이 많이 부족하고 Swift 코드에 익숙하지 않아 최대한 자세하게 적어보려고 노력중입니다.

앞으로는 Void 같은 경우에는 생략하겠습니다!.

그리고 while문 내부에는, set이 중복이 허용되지 않은 점을 이용해서 만약 루프를 돌다 같은 값이 들어와 추가가 되더라도 

카운트에는 변함이 없다는 점을 이용했습니다!

2022-02-16 02:53 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +    var commonNumber: Array<Int> = Array<Int>()
말씀하신대로 코드의 11번째 줄 "let myLottoNumbers: [Int] = [1,2,3,4,5,6]" 부분에서는 [Type]으로 했는데

다른곳에서는 Array<Type>인걸 인지했습니다. 사실 11번째 줄의 코드는 이미 야곰 사이트에서 주어진 코드라 아무생각 없이 썼는데

생각해보니 다른사람이 읽었을때 선언방식이 다르면 혼동을 줄 수 있을것 같습니다. 앞으로는 일관성있게 짜보겠습니다!

2022-02-16 02:53 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +    for element in winningNumber {
감사합니다!

2022-02-16 02:57 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +        result.removeLast()
제가 생각나는대로 구현을 하다보니 이렇게 된것 같습니다. 조금만 더 신경 썼으면 좋았을텐데 하는 아쉬움이 남습니다.

2022-02-16 02:58 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +        if(myNumbers.contains(element)){
제가 다른언어에서 쓰던 괄호 강박증(?)을 빨리 버리겠습니다.

2022-02-16 06:50 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +var randomNumber : Set<Int> = Set<Int>()
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/68595ee61b0d9aed05425fe1f934b74fb82846bb

간격 및 선언 방식 수정했습니다!

2022-02-16 06:58 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +let myLottoNumbers: [Int] = [1,2,3,4,5,6]
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/68595ee61b0d9aed05425fe1f934b74fb82846bb

간격 및 Array 선언방식 수정했습니다!

2022-02-16 07:13 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +var randomNumber : Set<Int> = Set<Int>()
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/9ceae1d91ea68467c444f84e7dfac77a4c910719

변수명: 타입으로 컨벤션을 맞추고 변수명을 복수형으로 수정했습니다.
변수가 전역에 관여하고있어 해당 되는 부분을 수정하였습니다.

2022-02-16 07:18 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +    for element in winningNumber {
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/e65918b1857a3b64a46ae91f997673d56a602bdc

checkLottoNumber에서도 리턴을 Void 로 하고있어서 삭제했습니다!

2022-02-16 07:20 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +        if(myNumbers.contains(element)){
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/9bb44b8d88673018ed4ed8b11d2aab4ddcb14930

if 문 이후의 불필요한 괄호를 삭제 했습니다!

2022-02-16 07:30 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +        result.removeLast()
https://github.com/yagom-academy/swift-starter-week2/pull/84/commits/7461539fa0597db3a4cc38acbe6ac8873c4a64b2

for in loop 사용으로 조금 더 읽기 쉬운 코드를 만들었습니다.

2022-02-16 08:25 UTC, cpp2swift commented
확실히 올라프님이 말씀해주신대로 수정하고 전체적으로 찬찬히 읽어보니 훨씬 읽기 쉬운 코드로 변했습니다.
한 스텝 스텝 올라갈때 마다 말씀해주신것 잊지않고 더 신경쓰겠습니다!

2022-02-16 17:11 UTC, 1Consumption commented
고생하셨습니다. 이번 스텝은 여기서 머지하도록 할게요. 다음 스텝을 진행하셔도 좋습니다!

2022-02-16 17:42 UTC, merged