Week2 [STEP 3] Kay Ahn
yagom-academy/swift-starter-week2 pull request #93
Opened 2022-02-17 10:16 UTC by cpp2swift

@1Consumption 
안녕하세요 올라프님!
Week2 Step 3 미션은 "로또 당첨 번호를 회차별로 저장하고, 확인하자!" 였습니다.

To Do List에서 프로그램 구현을 위해 해야 했던 작업은..

1. 회차와 로또 번호들을 저장하는 Dictionary 타입의 변수를 생성
2. Step2의 로또 당첨 번호 생성 함수를 호출할 때 마다, 회차와 로또 번호를 Dictionary에 저장하도록 동작하는 함수 구현
3. 로또 당첨 번호를 5번 생성
4.  Dictionary 에서 2회차의 로또 당첨번호를 찾는다.
5. Optional 값을 안전하게 추출한다.
6. 추출한 값을 예제처럼 출력한다.

항상 저를 위한 코멘트 달아주셔서 감사합니다!

2022-02-17 14:43 UTC, 1Consumption requested changes
안녕하세요 KayAhn님~ 코드 잘 읽었습니다.
점점 swift에 익숙해지는게 눈에 보입니다.

코드의 동작에도 문제가 없고, 가독성도 정말 좋네요!
딱히 크게 피드백할게 없어요. 그동안 알려드린 부분을 모두 신경써서 개발한다는 느낌을 받았습니다.

나머지는 코멘트를 참고해주세요.

2022-02-18 06:03 UTC, cpp2swift commented on CodeStarterCamp_Week2/main.swift
> +//checkLottoNumber(myNumbers: myLottoNumbers, winningNumber: randomNumbers)
https://github.com/yagom-academy/swift-starter-week2/pull/93/commits/05839e83073dff6e4c0cbd61964ec98df834ff10

말씀해 주신대로 저렇게 불필요한 주석은 나중에 보게되면 "왜 이게 주석처리가 되어있지?", "혹시 다른사람이 잠깐 해놓은건가?" 라는 생각이 들었습니다.

2022-02-18 06:05 UTC, cpp2swift commented on CodeStarterCamp_Week2/Lotto.swift
> +var lottoNumbersByWeek: Dictionary<Int, Set<Int>> = Dictionary<Int, Set<Int>>()
var anotherWayToDeclareSet: [Int:Int] = .init()          // 알려주신 팁
var otherWayToDeclareSet: [Int:Int] = [:]                   // 조금 더 간결하게 쓰는법

알려주신 위 두개의 선언 방식과 제가 썼던 기본 방식을 숙지하고 있겠습니다!

2022-02-18 06:07 UTC, cpp2swift commented
@1Consumption

올라프님의 자세한 코드 리뷰 감사합니다.
나쁜 습관 빨리 고칠수 있도록 노력하겠습니다~!

2022-02-21 01:37 UTC, merged